test: implement end to end test
starkware-libs/mempool pull request #106
Opened 2024-05-07 11:04 UTC by MohammadNassar1

2024-05-08 10:38 UTC, ayeletstarkware reviewed
> Reviewed 5 of 15 files at r1, 9 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: all files reviewed, 8 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIHB2q3N8Sn5bs88mk:-NxIHB2q3N8Sn5bs88ml:bodtvhn) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/src/gateway.rs#L120)):*
> ```XML
>     // Send response.
> 
>     let internal_transaction = create_tx_for_testing();
> ```

why use "create_for_testing" outside of tests?
___
*[`crates/gateway/src/utils.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIL5IvDkoadji6Vev2:-NxIL5IvDkoadji6Vev3:bciowcd) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/src/utils.rs#L131)):*
> ```XML
> }
> 
> pub fn create_tx_for_testing() -> InternalTransaction {
> ```

add a todo to change to ThinTransaction?
___
*[`crates/gateway/tests/end_to_end_test.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIOus2-JTzuCYbHAHW:-NxIOus2-JTzuCYbHAHX:bgkncfh) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/tests/end_to_end_test.rs#L140)):*
> ```XML
> 
>     let gateway = Gateway {
>         config: gateway_config.clone(),
> ```

is the clone necessary? 
___
*[`crates/gateway/tests/end_to_end_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIP8tZBE9j8jY5KEk7:-NxIP8tZBE9j8jY5KEk8:b-89pb58) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/tests/end_to_end_test.rs#L165)):*
> ```XML
>     let response: Response<Body> = client.request(request).await.unwrap();
> 
>     assert_eq!(response.status(), StatusCode::default());
> ```

what is the default? 



_Code quote:_
```XML
StatusCode::default()
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMkYRtEXV9GMznL2kI:-NxMkYRtEXV9GMznL2kJ:b4xypz0) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/end_to_end_test.rs#L136)):*
> ```XML
>         validate_non_zero_l1_gas_fee: true,
>         max_calldata_length: 10,
>         max_signature_length: 2,
> ```

why did you choose these numbers?



_Code quote:_
```XML
        max_calldata_length: 10,
        max_signature_length: 2,
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 184 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMkjvQ5npOrJaIWAyE:-NxMkjvQ5npOrJaIWAyF:b3l6zo7) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/end_to_end_test.rs#L184)):*
> ```XML
> #[tokio::test]
> async fn test_end_to_end() {
>     let (network_gateway, network_mempool) = initialize_network_channels();
> ```

Perhaps 'network_gateway_to_mempool' would be clearer, or adding a comment would help.



_Code quote:_
```XML
(network_gateway, network_mempool
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMl5kGElzLmzyYYXWR:-NxMl5kGElzLmzyYYXWS:b-xtdxkx) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/end_to_end_test.rs#L196)):*
> ```XML
>     let mempool = Arc::new(Mutex::new(Mempool::new([], network_mempool)));
> 
>     let mempool_clone = mempool.clone();
> ```

Is this necessary? 
___
*[`crates/gateway/tests/routing_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMk9PHCIM5Caswdm4I:-NxMk9PI-51HeCdicR3P:b-jvkqhb) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/routing_test.rs#L60)):*
> ```XML
>         ..Default::default()
>     };
>     let (tx_gateway_2_mempool, _rx_gateway_2_mempool) = channel::<GatewayMessage>(1);
> ```

I think "to" looks better, don't you?



_Code quote:_
```XML
2
```


<!-- Sent from Reviewable.io -->

2024-05-08 14:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/gateway/src/gateway.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIHB2q3N8Sn5bs88mk:-NxNbo4o27rVPHb_efcJ:bhsacuf) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/src/gateway.rs#L120)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why use "create_for_testing" outside of tests?
</blockquote></details>

It's temporal.
Added a TODO.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIOus2-JTzuCYbHAHW:-NxNcG733ko3-azDpchI:bcrm70p) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/tests/end_to_end_test.rs#L140)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is the clone necessary?
</blockquote></details>

No, removed :)
___
*[`crates/gateway/tests/end_to_end_test.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIP8tZBE9j8jY5KEk7:-NxNcL8p2IpUCWaXc9AU:bd4ovy1) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/tests/end_to_end_test.rs#L165)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what is the default?
</blockquote></details>

`StatusCode::OK`.
Updated.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMkYRtEXV9GMznL2kI:-NxNc40i6txBNxKenybT:b3m3uhy) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/end_to_end_test.rs#L136)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why did you choose these numbers?
</blockquote></details>

These are the lengths of the invoke json.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxMl5kGElzLmzyYYXWR:-NxNcjE2AtD8YQu-Tv23:b-kw7wn6) ([raw file](https://github.com/starkware-libs/mempool/blob/a8f09b9972f024d848ffa99253366a3f47007b16/crates/gateway/tests/end_to_end_test.rs#L196)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Yes, borrowing issue...


<!-- Sent from Reviewable.io -->

2024-05-09 08:44 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxRT96c6yp1BECA6BrV:-NxRT96c6yp1BECA6BrW:btu7ozy) ([raw file](https://github.com/starkware-libs/mempool/blob/7ebf6052ab91bbd7308ba444629aac634f8750b4/crates/gateway/src/gateway_test.rs#L55)):*
> ```XML
>         .max_signature_length = TOO_SMALL_SIGNATURE_LENGTH;
> 
>     let (tx_gateway_to_mempool, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
> ```

Change to `_` if unused.



_Code quote:_
```XML
 _rx_gateway_to_mempool
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxRVqyC6I03dSIJFK2B:-NxRVqyC6I03dSIJFK2C:b-wo0s8w) ([raw file](https://github.com/starkware-libs/mempool/blob/7ebf6052ab91bbd7308ba444629aac634f8750b4/crates/gateway/tests/end_to_end_test.rs#L115)):*
> ```XML
> }
> 
> const TEST_FILES_FOLDER: &str = "./tests/fixtures";
> ```

Move to top of file?



_Code quote:_
```XML
const TEST_FILES_FOLDER: &str = "./tests/fixtures";
```


<!-- Sent from Reviewable.io -->

2024-05-09 09:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxRT96c6yp1BECA6BrV:-NxRiLJs89VOGkH0jsv3:b-1yh73r) ([raw file](https://github.com/starkware-libs/mempool/blob/7ebf6052ab91bbd7308ba444629aac634f8750b4/crates/gateway/src/gateway_test.rs#L55)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Change to `_` if unused.
</blockquote></details>

`_` closes the channel (the receiver was dropped). In this case, the test fails on `SendError`.


<!-- Sent from Reviewable.io -->

2024-05-09 14:32 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxRVqyC6I03dSIJFK2B:-NxSkJEf1w1F0hgCCrRc:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/7ebf6052ab91bbd7308ba444629aac634f8750b4/crates/gateway/tests/end_to_end_test.rs#L115)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Move to top of file?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-12 07:06 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfa1Jq0LndbDlqB-qI:-Nxfa1Jq0LndbDlqB-qJ:b-u996jm) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L46)):*
> ```XML
>     gateway_state: GatewayState,
>     network: Arc<GatewayNetworkComponent>,
> }
> ```

Why Arc?
Is it because of this? `A workaround for enabling clone for the state.` Is it possible to derive `Clone` for the network component?



_Suggestion:_
```XML
#[derive(Clone)]
pub struct AppState {
    gateway_state: GatewayState,
    network: GatewayNetworkComponent,
}
```
___
*[`crates/gateway/src/gateway.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfb03D6dtB2Mamz7aB:-Nxfb03D6dtB2Mamz7aC:bmtv1u2) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L59)):*
> ```XML
> 
>     // TODO(Arni, 7/5/2024): Change this function to accept GatewayConfig.
>     /// Sets up the router with the specified routes for the server.
> ```

Please delete :).
I have another TODO in this file - about Squashing `stateless_transaction_validator_config` into network config.



_Code quote:_
```XML
    // TODO(Arni, 7/5/2024): Change this function to accept GatewayConfig.
    /// Sets up the router with the specified routes for the server.
```


<!-- Sent from Reviewable.io -->

2024-05-12 07:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfa1Jq0LndbDlqB-qI:-NxffyBY5jL282mEWRmW:b2uvw4o) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L46)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why Arc?
Is it because of this? `A workaround for enabling clone for the state.` Is it possible to derive `Clone` for the network component?
</blockquote></details>

Correct.
Note that `GatewayNetworkComponent` doesn't implement `Clone`, as the [receiver](https://github.com/starkware-libs/mempool/blob/dbc3e6459a9ee94ff0bb51e607e0d9438afeb30b/crates/mempool_infra/src/network_component.rs#L13) doesn't implement `Clone` since there is a single channel to receive.
___
*[`crates/gateway/src/gateway.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfb03D6dtB2Mamz7aB:-NxfgnR33uewkkOUHHeR:brv7hwf) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please delete :).
I have another TODO in this file - about Squashing `stateless_transaction_validator_config` into network config.
</blockquote></details>

Not sure I get it :)
I didn't create this task. Are you saying that the PR addresses this specific todo?


<!-- Sent from Reviewable.io -->

2024-05-12 08:20 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfb03D6dtB2Mamz7aB:-Nxfspcz1B__AWxtCx_R:b-7tcdgi) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I get it :)
I didn't create this task. Are you saying that the PR addresses this specific todo?
</blockquote></details>

Yes, This PR addresses this issue. Thank you.


<!-- Sent from Reviewable.io -->

2024-05-12 08:26 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfu0-v8EEsw_wUhlE-:-Nxfu0-wEwleFE9W8QdX:b-leufkj) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L67)):*
> ```XML
>         };
> 
>         // A workaround for enabling clone for state.
> ```

Please remove. 
1. Please address this issue here: https://reviewable.io/reviews/starkware-libs/mempool/121#-NxftI5t39GATgcQc3Nk
2. This is not a workaround, it is a design choice (That I like) :)



_Code quote:_
```XML
        // A workaround for enabling clone for state.
```


<!-- Sent from Reviewable.io -->

2024-05-12 09:53 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 17 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 59 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfb03D6dtB2Mamz7aB:-NxgDHLf27HT640Bhe8k:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yes, This PR addresses this issue. Thank you.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/mempool/106#-Nxfu0-v8EEsw_wUhlE-:-NxgDGHRE_l32ucEq8dK:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/e6c391672c44499c92921d5354b6940233a48c0a/crates/gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please remove. 
1. Please address this issue here: https://reviewable.io/reviews/starkware-libs/mempool/121#-NxftI5t39GATgcQc3Nk
2. This is not a workaround, it is a design choice (That I like) :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-12 15:27 UTC, ArniStarkware reviewed
> Reviewed 1 of 15 files at r1, 5 of 11 files at r2, 1 of 8 files at r5, 3 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 18 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-12 15:40 UTC, ArniStarkware commented
*[`crates/gateway/src/gateway.rs` line 138 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxhQrG7B8YTaImDo0l5:-NxhQrG7B8YTaImDo0l6:b-ls0dsu) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L138)):*
> ```XML
>         thin_transaction,
>     ))
> }
> ```

If you want to wrap all the validations in one function, this function should not return anything.
(I think it is pointless to wrap all validations in one function - it is going to be just two validations - one very simple (the stateless) - one more complicated - the stateful).

Thin transaction has nothing to do with validations. Create the thin transaction outside of this function.



_Suggestion:_
```XML
fn validate_transaction(
    validator: StatelessTransactionValidator,
    transaction: ExternalTransaction,
) -> GatewayResult<()> {
    // TODO(Arni, 1/5/2024): Preform congestion control.

    // Perform stateless validations.
    validator.validate(&transaction)?;

    // TODO(Yael, 1/5/2024): Preform state related validations.
    // TODO(Arni, 1/5/2024): Move transaction to mempool. - delete this line - this is `network_component.send(..)`.

    // TODO(Arni, 1/5/2024): Produce response. - This is not part of validation.
    // Send response.

    // TODO(Yael, 15/5/2024): Add tx converter. - Isn't it exactly what `thin_transaction` is for?

    Ok(())
}
```


<!-- Sent from Reviewable.io -->

2024-05-15 06:26 UTC, elintul reviewed
> Reviewed 5 of 11 files at r2, 1 of 8 files at r5, 6 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 12 of 18 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-15 06:52 UTC, elintul reviewed
> Reviewed 1 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 72 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuwYOMCdjitS0yhYst:-NxuwYOMCdjitS0yhYsu:br1pa1r) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L72)):*
> ```XML
> }
> 
> async fn is_alive() -> GatewayResult<String> {
> ```

Please add a header for the GW handlers.



_Code quote:_
```XML
async fn is_alive() -> GatewayResult<String> {
```
___
*[`crates/gateway/src/gateway.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuwUim6gpIDA5hpVfh:-NxuwUinAH3clhjSOcTD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L76)):*
> ```XML
> }
> 
> async fn add_transaction(
> ```





_Suggestion:_
```XML
add_tx
```
___
*[`crates/gateway/src/gateway.rs` line 78 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuwewW3C0OPNxuVfd4:-NxuwewW3C0OPNxuVfd5:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L78)):*
> ```XML
> async fn add_transaction(
>     State(app_state): State<AppState>,
>     Json(transaction): Json<ExternalTransaction>,
> ```





_Suggestion:_
```XML
Json(tx)
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuvbaQ5ky9lzr4tjji:-NxuvbaQ5ky9lzr4tjjj:bvw9c7) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/starknet_api_test_utils.rs#L23)):*
> ```XML
>     Invoke,
> }
> ```

Please move to SN API.
Regardless, should appear in a separate PR.


<!-- Sent from Reviewable.io -->

2024-05-16 06:09 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 18 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--wbzDDTHWRNqF7SS:-Ny--wbzDDTHWRNqF7ST:b-djpt87) (no related file):*
Please change `transaction -> tx` in function and variable names (i.e., snakecase); `Tx -> Transaction` in enum and struct names (i.e., camelcase). 
Can be done in another PR.

___
___
*[`crates/gateway/src/gateway.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--OHa03WY90F-9SCl:-Ny--OHa03WY90F-9SCm:b-nds623) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L76)):*
> ```XML
> }
> 
> async fn add_transaction(
> ```

No `unwrap`s should appear in prod. code; we should handle the errors. Since it's user-facing, perhaps we should use `anyhow`.
___
*[`crates/gateway/src/gateway.rs` line 85 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny---HhBMYFbW9dHp_5:-Ny---HhBMYFbW9dHp_6:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L85)):*
> ```XML
>     .await?;
> 
>     println!("Validation result: {:?}", validation_result);
> ```

Remove.



_Code quote:_
```XML
println!("Validation result: {:?}", validation_result);
```
___
*[`crates/gateway/src/gateway.rs` line 88 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--Iuh0ggw0PoJ2bC-:-Ny--Iuh0ggw0PoJ2bC0:b92okrw) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L88)):*
> ```XML
> 
>     match validation_result {
>         Err(e) => Err(e),
> ```

Doesn't the `?` after the `await` above do exactly that?



_Code quote:_
```XML
Err(e) => Err(e),
```
___
*[`crates/gateway/src/gateway.rs` line 94 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--i7U1tN194yd9Xwn:-Ny--i7U1tN194yd9Xwo:b-eamjs5) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L94)):*
> ```XML
>                 address: ContractAddress::default(),
>                 state: AccountState { nonce: Nonce::default() },
>             };
> ```

`derive(Default)`?
Although having a default address is a bit weird, but it's already there.



_Code quote:_
```XML
            let account = Account {
                address: ContractAddress::default(),
                state: AccountState { nonce: Nonce::default() },
            };
```
___
*[`crates/gateway/src/gateway.rs` line 98 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--pvL5CyTPyFhtwnS:-Ny--pvL5CyTPyFhtwnT:b-hjs2yv) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L98)):*
> ```XML
>             let message = GatewayToMempoolMessage::AddTx(thin_transaction, account);
>             task::spawn(async move {
>                 app_state.network_component.send(message).await.unwrap();
> ```

A thinner access would be nice.



_Code quote:_
```XML
app_state.network_component.send
```


<!-- Sent from Reviewable.io -->

2024-05-16 07:08 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 20 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-DMTB9JIlIMKCL4HG:-Ny-DMTB9JIlIMKCL4HH:b3bmxy6) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L136)):*
> ```XML
> 
>     // Initialize Mempool.
>     let mempool = Arc::new(Mutex::new(Mempool::new([], mempool_to_gateway_network)));
> ```

Please add `empty` c-tor.



_Code quote:_
```XML
Mempool::new([]
```
___
*[`crates/gateway/tests/routing_test.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-DosF7HmTEuZVivBb:-Ny-DosF7HmTEuZVivBc:b3nn3lb) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/routing_test.rs#L19)):*
> ```XML
> 
> const TEST_FILES_FOLDER: &str = "./tests/fixtures";
> ```

Why did this file change?


<!-- Sent from Reviewable.io -->

2024-05-16 07:13 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 20 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuvbaQ5ky9lzr4tjji:-Ny-EmDaE2Ra9DCZtNct:bdh7qr1) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/starknet_api_test_utils.rs#L23)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please move to SN API.
Regardless, should appear in a separate PR.
</blockquote></details>

I don't think it's better to add many temporary getters; maybe simply implement the converter?


<!-- Sent from Reviewable.io -->

2024-05-16 07:15 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 21 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-EzQi5PhytcWsuucy:-Ny-EzQi5PhytcWsuucz:bo28nlr) (no related file):*
PR split suggestion (`|` means "independently of"):
- Gateway change | (unused at this stage) utils | E2E test frame.
- Connecting the changes of the GW by thickening E2E test.
- Rest of test changes (not sure why they changed).

___


<!-- Sent from Reviewable.io -->

2024-05-16 08:59 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 13 of 18 files reviewed, 21 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--wbzDDTHWRNqF7SS:-Ny-bHAO7KVozU3PY9Ae:b-mke0f5) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please change `transaction -> tx` in function and variable names (i.e., snakecase); `Tx -> Transaction` in enum and struct names (i.e., camelcase). 
Can be done in another PR.
</blockquote></details>

Handled in a separate PR:
https://github.com/starkware-libs/mempool/pull/140

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-EzQi5PhytcWsuucy:-Ny-c8PK-SV5bH2ag-pN:bwxneh5) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

PR split suggestion (`|` means "independently of"):
- Gateway change | (unused at this stage) utils | E2E test frame.
- Connecting the changes of the GW by thickening E2E test.
- Rest of test changes (not sure why they changed).
</blockquote></details>

I've opened a PR for GW changes:
https://reviewable.io/reviews/starkware-libs/mempool/133

___
___
*[`crates/gateway/src/gateway.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuwUim6gpIDA5hpVfh:-Ny-bQqH4C84a54Bbq6q:b31222b) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L76)):*
> ```XML
> }
> 
> async fn add_transaction(
> ```

handled [here](https://github.com/starkware-libs/mempool/pull/140).
___
*[`crates/gateway/src/gateway.rs` line 78 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuwewW3C0OPNxuVfd4:-Ny-bTfB1DCRnniNv71y:b31222b) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L78)):*
> ```XML
> async fn add_transaction(
>     State(app_state): State<AppState>,
>     Json(transaction): Json<ExternalTransaction>,
> ```

handled [here](https://github.com/starkware-libs/mempool/pull/140).


<!-- Sent from Reviewable.io -->

2024-05-16 13:59 UTC, ArniStarkware reviewed
> Reviewed 1 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 14 of 18 files reviewed, 17 unresolved discussions (waiting on @ayeletstarkware, @elintul, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-16 15:33 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 18 files reviewed, 14 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-EzQi5PhytcWsuucy:-Ny10syH94_97DEvcvPp:b-6er9w4) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I've opened a PR for GW changes:
https://reviewable.io/reviews/starkware-libs/mempool/133
</blockquote></details>

Opened a new PR that implements the test utils:
https://github.com/starkware-libs/mempool/pull/145

___
___
*[`crates/gateway/src/gateway.rs` line 88 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--Iuh0ggw0PoJ2bC-:-Ny0tx-K1t0iIETWZ6lZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Doesn't the `?` after the `await` above do exactly that?
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 138 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxhQrG7B8YTaImDo0l5:-Ny0uNrk-GH-akf827pM:bxhhnh6) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L138)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If you want to wrap all the validations in one function, this function should not return anything.
(I think it is pointless to wrap all validations in one function - it is going to be just two validations - one very simple (the stateless) - one more complicated - the stateful).

Thin transaction has nothing to do with validations. Create the thin transaction outside of this function.
</blockquote></details>

Was handled [here](https://reviewable.io/reviews/starkware-libs/mempool/133)
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxuvbaQ5ky9lzr4tjji:-Ny10cnf9HP4yF4KdJRJ:bcpn5ja) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/starknet_api_test_utils.rs#L23)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't think it's better to add many temporary getters; maybe simply implement the converter?
</blockquote></details>

Implemented [here](https://github.com/starkware-libs/mempool/pull/145).
AFAIK, `starkent_api_test_util` is a temp file, that should be implemented in SN_API.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-DMTB9JIlIMKCL4HG:-Ny0yRhQBo11qyM26_dy:b3snenr) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L136)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add `empty` c-tor.
</blockquote></details>

As a test util?
___
*[`crates/gateway/tests/routing_test.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-DosF7HmTEuZVivBb:-Ny0yYAy4crOfKWFbnQk:bhitrkh) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/routing_test.rs#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why did this file change?
</blockquote></details>

Now it's part of [this](https://reviewable.io/reviews/starkware-libs/mempool/133) PR.
Also explained there.


<!-- Sent from Reviewable.io -->

2024-05-16 15:37 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 9 of 18 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny11GZUAG21QSQnpkDx:-Ny11GZUAG21QSQnpkDy:bmzgsgq) (no related file):*
Preceding PRs for review:
1. GW changes: https://reviewable.io/reviews/starkware-libs/mempool/133
2. Mempool changes: https://reviewable.io/reviews/starkware-libs/mempool/119
3. Utils: https://reviewable.io/reviews/starkware-libs/mempool/145

___


<!-- Sent from Reviewable.io -->

2024-05-20 07:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 7 of 18 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 76 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--OHa03WY90F-9SCl:-NyJbDfj-uAIgZCHW__p:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L76)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No `unwrap`s should appear in prod. code; we should handle the errors. Since it's user-facing, perhaps we should use `anyhow`.
</blockquote></details>

Done.
___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny-DMTB9JIlIMKCL4HG:-NyJc6KtAetT34iqmhNo:b2dorpw) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L136)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

As a test util?
</blockquote></details>

Added in mempool.rs


<!-- Sent from Reviewable.io -->

2024-05-21 09:05 UTC, elintul reviewed
> Reviewed 3 of 9 files at r8, 2 of 5 files at r9, 6 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 17 of 18 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 70 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPNu6AEkqz8SXvzkZ1:-NyPNu6AEkqz8SXvzkZ2:ba3dfmt) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/gateway/src/gateway.rs#L70)):*
> ```XML
> 
> // Gateway handlers.
> /// Checks if the gateway is alive.
> ```

Remove.



_Code quote:_
```XML
/// Checks if the gateway is alive.
```
___
*[`crates/mempool/src/mempool.rs` line 57 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPOJOoCVn00FUptfdz:-NyPOJOp-i20hCWYzjT0:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/mempool/src/mempool.rs#L57)):*
> ```XML
>     }
> 
>     pub fn empty_mempool(network: MempoolNetworkComponent) -> Self {
> ```





_Suggestion:_
```XML
empty
```


<!-- Sent from Reviewable.io -->

2024-05-21 09:27 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 15 of 18 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 98 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-Ny--pvL5CyTPyFhtwnS:-NyPT9fM5GaEidzu8nx4:bsfzzgt) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/src/gateway.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A thinner access would be nice.
</blockquote></details>

Any suggestion? :)


<!-- Sent from Reviewable.io -->

2024-05-21 09:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 15 of 18 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxIHB2q3N8Sn5bs88mk:-NyPTrzi1dLl_TsCkgfa:b-80ul4c) ([raw file](https://github.com/starkware-libs/mempool/blob/39301784e9c93789cbaf25882eb1cd3b1014512c/crates/gateway/src/gateway.rs#L120)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's temporal.
Added a TODO.
</blockquote></details>

Stale


<!-- Sent from Reviewable.io -->

2024-05-21 10:27 UTC, elintul requested changes
> Reviewed 1 of 3 files at r12, 2 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 70 at r14](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPfkgIB90sahg5k0oe:-NyPfkgIB90sahg5k0of:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/37205a7e949f90d4aa977bc43c82e16351347931/crates/gateway/src/gateway.rs#L70)):*
> ```XML
> 
> // Gateway handlers.
> async fn is_alive() -> GatewayResult<String> {
> ```





_Suggestion:_
```XML
// Gateway handlers.

async fn is_alive() -> GatewayResult<String> {
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 26 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPOmZr7kWTC6tiGGtr:-NyPOmZr7kWTC6tiGGts:b-vn1vi3) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/gateway/tests/end_to_end_test.rs#L26)):*
> ```XML
> const TEST_FILES_FOLDER: &str = "./tests/fixtures";
> 
> pub fn create_default_account() -> Account {
> ```

Change to `derive::Default`, can be done in another PR.



_Code quote:_
```XML
Account
```
___
*[`crates/mempool/src/mempool.rs` line 157 at r14](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPfw9V9BHtyQs1PJGz:-NyPfw9V9BHtyQs1PJH-:b-s6361f) ([raw file](https://github.com/starkware-libs/mempool/blob/37205a7e949f90d4aa977bc43c82e16351347931/crates/mempool/src/mempool.rs#L157)):*
> ```XML
>                 self.batcher_tx.send(txs).await?;
>                 Ok(())
>             }
> ```

Waiting for this PR to be `rebase`d over Batcher network component.


<!-- Sent from Reviewable.io -->

2024-05-21 10:40 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 157 at r14](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPfw9V9BHtyQs1PJGz:-NyPil222fkb6HQAfvaY:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/37205a7e949f90d4aa977bc43c82e16351347931/crates/mempool/src/mempool.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Waiting for this PR to be `rebase`d over Batcher network component.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 10:44 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 26 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPOmZr7kWTC6tiGGtr:-NyPk23j9djkO0YLRbws:b-yurfp2) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/gateway/tests/end_to_end_test.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Change to `derive::Default`, can be done in another PR.
</blockquote></details>

Removed, as it's not in use anymore.


<!-- Sent from Reviewable.io -->

2024-05-21 10:49 UTC, elintul reviewed
> Reviewed 4 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 17 at r15](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPkwbV5gLK_ZcWXQMO:-NyPkwbV5gLK_ZcWXQMP:bv0np06) ([raw file](https://github.com/starkware-libs/mempool/blob/6426c74b4104aab3908ef80ebd5d2a13eee5f133/crates/gateway/src/gateway.rs#L17)):*
> ```XML
> use crate::starknet_api_test_utils::get_sender_address;
> use crate::stateless_transaction_validator::StatelessTransactionValidator;
> use crate::utils::external_tx_to_thin_tx;
> ```

Will this be moved to SN API?



_Code quote:_
```XML
crate::utils::external_tx_to_thin_tx
```


<!-- Sent from Reviewable.io -->

2024-05-21 10:55 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 11 files at r2, 2 of 9 files at r8, 2 of 5 files at r9, 4 of 7 files at r11, 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106#-:-NyPmi6v-aT1hvNTFr6S:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-05-21 11:41 UTC, ArniStarkware approved these changes
> Reviewed 1 of 9 files at r8, 1 of 7 files at r11, 4 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 121 at r15](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyPvNqt1lV9cIy3Jrni:-NyPvNqu3I-NCOdeTNhL:bb46lf4) ([raw file](https://github.com/starkware-libs/mempool/blob/6426c74b4104aab3908ef80ebd5d2a13eee5f133/crates/gateway/tests/end_to_end_test.rs#L121)):*
> ```XML
> 
>     let (tx_batcher_to_mempool, rx_batcher_to_mempool) = channel::<BatcherToMempoolMessage>(1);
>     let (tx_mempool_to_batcher, mut rx_mempool_to_batcher) = channel::<MempoolToBatcherMessage>(1);
> ```

Extract to a function? `initizalize_mempool_network_channels`.

Or even include the creating of the `batcher_channels`.



_Code quote:_
```XML
    let (tx_batcher_to_mempool, rx_batcher_to_mempool) = channel::<BatcherToMempoolMessage>(1);
    let (tx_mempool_to_batcher, mut rx_mempool_to_batcher) = channel::<MempoolToBatcherMessage>(1);
```


<!-- Sent from Reviewable.io -->

2024-05-21 12:01 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 11 files at r2, 1 of 8 files at r5, 2 of 12 files at r7, 3 of 9 files at r8, 2 of 5 files at r9, 6 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106#-:-NyQ0i1i89eZDBda0UNr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 92 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxwGbSl5D0JYy7jqMgr:-NxwGbSl5D0JYy7jqMgs:baexo8h) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L92)):*
> ```XML
> 
>     // Ensure the server has time to start up
>     sleep(Duration::from_millis(1000)).await;
> ```

In general better avoid long sleeps, it slows down tests and can create false negatives in case there are network issues.

Polling + timeouts are probably better, but we can address this issue later.



_Code quote:_
```XML
    // Ensure the server has time to start up
    sleep(Duration::from_millis(1000)).await;
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 93 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxwJN977iPjvNiCauJz:-NxwJN977iPjvNiCauK-:b-hnljb1) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L93)):*
> ```XML
>     // Ensure the server has time to start up
>     sleep(Duration::from_millis(1000)).await;
>     (ip, port)
> ```

Later, not in this PR.

Rationale: they are always used together i think.



_Suggestion:_
```XML
    SocketAddr::from((ip, port))
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 105 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxwJdfoAZJT4bAs380d:-NxwJdfoAZJT4bAs380e:b-850w3d) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L105)):*
> ```XML
>     let request = Request::builder()
>         .method("POST")
>         .uri(format!("http://{}", SocketAddr::from((ip, port))) + "/add_transaction")
> ```

Later



_Suggestion:_
```XML
async fn send_and_verify_transaction(
    socket_addr: SocketAddr,
    json_file_path: &Path,
    expected_response: &str,
) {
    let tx_json = fs::read_to_string(json_file_path).unwrap();
    let uri = format!("http://{socket_addr}/add_transaction");
    let request = Request::post(uri)
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 111 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NxwKhly6BkhRUigyVac:-NxwKhly6BkhRUigyVad:b73scwr) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L111)):*
> ```XML
> 
>     // Create a client
>     let client = Client::new();
> ```

Later. 

+ other comments that can be understood from the good variable naming



_Suggestion:_
```XML

    let client = Client::new();
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyQ0U9TC24Ut_9zgpbn:-NyQ0U9UA-Mia5_ZJ_1r:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L136)):*
> ```XML
> 
>     // Initialize Mempool.
>     let mempool = Arc::new(Mutex::new(Mempool::new([], mempool_to_gateway_network)));
> ```





_Suggestion:_
```XML
    let mempool = Arc::new(Mutex::new(Mempool::empty_mempool(mempool_to_gateway_network)));
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 147 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyQ0Do19zzg3sdPUKKv:-NyQ0Do19zzg3sdPUKKw:bzdz3rg) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L147)):*
> ```XML
> 
>     // Wait for the listener to receive the transactions.
>     sleep(Duration::from_secs(2)).await;
> ```

Same (nonblocking) commment on sleeps as above.



_Code quote:_
```XML
    sleep(Duration::from_secs(2)).await;
```
___
*[`crates/mempool/src/mempool.rs` line 57 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyQ0Zjj-9w5DheJYZAJ:-NyQ0Zjj-9w5DheJYZAK:bjtloih) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/mempool/src/mempool.rs#L57)):*
> ```XML
>     }
> 
>     pub fn empty_mempool(network: MempoolNetworkComponent) -> Self {
> ```

Canonical naming



_Suggestion:_
```XML
 pub fn empty(network: MempoolNetworkComponent) -> Self {
```


<!-- Sent from Reviewable.io -->

2024-05-21 12:02 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-21 12:07 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyQ0U9TC24Ut_9zgpbn:-NyQ1x-F8fka9wc9Hflq:bze417v) ([raw file](https://github.com/starkware-libs/mempool/blob/ebdc04a7a3c2c85e7606a06a7988fe09e7ad2442/crates/gateway/tests/end_to_end_test.rs#L136)):*
> ```XML
> 
>     // Initialize Mempool.
>     let mempool = Arc::new(Mutex::new(Mempool::new([], mempool_to_gateway_network)));
> ```

Stale?
___
*[`crates/mempool/src/mempool.rs` line 57 at r11](https://reviewable.io/reviews/starkware-libs/mempool/106#-NyQ0Zjj-9w5DheJYZAJ:-NyQ24ue9TUKRaGNDiWL:b-khk451) ([raw file](https://github.com/starkware-libs/mempool/blob/9ea0417312362e06a35b0896eb712b7d68f58bd6/crates/mempool/src/mempool.rs#L57)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Canonical naming
</blockquote></details>

stale?


<!-- Sent from Reviewable.io -->

2024-05-21 12:07 UTC, merged