feat: send add tx requests through network channel
starkware-libs/mempool pull request #133
Opened 2024-05-15 14:09 UTC by MohammadNassar1

2024-05-16 06:09 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny--g2cEoHy2-wxZ7wD:-Ny--g2cEoHy2-wxZ7wE:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L93)):*
> ```XML
>     .unwrap();
>     Ok(res.0)
> }
> ```





_Suggestion:_
```XML
async fn add_transaction(
    State(app_state): State<AppState>,
    Json(transaction): Json<ExternalTransaction>,
) -> GatewayResult<String> {
    let result = tokio::task::spawn_blocking(move || {
        validate_transaction(app_state.stateless_transaction_validator, transaction)
    })
    .await??;

    let (response, thin_transaction, account) = result;

    let message = GatewayToMempoolMessage::AddTx(thin_transaction, account);
    task::spawn(async move {
        app_state.network_component.send(message).await.unwrap();
    })
    .await
    .unwrap();
    Ok(response)
}
```
___
*[`crates/gateway/src/gateway.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-NxzzfpBDVSySEYwWl1O:-NxzzfpC0xOmGzi_9y4m:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L98)):*
> ```XML
>     validator: StatelessTransactionValidator,
>     transaction: ExternalTransaction,
> ) -> GatewayResult<(String, ThinTransaction, Account)> {
> ```





_Suggestion:_
```XML
fn validate_and_pre_process(
    validator: StatelessTransactionValidator,
    transaction: ExternalTransaction,
) -> GatewayResult<(String, ThinTransaction, Account)> {
```
___
*[`crates/gateway/src/gateway.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Nxzzjmx73kl7ztuBKUg:-Nxzzjmx73kl7ztuBKUh:b-bsnr4p) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L105)):*
> ```XML
> 
>     // TODO(Yael, 1/5/2024): Preform state related validations.
>     // TODO(Arni, 1/5/2024): Move transaction to mempool.
> ```

This is what the network component is doing :)


<!-- Sent from Reviewable.io -->

2024-05-16 07:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Nxzyp0A77A0dYLZyxs0:-Ny-DnEh8JrxPsQZmRq4:b1jo4qb) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L84)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we have to clone the result here?
I think it is ok if the ownership will be passed to the `GatewayToMempoolMessage`
</blockquote></details>

For now, I added Copy trait to `ThinTransaction`.
Once we start using `SN_API` transaction we need to clone, as they do not implement `Copy`.
___
*[`crates/gateway/src/gateway.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-NxzzEZGAvPKtfFoyyNG:-Ny-Hx5ZAq8_fiLo6w3f:bloenow) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L89)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why is it inside a `task::spawn`?
</blockquote></details>

You're right.
It shouldn't.
Updated.
___
*[`crates/gateway/src/gateway.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny--g2cEoHy2-wxZ7wD:-Ny-EVpE0qrnrs08IaMY:b-83sjoh) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L93)):*
> ```XML
>     .unwrap();
>     Ok(res.0)
> }
> ```

Nice!
___
*[`crates/gateway/src/gateway.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-NxzzfpBDVSySEYwWl1O:-Ny-EaA295by9BS6JoLR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L98)):*
> ```XML
>     validator: StatelessTransactionValidator,
>     transaction: ExternalTransaction,
> ) -> GatewayResult<(String, ThinTransaction, Account)> {
> ```

Done.
___
*[`crates/gateway/src/gateway.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Nxzzjmx73kl7ztuBKUg:-Ny-EcbxCaFEg8vBJmgu:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L105)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is what the network component is doing :)
</blockquote></details>

Done
___
*[`crates/gateway/src/gateway.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-1Esr3JPp1e09aV37:-Ny-FkT_ANyxlIOCSLGo:b-tkuitu) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L117)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we need this to be returned? I think we can remove it and just return `Ok()` from `add_transaction`
</blockquote></details>

The `add transaction` function should return specific information to the client based on the transaction type:

-   For `invoke` transactions, return the transaction hash.
-   For `deploy account` transactions, return the contract address.
-   For `declare` transactions, return the class hash.

Currently, we are returning the transaction type as a temporary  until these calculations are done. Please note that this approach is not new and was not introduced in the current PR.

I think we should return something, so in gateway test we can test different trasnactions.


<!-- Sent from Reviewable.io -->

2024-05-16 07:35 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-JYaJ2FyGg8xuJt6Y:-Ny-JYaJ2FyGg8xuJt6Z:baceyls) ([raw file](https://github.com/starkware-libs/mempool/blob/4f3c51274932ee2fa98148064edcfb6c74e39566/crates/mempool_types/src/mempool_types.rs#L6)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug, PartialEq, Eq)]
> pub struct ThinTransaction {
> ```

Do we still need the `Copy` trait here?
There was a discussion in `gateway.rs`, but the code has changed somewhat since then. Is the discussion still relevant?



_Suggestion:_
```XML
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ThinTransaction {
```


<!-- Sent from Reviewable.io -->

2024-05-16 08:22 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/mempool/133#-Nxzyp0A77A0dYLZyxs0:-Ny-UVi0CPtL6NtxGfvR:b23q171) ([raw file](https://github.com/starkware-libs/mempool/blob/caf3f02e7bd2bc8148dc456faf93a76c27590fb6/crates/gateway/src/gateway.rs#L84)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I am still not sure why we need to copy here at all. And I think after the last changes you made, we actually don't do a copy.
</blockquote></details>

You're right.
Now we don't need a copy.
updated.
___
*[`crates/mempool_types/src/mempool_types.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-JYaJ2FyGg8xuJt6Y:-Ny-USU8E0n8VYU4t6TL:b2oz6m) ([raw file](https://github.com/starkware-libs/mempool/blob/4f3c51274932ee2fa98148064edcfb6c74e39566/crates/mempool_types/src/mempool_types.rs#L6)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we still need the `Copy` trait here?
There was a discussion in `gateway.rs`, but the code has changed somewhat since then. Is the discussion still relevant?
</blockquote></details>

Got it, correct.
Done.


<!-- Sent from Reviewable.io -->

2024-05-16 08:49 UTC, dafnamatsry approved these changes
> Reviewed 1 of 2 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-16 10:05 UTC, ArniStarkware requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny-bEsT-V0YblUig569:bgex789) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
> ```XML
>         rx_gateway_to_mempool,
>     )
> }
> ```

why even return the second member? where is it used?



_Suggestion:_
```XML
#[fixture]
pub fn network_component_and_mempool_reciver() -> (GatewayNetworkComponent, Receiver<GatewayToMempoolMessage>) {
    let (tx_gateway_to_mempool, rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
    let (_, rx_mempool_to_gateway) = channel::<MempoolToGatewayMessage>(1);

    (
        GatewayNetworkComponent::new(tx_gateway_to_mempool, rx_mempool_to_gateway),
        rx_gateway_to_mempool,
    )
}
```


<!-- Sent from Reviewable.io -->

2024-05-16 10:05 UTC, elintul requested changes
> Reviewed 1 of 5 files at r1, 2 of 2 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qYMbDjSEOFILkVRw:-Ny-qYMbDjSEOFILkVRx:bauye2d) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L88)):*
> ```XML
> }
> 
> fn validate_and_pre_process(
> ```

Why was this separated into a function?



_Code quote:_
```XML
validate_and_pre_process
```
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oUsu0VUR3gR7XML1:-Ny-oUsu0VUR3gR7XML2:bqwf8i2) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
> ```XML
>     validator: StatelessTransactionValidator,
>     transaction: ExternalTransaction,
> ) -> GatewayResult<(String, ThinTransaction, Account)> {
> ```

`MempoolInput`? I think we already defined it. Note you import it from a location the GW should naturally know.



_Code quote:_
```XML
ThinTransaction, Account
```
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-Ny-oj_hBZxw-Vc3PxWk:b-7nte21) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
> ```XML
>     validator: StatelessTransactionValidator,
>     transaction: ExternalTransaction,
> ) -> GatewayResult<(String, ThinTransaction, Account)> {
> ```

Not needed anymore?



_Code quote:_
```XML
String
```
___
*[`crates/gateway/src/gateway_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qjwy67-b1BW1qSpA:-Ny-qjwy67-b1BW1qSpB:bbpnm34) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L24)):*
> ```XML
> 
> #[fixture]
> pub fn network_component() -> (GatewayNetworkComponent, Receiver<GatewayToMempoolMessage>) {
> ```

Can you explain why is this change needed?
Also, if it's not used in all tests, consider adding another fixture to peel off the receiver.
Same for the `gateway` fixture.



_Code quote:_
```XML
network_component
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-r0Dq8rfbOLE_G1vr:-Ny-r0Dq8rfbOLE_G1vs:b-qvvp3r) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/tests/end_to_end_test.rs#L27)):*
> ```XML
> 
>     let tx_hash = TransactionHash::default();
>     let thin_tx = create_thin_tx_for_testing(Tip::default(), tx_hash, ContractAddress::default());
> ```

Why not simply `ThinTransaction::default()`, to pass a non-zero hash?



_Code quote:_
```XML
    let tx_hash = TransactionHash::default();
    let thin_tx = create_thin_tx_for_testing(Tip::default(), tx_hash, ContractAddress::default());
```


<!-- Sent from Reviewable.io -->

2024-05-16 10:18 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qYMbDjSEOFILkVRw:-Ny-tMOM1gWESvnt3DR_:bmqnl1p) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why was this separated into a function?
</blockquote></details>

We separated the synchronization parts into a separate thread to handle multiple requests, leaving only the channel part unparallelized.
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-Ny-tv-K5_OCSKU5LyCk:b-4x70y6) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not needed anymore?
</blockquote></details>

Why?
we need to return the transaction type.
___
*[`crates/gateway/src/gateway_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qjwy67-b1BW1qSpA:-Ny-u04H96gO2O0EuM-W:bdr0lc4) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain why is this change needed?
Also, if it's not used in all tests, consider adding another fixture to peel off the receiver.
Same for the `gateway` fixture.
</blockquote></details>

Please see the below discussion with Arni.
___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny-saY4ETjzeFrVrAa7:b-rrh7gk) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

why even return the second member? where is it used?
</blockquote></details>

Good question.
It's a hack used in gateway tests, where we don't have a receiver channel.
In case we don't return the channel, the receiver will be dropped and consequently, the channel will be closed.
@Itay-Tsabary-Starkware, do you approve this hack?


<!-- Sent from Reviewable.io -->

2024-05-16 10:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-r0Dq8rfbOLE_G1vr:-Ny-v-op3BfSxgdkEbyS:bysk6yr) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/tests/end_to_end_test.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not simply `ThinTransaction::default()`, to pass a non-zero hash?
</blockquote></details>

Already handled [here](https://reviewable.io/reviews/starkware-libs/mempool/119)


<!-- Sent from Reviewable.io -->

2024-05-16 10:51 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qYMbDjSEOFILkVRw:-Ny-uiBwArQ7GmJ_cgFp:b-e2yo1r) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L88)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

We separated the synchronization parts into a separate thread to handle multiple requests, leaving only the channel part unparallelized.
</blockquote></details>

So this is the entire GW sync. task that will run in a separate thread per transaction? That's the only reason for it not to be a method. Maybe it can Should be called `process_tx`
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-Ny-uJS_7U4dIEX0BoYR:be12qwj) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why?
we need to return the transaction type.
</blockquote></details>

Why? :)
___
*[`crates/gateway/src/gateway_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qjwy67-b1BW1qSpA:-Ny-uThv5L4Lx_A1Qcx1:bnr9r4n) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please see the below discussion with Arni.
</blockquote></details>

Regardless, if there are tests that only need the gateway/network component, no need for them to unpack it to `_`; an additional fixture is cleaner.
___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny-uS1l6D0zwhBYFx3c:bcjhaqo) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good question.
It's a hack used in gateway tests, where we don't have a receiver channel.
In case we don't return the channel, the receiver will be dropped and consequently, the channel will be closed.
@Itay-Tsabary-Starkware, do you approve this hack?
</blockquote></details>

Not sure I understand.


<!-- Sent from Reviewable.io -->

2024-05-16 12:47 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny0RH_GEbf1u9HE8DZ0:b3d4rrc) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If we do use this design, Please document the reason for this hack.
</blockquote></details>

Yea, this is ok for now, will be changed when we move to the new interface.


<!-- Sent from Reviewable.io -->

2024-05-16 12:54 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, @giladchase, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny0SHnY5Vpx7rnbHOVV:b-46ras4) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Yea, this is ok for now, will be changed when we move to the new interface.
</blockquote></details>

As I said - please document.
Explain it is a hack. Explain it is for the channel to remain open.

If this is so complicated, maybe it should not be a fixture? (Add a TODO to make it a fixture again when the time comes).


<!-- Sent from Reviewable.io -->

2024-05-16 13:21 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny0YxxDCBXsqjeoawc5:bn9j0sm) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

As I said - please document.
Explain it is a hack. Explain it is for the channel to remain open.

If this is so complicated, maybe it should not be a fixture? (Add a TODO to make it a fixture again when the time comes).
</blockquote></details>

We have a circular dependency :-)
I'm waiting for this pr to be merged to start changing to the new interface...


<!-- Sent from Reviewable.io -->

2024-05-16 14:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qYMbDjSEOFILkVRw:-Ny0RSTT-CAMtidLoBqx:bjmnjnm) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So this is the entire GW sync. task that will run in a separate thread per transaction? That's the only reason for it not to be a method. Maybe it can Should be called `process_tx`
</blockquote></details>

I don't think this is the reason for the function.
Changed to `process_tx`.
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-Ny0TgtwDRKbML9AFSqb:b-9qad1a) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why? :)
</blockquote></details>

The `add_tx` should return a response to the client.
It needs to return tx hash and / or class hash.
___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oUsu0VUR3gR7XML1:-Ny0Wf796mEwDitEkXY4:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`MempoolInput`? I think we already defined it. Note you import it from a location the GW should naturally know.
</blockquote></details>

Done
___
*[`crates/gateway/src/gateway_test.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-qjwy67-b1BW1qSpA:-Ny0hz3_9wW8MtnwtMo0:b-qz4wel) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Regardless, if there are tests that only need the gateway/network component, no need for them to unpack it to `_`; an additional fixture is cleaner.
</blockquote></details>

I removed the fixture.
and added a doc explaining the hack.
___
*[`crates/gateway/src/gateway_test.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-bEsT-V0YblUig568:-Ny0hmqI2Mb1UIqiTlMq:b-qz4wel) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway_test.rs#L32)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We have a circular dependency :-)
I'm waiting for this pr to be merged to start changing to the new interface...
</blockquote></details>

I removed the fixture.
and added a doc explaining the hack.


<!-- Sent from Reviewable.io -->

2024-05-20 09:12 UTC, elintul reviewed
> Reviewed 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-NyKGUoB-oXrV2g1_PUx:bbwgs3k) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The `add_tx` should return a response to the client.
It needs to return tx hash and / or class hash.
</blockquote></details>

Can we give up on the string by now?
___
*[`crates/gateway/tests/routing_test.rs` line 52 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKG2HfC1wzyAhAPOlO:-NyKG2HfC1wzyAhAPOlP:b-88ucpi) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/tests/routing_test.rs#L52)):*
> ```XML
> 
> async fn check_request(request: Request<Body>, status_code: StatusCode) -> Bytes {
>     let ip = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));
> ```

Why not a fixture anymore? Are we instantiating a new GW for each request we send?


<!-- Sent from Reviewable.io -->

2024-05-20 09:32 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKKRDB8G_EbxHJvMC-:-NyKKRDB8G_EbxHJvMC0:b-u4w664) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L75)):*
> ```XML
>     Json(tx): Json<ExternalTransaction>,
> ) -> GatewayResult<String> {
>     let result = tokio::task::spawn_blocking(move || {
> ```

Do we want to use `spawn` here?



_Code quote:_
```XML
spawn_blocking
```
___
*[`crates/gateway/src/gateway.rs` line 80 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKKXSY8Yu259Cijzdl:-NyKKXSY8Yu259Cijzdm:br6055b) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L80)):*
> ```XML
>     .await??;
> 
>     let (response, mempool_input) = result;
> ```

Please unpack in the previous line; feels like `result` isn't really needed.



_Code quote:_
```XML
let (response, mempool_input) = result;
```
___
*[`crates/gateway/src/gateway.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKKeLb30eUJQ8kaqbY:-NyKKeLb30eUJQ8kaqbZ:b4u7wi1) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L82)):*
> ```XML
>     let (response, mempool_input) = result;
>     let message = GatewayToMempoolMessage::AddTransaction(mempool_input);
>     app_state.network_component.send(message).await.unwrap();
> ```

Handle errors (use `anyhow`, or the error-handling convention of `axum`).



_Code quote:_
```XML
unwrap
```


<!-- Sent from Reviewable.io -->

2024-05-20 10:18 UTC, giladchase requested changes
> Reviewed 1 of 2 files at r5, 1 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKJ9qH3tRE5bitkL-3:-NyKJ9qH3tRE5bitkL-4:b-7xyn9s) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L72)):*
> ```XML
> 
> async fn add_tx(
>     State(app_state): State<AppState>,
> ```

Plz make sure with dafna that this is OK, cause she added the async_add_tx specifically 



_Code quote:_
```XML
async fn add_tx(
    State(app_state): State<AppState>,
```
___
*[`crates/gateway/src/gateway.rs` line 80 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKIR9-BcXI8bHxdQz1:-NyKIR9-BcXI8bHxdQz2:b-izt6yx) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L80)):*
> ```XML
>     .await??;
> 
>     let (response, mempool_input) = result;
> ```

Either that or change the name of the variable from`result` 



_Suggestion:_
```XML
    let result = tokio::task::spawn_blocking(move || {
        process_tx(app_state.stateless_transaction_validator, tx)
    })
    .await?;

    let (response, mempool_input) = result?;
```
___
*[`crates/gateway/src/gateway.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKIv0S5peH9B-yxtAF:-NyKIv0S5peH9B-yxtAG:b-7okk2b) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L82)):*
> ```XML
>     let (response, mempool_input) = result;
>     let message = GatewayToMempoolMessage::AddTransaction(mempool_input);
>     app_state.network_component.send(message).await.unwrap();
> ```

And add an error variant if one doesn't exist already



_Suggestion:_
```XML
    app_state.network_component.send(message).await?;
```


<!-- Sent from Reviewable.io -->

2024-05-20 10:18 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133#-:-NyKVaWE2oH6XmHzGhMT:bnfp4nl)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-20 12:02 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKJ9qH3tRE5bitkL-3:-NyKqPVz4eKPNIYFwxg7:bs31b4c) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L72)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz make sure with dafna that this is OK, cause she added the async_add_tx specifically
</blockquote></details>

@dafnamatsry approved this.
___
*[`crates/gateway/src/gateway.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKKRDB8G_EbxHJvMC-:-NyKrKdJDgk1FyB7D1iB:b-in49ob) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to use `spawn` here?
</blockquote></details>

We want to open a thread for each tx.
___
*[`crates/gateway/src/gateway.rs` line 80 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKIR9-BcXI8bHxdQz1:-NyKrefT3k8aVV4J-PGd:b-hmjqxu) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L80)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Either that or change the name of the variable from`result`
</blockquote></details>

I've removed the `result`. It's not in use.
___
*[`crates/gateway/src/gateway.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKKeLb30eUJQ8kaqbY:-NyKs5kv-taPrzmB56tg:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Handle errors (use `anyhow`, or the error-handling convention of `axum`).
</blockquote></details>

Done
___
*[`crates/gateway/src/gateway.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKIv0S5peH9B-yxtAF:-NyKs7860DZNO-7nhDRG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/src/gateway.rs#L82)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

And add an error variant if one doesn't exist already
</blockquote></details>

Done.
___
*[`crates/gateway/tests/routing_test.rs` line 52 at r8](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyKG2HfC1wzyAhAPOlO:-NyKsIYY7nrY8cV3bsRz:bv9b6n8) ([raw file](https://github.com/starkware-libs/mempool/blob/2e10b4c3dbe11f1e57d86ae417279cd8321c5952/crates/gateway/tests/routing_test.rs#L52)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not a fixture anymore? Are we instantiating a new GW for each request we send?
</blockquote></details>

let's talk F2F


<!-- Sent from Reviewable.io -->

2024-05-20 12:59 UTC, ArniStarkware requested changes
> Reviewed 4 of 5 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 90 at r9](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyL3d4DE5hG_4kZUw-d:-NyL3d4DE5hG_4kZUw-e:bn5ttu9) ([raw file](https://github.com/starkware-libs/mempool/blob/281ed682b0fea0459b58e05e3d4e4ede385f4c4d/crates/gateway/src/gateway.rs#L90)):*
> ```XML
>     validator: StatelessTransactionValidator,
>     tx: ExternalTransaction,
> ) -> GatewayResult<(String, MempoolInput)> {
> ```

Soon, this function will have a parameter called `stateful_transaction_validator`. The word `validator` is not indicative enough.



_Suggestion:_
```XML
fn process_tx(
    stateless_transaction_validator: StatelessTransactionValidator,
    tx: ExternalTransaction,
) -> GatewayResult<(String, MempoolInput)> {
```
___
*[`crates/mempool/src/mempool.rs` line 120 at r9](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyL2WPu1Q0ZpmVGHsHq:-NyL2WPv4APJnZxfPnTJ:b9qlan9) ([raw file](https://github.com/starkware-libs/mempool/blob/281ed682b0fea0459b58e05e3d4e4ede385f4c4d/crates/mempool/src/mempool.rs#L120)):*
> ```XML
>                 self.add_tx(mempool_input.tx, mempool_input.account)?;
>                 Ok(())
>             }
> ```

Probably out of scope of this PR.
Is it the plan for the next PR, to change the input types of `add_tx`?



_Suggestion:_
```XML
            GatewayToMempoolMessage::AddTransaction(mempool_input) => {
                self.add_tx(mempool_input)?;
                Ok(())
            }
```


<!-- Sent from Reviewable.io -->

2024-05-20 15:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/mempool/133#-Ny-oj_hBZxw-Vc3PxWj:-NyLS4Di5YbdmZt-axpe:b-q5bof5) ([raw file](https://github.com/starkware-libs/mempool/blob/b3d5eebea11647c6aa3df26e8200e52ffa98b2d8/crates/gateway/src/gateway.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we give up on the string by now?
</blockquote></details>

Let's do it later. WDYT?
This change will require modifying the GW test and routine tests.
___
*[`crates/gateway/src/gateway.rs` line 90 at r9](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyL3d4DE5hG_4kZUw-d:-NyLSoFc3jhxDp2c1oEU:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/281ed682b0fea0459b58e05e3d4e4ede385f4c4d/crates/gateway/src/gateway.rs#L90)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Soon, this function will have a parameter called `stateful_transaction_validator`. The word `validator` is not indicative enough.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 120 at r9](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyL2WPu1Q0ZpmVGHsHq:-NyLXiOr4oT77ifGKsLB:b-rt8hyw) ([raw file](https://github.com/starkware-libs/mempool/blob/281ed682b0fea0459b58e05e3d4e4ede385f4c4d/crates/mempool/src/mempool.rs#L120)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Probably out of scope of this PR.
Is it the plan for the next PR, to change the input types of `add_tx`?
</blockquote></details>

Good idea!
Adding a TODO.


<!-- Sent from Reviewable.io -->

2024-05-20 16:14 UTC, ArniStarkware approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-21 04:09 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, and @elintul)

___
*[`crates/gateway/src/gateway.rs` line 83 at r10](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyOJw3xAPv927zznET8:-NyOJw3xAPv927zznET9:b-b2qbub) ([raw file](https://github.com/starkware-libs/mempool/blob/0cb907c836f27090445d5460190716b169c19f97/crates/gateway/src/gateway.rs#L83)):*
> ```XML
>     app_state.network_component.send(message).await.map_err(|e| {
>         GatewayError::MessageSendError(format!("Failed to send transaction message: {}", e))
>     })?;
> ```

The error string preceding the error variant is sufficient.
Requires changing the inner type of the error variant from String to whatever the type here is/



_Suggestion:_
```XML
    app_state.network_component.send(message).await.map_err(GatewayError::MessageSendError)?;
```


<!-- Sent from Reviewable.io -->

2024-05-21 08:50 UTC, elintul approved these changes
> Reviewed 1 of 3 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 83 at r10](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyOJw3xAPv927zznET8:-NyPKuev2JlgRxNia-jW:b7det80) ([raw file](https://github.com/starkware-libs/mempool/blob/0cb907c836f27090445d5460190716b169c19f97/crates/gateway/src/gateway.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The error string preceding the error variant is sufficient.
Requires changing the inner type of the error variant from String to whatever the type here is/
</blockquote></details>

Why not `??`, as before?


<!-- Sent from Reviewable.io -->

2024-05-21 08:54 UTC, giladchase approved these changes
> Reviewed 3 of 5 files at r8, 1 of 3 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, and @elintul)

___
*[`crates/gateway/src/gateway.rs` line 83 at r10](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyOJw3xAPv927zznET8:-NyPLS3b1-lOl3TfkQnK:b-paajch) ([raw file](https://github.com/starkware-libs/mempool/blob/0cb907c836f27090445d5460190716b169c19f97/crates/gateway/src/gateway.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not `??`, as before?
</blockquote></details>

+1 for ??
This also follows from changing the variant `MessageSendError(String)` into `MessageSendError(<whatever e is>)`, unless that is problematic somehow :thinking: 


<!-- Sent from Reviewable.io -->

2024-05-21 09:02 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @dafnamatsry, and @elintul)

___
*[`crates/gateway/src/gateway.rs` line 83 at r10](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyOJw3xAPv927zznET8:-NyPNi3w2o9b_h1bGkmN:b9c377) ([raw file](https://github.com/starkware-libs/mempool/blob/0cb907c836f27090445d5460190716b169c19f97/crates/gateway/src/gateway.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

+1 for ??
This also follows from changing the variant `MessageSendError(String)` into `MessageSendError(<whatever e is>)`, unless that is problematic somehow :thinking:
</blockquote></details>

Let's discuss it in Slack.
Max I'll change it in another PR.


<!-- Sent from Reviewable.io -->

2024-05-21 09:03 UTC, merged

2024-05-21 10:24 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/133)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/gateway/src/gateway_test.rs` line 35 at r11](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyPLSM_Dg3Pq4ZSYd5O:-NyPLSMa6h3QZuv446FL:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e277030b4f01feaf8418b625eb8d47e749e855df/crates/gateway/src/gateway_test.rs#L35)):*
> ```XML
> async fn test_add_tx(#[case] json_file_path: &Path, #[case] expected_response: &str) {
>     // The  `_rx_gateway_to_mempool`   is retained to keep the channel open, as dropping it would
>     // prevent the sender from transmitting messages.
> ```





_Suggestion:_
```XML
    // The receiving end to mempool is retained to keep the channel open, as dropping it 
    // would prevent the sender from transmitting messages.
```
___
*[`crates/gateway/src/gateway_test.rs` line 44 at r11](https://reviewable.io/reviews/starkware-libs/mempool/133#-NyPMo595fvG9myVvAad:-NyPMo595fvG9myVvAae:b-kpfd4w) ([raw file](https://github.com/starkware-libs/mempool/blob/e277030b4f01feaf8418b625eb8d47e749e855df/crates/gateway/src/gateway_test.rs#L44)):*
> ```XML
> 
>     let json_file = File::open(json_file_path).unwrap();
>     let tx: ExternalTransaction = serde_json::from_reader(json_file).unwrap();
> ```

Move right before usage.



_Code quote:_
```XML
    let json_file = File::open(json_file_path).unwrap();
    let tx: ExternalTransaction = serde_json::from_reader(json_file).unwrap();
```


<!-- Sent from Reviewable.io -->