feat: wrap mempool as a component with trait, client and server
starkware-libs/mempool pull request #160
Opened 2024-05-22 06:12 UTC by Itay-Tsabary-Starkware

2024-05-22 14:06 UTC, MohammadNassar1 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 7 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVQPHQ7ohzPf9vYyKE:-NyVQPHQ7ohzPf9vYyKF:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/Cargo.toml#L18)):*
> ```TOML
> starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
> tokio.workspace = true
> async-trait.workspace = true
> ```





_Suggestion:_
```TOML
anyhow.workspace = true
async-trait.workspace = true
derive_more.workspace = true
mempool_infra = { path = "../mempool_infra", version = "0.0" }
starknet_api.workspace = true
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
tokio.workspace = true
```
___
*[`crates/mempool_types/Cargo.toml` line 16 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVWzQPDeGNgGPnZYxh:-NyVWzQPDeGNgGPnZYxi:b-kxmnem) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/Cargo.toml#L16)):*
> ```TOML
> tokio.workspace = true
> thiserror.workspace = true
> async-trait.workspace = true
> ```

Please alphabatize.



_Code quote:_
```TOML
async-trait.workspace = true
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVZnWYB1AtYxX5cRgb:-NyVZnWYB1AtYxX5cRgc:b-ov8qcx) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
> ```XML
> pub type MempoolResult<T> = Result<T, MempoolError>;
> #[async_trait]
> pub trait MempoolTrait: Send + Sync {
> ```

Why do we need this trait?
It's only implemented by Mempool, right?



_Code quote:_
```XML
MempoolTrait
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_1KUC0_tI2w7e7g7:-NyV_1KV48UEK-J7vQAN:b-gpc64v) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
> ```XML
> #[async_trait]
> pub trait MempoolTrait: Send + Sync {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
> ```

Why it's `async`?
And can you think of another name for the method? :)



_Code quote:_
```XML
async
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_Fix7Lm7To3iHK4X:-NyV_Fix7Lm7To3iHK4Y:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L75)):*
> ```XML
> pub enum MempoolMessages {
>     AsyncAddTransaction(ThinTransaction, Account),
>     AsyncGetTxs(usize),
> ```





_Suggestion:_
```XML
Transactions
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_Jja6pEuz7pyDufo:-NyV_Jja6pEuz7pyDufp:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L81)):*
> ```XML
> pub enum MempoolResponses {
>     AsyncAddTransaction(MempoolResult<()>),
>     AsyncGetTxs(MempoolResult<Vec<ThinTransaction>>),
> ```





_Suggestion:_
```XML
Transactions
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVYfsaEIIYWA9qWj7d:-NyVYfsaEIIYWA9qWj7e:b5gssvn) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L101)):*
> ```XML
>         }
>     }
> }
> ```

I think it can be in a different file.



_Code quote:_
```XML
#[async_trait]
pub trait MempoolTrait: Send + Sync {
    async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
    async fn async_get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>>;
}

#[derive(Debug)]
pub enum MempoolMessages {
    AsyncAddTransaction(ThinTransaction, Account),
    AsyncGetTxs(usize),
}

#[derive(Debug)]
pub enum MempoolResponses {
    AsyncAddTransaction(MempoolResult<()>),
    AsyncGetTxs(MempoolResult<Vec<ThinTransaction>>),
}

#[async_trait]
impl MempoolTrait for ComponentClient<MempoolMessages, MempoolResponses> {
    async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
        let res = self.send(MempoolMessages::AsyncAddTransaction(tx, account)).await;
        match res {
            MempoolResponses::AsyncAddTransaction(res) => res,
            _ => panic!("Unexpected response type."),
        }
    }

    async fn async_get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
        let res = self.send(MempoolMessages::AsyncGetTxs(n_txs)).await;
        match res {
            MempoolResponses::AsyncGetTxs(res) => res,
            _ => panic!("Unexpected response type."),
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-23 08:24 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 13 unresolved discussions (waiting on @Itay-Tsabary-Starkware and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR3na2jKLWN3FR1yv:-NyZR3na2jKLWN3FR1yw:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
> ```XML
> #[async_trait]
> pub trait MempoolTrait: Send + Sync {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
> ```





_Suggestion:_
```XML
add_transaction
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR7ToCX7dXPrvGMPE:-NyZR7ToCX7dXPrvGMPF:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L69)):*
> ```XML
> pub trait MempoolTrait: Send + Sync {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
>     async fn async_get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>>;
> ```





_Suggestion:_
```XML
get_transactions
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRVrb3rX3Bdp4yp1-:-NyZRVrb3rX3Bdp4yp10:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L74)):*
> ```XML
> #[derive(Debug)]
> pub enum MempoolMessages {
>     AsyncAddTransaction(ThinTransaction, Account),
> ```





_Suggestion:_
```XML
AddTransaction
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRY7m8ZBDFKg1qK1H:-NyZRY7m8ZBDFKg1qK1I:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L75)):*
> ```XML
> pub enum MempoolMessages {
>     AsyncAddTransaction(ThinTransaction, Account),
>     AsyncGetTxs(usize),
> ```





_Suggestion:_
```XML
GetTransactions
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRbn1-XUx9e1EFAmi:-NyZRbn1-XUx9e1EFAmj:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L80)):*
> ```XML
> #[derive(Debug)]
> pub enum MempoolResponses {
>     AsyncAddTransaction(MempoolResult<()>),
> ```





_Suggestion:_
```XML
AddTransactionResponse
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRevR1E1NzBpk21Dj:-NyZRevR1E1NzBpk21Dk:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L81)):*
> ```XML
> pub enum MempoolResponses {
>     AsyncAddTransaction(MempoolResult<()>),
>     AsyncGetTxs(MempoolResult<Vec<ThinTransaction>>),
> ```





_Suggestion:_
```XML
GetTransactionsResponse
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 101 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVYfsaEIIYWA9qWj7d:-NyZSPC41xwjqk2BcncG:b-3a0v66) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L101)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it can be in a different file.
</blockquote></details>

I agree.

Also add a type definition: 
```
pub type MempoolClient = ComponentClient<MempoolMessages, MempoolResponses>
```


<!-- Sent from Reviewable.io -->

2024-05-23 11:25 UTC, elintul approved these changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 16 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_Aw9rCUCy9UL9RUGN:-Ny_Aw9s19zK1Irldefn:bexylh6) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L66)):*
> ```XML
> 
> pub type MempoolResult<T> = Result<T, MempoolError>;
> #[async_trait]
> ```

Please also add blank lines between trait methods.



_Suggestion:_
```XML
pub type MempoolResult<T> = Result<T, MempoolError>;

#[async_trait]
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR3na2jKLWN3FR1yv:-Ny_B8TNC4X150lQu6ik:bemj8zq) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
> ```XML
> #[async_trait]
> pub trait MempoolTrait: Send + Sync {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
> ```

I'd use `tx` in function and variable names (snakecase); `Transaction` in trait and struct names (camelcase). The `async` shouldn't appear in the name, it's clear from the signature.
___
*[`crates/mempool_types/src/mempool_types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_B_Pw1pBL2SgtjIHR:-Ny_B_Pw1pBL2SgtjIHS:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L73)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum MempoolMessages {
> ```





_Suggestion:_
```XML
MempoolIngoingMessage
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_Bd0p6YefLBC12ws-:-Ny_Bd0p6YefLBC12ws0:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L79)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum MempoolResponses {
> ```





_Suggestion:_
```XML
MempoolOutgoingMessage
```


<!-- Sent from Reviewable.io -->

2024-05-23 11:26 UTC, elintul requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 16 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-23 11:30 UTC, elintul requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 17 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_CI4XE8jsEGRzqItI:-Ny_CI4XE8jsEGRzqItJ:bxo4tib) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
> ```XML
> pub type MempoolResult<T> = Result<T, MempoolError>;
> #[async_trait]
> pub trait MempoolTrait: Send + Sync {
> ```

Not a good name, IMO; it will appear in the code of components interacting with it, and appears unnatural. Maybe the trait's name should simply be `Mempool` and the actual mempool struct will be called `MempoolCore`, or something similar? 



_Code quote:_
```XML
MempoolTrait
```


<!-- Sent from Reviewable.io -->

2024-05-23 11:41 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 20 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_DexxDJxm27Q6RP6N:-Ny_DexxDJxm27Q6RP6O:bspahye) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L85)):*
> ```XML
> 
> #[async_trait]
> impl MempoolTrait for ComponentClient<MempoolMessages, MempoolResponses> {
> ```

Went to read the client code to understand this PR.
`M, R` aren't good parameter names; I suggest changing to something that embeds the flow better: `Input<>Output`/`Ingoing<>Outgoing`/`I<>O`/`Request/Response`.



_Code quote:_
```XML
MempoolMessages, MempoolResponses
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EaSK-Dj4ogmR1Los:-Ny_EaSK-Dj4ogmR1Lot:bpoledb) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L87)):*
> ```XML
> impl MempoolTrait for ComponentClient<MempoolMessages, MempoolResponses> {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
>         let res = self.send(MempoolMessages::AsyncAddTransaction(tx, account)).await;
> ```

Please define separate variable: `add_tx_message`, so this line is easier to read. Also in `get_txs`.



_Code quote:_
```XML
MempoolMessages::AsyncAddTransaction(tx, account)
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EMUsAuc6tYCl3BR7:-Ny_EMUsAuc6tYCl3BR8:bz863zt) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L90)):*
> ```XML
>         match res {
>             MempoolResponses::AsyncAddTransaction(res) => res,
>             _ => panic!("Unexpected response type."),
> ```

Why not handling errors? I.e., adding an error variant of unsupported message to the error enum.
Also, I think we should somehow express in code the pairing between requests and responses.



_Code quote:_
```XML
_ => panic!("Unexpected response type."),
```


<!-- Sent from Reviewable.io -->

2024-05-23 12:01 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_I-xaCetU05s7MMKa:-Ny_I-xaCetU05s7MMKb:bqop3i9) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/src/mempool.rs#L161)):*
> ```XML
> #[async_trait]
> impl MempoolTrait for Mempool {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
> ```

It's important for `self` to remain immutable in the communication layer, which is the primary reason for this `trait`. As we discussed, the communication clients should be easily clonable, ensuring they provide an immutable API. Since we will have multiple gateways containing a mempool client, they should not lock it, as this would lead to sequential sending, although out usecase is multiple async. senders which channels (and other communication implementations) allow.



_Suggestion:_
```XML
&self
```


<!-- Sent from Reviewable.io -->

2024-05-25 13:37 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_I-xaCetU05s7MMKa:-NyjqKI-ALqKJXXc2HBE:bgcn6g9) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/src/mempool.rs#L161)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's important for `self` to remain immutable in the communication layer, which is the primary reason for this `trait`. As we discussed, the communication clients should be easily clonable, ensuring they provide an immutable API. Since we will have multiple gateways containing a mempool client, they should not lock it, as this would lead to sequential sending, although out usecase is multiple async. senders which channels (and other communication implementations) allow.
</blockquote></details>

The mutable reference in the trait is needed for the Mempool itself, so it can invoke its internal `add_tx` function:

```
#[async_trait]
impl MempoolTrait for Mempool {
    async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
        self.add_tx(tx, account)
    }

    ....
}
```

Removing the `mut` from the fn definition in `MempoolTrait` prevents this.

Let's discuss this in person though, I'll set a meeting.
___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVZnWYB1AtYxX5cRgb:-NyjrYsa0Y5Bi3XO1q__:b-jk4gkt) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why do we need this trait?
It's only implemented by Mempool, right?
</blockquote></details>

Other components that will want to interact with a mempool instance will have a `Box<dyn MempoolTrait>` object whose functions they can invoke. The infra will instantiate this object according to the setup -- single / multiple machine.
This setup also allows directly plugging a mempool object to the gateway for testing purposes,  removing the communication overhead.
___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_CI4XE8jsEGRzqItI:-NyjtIgz7avurMmdf7jT:b-tgkl2r) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not a good name, IMO; it will appear in the code of components interacting with it, and appears unnatural. Maybe the trait's name should simply be `Mempool` and the actual mempool struct will be called `MempoolCore`, or something similar?
</blockquote></details>

Sure, I just came up with something, I'd be happy to change to whatever you'd prefer. We can go with `MempoolExternalInvocations` or `MempoolInvocations`, please lmk.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_1KUC0_tI2w7e7g7:-NyjtYI29ee8Mt9FtK5n:b-jh0rx2) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's `async`?
And can you think of another name for the method? :)
</blockquote></details>

Not sure which of the `async`s you are referring to:
The function is async because we use async communication between components.
The name has async to differentiate it from the inner `add_tx` mempool fn. I don't mind changing this to whatever.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR3na2jKLWN3FR1yv:-NyjtoeZ9k4srDXG38dT:bzhcdap) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd use `tx` in function and variable names (snakecase); `Transaction` in trait and struct names (camelcase). The `async` shouldn't appear in the name, it's clear from the signature.
</blockquote></details>

I chose this name as it reflects the async wrapping of the inner `add_tx` mempool fn; I'd be happy to change. To remove the explicit usage of async, we can go with 
`ExternalAddTransaction`, does that works. Keep in mind it cannot conflict with the inner function name.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR7ToCX7dXPrvGMPE:-NyjuHEoDgLSvJtdJK7I:b-dzjxxx) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L69)):*
> ```XML
> pub trait MempoolTrait: Send + Sync {
>     async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()>;
>     async fn async_get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>>;
> ```

There's a mempool fn called `get_txs`, and these names cannot conflict. Following the discussion above, I assume you'd like to change the inner function name to `get_transactions`, and if so, what should the trait fn name be?


<!-- Sent from Reviewable.io -->

2024-05-26 09:02 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_I-xaCetU05s7MMKa:-NynzQMiEAh63eDeCBcZ:b39e12v) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/src/mempool.rs#L161)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The mutable reference in the trait is needed for the Mempool itself, so it can invoke its internal `add_tx` function:

```
#[async_trait]
impl MempoolTrait for Mempool {
    async fn async_add_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
        self.add_tx(tx, account)
    }

    ....
}
```

Removing the `mut` from the fn definition in `MempoolTrait` prevents this.

Let's discuss this in person though, I'll set a meeting.
</blockquote></details>

I understand your perspective, let me explain how I view things. :)

The aim of this trait is to allow transparent communication with the core logic component; regardless of the type of communication or topology used.
To achieve this, we need to meet two key requirements: facilitating efficient communication (such as using `async` methods) and embedding the core logic flow (methods' names, inputs and outputs). These requirements might sometimes conflict, and we'll need to address each situation as it arises.

In this case:
- The mempool core operates synchronously, while the communication code should be `async` (since scheduling code is asynchronous).
- The mempool core needs to be mutable, as it represents a collection. However, the communication code should be immutable. This is because channels, RPC, or other forms of multi-machine communication shouldn't alter clients' state unless buffering/caching is necessary (i.e., communication code itself requires it). Additionally, a multiple senders and single receiver setup can complicate implementation regarding ownership if multiple mutable ownership is needed.

Both issues can be resolved by wrapping the mempool and creating an indirection. The wrapper can implement the trait as-is and meet the communication needs. Inside, the actual mempool the wrapper holds will remain synchronous and mutable, while the wrapper code will mitigate both those differences.


<!-- Sent from Reviewable.io -->

2024-05-26 09:15 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_CI4XE8jsEGRzqItI:-Nyo9BnIBoje5oJLKJQt:b-k114en) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Sure, I just came up with something, I'd be happy to change to whatever you'd prefer. We can go with `MempoolExternalInvocations` or `MempoolInvocations`, please lmk.
</blockquote></details>

Simply `Mempool` sounds most natural to me, since from the GW's perspective it acts like a mempool; it's agnostic to the fact that there are multiple implementations to this trait. We can also go with `MempoolInterface`, but I prefer the first option.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_1KUC0_tI2w7e7g7:-Nyo9b3sEaV1Yldk1JYo:bhfiv3m) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not sure which of the `async`s you are referring to:
The function is async because we use async communication between components.
The name has async to differentiate it from the inner `add_tx` mempool fn. I don't mind changing this to whatever.
</blockquote></details>

There's no need to include the word `async` in the method's name when it's already clear from the signature. :) 
The current name is just temporary and can be confusing. It might become outdated if the method changes to synchronous (it probably won't, but as a good practice). In general, it's better not to embed code properties in names or documentation, which are decoupled from the code.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR3na2jKLWN3FR1yv:-NyoAHGMApWofuSsksws:bbcpa2t) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I chose this name as it reflects the async wrapping of the inner `add_tx` mempool fn; I'd be happy to change. To remove the explicit usage of async, we can go with 
`ExternalAddTransaction`, does that works. Keep in mind it cannot conflict with the inner function name.
</blockquote></details>

The same response (re the trait name) applies: the gateway should feel as if it is interacting directly with the actual mempool; method names should remain free from technical complexities.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR7ToCX7dXPrvGMPE:-NyoAhnJ1uSq-J_od6hg:b-pgnjej) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L69)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There's a mempool fn called `get_txs`, and these names cannot conflict. Following the discussion above, I assume you'd like to change the inner function name to `get_transactions`, and if so, what should the trait fn name be?
</blockquote></details>

Same as above. :)


<!-- Sent from Reviewable.io -->

2024-05-26 09:21 UTC, elintul reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-27 08:20 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 0 of 5 files reviewed, 21 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyVQPHQ7ohzPf9vYyKE:-NyslIZ2DhbNYRVy00R0:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/Cargo.toml#L18)):*
> ```TOML
> starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
> tokio.workspace = true
> async-trait.workspace = true
> ```

Done.
___
*[`crates/mempool/src/mempool.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_I-xaCetU05s7MMKa:-Nyt4wEH1fy-uUlT8PgT:b-nfsg6r) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool/src/mempool.rs#L161)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I understand your perspective, let me explain how I view things. :)

The aim of this trait is to allow transparent communication with the core logic component; regardless of the type of communication or topology used.
To achieve this, we need to meet two key requirements: facilitating efficient communication (such as using `async` methods) and embedding the core logic flow (methods' names, inputs and outputs). These requirements might sometimes conflict, and we'll need to address each situation as it arises.

In this case:
- The mempool core operates synchronously, while the communication code should be `async` (since scheduling code is asynchronous).
- The mempool core needs to be mutable, as it represents a collection. However, the communication code should be immutable. This is because channels, RPC, or other forms of multi-machine communication shouldn't alter clients' state unless buffering/caching is necessary (i.e., communication code itself requires it). Additionally, a multiple senders and single receiver setup can complicate implementation regarding ownership if multiple mutable ownership is needed.

Both issues can be resolved by wrapping the mempool and creating an indirection. The wrapper can implement the trait as-is and meet the communication needs. Inside, the actual mempool the wrapper holds will remain synchronous and mutable, while the wrapper code will mitigate both those differences.
</blockquote></details>

Thanks -- changed according to our in-person discussion (along with suggested names).
___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-Nyt5Ib05C86nXxGC9Jn:bon5tqb) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
> ```XML
> 
> pub struct MempoolCommunicationWrapper {
>     pub mempool: Mutex<Mempool>,
> ```

@elintul @dafnamatsry please note the `Mutex`, opposed to the discussed using `RefCell`. I tried using the latter but that resulted in complication errors.
Checked the docs which conclude the `RefCell` chapter with the following:

"Note that `RefCell<T>` does not work for multithreaded code! `Mutex<T>` is the thread-safe version of `RefCell<T>` and we’ll discuss `Mutex<T>` in Chapter 16."

https://doc.rust-lang.org/book/ch15-05-interior-mutability.html
___
*[`crates/mempool_types/src/mempool_types.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_CI4XE8jsEGRzqItI:-NyspEyGCvpAk5Nfqj7C:bmqusm9) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L67)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Simply `Mempool` sounds most natural to me, since from the GW's perspective it acts like a mempool; it's agnostic to the fact that there are multiple implementations to this trait. We can also go with `MempoolInterface`, but I prefer the first option.
</blockquote></details>

Changed to `MempoolInterface` to avoid refactoring the current `Mempool` struct, let's leave the potential future refactor to a different pr.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_1KUC0_tI2w7e7g7:-NyspNDCDptszZypQOf0:b-oanpkm) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

There's no need to include the word `async` in the method's name when it's already clear from the signature. :) 
The current name is just temporary and can be confusing. It might become outdated if the method changes to synchronous (it probably won't, but as a good practice). In general, it's better not to embed code properties in names or documentation, which are decoupled from the code.
</blockquote></details>

I added that prefix to avoid fn name collision with the mempool's internal function `add_tx` . When using the wrapper this prefix is redundant, so removed.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR3na2jKLWN3FR1yv:-NysprL-CevhOlmDNcvO:b-xrij9o) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The same response (re the trait name) applies: the gateway should feel as if it is interacting directly with the actual mempool; method names should remain free from technical complexities.
</blockquote></details>

Resolved due to the addition of the wrapper.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZR7ToCX7dXPrvGMPE:-NyspurfDtyaiEMQc0Fn:bmvd1lw) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same as above. :)
</blockquote></details>

Same :)
___
*[`crates/mempool_types/src/mempool_types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_B_Pw1pBL2SgtjIHR:-NyspydU613yFVl51bH6:b5sk5x1) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L73)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum MempoolMessages {
> ```

Changed in a similar fashion :)
___
*[`crates/mempool_types/src/mempool_types.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRVrb3rX3Bdp4yp1-:-Nysq3hz1OGt4IRKDKPe:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L74)):*
> ```XML
> #[derive(Debug)]
> pub enum MempoolMessages {
>     AsyncAddTransaction(ThinTransaction, Account),
> ```

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyV_Fix7Lm7To3iHK4X:-Nysq4sl6NgfPj0Pl6IH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L75)):*
> ```XML
> pub enum MempoolMessages {
>     AsyncAddTransaction(ThinTransaction, Account),
>     AsyncGetTxs(usize),
> ```

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyZRY7m8ZBDFKg1qK1H:-Nysq6BkEtxuBIXcu6Lh:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L75)):*
> ```XML
> pub [...]

2024-05-27 11:19 UTC, elintul requested changes
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 3 of 5 files reviewed, 19 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-NyteqNa2lreZzjCMv9q:b69gmzi) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

@elintul @dafnamatsry please note the `Mutex`, opposed to the discussed using `RefCell`. I tried using the latter but that resulted in complication errors.
Checked the docs which conclude the `RefCell` chapter with the following:

"Note that `RefCell<T>` does not work for multithreaded code! `Mutex<T>` is the thread-safe version of `RefCell<T>` and we’ll discuss `Mutex<T>` in Chapter 16."

https://doc.rust-lang.org/book/ch15-05-interior-mutability.html
</blockquote></details>

Can you elaborate about the errors you got? 
`Mutex` has an overhead, and I'd rather change the code to be multithread-compatible when need arrises.
Also, I think the member should be private.
___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nytf-ku9hjv_PaFVkiu:-Nytf-ku9hjv_PaFVkiv:bzat9w3) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
> ```XML
> 
> pub struct MempoolCommunicationWrapper {
>     pub mempool: Mutex<Mempool>,
> ```

Please document on why this is okay: at this point the flow is sequential, so runtime doesn't suffer.



_Code quote:_
```XML
Mutex<Mempool>
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_Bd0p6YefLBC12ws-:-NythB906-9pnDp17Ovh:bf4kud5) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

That's slightly misleading imo as it could suggest that these are the messages the mempool sends to invoke other components. I changed in accordance to the invocation messages to reflect these are responses to invocations.
</blockquote></details>

The input side should be symmetrically named `MempoolInvocation[Request]`. However, I believe the fact that the invocation is triggered by this communication shouldn't be included in its name. The enums should solely indicate the direction of the information.
___
*[`crates/mempool_types/src/mempool_types.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EaSK-Dj4ogmR1Los:-Nytg5jG2v15UCMYnbnl:bpvb8n2) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L87)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Changed. 
Please note the current mempool core's `add_tx` also takes in two args in the above format (the code has a TODO to address that).
</blockquote></details>

Please define a variable for the message.


<!-- Sent from Reviewable.io -->

2024-05-27 11:47 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 12 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-NytmXxx0G_0ZgOivqzx:brb1usj) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you elaborate about the errors you got? 
`Mutex` has an overhead, and I'd rather change the code to be multithread-compatible when need arrises.
Also, I think the member should be private.
</blockquote></details>

Changing `Mutex -> RefCell` results in 
```
`std::cell::RefCell<mempool::Mempool>` cannot be shared between threads safely
within `mempool::MempoolCommunicationWrapper`, the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<mempool::Mempool>`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock` instead
```


<!-- Sent from Reviewable.io -->

2024-05-27 11:47 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 12 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-Nyts3tQCFrjqKZ66n4V:bzer3h6) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Changing `Mutex -> RefCell` results in 
```
`std::cell::RefCell<mempool::Mempool>` cannot be shared between threads safely
within `mempool::MempoolCommunicationWrapper`, the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<mempool::Mempool>`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock` instead
```
</blockquote></details>

We can go with `RwLock` instead of `Mutex` as the compiler suggests, but its overhead should be higher.


<!-- Sent from Reviewable.io -->

2024-05-27 11:55 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 12 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-NyttvXw-Ap03UVxLMT_:b-t6r803) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We can go with `RwLock` instead of `Mutex` as the compiler suggests, but its overhead should be higher.
</blockquote></details>

Can you please point me to the line that's failing? The mempool shouldn't be threadsafe, or shouldn't be called from concurrent code.


<!-- Sent from Reviewable.io -->

2024-05-27 11:58 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nytf-ku9hjv_PaFVkiu:-NytudNY-fae8YOaY-5n:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please document on why this is okay: at this point the flow is sequential, so runtime doesn't suffer.
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_Bd0p6YefLBC12ws-:-NytswgsB40bNCHBDdJZ:bm7pzh7) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L79)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The input side should be symmetrically named `MempoolInvocation[Request]`. However, I believe the fact that the invocation is triggered by this communication shouldn't be included in its name. The enums should solely indicate the direction of the information.
</blockquote></details>

Ack, will refactor in a different pr (rebase hell).
___
*[`crates/mempool_types/src/mempool_types.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EaSK-Dj4ogmR1Los:-NytsmPO2qClc3LujY0d:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please define a variable for the message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-27 12:08 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nyt5Ib05C86nXxGC9Jm:-Nytuo00EmUMCOJjMhx4:b7xk3r4) ([raw file](https://github.com/starkware-libs/mempool/blob/7e34b13244fcfa8e111b7cbdb1be3324e588623e/crates/mempool/src/mempool.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please point me to the line that's failing? The mempool shouldn't be threadsafe, or shouldn't be called from concurrent code.
</blockquote></details>

The `MempoolInterface` trait is defined as `Send + Sync` so the gateway can pass its `mempool_client` member (throug the `AppState` struct) between its threads. The `Send + Sync` results in the error above.

I suggest taking the latest pr in this series (#167) and experimenting with it -- anyhow, that's what I did.


<!-- Sent from Reviewable.io -->

2024-05-30 07:58 UTC, dafnamatsry requested changes
> Reviewed 3 of 5 files at r2, 1 of 2 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Sx2K1jLdaJHN5nqa:-Nz7Sx2K1jLdaJHN5nqb:b-obfqul) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L71)):*
> ```XML
> 
> #[async_trait]
> pub trait MempoolInvocation: Send + Sync {
> ```

`MempoolInvocation` sounds like an object you would create for each invocation of a mempool function, and not like a trait that defines the interface of the mempool.

I prefer `MempoolClient`, `Mempool`,  or `MempoolInterface`.



_Code quote:_
```XML
MempoolInvocation
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-Nz7Twge2OloPJ0J9n9T:bwvymoz) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
> ```XML
> #[async_trait]
> pub trait MempoolInvocation: Send + Sync {
>     async fn add_tx(&self, mempool_input: MempoolInput) -> Result<MempoolResult<()>, NetworkError>;
> ```

To avoid returning `Result<Result<...>>`, Please define a new error type:

```
pub enum MempoolClientError {
   MempoolError(...),
   NetworkError,
}
```



_Code quote:_
```XML
Result<MempoolResult<()>, NetworkError>
```


<!-- Sent from Reviewable.io -->

2024-06-02 07:12 UTC, elintul reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-02 07:43 UTC, elintul reviewed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzMspA1DtcKJILKPwdD:-NzMspA1DtcKJILKPwdE:b-8mk4et) ([raw file](https://github.com/starkware-libs/mempool/blob/d386d3586195aec5eaa6c14e1d129c3339ec4598/crates/mempool_types/src/mempool_types.rs#L80)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum MempoolClientRequest {
> ```

Do you think the word `Client` enhances context and readability in this case? It makes the name longer, and since these `enum`s are only used in communication code within the clear context of the `MempoolClient` trait, I believe it's unnecessary. `Mempool[Request/Response]` seems clear enough on its own.



_Code quote:_
```XML
MempoolClientRequest
```


<!-- Sent from Reviewable.io -->

2024-06-02 07:46 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 174 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8Eqsk6dh7EwrrxXET:-NzMVJZo3RKiOwteynmF:b-yfcnmz) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No need for the wrapper if it doesn't implement the trait; let's make the server hold the mempool directly.
</blockquote></details>

Its purpose is to implement the component execution trait. I'd prefer not to pile this functionality on the mempool itself. WDYT?
___
*[`crates/mempool/src/mempool.rs` line 185 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8PHag7dzEGhR2lvzQ:-NzMV_pY03TXYG6KMRYV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L185)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Naming suggestion.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 188 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8PMBqATOFc_nZNMYE:-NzMVu3f2pt_M_2QCtxd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L188)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Naming suggestion.
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_DexxDJxm27Q6RP6N:-NzMtEYa5SObygbijhTH:b-cvweuk) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should go with `MempoolRequest<>MempoolResponse` (also no need for plural).
Why not now? It's new code.
</blockquote></details>

This required a changing the infra code, which I didn't want to handle now. Anyhow, created a base pr and rebased this one on top of it, so should be resolved.
___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-NzMlyd86myUSnlTvSFe:b-q45m2w) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

To avoid returning `Result<Result<...>>`, Please define a new error type:

```
pub enum MempoolClientError {
   MempoolError(...),
   NetworkError,
}
```
</blockquote></details>

I prefer not to; let's discuss in person.


<!-- Sent from Reviewable.io -->

2024-06-02 07:48 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @elintul)

___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-NzMuiWgB7TaMkvxhVmB:b-3xr350) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I prefer not to; let's discuss in person.
</blockquote></details>

Reconsidering, will update.


<!-- Sent from Reviewable.io -->

2024-06-02 07:48 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_DexxDJxm27Q6RP6N:-NzMuvb022Xg39lzOyAh:bn5bjqy) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L85)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This required a changing the infra code, which I didn't want to handle now. Anyhow, created a base pr and rebased this one on top of it, so should be resolved.
</blockquote></details>

Let's add to the renaming TODOs after this tasks; current names aren't clear IMO.


<!-- Sent from Reviewable.io -->

2024-06-02 07:51 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 174 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8Eqsk6dh7EwrrxXET:-NzMvJ2X5v4PaHRumScy:b-cc5bqz) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L174)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Its purpose is to implement the component execution trait. I'd prefer not to pile this functionality on the mempool itself. WDYT?
</blockquote></details>

But currently it doesn't, so it's only a proxy, which isn't needed IMO. 
If you choose to leave it, let's make the `mempool` field private, so that this `struct` would have (`mut`able) access to it.


<!-- Sent from Reviewable.io -->

2024-06-02 07:51 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry)

___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-NzMuwXv3Q1pJ9O_5YWz:bj8zf1c) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Reconsidering, will update.
</blockquote></details>

My intuition is as follows: the server code does not care about function return types, so `MempoolError` or `MempoolSuccess` is all of the same for it. Indeed, this is captured by using `MempoolResult<()>`. 


<!-- Sent from Reviewable.io -->

2024-06-02 07:53 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/mempool_types/src/mempool_types.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EMUsAuc6tYCl3BR7:-NzMvrSc7UmKJb165B4b:bckly5b) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The service should never `panic`, we should throughly map the different error layers and represent them in corresponding enums and `Result`s; similarly to what Dafna suggested in a comment above.
</blockquote></details>

I thought we discussed in person (with @giladchase) that these errors indicate a concrete irrecoverable bug that should in fact crash the service.


<!-- Sent from Reviewable.io -->

2024-06-02 07:58 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 174 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8Eqsk6dh7EwrrxXET:-NzMwqYb4cghB1Xnnqi0:b-e3vrk5) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L174)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But currently it doesn't, so it's only a proxy, which isn't needed IMO. 
If you choose to leave it, let's make the `mempool` field private, so that this `struct` would have (`mut`able) access to it.
</blockquote></details>

Right, removed `pub`. Thanks.


<!-- Sent from Reviewable.io -->

2024-06-02 07:58 UTC, elintul reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-02 08:45 UTC, dafnamatsry reviewed
> Reviewed 1 of 3 files at r6, 1 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzMspA1DtcKJILKPwdD:-NzN5xqAEqTxpPdOQblI:bqog7zb) ([raw file](https://github.com/starkware-libs/mempool/blob/d386d3586195aec5eaa6c14e1d129c3339ec4598/crates/mempool_types/src/mempool_types.rs#L80)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think the word `Client` enhances context and readability in this case? It makes the name longer, and since these `enum`s are only used in communication code within the clear context of the `MempoolClient` trait, I believe it's unnecessary. `Mempool[Request/Response]` seems clear enough on its own.
</blockquote></details>

Agree.


<!-- Sent from Reviewable.io -->

2024-06-02 10:01 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-NzNO8UnAAA_7wQREVwL:bv9xzhl) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

My intuition is as follows: the server code does not care about function return types, so `MempoolError` or `MempoolSuccess` is all of the same for it. Indeed, this is captured by using `MempoolResult<()>`.
</blockquote></details>

Not sure I understand. Can you elaborate?


<!-- Sent from Reviewable.io -->

2024-06-02 12:09 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 199 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8PQ0N-u3K6BL2jfoK:-NzNEYzu6WJxyOOoFI4r:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool/src/mempool.rs#L199)):*
> ```XML
>             }
>         }
>     }
> ```

Done.
___
*[`crates/mempool_types/src/mempool_types.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_DexxDJxm27Q6RP6N:-NzNCmEO8ubKaXAS40hZ:b6r17r8) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's add to the renaming TODOs after this tasks; current names aren't clear IMO.
</blockquote></details>

Ended up changing in this pr; base pr already merged.
___
*[`crates/mempool_types/src/mempool_types.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/mempool/160#-Ny_EMUsAuc6tYCl3BR7:-NzNqDB5DrKvIBM69LMc:b6dnp7x) ([raw file](https://github.com/starkware-libs/mempool/blob/6da9473e494f3dc71d788c7e764d5d995e8ecade/crates/mempool_types/src/mempool_types.rs#L90)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I thought we discussed in person (with @giladchase) that these errors indicate a concrete irrecoverable bug that should in fact crash the service.
</blockquote></details>

Removed `panic`, added specific errors.
___
*[`crates/mempool_types/src/mempool_types.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/mempool/160#-NyyaAjQDlWqmoQolINg:-NzNpy7-AtXVPILIaTVt:b9am6wi) ([raw file](https://github.com/starkware-libs/mempool/blob/819885f4c1594b015b9923b1305b56f5ab336e16/crates/mempool_types/src/mempool_types.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please ensure documentation is provided; `pub`lic structs and interfaces should be thoroughly documented.
</blockquote></details>

Added for the trait and struct, please lmk if anything else is needed.
___
*[`crates/mempool_types/src/mempool_types.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7c0oc4dpXgu-7qC6z:-NzNE_-8CE1dDw7KItAI:blb56ds) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L68)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should this be an error enum?
</blockquote></details>

Yes, changed.
___
*[`crates/mempool_types/src/mempool_types.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Sx2K1jLdaJHN5nqa:-NzNEbI2CV6kqkowo5OX:b-5c3vop) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L71)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Agreed; let's use `mempool_client: MempoolClient` as the naming convention for `field: Trait`. This approach clarifies that the outer component doesn't directly contain the inner component, but rather holds a representation for communication with it.
</blockquote></details>

Both the struct alias and the trait will be used throughout the code; this pr does not reflect that as it just adds the trait def, but does not add using the struct alias throughout the components.

My suggested path forward is:
1. name the trait `MempoolClient`
2. name the struct alias `MempoolClientImpl`
3. refactor these out of the scope of the integration pr if any other issues arise
___
*[`crates/mempool_types/src/mempool_types.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz7Twge2OloPJ0J9n9S:-NzNZ0nX83BZUWaeKkEC:b-vf24sp) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L72)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not sure I understand. Can you elaborate?
</blockquote></details>

Discussed in person, following your suggesstion.
___
*[`crates/mempool_types/src/mempool_types.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8NzAgClHywGiurTnl:-NzNqVd2592Qja1vICbK:bxcz21) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L102)):*
> ```XML
>             _ => panic!("Unexpected response type."),
>         }
>     }
> ```

Changed in the spirit of the suggested changes. Tried to keep the lines not too lengthy as well. Please lmk if anything else is needed.
___
*[`crates/mempool_types/src/mempool_types.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/mempool/160#-Nz8O6aj0ixLcHk-UHj5:-NzNEl_H1bO2gtJ86Mx4:b-a2ujfl) ([raw file](https://github.com/starkware-libs/mempool/blob/13c9c9f06ddaf1117c4829a666b85c2c4e416202/crates/mempool_types/src/mempool_types.rs#L114)):*
> ```XML
>             _ => panic!("Unexpected response type."),
>         }
>     }
> ```

Changed.
___
*[`crates/mempool_types/src/mempool_types.rs` line 80 at r7](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzMspA1DtcKJILKPwdD:-NzNC4-8A3OtO6iash3c:bii4qr4) ([raw file](https://github.com/starkware-libs/mempool/blob/d386d3586195aec5eaa6c14e1d129c3339ec4598/crates/mempool_types/src/mempool_types.rs#L80)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

Changed accordingly.


<!-- Sent from Reviewable.io -->

2024-06-02 13:40 UTC, MohammadNassar1 reviewed
> Reviewed 2 of 4 files at r4, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @Itay-Tsabary-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 175 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzO5ptS2s-paqUrLKFM:-NzO5ptS2s-paqUrLKFN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool/src/mempool.rs#L175)):*
> ```XML
> }
> 
> impl MempoolCommunicationWrapper {
> ```


___
*[`crates/mempool/src/mempool.rs` line 176 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzO9LP4DXhbn-ZUMnuh:-NzO9LP4DXhbn-ZUMnui:b-9xv4wg) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool/src/mempool.rs#L176)):*
> ```XML
> 
> impl MempoolCommunicationWrapper {
>     async fn add_tx(&mut self, mempool_input: MempoolInput) -> MempoolResult<()> {
> ```

Why it's async



_Code quote:_
```XML
async
```
___
*[`crates/mempool/src/mempool.rs` line 180 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzO9O_EBqp3A3oAqkht:-NzO9O_EBqp3A3oAqkhu:bb73xfv) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool/src/mempool.rs#L180)):*
> ```XML
>     }
> 
>     async fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
> ```

Same



_Code quote:_
```XML
async
```


<!-- Sent from Reviewable.io -->

2024-06-02 17:23 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: all files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 176 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzO9LP4DXhbn-ZUMnuh:-NzOy4de3pJrrTrhgPY2:bq73zju) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool/src/mempool.rs#L176)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's async
</blockquote></details>

The generic server works with async functions, this is actually the whole purpose of this wrapper: invoke async'ly the sync inner function.


<!-- Sent from Reviewable.io -->

2024-06-03 06:15 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160#-:-NzRj91U-3MALipwthtR:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 84 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzRiBPYEVEr2oqJUu15:-NzRiBPYEVEr2oqJUu16:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool_types/src/mempool_types.rs#L84)):*
> ```XML
> }
> 
> /// Serves as the mempool's shared interface for inbound communication from other components.
> ```





_Suggestion:_
```XML
/// Serves as the mempool's shared interface.
```


<!-- Sent from Reviewable.io -->

2024-06-03 08:38 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry, @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/mempool_types.rs` line 84 at r12](https://reviewable.io/reviews/starkware-libs/mempool/160#-NzRiBPYEVEr2oqJUu15:-NzSF3srD0VLpUAXqEWA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/mempool_types/src/mempool_types.rs#L84)):*
> ```XML
> }
> 
> /// Serves as the mempool's shared interface for inbound communication from other components.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-03 09:14 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks! Will suggest some changes offline/in a PR. :)

> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160#-:-NzSMzAZ2-02ByKogwG1:bmtfzzt)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-03 10:02 UTC, dafnamatsry approved these changes
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-03 10:31 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/160#-:-NzSdx2j7Cg-6yZuAvl0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-03 10:53 UTC, merged