feat: replace network-component to trait-based communication
starkware-libs/mempool pull request #161
Opened 2024-05-22 06:12 UTC by Itay-Tsabary-Starkware

**Stack**:
- #160
- #159

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-05-23 11:44 UTC, elintul requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_FZyq2IAmF3m7pqYg:-Ny_FZyr-p3LEvIqReVR:b-yazrrl) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L38)):*
> ```XML
>     pub network_component: GatewayNetworkComponent,
>     pub state_reader_factory: Arc<dyn StateReaderFactory>,
>     pub mempool: Box<dyn MempoolTrait>,
> ```

Alias please.



_Code quote:_
```XML
Box<dyn MempoolTrait>
```
___
*[`crates/gateway/src/gateway.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_Ff6qAzpolEWxe1mu:-Ny_Ff6qAzpolEWxe1mv:bb76mu4) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L72)):*
> ```XML
>             network_component: Arc::new(self.network_component),
>             state_reader_factory: self.state_reader_factory,
>             mempool: Arc::new(Mutex::new(self.mempool)),
> ```

Why?



_Code quote:_
```XML
Arc::new(Mutex
```
___
*[`crates/gateway/src/gateway.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_FlicB-VWQeuQWlAU:-Ny_FlicB-VWQeuQWlAV:b-llehpr) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L108)):*
> ```XML
>         .lock()
>         .await
>         .async_add_tx(mempool_input.tx, mempool_input.account)
> ```

Please upack.



_Code quote:_
```XML
mempool_input.tx, mempool_input.account
```
___
*[`crates/mempool/src/mempool.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_Fr__69VYogLGzu8s:-Ny_Fr__69VYogLGzu8t:ba854hx) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/mempool/src/mempool.rs#L79)):*
> ```XML
>         let txs = self.txs_queue.pop_last_chunk(n_txs);
>         for tx in &txs {
>             self.state.remove(&tx.contract_address);
> ```

Revert.


<!-- Sent from Reviewable.io -->

2024-05-23 11:44 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_G4PjDUsTNuMX4eHt:-Ny_G4PjDUsTNuMX4eHu:b-lzr4hr) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L36)):*
> ```XML
>     pub stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
>     pub stateful_transaction_validator_config: StatefulTransactionValidatorConfig,
>     pub network_component: GatewayNetworkComponent,
> ```

Is this still needed after this PR?



_Code quote:_
```XML
pub network_component: GatewayNetworkComponent,
```


<!-- Sent from Reviewable.io -->

2024-05-23 11:46 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_G4PjDUsTNuMX4eHt:-Ny_GTr13OidkYetn437:bw5b9og) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this still needed after this PR?
</blockquote></details>

Sorry, I see you have other deletion PRs based on this one.


<!-- Sent from Reviewable.io -->

2024-05-23 12:22 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_FZyq2IAmF3m7pqYg:-Ny_OPh4Dd_B5XHgFc_K:b-kxfaqg) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Alias please.
</blockquote></details>

Have you tried using generics? I think it depicts reality better, and might not pollute our code as much (`<_>`s are a reasonable workaround, and would probably be okay by the compiler in most places).


<!-- Sent from Reviewable.io -->

2024-05-27 09:08 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/gateway/src/gateway.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_FZyq2IAmF3m7pqYg:-NytG78Z4aR7DbDGP1yq:biqsqrc) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L38)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Have you tried using generics? I think it depicts reality better, and might not pollute our code as much (`<_>`s are a reasonable workaround, and would probably be okay by the compiler in most places).
</blockquote></details>

The comment now belongs elsewhere, but answering here:

Aliasing: There are total of 3 instances of that. Does that merit an alias? If so, what's our naming convention? `BoxedMempoolInterface`? `MempoolInterfaceObj`?

Generics: Yes, didn't work out as I wanted it to. Do you have something concrete in mind?
___
*[`crates/gateway/src/gateway.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_Ff6qAzpolEWxe1mu:-NytGhLV6vCsj2n-m38m:b-xuztj9) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Removed due to our in-person discussion.
___
*[`crates/gateway/src/gateway.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/mempool/161#-Ny_R28-APxKhS0zu87x:-NytH2oG2oSv9vZ39p4S:b-eapff3) ([raw file](https://github.com/starkware-libs/mempool/blob/4859d70e32433286dd93e22d1dc522d4b7eea8df/crates/gateway/src/gateway.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I wouldn't want to pause a GW task at this point, I'd want them to be sent asynchronously to the mempool, and sequentially process them there.
</blockquote></details>

Resolved.
___
*[`crates/gateway/src/gateway_test.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/mempool/161#-NytHFkTAy_-g2qj1vdC:-NytHFkTAy_-g2qj1vdD:bimycia) ([raw file](https://github.com/starkware-libs/mempool/blob/abf74aac2dd9e3b4120f9f8f6fc1c07141054265/crates/gateway/src/gateway_test.rs#L65)):*
> ```XML
>     let (tx_mempool, rx_mempool) = channel::<MempoolMessageAndResponseSender>(32);
>     // TODO(Tsabary, 1/6/2024): Wrap with a dedicated create_mempool_server function.
>     let mut mempool_server = ComponentServer::new(MempoolCommunicationWrapper{ mempool : Mutex::new(mempool) }, rx_mempool);
> ```

Addressed in the next prs.



_Code quote:_
```XML
    // TODO(Tsabary, 1/6/2024): Wrap with a dedicated create_mempool_server function.
    let mut mempool_server = ComponentServer::new(MempoolCommunicationWrapper{ mempool : Mutex::new(mempool) }, rx_mempool);
```


<!-- Sent from Reviewable.io -->

2024-05-27 11:35 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/mempool/161#-NytpEV9-pI0oZBPUVxf:-NytpEV9-pI0oZBPUVxg:bxk3fui) ([raw file](https://github.com/starkware-libs/mempool/blob/304780a0c059376c7eaee15927a41b9a658dbcb6/crates/gateway/src/gateway.rs#L50)):*
> ```XML
>         mempool: Box<dyn MempoolInterface>,
>     ) -> Self {
>         let app_state = AppState {
> ```

Is this related to this PR?



_Code quote:_
```XML
app_state
```


<!-- Sent from Reviewable.io -->

2024-05-28 05:28 UTC, MohammadNassar1 requested changes
> Reviewed 3 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyuOMJC3uDtDK1ZMzwh:-NyuOMJC3uDtDK1ZMzwi:b-zhtzwx) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L11)):*
> ```XML
> use rstest::rstest;
> use starknet_api::external_transaction::ExternalTransaction;
> use starknet_mempool::mempool::Mempool;
> ```

AFAIK, Mempool and Gateway do not depend on each other.



_Code quote:_
```XML
use starknet_mempool::mempool::Mempool;
```
___
*[`crates/gateway/src/gateway_test.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyxd-Mh10D5oU09V2t5:-Nyxd-Mh10D5oU09V2t6:b-h27bku) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L74)):*
> ```XML
> 
>     // Create the gateway's mempool client.
>     let gateway_mempool_client = Box::new(MempoolClient::new(tx_mempool.clone()));
> ```

Why cloning?



_Code quote:_
```XML
clone()
```
___
*[`crates/gateway/tests/end_to_end_test.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyxe57P6aNsLY2_k2k8:-Nyxe57P6aNsLY2_k2k9:bb73xfv) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/tests/end_to_end_test.rs#L140)):*
> ```XML
> 
>     // Check that the mempool received the transaction.
>     let batcher_mempool_client = Box::new(MempoolClient::new(tx_mempool.clone()));
> ```

Same



_Code quote:_
```XML
.clone()
```


<!-- Sent from Reviewable.io -->

2024-05-28 05:52 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 9 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyxkIUN3kOH18u-Uqgf:-NyxkIUN3kOH18u-Uqgg:b-nfx9yl) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L63)):*
> ```XML
>     // Create and start the mempool server.
>     let mempool = Mempool::new([], gateway_network, batcher_network);
>     let (tx_mempool, rx_mempool) = channel::<MempoolMessageAndResponseSender>(32);
> ```

Please add a constant



_Code quote:_
```XML
(32)
```


<!-- Sent from Reviewable.io -->

2024-05-28 05:56 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyxkwhJ2YgbpToHXNDJ:-NyxkwhKBCv6Vxkv3fqj:be1zcsi) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L11)):*
> ```XML
> use rstest::rstest;
> use starknet_api::external_transaction::ExternalTransaction;
> use starknet_mempool::mempool::Mempool;
> ```

Note that if we have bidirectional communication, we will have a dependency loop. 
This will happen soon when we add BatcherMock, as we need to add a client instance.



_Code quote:_
```XML
:mempool::Mempool;
```
___
*[`crates/gateway/src/gateway_test.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyxkmr512QcO2BLgtDJ:-Nyxkmr6AdZ2IMY6eDb1:b-2ljuc4) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L74)):*
> ```XML
> 
>     // Create the gateway's mempool client.
>     let gateway_mempool_client = Box::new(MempoolClient::new(tx_mempool.clone()));
> ```

Why don't we have gateway_client for mempool?



_Code quote:_
```XML
let gateway_mempool_client =
```


<!-- Sent from Reviewable.io -->

2024-05-28 07:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyxkwhJ2YgbpToHXNDJ:-Nyy6_SY9Tt-hg1cBB7Z:bhuvb3d) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L11)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that if we have bidirectional communication, we will have a dependency loop. 
This will happen soon when we add BatcherMock, as we need to add a client instance.
</blockquote></details>

Actually, this won't happen soon :)


<!-- Sent from Reviewable.io -->

2024-05-28 09:51 UTC, dafnamatsry requested changes
> Reviewed 1 of 6 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 14 unresolved discussions (waiting on @elintul, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyya_lZ4CMdysSDBqDk:-Nyya_lZ4CMdysSDBqDl:b6v3ire) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway.rs#L40)):*
> ```XML
>     pub network_component: Arc<GatewayNetworkComponent>,
>     pub state_reader_factory: Arc<dyn StateReaderFactory>,
>     pub mempool: Arc<Box<dyn MempoolInterface>>,
> ```

Why the Box? not sure it is needed.



_Code quote:_
```XML
Arc<Box<dyn MempoolInterface>>
```
___
*[`crates/gateway/src/gateway_test.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyyYE533rg_Du79jRdL:-NyyYE533rg_Du79jRdM:bzictvt) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L39)):*
> ```XML
>     // prevent the sender from transmitting messages.
> 
>     use starknet_mempool::mempool::MempoolCommunicationWrapper;
> ```

Move up.



_Code quote:_
```XML
 use starknet_mempool::mempool::MempoolCommunicationWrapper;
```
___
*[`crates/gateway/src/gateway_test.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-NyyYy7V38sGi4SBGqBJ:-NyyYy7V38sGi4SBGqBK:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway_test.rs#L74)):*
> ```XML
> 
>     // Create the gateway's mempool client.
>     let gateway_mempool_client = Box::new(MempoolClient::new(tx_mempool.clone()));
> ```





_Suggestion:_
```XML
mempool_client
```


<!-- Sent from Reviewable.io -->

2024-05-28 18:01 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 97 at r6](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nz-MGOn5kKPeEuRbUqg:-Nz-MGOn5kKPeEuRbUqh:blkwwjn) ([raw file](https://github.com/starkware-libs/mempool/blob/50bb69d715d6d3034948b363b97b308154ceac1e/crates/gateway/src/gateway.rs#L97)):*
> ```XML
>     .await??;
> 
>     // TODO(Elin/Dafna, 1/5/2024): Replace "expect" with required error handling.
> ```

Please note this TODO.


<!-- Sent from Reviewable.io -->

2024-05-30 08:03 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @elintul, @Itay-Tsabary-Starkware, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyya_lZ4CMdysSDBqDk:-Nz7VgqW-nkzgSPnZF5_:blkv9ng) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

AFAIK the size of a struct implementing the trait is unknown, hence the size of this struct will also be unknown. The way around that is by storing in struct a reference to the heap (`Box`).
</blockquote></details>

I think `Arc` would be enough. It also allocates the memory on the heap.


<!-- Sent from Reviewable.io -->

2024-05-30 12:17 UTC, elintul reviewed
> Reviewed 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 10 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-30 12:18 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nz8Qt7UDkKE2sS8Bf8k:-Nz8Qt7UDkKE2sS8Bf8l:b-1ok9hp) (no related file):*
Waiting for this PR to be `rebase`d over #160's changes; a lot of this code will change as well.

___


<!-- Sent from Reviewable.io -->

2024-06-02 07:27 UTC, elintul reviewed
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-02 07:43 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @Itay-Tsabary-Starkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-02 12:12 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nz8Qt7UDkKE2sS8Bf8k:-NzNrN2wAWWlJXR2DMUk:b-tr3vpd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Waiting for this PR to be `rebase`d over #160's changes; a lot of this code will change as well.
</blockquote></details>

Ready for another pass ^ :pray: 

___


<!-- Sent from Reviewable.io -->

2024-06-02 12:17 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyya_lZ4CMdysSDBqDk:-NzNrjQUC53OwWnxYNRV:b-q9rxys) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think `Arc` would be enough. It also allocates the memory on the heap.
</blockquote></details>

Removing `Box` results in:

```
the size for values of type `dyn starknet_mempool_types::mempool_types::MempoolClient` cannot be known at compilation time
the trait `std::marker::Sized` is not implemented for `dyn starknet_mempool_types::mempool_types::MempoolClient`
```
To the best of my knowledge using `Box` is the standard in these cases. From the docs (first and third points are the relevant ones):

```
Boxes don’t have performance overhead, other than storing their data on the heap instead of on the stack. But they don’t have many extra capabilities either. You’ll use them most often in these situations:

-   When you have a type whose size can’t be known at compile time and you want to use a value of that type in a context that requires an exact size
-   When you have a large amount of data and you want to transfer ownership but ensure the data won’t be copied when you do so
-   When you want to own a value and you care only that it’s a type that implements a particular trait rather than being of a specific type
```

https://doc.rust-lang.org/book/ch15-01-box.html


<!-- Sent from Reviewable.io -->

2024-06-02 15:11 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 4 files at r6, 4 of 5 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzONydX747K84YZ_Nhq:-NzONydX747K84YZ_Nhr:b-wqv6yv) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/gateway/src/gateway_test.rs#L49)):*
> ```XML
>     let (tx_gateway_to_mempool, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
>     let (_, rx_mempool_to_gateway) = channel::<MempoolToGatewayMessage>(1);
>     // TODO: Add fixture.
> ```

Please keep it.



_Code quote:_
```XML
 // TODO: Add fixture.
```
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzOMd_3DmzFi2N-X5a-:-NzOMd_3DmzFi2N-X5a0:b-ah5f1y) ([raw file](https://github.com/starkware-libs/mempool/blob/85dee46d92345aef10dfbb74055ea9449cf43294/crates/gateway/src/gateway_test.rs#L54)):*
> ```XML
>     // The `_rx_gateway_to_mempool` is retained to keep the channel open, as dropping it would
>     // prevent the sender from transmitting messages.
>     let (_, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
> ```

It seems that this channel is no longer in use.
Please remove it



_Code quote:_
```XML
    // The `_rx_gateway_to_mempool` is retained to keep the channel open, as dropping it would
    // prevent the sender from transmitting messages.
    let (_, _rx_gateway_to_mempool) = channel::<GatewayToMempoolMessage>(1);
```


<!-- Sent from Reviewable.io -->

2024-06-02 17:25 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzONydX747K84YZ_Nhq:-NzOyyn6AZIp23hnoEW_:b8j2e2c) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/gateway/src/gateway_test.rs#L49)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please keep it.
</blockquote></details>

For the gateway network component? It is being deprecated.
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzOMd_3DmzFi2N-X5a-:-NzOytqb3N5ZNWNY_zwT:b-anmsrn) ([raw file](https://github.com/starkware-libs/mempool/blob/85dee46d92345aef10dfbb74055ea9449cf43294/crates/gateway/src/gateway_test.rs#L54)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It seems that this channel is no longer in use.
Please remove it
</blockquote></details>

There are cleanup prs coming up next.


<!-- Sent from Reviewable.io -->

2024-06-03 05:19 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @elintul, and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway_test.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzONydX747K84YZ_Nhq:-NzRX59P48GKFcuyjx5j:balylsh) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/gateway/src/gateway_test.rs#L49)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

For the gateway network component? It is being deprecated.
</blockquote></details>

For the test configuration, we want to add the configuration.
I'd prefer to move the init/config of the mempool client to a fixture.
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzOMd_3DmzFi2N-X5a-:-NzRWttsEJOWCf238KY9:b6rj6t2) ([raw file](https://github.com/starkware-libs/mempool/blob/85dee46d92345aef10dfbb74055ea9449cf43294/crates/gateway/src/gateway_test.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

There are cleanup prs coming up next.
</blockquote></details>

You've defined `GatewayToMempoolMessage` twice.


<!-- Sent from Reviewable.io -->

2024-06-03 06:39 UTC, dafnamatsry requested changes
> Reviewed 1 of 2 files at r8, 2 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @Itay-Tsabary-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyya_lZ4CMdysSDBqDk:-NzRmLH99TmRN3d6rrAh:b7novo6) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway.rs#L40)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Removing `Box` results in:

```
the size for values of type `dyn starknet_mempool_types::mempool_types::MempoolClient` cannot be known at compilation time
the trait `std::marker::Sized` is not implemented for `dyn starknet_mempool_types::mempool_types::MempoolClient`
```
To the best of my knowledge using `Box` is the standard in these cases. From the docs (first and third points are the relevant ones):

```
Boxes don’t have performance overhead, other than storing their data on the heap instead of on the stack. But they don’t have many extra capabilities either. You’ll use them most often in these situations:

-   When you have a type whose size can’t be known at compile time and you want to use a value of that type in a context that requires an exact size
-   When you have a large amount of data and you want to transfer ownership but ensure the data won’t be copied when you do so
-   When you want to own a value and you care only that it’s a type that implements a particular trait rather than being of a specific type
```

https://doc.rust-lang.org/book/ch15-01-box.html
</blockquote></details>

This is weird. 
`Arc<T>`, like `Box<T>` allocates `T` on the heap, so it serves the same purpose when dealing with types of unknown size. The difference is that `Arc` provides a thread-safe shared ownership, while `Box` provides exclusive ownership.


<!-- Sent from Reviewable.io -->

2024-06-03 08:40 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/161#-Nyya_lZ4CMdysSDBqDk:-NzSFDu_4_e2OJz6ZMeJ:bvw71rf) ([raw file](https://github.com/starkware-libs/mempool/blob/e1db209da8259ec7ac4f9b3da93127cccb070c69/crates/gateway/src/gateway.rs#L40)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This is weird. 
`Arc<T>`, like `Box<T>` allocates `T` on the heap, so it serves the same purpose when dealing with types of unknown size. The difference is that `Arc` provides a thread-safe shared ownership, while `Box` provides exclusive ownership.
</blockquote></details>

How should we proceed?
___
*[`crates/gateway/src/gateway_test.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzONydX747K84YZ_Nhq:-NzRxMfg4rzH-_QxFCNV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f973e9f35bedabe55c81560797733b115015b9e8/crates/gateway/src/gateway_test.rs#L49)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

For the test configuration, we want to add the configuration.
I'd prefer to move the init/config of the mempool client to a fixture.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 54 at r12](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzOMd_3DmzFi2N-X5a-:-NzRx7nS9msP9kjI5Z5r:bpsx7q2) ([raw file](https://github.com/starkware-libs/mempool/blob/85dee46d92345aef10dfbb74055ea9449cf43294/crates/gateway/src/gateway_test.rs#L54)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

You've defined `GatewayToMempoolMessage` twice.
</blockquote></details>

Right. It will be removed in the next pr anyway, but editted here as well. Thanks.


<!-- Sent from Reviewable.io -->

2024-06-03 10:52 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r13, 2 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161#-:-NzSiiYzAaovXvOTCjP_:bnfp4nl)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-03 10:59 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161#-:-NzSkJsw6AoBm8JEcH6u:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @elintul)



<!-- Sent from Reviewable.io -->

2024-06-03 18:17 UTC, Itay-Tsabary-Starkware reviewed
> Reviewed 1 of 2 files at r8, 1 of 5 files at r11, 1 of 2 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-04 06:17 UTC, elintul approved these changes
> Reviewed 1 of 5 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-04 06:18 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161#-:-NzWtXq82xiVsfTFIVqq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-04 06:19 UTC, elintul approved these changes
> Reviewed 1 of 2 files at r13, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: all files reviewed, 1 unresolved discussion (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/gateway/tests/end_to_end_test.rs` line 69 at r14](https://reviewable.io/reviews/starkware-libs/mempool/161#-NzWtbk63UPJOCQ6vKCO:-NzWtbk63UPJOCQ6vKCP:bst4edj) ([raw file](https://github.com/starkware-libs/mempool/blob/d8b8e1702a2338304512b526766db8f241b8a295/crates/gateway/tests/end_to_end_test.rs#L69)):*
> ```XML
> }
> 
> async fn set_up_gateway(mempool_client: Arc<dyn MempoolClient>) -> SocketAddr {
> ```

I think it can be aliased (used more than three times).



_Code quote:_
```XML
Arc<dyn MempoolClient>
```


<!-- Sent from Reviewable.io -->

2024-06-04 10:14 UTC, Itay-Tsabary-Starkware reviewed
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-04 10:14 UTC, merged