chore: create integration tests crate
starkware-libs/mempool pull request #172
Opened 2024-05-26 09:48 UTC by giladchase

move e2e test into it.

---

**Stack**:
- #51
- #50

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-05-26 14:08 UTC, MohammadNassar1 approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/tests-integration/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/172#-NypDlrZ5ecbTNSpYXOo:-NypDlrZ5ecbTNSpYXOp:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e1b23111426fb8b70bf075f164d4c77014ee3f2a/crates/tests-integration/Cargo.toml#L21)):*
> ```TOML
> starknet_gateway = { path = "../gateway", version = "0.0" }
> starknet_mempool = { path = "../mempool", version = "0.0" }
> starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
> ```





_Suggestion:_
```TOML
starknet_api.workspace = true
starknet_gateway = { path = "../gateway", version = "0.0" }
starknet_mempool = { path = "../mempool", version = "0.0" }
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
serde_json.workspace = true
```


<!-- Sent from Reviewable.io -->

2024-05-26 14:52 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/tests-integration/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/172#-NypDlrZ5ecbTNSpYXOo:-NypNf637FEsMgHp1Cz7:b-vvd6xs) ([raw file](https://github.com/starkware-libs/mempool/blob/e1b23111426fb8b70bf075f164d4c77014ee3f2a/crates/tests-integration/Cargo.toml#L21)):*
> ```TOML
> starknet_gateway = { path = "../gateway", version = "0.0" }
> starknet_mempool = { path = "../mempool", version = "0.0" }
> starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
> ```

tnx!
looks like serde_json wasn't even used, also thiserror, so removed them both.


<!-- Sent from Reviewable.io -->

2024-05-27 04:59 UTC, MohammadNassar1 approved these changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/starkware-libs/mempool/172#-NysPDZo2pkA9LS1BK5C):*




_Suggestion:_
```
move e2e
```
___
*[`crates/tests-integration/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/172#-NypDlrZ5ecbTNSpYXOo:-NysP2ZQ7u321hyibOwp:b-8ns53p) ([raw file](https://github.com/starkware-libs/mempool/blob/e1b23111426fb8b70bf075f164d4c77014ee3f2a/crates/tests-integration/Cargo.toml#L21)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

tnx!
looks like serde_json wasn't even used, also thiserror, so removed them both.
</blockquote></details>

Interesting, so why `udeps` didn't fail?


<!-- Sent from Reviewable.io -->

2024-05-27 10:41 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/tests-integration/Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/172#-NypDlrZ5ecbTNSpYXOo:-NytcaA36uLCK_9I7yer:bh22l2q) ([raw file](https://github.com/starkware-libs/mempool/blob/e1b23111426fb8b70bf075f164d4c77014ee3f2a/crates/tests-integration/Cargo.toml#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Interesting, so why `udeps` didn't fail?
</blockquote></details>

Not sure, but i reproduced locally, and seems like it's a false negative.

Looks like machete caught it, also a bunch of other stuff, also  faster, also easier to setup in the CI.
Soooo: https://reviewable.io/reviews/starkware-libs/mempool/178


<!-- Sent from Reviewable.io -->

2024-05-28 06:02 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172#-:-NyxmnFkDaipMbeHyNfJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-29 10:36 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-02 11:24 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzNgMTb8RHB7h7NHABA:-NzNgMTb8RHB7h7NHABB:b-n6khor) (no related file):*
Please rebase

___


<!-- Sent from Reviewable.io -->

2024-06-03 05:18 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzNgMTb8RHB7h7NHABA:-NzRXI0s4KOzV6POnfna:b-896fix) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-06-03 05:23 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172#-:-NzRYQi2-_HGF0q08ClC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/Cargo.toml` line 4 at r8](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzRY5Jv2CNBw2zzxu-L:-NzRY5Jw7x-GCiLTbMQH:b-csfwee) ([raw file](https://github.com/starkware-libs/mempool/blob/9f50c44416f25a51d4eef115c6b777f3cf00fefd/crates/gateway/Cargo.toml#L4)):*
> ```TOML
> edition.workspace = true
> license.workspace = true
> name = "starknet_gateway"
> ```

Usually, the name appears at the top, right?



_Code quote:_
```TOML
name = "starknet_gateway"
```


<!-- Sent from Reviewable.io -->

2024-06-03 05:24 UTC, MohammadNassar1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzNgMTb8RHB7h7NHABA:-NzRYTRIBfp3_6Jc6Z0z:b-1bjpmn) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks :)

___


<!-- Sent from Reviewable.io -->

2024-06-03 06:19 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/gateway/Cargo.toml` line 4 at r8](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzRY5Jv2CNBw2zzxu-L:-NzRk-6lDTdVe3iH3qi3:b-2ihubo) ([raw file](https://github.com/starkware-libs/mempool/blob/9f50c44416f25a51d4eef115c6b777f3cf00fefd/crates/gateway/Cargo.toml#L4)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Usually, the name appears at the top, right?
</blockquote></details>

Ya i just added auto-alphabetize to my formatter, wasn't sure about this moving down.

Should I look into overriding it for this section so that name is on top?
I'm leaning towards yes if it bugged you too? :thinking: 


<!-- Sent from Reviewable.io -->

2024-06-03 06:36 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/gateway/Cargo.toml` line 4 at r8](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzRY5Jv2CNBw2zzxu-L:-NzRnuzn2TzlNWbTWXGA:b-nmfkzc) ([raw file](https://github.com/starkware-libs/mempool/blob/9f50c44416f25a51d4eef115c6b777f3cf00fefd/crates/gateway/Cargo.toml#L4)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya i just added auto-alphabetize to my formatter, wasn't sure about this moving down.

Should I look into overriding it for this section so that name is on top?
I'm leaning towards yes if it bugged you too? :thinking:
</blockquote></details>

Reverted back to name on top + configured my linter to ignore this section (also see slack channel on configs)


<!-- Sent from Reviewable.io -->

2024-06-03 07:14 UTC, MohammadNassar1 approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/gateway/Cargo.toml` line 4 at r8](https://reviewable.io/reviews/starkware-libs/mempool/172#-NzRY5Jv2CNBw2zzxu-L:-NzRwag54CR9HSnW77DD:b-txoim5) ([raw file](https://github.com/starkware-libs/mempool/blob/9f50c44416f25a51d4eef115c6b777f3cf00fefd/crates/gateway/Cargo.toml#L4)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Reverted back to name on top + configured my linter to ignore this section (also see slack channel on configs)
</blockquote></details>

:1st_place_medal: 


<!-- Sent from Reviewable.io -->

2024-06-04 08:35 UTC, giladchase reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-04 08:36 UTC, giladchase reviewed
> Reviewed 2 of 6 files at r2, 1 of 4 files at r7, 1 of 3 files at r8, 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-04 08:36 UTC, merged