feat: add IntegrationTestSetup
starkware-libs/mempool pull request #174
Opened 2024-05-26 09:48 UTC by giladchase

Most of the changes are extraction from the end-to-end test, with the
following differences:
- spawning tasks via `TokioExecutor#spawn_with_handle`, which the mock
stores as a field to facilitate aborting the job (our `main` will
likely do something similar to this).
- added an abstract `add_tx` and `get_tx` to the mock, which will hide the
message sending boiler-plate from the code; using reqwest instead of
hyper for less boilerplate.

---

**Stack**:
- #174 ⬅
- #173
- #172
- #51
- #50

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-05-26 11:51 UTC, giladchase reviewed
Was wondering if this should be split: the only way I can think of is to first create `IntegrationTestSetup` and in a separate PR to make the e2e use it.
But doing that might not make it clear that most of the logic in `IntegrationTestSetup` is extracted from the e2e test :thinking: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174#-:-NyojCUR0NqrKsEVmI0p:bwqnqig)* status: 0 of 7 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-26 12:20 UTC, giladchase reviewed
This PR is currently clashing with `GatewayClient` that Ayelet has merged, will integrate it here once I refactor it in a separate PR. Will post here soon.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174#-:-Nyoq-dF3f6UjWLzP1jn:b-l85vrn)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-30 12:19 UTC, elintul reviewed
> Reviewed 1 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-30 12:34 UTC, elintul requested changes
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/tests-integration/Cargo.toml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TOzS0YLrSWHF1FBd:-Nz8TOzS0YLrSWHF1FBe:bj338gp) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/Cargo.toml#L17)):*
> ```TOML
> starknet_api.workspace = true
> starknet_gateway = { path = "../gateway", version = "0.0", features = [
>     "testing",
> ```

Can the trailing comma be removed, so the line doesn't break?



_Suggestion:_
```TOML
"testing"
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TYzl44A_6dLMKTFf:-Nz8TYzl44A_6dLMKTFg:b-x6bbtv) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L22)):*
> ```XML
> 
> pub struct IntegrationTestSetup {
>     pub executor: TokioExecutor,
> ```

Not to be confused with transaction execution.



_Suggestion:_
```XML
task_executor
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TmZG9MRLEuW46kIE:-Nz8TmZG9MRLEuW46kIF:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L40)):*
> ```XML
>             initialize_gateway_network_channels();
> 
>         // Build and run Gateway and initialize a gateway client.
> ```





_Suggestion:_
```XML
// Build and run gateway; initialize a gateway client.
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8U3U755-D7X41Wpsb:-Nz8U3U8BpH621eN7GyA:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L59)):*
> ```XML
>         let batcher_channels =
>             BatcherToMempoolChannels { rx: rx_batcher_to_mempool, tx: tx_mempool_to_batcher };
>         // Build and run mempool.
> ```





_Suggestion:_
```XML
            BatcherToMempoolChannels { rx: rx_batcher_to_mempool, tx: tx_mempool_to_batcher };
        
        // Build and run mempool.
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8UJtX8YoByNzjKjoo:-Nz8UJtX8YoByNzjKjop:bb76mu4) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L69)):*
> ```XML
>             gateway_client,
>             tx_batcher_to_mempool,
>             rx_mempool_to_batcher: Mutex::new(rx_mempool_to_batcher),
> ```

Why?



_Code quote:_
```XML
Mutex
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:40 UTC, elintul requested changes
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VeCM2CXgjWyuIgAO:-Nz8VeCM2CXgjWyuIgAP:b-g10vt7) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/gateway/src/gateway.rs#L83)):*
> ```XML
>     #[cfg(any(test, feature = "testing"))]
>     pub async fn create_for_testing(network_component: GatewayNetworkComponent) -> Gateway {
>         let stateless_transaction_validator_config =
> ```

Across snakecase code.



_Suggestion:_
```XML
tx
```
___
*[`crates/gateway/src/gateway.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8Vbka3wxZCoqreeZU:-Nz8Vbka3wxZCoqreeZV:bao22wm) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/gateway/src/gateway.rs#L84)):*
> ```XML
>     pub async fn create_for_testing(network_component: GatewayNetworkComponent) -> Gateway {
>         let stateless_transaction_validator_config =
>             crate::config::StatelessTransactionValidatorConfig {
> ```

Why fully qualified?



_Code quote:_
```XML
crate::config::StatelessTransactionValidatorConfig
```
___
*[`crates/gateway/src/gateway.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VnVm1A_7YEcNBlG8:-Nz8VnVm1A_7YEcNBlG9:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/gateway/src/gateway.rs#L96)):*
> ```XML
>             crate::config::StatefulTransactionValidatorConfig::create_for_testing();
> 
>         let config = GatewayConfig {
> ```





_Suggestion:_
```XML
gateway_config
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VRik1uiIfm-21DfM:-Nz8VRik1uiIfm-21DfN:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/tests/end_to_end_test.rs#L46)):*
> ```XML
> #[tokio::test]
> async fn test_end_to_end() {
>     let mock = IntegrationTestSetup::new().await;
> ```





_Suggestion:_
```XML
mock_running_system
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:42 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 10 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VzkxC9TM-SKsDlaD:-Nz8VzkxC9TM-SKsDlaE:b4uwhok) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L75)):*
> ```XML
>     }
> 
>     pub async fn assert_add_tx_success(&self, tx: &ExternalTransaction, expected: &str) {
> ```

Is this method needed? 



_Suggestion:_
```XML
add_tx
```


<!-- Sent from Reviewable.io -->

2024-06-03 05:10 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8Vbka3wxZCoqreeZU:-NzRJ3J75cFmrJWJ9rJ8:bipdtgj) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/gateway/src/gateway.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why fully qualified?
</blockquote></details>

Because of the `#[cfg(any(test, feature = "testing"))]`, new imports inside conditionally compiled code need to either:
1.  be fully qualified
2. have imports inside the function (yuck)
3.  add imports in the usual place, but with more `#[cfg(any(test, feature = "testing"))]`, one per new import per import (also yuck)
___
*[`crates/tests-integration/Cargo.toml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TOzS0YLrSWHF1FBd:-NzRLuB8DiXVESXCDMYJ:bl8eewu) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/Cargo.toml#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the trailing comma be removed, so the line doesn't break?
</blockquote></details>

Tnx, finally i got around to fixing the defaults in my TOML formatter.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8U3U755-D7X41Wpsb:-NzRMF9G9HDQvy9X91q3:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L59)):*
> ```XML
>         let batcher_channels =
>             BatcherToMempoolChannels { rx: rx_batcher_to_mempool, tx: tx_mempool_to_batcher };
>         // Build and run mempool.
> ```

Done.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8UJtX8YoByNzjKjoo:-NzRMfaD5Q3zrqal6o4k:b-xmxgz6) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L69)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I have no idea :thinking: 
Removed.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VzkxC9TM-SKsDlaD:-NzRPzBKDRuWabqF3JLc:b-52f2bh) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this method needed?
</blockquote></details>

Not 100 sure :thinking: 
It's currently a wrapper around a gw_client method of the same name, that calls `add_tx` but also asserts success.
If I just call it `add_tx` it might be a surprise for users doing negative flows.

Perhaps it should be renamed into `add_tx` like you said, and for negative flows I'll add a `add_tx_failure`?
Is it OK to hide the assert_success part in that case?
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzRVAeS0-LdF_rlgy8H:-NzRVAeS0-LdF_rlgy8I:b-jygcnf) ([raw file](https://github.com/starkware-libs/mempool/blob/b48765e1c8c874a880d068e1ef4414e124eb7111/crates/tests-integration/src/integration_test_setup.rs#L81)):*
> ```XML
> 
>     pub async fn add_tx_error(&self, tx: &ExternalTransaction) -> GatewayError {
>         self.gateway_client.assert_add_tx_error(tx).await
> ```

Doesn't compile yet, waiting on [this PR](https://reviewable.io/reviews/starkware-libs/mempool/204)



_Code quote:_
```XML
      self.gateway_client.assert_add_tx_error(tx).await
```


<!-- Sent from Reviewable.io -->

2024-06-04 06:30 UTC, elintul reviewed
> Reviewed 1 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzWur6A8cMLUKvdS_Or:-NzWur6A8cMLUKvdS_Os:bfajci5) ([raw file](https://github.com/starkware-libs/mempool/blob/a7bec1986b947e948b16fbbef2f69759b4fc855f/crates/gateway/src/gateway.rs#L99)):*
> ```XML
>         let gateway_config = GatewayConfig {
>             network_config,
>             stateless_transaction_validator_config: stateless_tx_validator_config,
> ```

Dammit. :(



_Code quote:_
```XML
stateless_transaction_validator_config: stateless_tx_validator_config,
```
___
*[`crates/tests-integration/Cargo.toml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TOzS0YLrSWHF1FBd:-NzWw2jt0ozM3NylScXZ:bbihj1d) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/Cargo.toml#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Tnx, finally i got around to fixing the defaults in my TOML formatter.
</blockquote></details>

Cool! Can we commit those configs to the repo.?
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8UJtX8YoByNzjKjoo:-NzWwCRh-yZ9VOx3tCJj:b32vhw) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L69)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I have no idea :thinking: 
Removed.
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2024-06-04 07:02 UTC, elintul approved these changes
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8VzkxC9TM-SKsDlaD:-NzX1n6TCHP5R69d1OLH:b-9hxfwy) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/src/integration_test_setup.rs#L75)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not 100 sure :thinking: 
It's currently a wrapper around a gw_client method of the same name, that calls `add_tx` but also asserts success.
If I just call it `add_tx` it might be a surprise for users doing negative flows.

Perhaps it should be renamed into `add_tx` like you said, and for negative flows I'll add a `add_tx_failure`?
Is it OK to hide the assert_success part in that case?
</blockquote></details>

I understand. Let's go with the client's terminology.


<!-- Sent from Reviewable.io -->

2024-06-04 07:43 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-04 09:01 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8Vbka3wxZCoqreeZU:-NzXOr2Q2f8S6gIzUCqp:b-u8f5vx) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/gateway/src/gateway.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks!! So is using fully-qualified names make it unnecessary to import the modules?
</blockquote></details>

yep, the left-most part of the fully-qualified thing is automatically imported: it's basically either `crate`, which is obviously always available, or the name of an external crate, like `tokio`, which are all auto-imported after they are included in cargo.toml.
___
*[`crates/gateway/src/gateway.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzWur6A8cMLUKvdS_Or:-NzXPL3i2WNsLl-qZuIn:b-lv8d5m) ([raw file](https://github.com/starkware-libs/mempool/blob/a7bec1986b947e948b16fbbef2f69759b4fc855f/crates/gateway/src/gateway.rs#L99)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

[Changed](https://reviewable.io/reviews/starkware-libs/mempool/206). :grimacing:
</blockquote></details>

fixed, tnx!
___
*[`crates/tests-integration/Cargo.toml` line 17 at r4](https://reviewable.io/reviews/starkware-libs/mempool/174#-Nz8TOzS0YLrSWHF1FBd:-NzXQ9ClBb5uQZaXHHkb:b-8taoj3) ([raw file](https://github.com/starkware-libs/mempool/blob/81c42ca379bb43d1c1fafe66bb9dd8937d4208fd/crates/tests-integration/Cargo.toml#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Cool! Can we commit those configs to the repo.?
</blockquote></details>

In the works.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzRVAeS0-LdF_rlgy8H:-NzXTqHzC5bLPdviZ8US:bish9o5) ([raw file](https://github.com/starkware-libs/mempool/blob/b48765e1c8c874a880d068e1ef4414e124eb7111/crates/tests-integration/src/integration_test_setup.rs#L81)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Doesn't compile yet, waiting on [this PR](https://reviewable.io/reviews/starkware-libs/mempool/204)
</blockquote></details>

Other PR merged, should work now (had to add a missing `async` in the decleration though, was a bug)


<!-- Sent from Reviewable.io -->

2024-06-04 09:16 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174#-:-NzXX5sTCwta9NV3OAG7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-06 07:56 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzRVAeS0-LdF_rlgy8H:-NzgY6H12q4k3w8WCwg4:bzfzy5w) ([raw file](https://github.com/starkware-libs/mempool/blob/b48765e1c8c874a880d068e1ef4414e124eb7111/crates/tests-integration/src/integration_test_setup.rs#L81)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Other PR merged, should work now (had to add a missing `async` in the decleration though, was a bug)
</blockquote></details>

Other PR merged, this PR passes now.


<!-- Sent from Reviewable.io -->

2024-06-06 11:06 UTC, elintul approved these changes
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 78 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCuhsC7oam1aqwE3k:-NzhCuhsC7oam1aqwE3l:bb6skvs) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/gateway/src/gateway.rs#L78)):*
> ```XML
> 
>     #[cfg(any(test, feature = "testing"))]
>     pub async fn create_for_testing(mempool_client: Arc<dyn MempoolClient>) -> Gateway {
> ```

Should we alias by now?



_Code quote:_
```XML
Arc<dyn MempoolClient>
```
___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCzbK01BuI3h5remZ:-NzhCzbL6dHe890EdHCb:b-ugrhkd) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/mempool_types/src/mempool_types.rs#L30)):*
> ```XML
>     pub state: AccountState,
> }
> ```

Why the `derive(Clone)`s?
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 25 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhDWmw5jmCbWVItYlk:-NzhDWmw5jmCbWVItYll:bjb892a) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/tests-integration/src/integration_test_setup.rs#L25)):*
> ```XML
>     pub gateway_client: GatewayClient,
>     // TODO(MockBatcher).
>     pub batcher_mempool_client: MempoolClientImpl,
> ```

Oh no, maybe the `trait` should be called `XClientInterface` and the specific impl. `XClient`? :grimacing: 



_Code quote:_
```XML
MempoolClientImpl
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 66 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhDNYl5wK75k1XB4bP:-NzhDNYl5wK75k1XB4bQ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/tests-integration/src/integration_test_setup.rs#L66)):*
> ```XML
> 
>         Self {
>             task_executor: executor,
> ```





_Suggestion:_
```XML
task_executor
```


<!-- Sent from Reviewable.io -->

2024-06-13 06:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 78 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCuhsC7oam1aqwE3k:-O-FHRh0BV1nB6U3Gp4j:b-cp741u) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should we alias by now?
</blockquote></details>

Good idea, adding in separate PR: https://reviewable.io/reviews/starkware-libs/mempool/237
___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCzbK01BuI3h5remZ:-O-FJr4Y3drmACcRCwQu:b-nwl37h) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/mempool_types/src/mempool_types.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why the `derive(Clone)`s?
</blockquote></details>

For the `get_txs` command in integration_test_setup.

I want to execute this call on a separate thread, to simulate it being called from an external batcher service (until we have a mockBatcher service ready at least).

To do that, I need to clone the mempool client, in order to pass it to the spawned task.

Since `Clone` is an Ok thing for MempoolRequest/Response to have (not too expensive), I added it without any cfg/testing thing.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 25 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhDWmw5jmCbWVItYlk:-O-FJOuiArB2h0VIFlzh:but0vpx) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/tests-integration/src/integration_test_setup.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Oh no, maybe the `trait` should be called `XClientInterface` and the specific impl. `XClient`? :grimacing:
</blockquote></details>

Can you xplain more plz, i'm not sure i follow :thinking: 
This is supposed to represent the "Mempool instance" that the (to be implemented MockBatcher) stores and issues commands to. 
When we have mockBatcher, this field will be a field there, and called `pub mempool_client` or maybe just `pub mempool`.


<!-- Sent from Reviewable.io -->

2024-06-13 09:33 UTC, MohammadNassar1 reviewed
> Reviewed 3 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 78 at r10](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-FuHdB2Qc8fu6-pGMO:-O-FuHdB2Qc8fu6-pGMP:b-saqfsy) ([raw file](https://github.com/starkware-libs/mempool/blob/7188957fad387086afbaa8ac82dcfa5e795c5d36/crates/gateway/src/gateway.rs#L78)):*
> ```XML
> 
>     #[cfg(any(test, feature = "testing"))]
>     pub async fn create_for_testing(mempool_client: Arc<dyn MempoolClient>) -> Gateway {
> ```

Why it's in a production file?
can you move it to test_util?



_Code quote:_
```XML
 pub async fn create_for_testing
```
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 11 at r10](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-FwNgy1uVeJglTw11c:-O-FwNgy1uVeJglTw11d:b5b31zc) ([raw file](https://github.com/starkware-libs/mempool/blob/7188957fad387086afbaa8ac82dcfa5e795c5d36/crates/tests-integration/tests/end_to_end_test.rs#L11)):*
> ```XML
>     let expected_tx_hash = mock_running_system.assert_add_tx_success(&invoke_tx()).await;
> 
>     // TODO: compare
> ```

What to compare?



_Code quote:_
```XML
 TODO: compare
```


<!-- Sent from Reviewable.io -->

2024-06-14 04:33 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 78 at r10](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-FuHdB2Qc8fu6-pGMO:-O-H29yi1fSk6amvLYh4:b-qwmimx) ([raw file](https://github.com/starkware-libs/mempool/blob/7188957fad387086afbaa8ac82dcfa5e795c5d36/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why it's in a production file?
can you move it to test_util?
</blockquote></details>

Done.

I initially thought about putting it there to make it easier to find, but since this one is only useful for integration testing, It's less justified.
___
*[`crates/tests-integration/tests/end_to_end_test.rs` line 11 at r10](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-FwNgy1uVeJglTw11c:-O-GyPz4CxpwjlME13nG:bb7evb8) ([raw file](https://github.com/starkware-libs/mempool/blob/7188957fad387086afbaa8ac82dcfa5e795c5d36/crates/tests-integration/tests/end_to_end_test.rs#L11)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What to compare?
</blockquote></details>

derp


<!-- Sent from Reviewable.io -->

2024-06-16 07:57 UTC, elintul approved these changes
> Reviewed 2 of 4 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 78 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCuhsC7oam1aqwE3k:-O-V0CGv76mDUBHd9m2G:bwsksa4) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good idea, adding in separate PR: https://reviewable.io/reviews/starkware-libs/mempool/237
</blockquote></details>

Thanks for thinking of a good name! Let Itay know? We've been struggling to find one.
___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCzbK01BuI3h5remZ:-O-V2B5Q32XHpAo56-mK:b-djx1l5) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/mempool_types/src/mempool_types.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For the `get_txs` command in integration_test_setup.

I want to execute this call on a separate thread, to simulate it being called from an external batcher service (until we have a mockBatcher service ready at least).

To do that, I need to clone the mempool client, in order to pass it to the spawned task.

Since `Clone` is an Ok thing for MempoolRequest/Response to have (not too expensive), I added it without any cfg/testing thing.
</blockquote></details>

Problem is, transactions might be big; let's revisit this.
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 25 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhDWmw5jmCbWVItYlk:-O-V0rrm7x-WWon60YyS:baoaw7o) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/tests-integration/src/integration_test_setup.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you xplain more plz, i'm not sure i follow :thinking: 
This is supposed to represent the "Mempool instance" that the (to be implemented MockBatcher) stores and issues commands to. 
When we have mockBatcher, this field will be a field there, and called `pub mempool_client` or maybe just `pub mempool`.
</blockquote></details>

Was wondering what's an in intuitive naming convention will be. Let's discuss offline.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 18 at r11](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-V13cB4kKkTUSyKTLG:-O-V13cB4kKkTUSyKTLH:b-12894b) ([raw file](https://github.com/starkware-libs/mempool/blob/439417957aec51d4ae24f9d7c7c83cecaa8d4d38/crates/tests-integration/src/integration_test_utils.rs#L18)):*
> ```XML
> use starknet_mempool_types::mempool_types::MempoolClient;
> 
> pub async fn create_gateway(mempool_client: Arc<dyn MempoolClient>) -> Gateway {
> ```

Why not a static method of `Gateway` anymore?



_Code quote:_
```XML
create_gateway
```


<!-- Sent from Reviewable.io -->

2024-06-17 04:38 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/src/gateway.rs` line 78 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCuhsC7oam1aqwE3k:-O-VGST0ADZcJlH0oXfa:b56h0hs) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks for thinking of a good name! Let Itay know? We've been struggling to find one.
</blockquote></details>

Pinged him about it now.
He's OOO so if he wants it changed we'll talk about it once he's back.
___
*[`crates/tests-integration/src/integration_test_utils.rs` line 18 at r11](https://reviewable.io/reviews/starkware-libs/mempool/174#-O-V13cB4kKkTUSyKTLG:-O-ZTphT3sJnFCanB8KQ:b-d4edz3) ([raw file](https://github.com/starkware-libs/mempool/blob/439417957aec51d4ae24f9d7c7c83cecaa8d4d38/crates/tests-integration/src/integration_test_utils.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not a static method of `Gateway` anymore?
</blockquote></details>

Mohammad brought it up, and I realized it is only useful for integration tests, so this seemed like a more natural place to look for it.
___
*[`crates/mempool_types/src/mempool_types.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/mempool/174#-NzhCzbK01BuI3h5remZ:-O-VVSieCjTHkZ03EqDv:b-sjwro8) ([raw file](https://github.com/starkware-libs/mempool/blob/e1d6e12a875ee70053eae61f57e04a0f1806fd14/crates/mempool_types/src/mempool_types.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Problem is, transactions might be big; let's revisit this.
</blockquote></details>

Okay it was a bug, clone wasn't really necessary, it's just the `derive(Clone)` that artificially forced them to be `Clone`. 
Deriving manually fixes this.
Fixed.


<!-- Sent from Reviewable.io -->

2024-06-18 06:28 UTC, giladchase reviewed
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-18 06:28 UTC, giladchase reviewed
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/174)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-06-18 06:30 UTC, merged