fix: add tie-breaker to mempool ordering
starkware-libs/mempool pull request #189
Opened 2024-05-29 12:35 UTC by giladchase

`BtreeSet` expects keys to be unique, so if we only cmp based on tip,
 trying to add txs with identical tips fails silently on the `push` that
 is now asserted against.

2024-05-29 13:44 UTC, MohammadNassar1 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz3Zf2294PQTplQPMm9:-Nz3Zf2294PQTplQPMmA:bcp940n) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/mempool_test.rs#L178)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_with_identical_tip_success(mut mempool: Mempool) {
> ```

Please check that it gets tx1 before tx2.
Test a scenario that tx1 tip > tx2 tip and tx1 hash < tx2 hash.
Test duplicated transactions.



_Code quote:_
```XML
test_add_tx_with_identical_tip_success
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:23 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz3Zf2294PQTplQPMm9:-Nz3apxV23wmTKy3fk61:bxoqn58) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/mempool_test.rs#L178)):*
> Please check that it gets tx1 before tx2.  
> Test a scenario that tx1 tip > tx2 tip and tx1 hash < tx2 hash.

I totally get why you want this, I thought about it too.
However, since we're planning to introduce more meaningful tie-breakers, testing hash-based ordering may not be necessary. The hash comparison is a failsafe and unlikely to be used frequently. Future secondary comparisons, like expiration time, will be more effective. The primary goal of this test is to ensure our ordering remains unique.

WDYT?

>Test duplicated transactions.

Tested separately in `test_add_same_tx`


<!-- Sent from Reviewable.io -->

2024-05-30 08:41 UTC, elintul approved these changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz7e9Z42axK4s6AtJiA:-Nz7e9Z58HnxZwlgj75C:b-f1o2oe) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/priority_queue.rs#L15)):*
> ```XML
>     pub fn push(&mut self, tx: ThinTransaction) {
>         let mempool_tx = PrioritizedTransaction(tx);
>         assert!(self.insert(mempool_tx), "keys should be unique; duplicates checked prior.");
> ```

Please also doc. this in the Q's docstring.



_Suggestion:_
```XML
Keys should be unique; duplicates are checked prior.
```


<!-- Sent from Reviewable.io -->

2024-05-30 09:19 UTC, elintul approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz7mzu-E6NaK2BkHscR:-Nz7mzu-E6NaK2BkHscS:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/57fa051023af22da78d0da9712f86d5538e402f7/crates/mempool/src/mempool_test.rs#L178)):*
> ```XML
> 
> #[rstest]
> fn test_add_tx_with_identical_tip_success(mut mempool: Mempool) {
> ```





_Suggestion:_
```XML
succeeds
```
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz7l4qxEbKC6xSwv1Nt:-Nz7l4qy7YhKG_8DHlyL:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/57fa051023af22da78d0da9712f86d5538e402f7/crates/mempool/src/mempool_test.rs#L187)):*
> ```XML
> 
>     let account2 = Account { address: contract_address!("0x1"), ..Default::default() };
>     // Create a tx with identical tip, it should be allowed through since the priority queue
> ```





_Suggestion:_
```XML
transaction
```


<!-- Sent from Reviewable.io -->

2024-05-30 09:56 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz3Zf2294PQTplQPMm9:-Nz7uWli10odYzD95cMP:b-xocsom) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/mempool_test.rs#L178)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> Please check that it gets tx1 before tx2.  
> Test a scenario that tx1 tip > tx2 tip and tx1 hash < tx2 hash.

I totally get why you want this, I thought about it too.
However, since we're planning to introduce more meaningful tie-breakers, testing hash-based ordering may not be necessary. The hash comparison is a failsafe and unlikely to be used frequently. Future secondary comparisons, like expiration time, will be more effective. The primary goal of this test is to ensure our ordering remains unique.

WDYT?

>Test duplicated transactions.

Tested separately in `test_add_same_tx`
</blockquote></details>

I think we still need to add such a scenario (that tests the tie-breaker), Then, when changing the tie-breaker we won't forget to add it.


<!-- Sent from Reviewable.io -->

2024-06-02 07:22 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz3Zf2294PQTplQPMm9:-NzMjj8nEUMVO-OciASg:bnfovnt) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/mempool_test.rs#L178)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think we still need to add such a scenario (that tests the tie-breaker), Then, when changing the tie-breaker we won't forget to add it.
</blockquote></details>

Fair enough.
Had to refactor some stuff before adding them though, things were getting too duplicat'ish: [PTAL](https://reviewable.io/reviews/starkware-libs/mempool/199) 
(The current PR depends on that one and will pass CI once #199 is merged)


<!-- Sent from Reviewable.io -->

2024-06-02 07:33 UTC, elintul requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz7l4qxEbKC6xSwv1Nt:-NzMpdnU6hE-ap5M5WNG:bry4eju) ([raw file](https://github.com/starkware-libs/mempool/blob/57fa051023af22da78d0da9712f86d5538e402f7/crates/mempool/src/mempool_test.rs#L187)):*
> ```XML
> 
>     let account2 = Account { address: contract_address!("0x1"), ..Default::default() };
>     // Create a tx with identical tip, it should be allowed through since the priority queue
> ```

Until now we used "transaction" in doc.; LMK if you think differently.
___
*[`crates/mempool/src/mempool_test.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/189#-NzMrLj8CJUMb7RvWc9O:-NzMrLj8CJUMb7RvWc9P:b-j818sd) ([raw file](https://github.com/starkware-libs/mempool/blob/1447a248e326ac53f0c38764ae8349e41e01fd88/crates/mempool/src/mempool_test.rs#L179)):*
> ```XML
> #[rstest]
> fn test_add_tx_with_identical_tip_succeeds(mut mempool: Mempool) {
>     let (tx1, account1) = add_tx_input!(Tip(1), TransactionHash(StarkFelt::TWO));
> ```

Can't find it anywhere, bad `rebase`?



_Code quote:_
```XML
add_tx_input
```


<!-- Sent from Reviewable.io -->

2024-06-02 09:30 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz7l4qxEbKC6xSwv1Nt:-NzNGuDB5LPDTBVy6fcF:b-92cqic) ([raw file](https://github.com/starkware-libs/mempool/blob/57fa051023af22da78d0da9712f86d5538e402f7/crates/mempool/src/mempool_test.rs#L187)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Until now we used "transaction" in doc.; LMK if you think differently.
</blockquote></details>

Nope yr right, i keep forgetting that :pleading_face:.
Done.
___
*[`crates/mempool/src/mempool_test.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/mempool/189#-NzMrLj8CJUMb7RvWc9O:-NzNGgxT6aqkluA9qp_f:bgo75va) ([raw file](https://github.com/starkware-libs/mempool/blob/1447a248e326ac53f0c38764ae8349e41e01fd88/crates/mempool/src/mempool_test.rs#L179)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't find it anywhere, bad `rebase`?
</blockquote></details>

Waiting on this [PR](https://reviewable.io/reviews/starkware-libs/mempool/199) (see thread with Mohammad above), didn't want to stack.
Will pass once it is merged.


<!-- Sent from Reviewable.io -->

2024-06-06 06:16 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/mempool/189#-Nz3Zf2294PQTplQPMm9:-NzgAXqt34B4ItyGV-4y:b-dthncl) ([raw file](https://github.com/starkware-libs/mempool/blob/dc33780f71e124f8e1730004783d3126c9d3b124/crates/mempool/src/mempool_test.rs#L178)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Fair enough.
Had to refactor some stuff before adding them though, things were getting too duplicat'ish: [PTAL](https://reviewable.io/reviews/starkware-libs/mempool/199) 
(The current PR depends on that one and will pass CI once #199 is merged)
</blockquote></details>

Should pass CI now.


<!-- Sent from Reviewable.io -->

2024-06-06 06:26 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/189#-:-NzgDS4088vdV2LiW_1d:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 06:32 UTC, merged