refactor: update priority queue to use ThinPriorityTransaction
starkware-libs/mempool pull request #195
Opened 2024-05-30 13:53 UTC by MohammadNassar1

2024-06-05 09:49 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzbmSVg0qt2imUZ3vHX:-NzbmSVg0qt2imUZ3vHY:b-16v46q) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L35)):*
> ```XML
>             tx_store: TransactionStore::default(),
>             state: HashMap::default(),
>         };
> ```

Unrelated to this PR, do we want to impl. `Default` for `Mempool`?
@giladchase, feel free to answer too.



_Code quote:_
```XML
        let mut mempool = Mempool {
            txs_queue: TransactionPriorityQueue::default(),
            tx_store: TransactionStore::default(),
            state: HashMap::default(),
        };
```
___
*[`crates/mempool/src/mempool.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmoa0-n1C26mLAT41:-Nzbmoa0-n1C26mLAT42:b-5mpwol) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L41)):*
> ```XML
>             // if the key was not present, otherwise returns the old value while updating
>             // the new value.
>             let prev_value = mempool.state.insert(input.account.address, input.account.state);
> ```

Please unpack earlier.



_Code quote:_
```XML
input.account.address, input.account.state
```
___
*[`crates/mempool/src/mempool.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbms6iDggCL-9btbSY:-Nzbms6iDggCL-9btbSZ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L41)):*
> ```XML
>             // if the key was not present, otherwise returns the old value while updating
>             // the new value.
>             let prev_value = mempool.state.insert(input.account.address, input.account.state);
> ```





_Suggestion:_
```XML
existing_account_state
```
___
*[`crates/mempool/src/mempool.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmkz-AQpJH2Er_Htk:-Nzbmkz-AQpJH2Er_Htl:bcgjvre) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L58)):*
> ```XML
>             );
> 
>             mempool.txs_queue.push(input.tx.clone().into());
> ```

Why this change?



_Code quote:_
```XML
mempool.txs_queue.push(input.tx.clone().into());
```


<!-- Sent from Reviewable.io -->

2024-06-06 07:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmkz-AQpJH2Er_Htk:-Nzcav0m-Cl7_ly_pTL1:bjpm8r8) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Now I store `ThinPriorityTransaction` in `txs_queue`.
And the transaction is stored in tx_store.


<!-- Sent from Reviewable.io -->

2024-06-06 07:27 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzbmSVg0qt2imUZ3vHX:-NzgR3Nb3nrxRmUpbieq:b-gy4mo2) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unrelated to this PR, do we want to impl. `Default` for `Mempool`?
@giladchase, feel free to answer too.
</blockquote></details>

Currently [empty](https://github.com/starkware-libs/mempool/blob/4744e13dec4e8933717063621d733be66b9458ca/crates/mempool/src/mempool.rs#L56-L58) returns default Mempool.
Do you want to replace it with default trait impl?


<!-- Sent from Reviewable.io -->

2024-06-09 07:46 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmoa0-n1C26mLAT41:-Nzvx5Tr61L22hgPas68:bqt06pk) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L41)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please unpack earlier.
</blockquote></details>

Use unpacking syntax instead: `let MempoolInput { sender address, state } = mempool_input`.


<!-- Sent from Reviewable.io -->

2024-06-09 09:14 UTC, ayeletstarkware requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwDq37B7nYmylbTIh3:-NzwDq37B7nYmylbTIh4:boy624s) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L43)):*
> ```XML
>             // the new value.
>             let address = input.account.sender_address;
>             let state = input.account.state;
> ```

why is it necessary?



_Code quote:_
```XML
            let address = input.account.sender_address;
            let state = input.account.state;
```
___
*[`crates/mempool/src/mempool.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwFn3-14enypvfypOm:-NzwFn3-14enypvfypOn:bm44qds) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L81)):*
> ```XML
>         let mut txs: Vec<ThinTransaction> = Vec::default();
>         for pq_tx in &pq_txs {
>             let tx = self.tx_store.remove(&pq_tx.tx_hash)?;
> ```

Why do you delete the txs from the tx_store? 
___
*[`crates/mempool/src/mempool_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwG9Fz1M5FV6KYv6k2:-NzwG9Fz1M5FV6KYv6k3:b-lxji4u) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool_test.rs#L152)):*
> ```XML
>         .iter()
>         .zip(mempool_txs)
>         .all(|(a, b)| <ThinTransaction as Into<ThinPriorityTransaction>>::into(a.clone()) == *b);
> ```

I find it hard to read
consider changing to something like this:



_Code snippet:_
```XML
fn check_mempool_txs_eq(mempool: &Mempool, expected_txs: &[ThinTransaction]) -> bool {
    let mempool_txs = mempool.txs_queue.iter();

    // Convert and compare transactions
    let transactions_match = expected_txs.iter().zip(mempool_txs).all(|(expected, actual)| {
        let expected_converted: ThinPriorityTransaction = expected.clone().into();
        expected_converted == *actual
    });

    transactions_match
}
```
___
*[`crates/mempool/src/priority_queue.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwCo_w2xGeyoNwnPTR:-NzwCo_w2xGeyoNwnPTS:b-t4c8u6) ([raw file](https://github.com/starkware-libs/mempool/blob/b0b1b47c2ea5a635e3038d253fca1db5497b8140/crates/mempool/src/priority_queue.rs#L26)):*
> ```XML
> }
> 
> impl From<Vec<ThinTransaction>> for TransactionPriorityQueue {
> ```

Why did you delete it? 
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-NzwBpCV5X416UQ4CLvC:b95bprq) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
> ```XML
> 
> #[derive(Clone, Debug, Default)]
> pub struct ThinPriorityTransaction {
> ```

Why not `PrioritizedTransaction`? It referred to `ThinTransaction` before without mentioning it.



_Code quote:_
```XML
ThinPriorityTransaction
```
___
*[`crates/mempool/src/transaction_store.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwCxf34816h8lrDlSI:-NzwCxf34816h8lrDlSJ:bgt7zzz) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/transaction_store.rs#L2)):*
> ```XML
> use std::collections::HashMap;
> ```

Perhaps you could remove the commit `- 92bfb61: feat: add transaction store data structure` so it doesn't appear to be part of the PR.


<!-- Sent from Reviewable.io -->

2024-06-09 09:33 UTC, ayeletstarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwFn3-14enypvfypOm:-NzwKjEP9nUPDVu17LSh:b-pf1e62) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L81)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why do you delete the txs from the tx_store?
</blockquote></details>

I guess it's part of inserting it into a staging area? If so, add a todo in this PR


<!-- Sent from Reviewable.io -->

2024-06-10 14:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwDq37B7nYmylbTIh3:-O-1_-qtCQdqFRqJqRBL:ba3dfob) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L43)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why is it necessary?
</blockquote></details>

Removed
___
*[`crates/mempool/src/mempool.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwFn3-14enypvfypOm:-O-1_Aut0FUCy26AxaiJ:bia72zu) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L81)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I guess it's part of inserting it into a staging area? If so, add a todo in this PR
</blockquote></details>

This Pr doesn't implement staging area.
So currently we delete tx in `get_txs`.


<!-- Sent from Reviewable.io -->

2024-06-12 11:52 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwG9Fz1M5FV6KYv6k2:-O-5kiWi1K24fOgn-Fyy:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool_test.rs#L152)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I find it hard to read
consider changing to something like this:
</blockquote></details>

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwCo_w2xGeyoNwnPTR:-O-BHVVeBIglJufOYCpV:bscl7nz) ([raw file](https://github.com/starkware-libs/mempool/blob/b0b1b47c2ea5a635e3038d253fca1db5497b8140/crates/mempool/src/priority_queue.rs#L26)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why did you delete it?
</blockquote></details>

Not in use anymore.
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-O-BHY-i8LHcIwr7yyN-:b-n9ep4s) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why not `PrioritizedTransaction`? It referred to `ThinTransaction` before without mentioning it.
</blockquote></details>

Changed back to `PrioritizedTransaction`
___
*[`crates/mempool/src/transaction_store.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwCxf34816h8lrDlSI:-O-BHblP6LxGN7I0MkDW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/transaction_store.rs#L2)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Perhaps you could remove the commit `- 92bfb61: feat: add transaction store data structure` so it doesn't appear to be part of the PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-20 09:37 UTC, elintul reviewed
> Reviewed 5 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzbmSVg0qt2imUZ3vHX:-Nzvz8mM7MZebguNIJaM:b-7ofegq) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Currently [empty](https://github.com/starkware-libs/mempool/blob/4744e13dec4e8933717063621d733be66b9458ca/crates/mempool/src/mempool.rs#L56-L58) returns default Mempool.
Do you want to replace it with default trait impl?
</blockquote></details>

Right, so let's use `empty` here.


<!-- Sent from Reviewable.io -->

2024-06-23 09:26 UTC, giladchase requested changes
> Reviewed 2 of 8 files at r6, all commit messages.
> Dismissed @ayeletstarkware from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O-Qg6yc12nbd7VpR4oh):*




_Suggestion:_
```
- ec0dae6: refactor: update priority queue to use PrioritizedTransaction
```
___
*[`crates/mempool/src/mempool.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmkz-AQpJH2Er_Htk:-O-QfIFE9cNAH1Nj6C4z:beokb0h) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L58)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Now I store `ThinPriorityTransaction` in `txs_queue`.
And the transaction is stored in tx_store.
</blockquote></details>

PriorityTransaction is an internal type of the priority queue (it should be private BTW), since it `Ord`ers and `==`s txs according to the priority queue, which doesn't make sense outside of the priority queue.
___
*[`crates/mempool/src/mempool.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwFn3-14enypvfypOm:-O03Nte16oLLYF2RI9VX:b75ddyf) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/mempool.rs#L81)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This Pr doesn't implement staging area.
So currently we delete tx in `get_txs`.
</blockquote></details>

Correct, you can dismiss Ayelet here since she's OOO.
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-O-Qgh9u9vtBC0WpmgQU:b-rap0j7) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Changed back to `PrioritizedTransaction`
</blockquote></details>

I think it should be`QueuedTransaction`, prioritized doesn't immediately make me feel of "in the priority queue".


<!-- Sent from Reviewable.io -->

2024-06-24 10:07 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzbmSVg0qt2imUZ3vHX:-O08JVd6CtfJh2TAFzxY:b5ylwo0) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Right, so let's use `empty` here.
</blockquote></details>

The empty function calls the new method with an empty list.
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-O08K6fu5DglwtpiLCFZ:bcs60xc) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think it should be`QueuedTransaction`, prioritized doesn't immediately make me feel of "in the priority queue".
</blockquote></details>

But queued means that it waits for another transaction(?). In this scenario, all the transactions are in PQ and ready to be sent.
wdyt about `ReadyTransaction`?


<!-- Sent from Reviewable.io -->

2024-06-24 10:07 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O-Qg6yc12nbd7VpR4oh):*
Done.


<!-- Sent from Reviewable.io -->

2024-06-24 12:33 UTC, elintul reviewed
> Reviewed 5 of 8 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-24 14:02 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzbmSVg0qt2imUZ3vHX:-O09VrZ0CB-orgD1l30U:behydpl) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The empty function calls the new method with an empty list.
</blockquote></details>

Done by @giladchase in [this](https://reviewable.io/reviews/starkware-libs/mempool/271) PR.
___
*[`crates/mempool/src/mempool.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmkz-AQpJH2Er_Htk:-O09Xdgp2KXK7Q-3Auzm:b-lbs7aj) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

PriorityTransaction is an internal type of the priority queue (it should be private BTW), since it `Ord`ers and `==`s txs according to the priority queue, which doesn't make sense outside of the priority queue.
</blockquote></details>

I can implement another struct (with the same fields without implementing Ord/Eq) in mempool.rs, and then implement the conversion. 
WDYT?


<!-- Sent from Reviewable.io -->

2024-06-25 08:11 UTC, elintul requested changes
> Reviewed 4 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 7 of 9 files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 21 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DE6suDLRnEM9OIG1F:-O0DE6suDLRnEM9OIG1G:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L21)):*
> ```XML
> pub struct Mempool {
>     // TODO: add docstring explaining visibility and coupling of the fields.
>     txs_queue: TransactionPriorityQueue,
> ```





_Suggestion:_
```XML
// Transactions eligible for sequencing.
tx_queue: TransactionQueue,
```
___
*[`crates/mempool/src/mempool.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DDl-i2AmTTHbBTKqx:-O0DDl-i2AmTTHbBTKqy:bg0n3w6) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L35)):*
> ```XML
>         };
> 
>         for MempoolInput { tx, account: Account { sender_address, state } } in inputs.into_iter() {
> ```

`for` already does that.



_Suggestion:_
```XML
inputs
```
___
*[`crates/mempool/src/mempool.rs` line 91 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DEJjfBJgyHGOAdQw2:-O0DEJjfBJgyHGOAdQw3:ba6fugr) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L91)):*
> ```XML
>                 entry.insert(account.state);
>                 // TODO(Mohammad): use `handle_tx`.
>                 self.txs_queue.push(tx.clone().into());
> ```

Is this needed? I want to remove `Clone` from transaction ASAP.



_Code quote:_
```XML
tx.clone()
```
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-O0DBf8o3zvTchRzh1hw:b-rwlfc5) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But queued means that it waits for another transaction(?). In this scenario, all the transactions are in PQ and ready to be sent.
wdyt about `ReadyTransaction`?
</blockquote></details>

`Queued` is good here, it means it's _in the queue_. :)
___
*[`crates/mempool/src/priority_queue.rs` line 12 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DCDWAAbfny9-7qhaZ:-O0DCDWAAbfny9-7qha_:bd5inr1) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L12)):*
> ```XML
> // transactions with future nonces will need to be stored, and potentially indexed on block commits.
> 
> // Priority queue of transactions with associated priority.
> ```

Not sure it adds information to the reader.



_Code quote:_
```XML
// Priority queue of transactions with associated priority.
```
___
*[`crates/mempool/src/priority_queue.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DE3vX4Jbg7a4W1ZGX:-O0DE3vX4Jbg7a4W1ZGY:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L14)):*
> ```XML
> // Priority queue of transactions with associated priority.
> #[derive(Clone, Debug, Default, derive_more::Deref, derive_more::DerefMut)]
> pub struct TransactionPriorityQueue(BTreeSet<PrioritizedTransaction>);
> ```





_Suggestion:_
```XML
TransactionQueue
```
___
*[`crates/mempool/src/priority_queue.rs` line 24 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DCZofEVLbfuU6otJl:-O0DCZofEVLbfuU6otJm:b283b7a) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L24)):*
> ```XML
> 
>     // TODO(gilad): remove collect
>     pub fn pop_last_chunk(&mut self, n_txs: usize) -> Vec<PrioritizedTransaction> {
> ```

Why did this method change? I think it was readable enough before (note you don't need the `.0`thanks to `derive_more::DerefMut`).



_Code quote:_
```XML
pop_last_chunk
```
___
*[`crates/mempool/src/priority_queue.rs` line 24 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DL3E1AGF1obQh8XyH:-O0DL3E1AGF1obQh8XyI:bxrrrcf) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L24)):*
> ```XML
> 
>     // TODO(gilad): remove collect
>     pub fn pop_last_chunk(&mut self, n_txs: usize) -> Vec<PrioritizedTransaction> {
> ```

Are we planning to change this to return only hashes?



_Code quote:_
```XML
Vec<PrioritizedTransaction>
```
___
*[`crates/mempool/src/priority_queue.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DDuj33tVrY3j6aGs4:-O0DDuj33tVrY3j6aGs5:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L34)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Clone, Debug, Default)]
> pub struct PrioritizedTransaction {
> ```





_Suggestion:_
```XML
struct PrioritizedTransaction
```
___
*[`crates/mempool/src/priority_queue.rs` line 35 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DD9bx1Yg0A5JzaSNl:-O0DD9bx1Yg0A5JzaSNm:b-cy1sr4) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L35)):*
> ```XML
> #[derive(Clone, Debug, Default)]
> pub struct PrioritizedTransaction {
>     pub address: ContractAddress,
> ```

For consistency,



_Suggestion:_
```XML
sender_address
```


<!-- Sent from Reviewable.io -->

2024-06-25 08:12 UTC, elintul reviewed
> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 148 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DRswsAlolE-7EkQ_w:-O0DRswt0GHWMK6dGNXJ:b-sx1vnq) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool_test.rs#L148)):*
> ```XML
> // transactions.
> #[track_caller]
> fn check_mempool_txs_eq(mempool: &Mempool, expected_txs: &[ThinTransaction]) {
> ```

Why not change the input type?



_Code quote:_
```XML
expected_txs: &[ThinTransaction]
```


<!-- Sent from Reviewable.io -->

2024-06-25 08:15 UTC, elintul reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 13 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 79 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DSeLbBUR0ZLaHBP1_:-O0DSeLbBUR0ZLaHBP1a:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L79)):*
> ```XML
>         }
> 
>         Ok(txs)
> ```





_Suggestion:_
```XML
        let eligible_tx_hashes = self.txs_queue.pop_last_chunk(n_txs).into_iter().map(|tx| tx.tx_hash);
        let mut eligible_txs: Vec<ThinTransaction> = Vec::with_capacity(n_txs);
        for tx_hash in eligible_tx_hashes {
            let tx = self.tx_pool.remove(tx_hash)?;
            self.state.remove(&tx.sender_address);
            eligible_txs.push(tx);
        }
```


<!-- Sent from Reviewable.io -->

2024-06-25 09:26 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 91 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DEJjfBJgyHGOAdQw2:-O0DbvA1BhS_-tLdkkC6:b7wyokv) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L91)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this needed? I want to remove `Clone` from transaction ASAP.
</blockquote></details>

Implement `from(&ThinTransaction`.
Done.
___
*[`crates/mempool/src/mempool_test.rs` line 148 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DRswsAlolE-7EkQ_w:-O0DbwLQBZViAnsmPgQ7:b-80206g) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool_test.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not change the input type?
</blockquote></details>

In the test, we have `ThinTransaction`, and we want to keep the test simple. so, we prefer to handle the conversion in the `test_utils` rather than in the test itself.
___
*[`crates/mempool/src/priority_queue.rs` line 28 at r5](https://reviewable.io/reviews/starkware-libs/mempool/195#-NzwBpCV5X416UQ4CLvB:-O0Dfxn-0j7TCPtJaQ-S:b32w0x) ([raw file](https://github.com/starkware-libs/mempool/blob/f5e0c9a46dea46ef38f709ac4a81636ae26ff0f8/crates/mempool/src/priority_queue.rs#L28)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`Queued` is good here, it means it's _in the queue_. :)
</blockquote></details>

OK
___
*[`crates/mempool/src/priority_queue.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DE3vX4Jbg7a4W1ZGX:-O0DcWxv0bmbEu_fr5MV:brpmqc3) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L14)):*
> ```XML
> // Priority queue of transactions with associated priority.
> #[derive(Clone, Debug, Default, derive_more::Deref, derive_more::DerefMut)]
> pub struct TransactionPriorityQueue(BTreeSet<PrioritizedTransaction>);
> ```

removed.
___
*[`crates/mempool/src/priority_queue.rs` line 24 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DL3E1AGF1obQh8XyH:-O0DdF6pBgKt4nqiXfWM:b-bw8e14) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we planning to change this to return only hashes?
</blockquote></details>

Updated.
___
*[`crates/mempool/src/priority_queue.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DDuj33tVrY3j6aGs4:-O0DgXbj8wli2aU2VVB0:b-kabh67) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L34)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Clone, Debug, Default)]
> pub struct PrioritizedTransaction {
> ```

It's used in `transaction_pool` file, the account_to_nonce store transaction of type `PrioritizedTransaction`.
Note that this file is pub(crate), means that it's cannot be used outside of the crate.


<!-- Sent from Reviewable.io -->

2024-06-25 10:37 UTC, elintul requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 21 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DE6suDLRnEM9OIG1F:-O0DvPws3rXQ-EcZ5sMo:b-n7wgml) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L21)):*
> ```XML
> pub struct Mempool {
>     // TODO: add docstring explaining visibility and coupling of the fields.
>     txs_queue: TransactionPriorityQueue,
> ```

Add the comment?
___
*[`crates/mempool/src/mempool.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvbT2BNQ1irQamG5l:-O0DvbT2BNQ1irQamG5m:btyjidb) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L43)):*
> ```XML
>             }
> 
>             mempool.tx_queue.push((&tx).into());
> ```

Is there a more elegant alternative here? x2



_Code quote:_
```XML
(&tx).into()
```
___
*[`crates/mempool/src/mempool.rs` line 45 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvfH_9nDvEQM-C_7G:-O0DvfHa6Eofj5kzHd_9:bg5571b) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L45)):*
> ```XML
>             mempool.tx_queue.push((&tx).into());
> 
>             let tx_hash = tx.tx_hash;
> ```

Not sure this variable is needed, if only used once.



_Code quote:_
```XML
let tx_hash = tx.tx_hash;
```
___
*[`crates/mempool/src/priority_queue.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DxpNo-5JariyYhdHO:-O0DxpNo-5JariyYhdHP:b-kyip7q) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L9)):*
> ```XML
> // Assumption: for the MVP only one transaction from the same contract class can be in the mempool
> // at a time. When this changes, saving the transactions themselves on the queu might no longer be
> // appropriate, because we'll also need to stores transactions without indexing them. For example,
> ```

After receiving LGTMs, please rename file to `transcation_queue.rs`.
___
*[`crates/mempool/src/priority_queue.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DDuj33tVrY3j6aGs4:-O0DwnPU6TP7ECkPUslF:bgbydu5) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L34)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's used in `transaction_pool` file, the account_to_nonce store transaction of type `PrioritizedTransaction`.
Note that this file is pub(crate), means that it's cannot be used outside of the crate.
</blockquote></details>

We want the mempool not to know this type though, right? See my comment in `mempool.rs`.
___
*[`crates/mempool/src/transaction_pool.rs` line 19 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Dxi555hY3ki0Ndfnp:-O0Dxi555hY3ki0Ndfnq:bay90js) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/transaction_pool.rs#L19)):*
> ```XML
>     tx_pool: HashMap<TransactionHash, ThinTransaction>,
>     // Transactions organized by account address, sorted by ascending nonce values.
>     txs_by_account: HashMap<ContractAddress, BTreeMap<Nonce, QueuedTransaction>>,
> ```

Let's define `TransactionReference` here, and in the queue file define a newtype: `struct QueuedTransaction(TransactionReference)`.



_Code quote:_
```XML
QueuedTransaction
```
___
*[`crates/mempool/src/transaction_pool.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DwM_8DOzbAHgU622V:-O0DwM_8DOzbAHgU622W:b-w21f4y) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/transaction_pool.rs#L24)):*
> ```XML
> impl TransactionPool {
>     // TODO(Mohammad): Remove the cloning of tx once the QueuedTransaction is updated.
>     pub fn push(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
> ```

Why did the order change? Please add a short comment in Reviewable if a change isn't trivial.



_Code quote:_
```XML
push
```


<!-- Sent from Reviewable.io -->

2024-06-25 14:37 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 10 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Ep72uCVB0y0hbQ90u:-O0Ep72uCVB0y0hbQ90v:b-f2etu1) (no related file):*
Let me know if you want me to split the PR.

___
___
*[`crates/mempool/src/mempool.rs` line 21 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DE6suDLRnEM9OIG1F:-O0E2WbK7E6S3uPNwg4L:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/mempool.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add the comment?
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvbT2BNQ1irQamG5l:-O0E8qyP5r53Qr-HIsa6:b-7hyhv7) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a more elegant alternative here? x2
</blockquote></details>

I can define `tx_ref` first.



_Code snippet:_
```XML
 let tx_ref: &ThinTransaction = &tx;
```
___
*[`crates/mempool/src/mempool.rs` line 45 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvfH_9nDvEQM-C_7G:-O0ELqEA1Vp2txFAoiEB:b-klogt4) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure this variable is needed, if only used once.
</blockquote></details>

I extracted it before moving `tx`.
___
*[`crates/mempool/src/priority_queue.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DxpNo-5JariyYhdHO:-O0E9DCeBIZFLNY9rlys:b-ygkabc) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L9)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

After receiving LGTMs, please rename file to `transcation_queue.rs`.
</blockquote></details>

I'll do it in a different PR.
___
*[`crates/mempool/src/priority_queue.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DDuj33tVrY3j6aGs4:-O0EnoR09c4AKFTA7PBz:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/0dc2a51e72c36ae45584cdb6f6534554dd8e9d12/crates/mempool/src/priority_queue.rs#L34)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We want the mempool not to know this type though, right? See my comment in `mempool.rs`.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_pool.rs` line 19 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Dxi555hY3ki0Ndfnp:-O0EWGX56pdIBBqrSflz:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/transaction_pool.rs#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's define `TransactionReference` here, and in the queue file define a newtype: `struct QueuedTransaction(TransactionReference)`.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_pool.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DwM_8DOzbAHgU622V:-O0EWHTWB_Snao8_Nhwo:b-96myhr) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/transaction_pool.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why did the order change? Please add a short comment in Reviewable if a change isn't trivial.
</blockquote></details>

To avoid using `clone,` I accessed the inner fields (nonce, address) before moving `tx`.


<!-- Sent from Reviewable.io -->

2024-06-26 08:16 UTC, giladchase reviewed
> Reviewed 3 of 8 files at r7, 3 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Ep72uCVB0y0hbQ90u:-O0ISYfjBVDqVueh15dt:b8rxn3w) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let me know if you want me to split the PR.
</blockquote></details>

Yep i think so :pray:  there are too many things going on in a single commit.

For example:
- A rename operation should be a separate PR, so that it can be LGTMed immediately and reduce the diff drastically.
- Changing the return type to tx_hash can also be self contained in a PR

Keep the current PR live, and after those are split off we'll see if more splitting is needed

___
___
*[`crates/mempool/src/mempool.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/mempool/195#-Nzbmkz-AQpJH2Er_Htk:-O0IbFPK-R0cf3VtM2gb:b-iypmbn) ([raw file](https://github.com/starkware-libs/mempool/blob/03ce42f4f5baa87af126510e741d8c4878c2e0c4/crates/mempool/src/mempool.rs#L58)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I can implement another struct (with the same fields without implementing Ord/Eq) in mempool.rs, and then implement the conversion. 
WDYT?
</blockquote></details>

Discussed offline
___
*[`crates/mempool/src/mempool.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O03QPSMAMzVB99mPVl6:-O03QPSMAMzVB99mPVl7:byjwchw) ([raw file](https://github.com/starkware-libs/mempool/blob/ec0dae6176b60443a46b30178d71449b309baa78/crates/mempool/src/mempool.rs#L49)):*
> ```XML
>                  mempool.",
>                 sender_address,
>                 tx
> ```

You can do this now because you are no longer accessing internal fields, which isn't supported inside format-strings.



_Suggestion:_
```XML
                "Sender address: {sender_address:?} already exists in the mempool. Can't add {tx:?} to the \
                 mempool.",
```


<!-- Sent from Reviewable.io -->

2024-06-26 10:08 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Ep72uCVB0y0hbQ90u:-O0Izgab-8CAJLHgKucL:bwvg7xm) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep i think so :pray:  there are too many things going on in a single commit.

For example:
- A rename operation should be a separate PR, so that it can be LGTMed immediately and reduce the diff drastically.
- Changing the return type to tx_hash can also be self contained in a PR

Keep the current PR live, and after those are split off we'll see if more splitting is needed
</blockquote></details>

Thanks!
I opened [this](https://reviewable.io/reviews/starkware-libs/mempool/286) PR. it rename `PriorityTransaction` -> `QueuedTransaction`, and `PrioritizedTransaction` -> `QueuedTransaction`. Also changed `QueuedTransaction` to be private.

___


<!-- Sent from Reviewable.io -->

2024-06-26 10:39 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 69 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IbmY41fBlzELuKSSj:-O0IbmY41fBlzELuKSSk:b-bsccka) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L69)):*
> ```XML
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
>         let mut eligible_txs: Vec<ThinTransaction> = Vec::with_capacity(n_txs);
>         for tx_hash in self.tx_queue.pop_last_chunk(n_txs).into_iter() {
> ```

`for` calls this implicity i think



_Suggestion:_
```XML
        for tx_hash in self.tx_queue.pop_last_chunk(n_txs)
```
___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0IdAxv3WVTPcDW4eoB:bwrefim) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
> ```XML
> 
>     #[cfg(any(feature = "testing", test))]
>     pub fn iter(&self) -> impl Iterator<Item = &TransactionReference> {
> ```

I think this one's useful enough to be added to the API without qualifications.



_Suggestion:_
```XML
    pub fn iter(&self) -> impl Iterator<Item = &TransactionReference> {
```


<!-- Sent from Reviewable.io -->

2024-06-26 10:50 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0J9X254K9KDno75Lty:b4efav2) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this one's useful enough to be added to the API without qualifications.
</blockquote></details>

Since it's a pub (crate) file, it needs to be used. Alternatively, I can add "allow dead code" instead.
WDYT?


<!-- Sent from Reviewable.io -->

2024-06-26 11:09 UTC, elintul requested changes
> Reviewed 3 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O03QPSMAMzVB99mPVl6:-O0IvH64D30TA3Z50_Re:b-7zi8tj) ([raw file](https://github.com/starkware-libs/mempool/blob/ec0dae6176b60443a46b30178d71449b309baa78/crates/mempool/src/mempool.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You can do this now because you are no longer accessing internal fields, which isn't supported inside format-strings.
</blockquote></details>

WDYM?
___
*[`crates/mempool/src/mempool.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvbT2BNQ1irQamG5l:-O0IvJ0815r70GSDH41b:buhxjum) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I can define `tx_ref` first.
</blockquote></details>

Re `From<&ThinTransaction> for TransactionReference`: I find it a bit unintuitive that `From` receives a reference to the source object. Let's instead implement a `new` c-tor for `TransactionReference` which will receive the reference. Can be done in a seprate PR if you prefer.
___
*[`crates/mempool/src/mempool.rs` line 24 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Ix7F8-GfYC7_aROVU:-O0Ix7F8-GfYC7_aROVV:b-3lpaob) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L24)):*
> ```XML
>     tx_queue: TransactionQueue,
>     // All transactions currently held in the mempool.
>     tx_pool: TransactionPool,
> ```

I find it more natural that the main DS will appear first.



_Suggestion:_
```XML
    // All transactions currently held in the mempool.
    tx_pool: TransactionPool,
    // Transactions eligible for sequencing.
    tx_queue: TransactionQueue,
```
___
*[`crates/mempool/src/mempool.rs` line 111 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J-ewhANU7j-n8eWly:-O0J-ewi7XyTNrP6DAj6:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L111)):*
> ```XML
> /// `TransactionReference` is a struct that provides a lightweight reference to a transaction. It is
> /// not a reference type (i.e., `&tx`), but rather a struct that contains essential details about a
> /// transaction.
> ```





_Suggestion:_
```XML
/// Provides a lightweight representation of a transaction for mempool usage (e.g., excluding execution fields).
```
___
*[`crates/mempool/src/mempool.rs` line 114 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J0AoSEsLykJ-IUm11:-O0J0AoTA6vn2cZWvHl5:btv4o3a) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L114)):*
> ```XML
> ///
> /// Note: This struct will be renamed to `ThinTransaction` once that name
> /// becomes available, to better reflect its purpose and usage.
> ```

Convert to a TODO.



_Code quote:_
```XML
/// Note: This struct will be renamed to `ThinTransaction` once that name
/// becomes available, to better reflect its purpose and usage.
```
___
*[`crates/mempool/src/priority_queue.rs` line 12 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J0Hew3k8MlOAOEX7i:-O0J0Hew3k8MlOAOEX7j:biv44c) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/priority_queue.rs#L12)):*
> ```XML
> // transactions with future nonces will need to be stored, and potentially indexed on block commits.
> 
> #[derive(Clone, Debug, Default, derive_more::Deref, derive_more::DerefMut)]
> ```

Why were they deleted?



_Code quote:_
```XML
, derive_more::Deref, derive_more::DerefMut
```
___
*[`crates/mempool/src/transaction_pool.rs` line 26 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JDeVi7mtvrMlAHFSN:-O0JDeVi7mtvrMlAHFSO:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L26)):*
> ```XML
>         let tx_hash = tx.tx_hash;
> 
>         let txs_from_account_entry = self.txs_by_account.entry(tx.sender_address).or_default();
> ```





_Suggestion:_
```XML
// Insert transaction into the mapping by account.
let txs_from_account_entry = self.txs_by_account.entry(tx.sender_address).or_default();
```
___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0JE7Bs5HXGIMrrjOWF:b-gc03ql) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
> ```XML
>             }
>             btree_map::Entry::Occupied(_) => {
>                 return Err(MempoolError::DuplicateTransaction { tx_hash });
> ```

I think the `Occupied` logics got confused...



_Code quote:_
```XML
return Err(MempoolError::DuplicateTransaction { tx_hash });
```


<!-- Sent from Reviewable.io -->

2024-06-26 11:38 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 111 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J-ewhANU7j-n8eWly:-O0JIp1b12wX1OAK0DPJ:b-9h77qo) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L111)):*
> ```XML
> /// `TransactionReference` is a struct that provides a lightweight reference to a transaction. It is
> /// not a reference type (i.e., `&tx`), but rather a struct that contains essential details about a
> /// transaction.
> ```

Resolved [here](https://reviewable.io/reviews/starkware-libs/mempool/286).
___
*[`crates/mempool/src/mempool.rs` line 114 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J0AoSEsLykJ-IUm11:-O0JJ17W1zUt5yzUXvEN:b-9h77qo) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/mempool.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Convert to a TODO.
</blockquote></details>

Resolved [here](https://reviewable.io/reviews/starkware-libs/mempool/286).
___
*[`crates/mempool/src/priority_queue.rs` line 12 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0J0Hew3k8MlOAOEX7i:-O0JJDI08ZNJWepMsDeA:bvmwr2r) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/priority_queue.rs#L12)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why were they deleted?
</blockquote></details>

Can't leak a private type in a pubic interface. Because I change the internal type to be private.


<!-- Sent from Reviewable.io -->

2024-06-26 12:58 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O03QPSMAMzVB99mPVl6:-O0JYJe0-GEgKtH-mmvH:b32v57) ([raw file](https://github.com/starkware-libs/mempool/blob/ec0dae6176b60443a46b30178d71449b309baa78/crates/mempool/src/mempool.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

+1
___
*[`crates/mempool/src/mempool.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvbT2BNQ1irQamG5l:-O0JbzE01Ir0dQHp1VzX:b-ikul6m) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L43)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Re `From<&ThinTransaction> for TransactionReference`: I find it a bit unintuitive that `From` receives a reference to the source object. Let's instead implement a `new` c-tor for `TransactionReference` which will receive the reference. Can be done in a seprate PR if you prefer.
</blockquote></details>

Ok, let's do it in another PR.
___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0JZI007TZjgvSeesL-:b-koryyr) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think the `Occupied` logics got confused...
</blockquote></details>

Why do you think it got confused?
If we have the same none, we return duplicated tx.


<!-- Sent from Reviewable.io -->

2024-06-26 13:15 UTC, elintul requested changes
> Reviewed 1 of 2 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0JfscU51Da3DpDmBOr:baunzzn) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why do you think it got confused?
If we have the same none, we return duplicated tx.
</blockquote></details>

The duplicate transaction error is returned if the hash already exists; otherwise we panic. Right? 


<!-- Sent from Reviewable.io -->

2024-06-26 13:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0DvbT2BNQ1irQamG5l:-O0Ji9pF4Jam-JCVA9DI:b-ssfjji) ([raw file](https://github.com/starkware-libs/mempool/blob/27c84765dfea28ce4046091975248cc47c105c59/crates/mempool/src/mempool.rs#L43)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Ok, let's do it in another PR.
</blockquote></details>

Done [here](https://reviewable.io/reviews/starkware-libs/mempool/288)
___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0JiLvt89zdp5usoI1T:byzmah2) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The duplicate transaction error is returned if the hash already exists; otherwise we panic. Right?
</blockquote></details>

We return a duplicated error if the transaction already exists.
and panic we added for the case that cannot happen (consistency error) that tx appears in one (account) mapping and doesn't appear in the other (store) mapping.
Then, panic is added in the second if condition.


<!-- Sent from Reviewable.io -->

2024-06-27 09:14 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/195#-O03QPSMAMzVB99mPVl6:-O0NxRD27zauYPnG3nBp:bd6iv77) ([raw file](https://github.com/starkware-libs/mempool/blob/ec0dae6176b60443a46b30178d71449b309baa78/crates/mempool/src/mempool.rs#L49)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

+1
</blockquote></details>

rust doesn't support `format!("{foo.bar}")`, or similarly `format!("{foo.bar:?}"`.

It only supports `format!("{foo.bar}")`, or similarly `format!("{foo.bar:?}"`.

I can't find it in the diff now, but for a while the access to sender address was through tx.sender_address, which made it impossible to use the former form, but now it is possible to use the latter form since sender_address is unpacked into a variable.
___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0Nwo6V8Lgi3rkHlc6E:b-qlesla) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Since it's a pub (crate) file, it needs to be used. Alternatively, I can add "allow dead code" instead.
WDYT?
</blockquote></details>

Let's add to mempool `iter_queue() -> Impl Iterator` which uses this.

It's a very useful API method to expose, even if we don't use it outside of tests.


<!-- Sent from Reviewable.io -->

2024-06-27 10:16 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0OA3jm2JUrl5GZyUpk:b-66rd3) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Let's add to mempool `iter_queue() -> Impl Iterator` which uses this.

It's a very useful API method to expose, even if we don't use it outside of tests.
</blockquote></details>

What mempool iterator should return? only the txs in priority queue?


<!-- Sent from Reviewable.io -->

2024-06-27 11:07 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0ONA9T1elZy7tXzP-E:b-uxz3u) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

We return a duplicated error if the transaction already exists.
and panic we added for the case that cannot happen (consistency error) that tx appears in one (account) mapping and doesn't appear in the other (store) mapping.
Then, panic is added in the second if condition.
</blockquote></details>

We should return `MempoolError::DuplicateTransaction` when the transaction hash is duplicated; it is not what currently happens.


<!-- Sent from Reviewable.io -->

2024-06-27 11:30 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0ORw-O92C5wATqiTwe:b-5lwfxn) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We should return `MempoolError::DuplicateTransaction` when the transaction hash is duplicated; it is not what currently happens.
</blockquote></details>

Shouldn't we return a duplication error if we have a transaction from the same account and the same nonce?
We don't support fee escalation, so we don't allow adding another tx with the same nonce.


<!-- Sent from Reviewable.io -->

2024-06-27 13:37 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0OtefL49M6GAZ-AN56:b-owq3d) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What mempool iterator should return? only the txs in priority queue?
</blockquote></details>

Yep.
That's what id expect iter_queue() to return, I think.
Do you think it's OK?


<!-- Sent from Reviewable.io -->

2024-06-27 13:45 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0OwPaf66d54Y8V15zX:b-pz6enc) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep.
That's what id expect iter_queue() to return, I think.
Do you think it's OK?
</blockquote></details>

What about the rest of the txs? (that are in store and not in tx_queue yet)


<!-- Sent from Reviewable.io -->

2024-06-30 06:18 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0bmUDJ6S4QNVQw6SOs:b6hc4mw) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

What about the rest of the txs? (that are in store and not in tx_queue yet)
</blockquote></details>

I think in terms of API, that might be less useful to iterate.
I can see why someone would want to iterate the queue, to inspect what's in store, but iterating over ineligible txs I think would not be as useful. 


<!-- Sent from Reviewable.io -->

2024-06-30 06:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0IdAxv3WVTPcDW4eoA:-O0bvBvWB8Jr8H2Y9zV6:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think in terms of API, that might be less useful to iterate.
I can see why someone would want to iterate the queue, to inspect what's in store, but iterating over ineligible txs I think would not be as useful.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-30 06:56 UTC, elintul approved these changes
> Reviewed 5 of 5 files at r15, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0buyeh6T2d0Q_ca8Pd:bf2c5oz) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Shouldn't we return a duplication error if we have a transaction from the same account and the same nonce?
We don't support fee escalation, so we don't allow adding another tx with the same nonce.
</blockquote></details>

This is not exactly the error you're returning; it's not guaranteed that a transaction of same address and nonce will have the same hash. Let's either not implement this part, or add a new error variant. In any case, add a TODO here for fee escalation.


<!-- Sent from Reviewable.io -->

2024-06-30 07:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/transaction_pool.rs` line 32 at r12](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0JE7Br-6WGIZoRbcl5:-O0c0FTZBBE7aVe5ZDpI:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/a0f1d7a31fe76019838beba32bdf5b8955052704/crates/mempool/src/transaction_pool.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is not exactly the error you're returning; it's not guaranteed that a transaction of same address and nonce will have the same hash. Let's either not implement this part, or add a new error variant. In any case, add a TODO here for fee escalation.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-30 12:46 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 51 at r21](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0dAhFd49wgvp_jKEKI:-O0dAhFe5w7lNJ_YrOE9:buu9ima) ([raw file](https://github.com/starkware-libs/mempool/blob/bd27a399903f5d3900b46d071c4aa076d02a1142/crates/mempool/src/transaction_queue.rs#L51)):*
> ```XML
> }
> 
> impl From<Vec<TransactionReference>> for TransactionQueue {
> ```

Implemented in [another](https://reviewable.io/reviews/starkware-libs/mempool/325) PR



_Code quote:_
```XML
impl From<Vec<TransactionReference>> for TransactionQueue
```


<!-- Sent from Reviewable.io -->

2024-06-30 12:49 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_queue.rs` line 51 at r21](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0dAhFd49wgvp_jKEKI:-O0dBIYf3Vx7VPAQWZKY:bkkoxyv) ([raw file](https://github.com/starkware-libs/mempool/blob/bd27a399903f5d3900b46d071c4aa076d02a1142/crates/mempool/src/transaction_queue.rs#L51)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Implemented in [another](https://reviewable.io/reviews/starkware-libs/mempool/325) PR
</blockquote></details>

I mean removed in anther PR :)


<!-- Sent from Reviewable.io -->

2024-06-30 13:23 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195#-:-O0dJ1CV4MxLnYSVigRp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-07-01 04:17 UTC, giladchase approved these changes
> Reviewed 1 of 5 files at r15, 2 of 3 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0Ep72uCVB0y0hbQ90u:-O0gVlS88J9z57Dm0BF5:bg7igkv) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Thanks!
I opened [this](https://reviewable.io/reviews/starkware-libs/mempool/286) PR. it rename `PriorityTransaction` -> `QueuedTransaction`, and `PrioritizedTransaction` -> `QueuedTransaction`. Also changed `QueuedTransaction` to be private.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

___
___
*[`-- commits` line 2 at r23](https://reviewable.io/reviews/starkware-libs/mempool/195#-O0gV4ag9SdZN5FcRxje):*
Note that the new commit message hints that this PR could have been broken down further, into two independent commits.

But let's get this merged as is for now. 



_Suggestion:_
```
feat: change TransactionReference structure and change the return value of pop_last_chunk
```


<!-- Sent from Reviewable.io -->

2024-07-01 04:52 UTC, merged

2024-07-01 05:57 UTC, MohammadNassar1 commented
Reopen the branch