feat: add transaction store data structure
starkware-libs/mempool pull request #200
Opened 2024-06-02 06:59 UTC by MohammadNassar1

2024-06-03 14:15 UTC, ayeletstarkware reviewed
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzTRwhS5mL-lOWAyLYk:-NzTRwhS5mL-lOWAyLYl:b-taacex) (no related file):*
what is the purpose of this data structure? 

___


<!-- Sent from Reviewable.io -->

2024-06-03 15:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzTRwhS5mL-lOWAyLYk:-NzTi_yU7O99x7Zdo6Ho:b-t403zj) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

what is the purpose of this data structure?
</blockquote></details>

To store the transaction in one place because the transaction size is large, we don't want to hold multiple duplications of it.
PriorityQueue, ParkingLot, and StaginArea will hold `TxHash`.

___


<!-- Sent from Reviewable.io -->

2024-06-06 13:51 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzh8oBZBaF6GU3tcjh5:-Nzhn2LT6xsPUOMp19ac:bt5i6wl) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/mempool.rs#L93)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

As both the `add_tx` func and `new` func update `state`, push to `tx_queue`, `tx_store`, I suggest creating `handle_tx` func, or rebasing over #72
</blockquote></details>

I added a TODO, and I'll use your code once it's merged.
___
*[`crates/mempool/src/transaction_store.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzh9cf8BvXr6_g9J5fj:-NzhTgDlDP8oPIMmTp4J:b8y6hs0) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L10)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

is BTree necessary for this MS? Consider changing to a vector
</blockquote></details>

It's not necessary now.
Changed.
___
*[`crates/mempool/src/transaction_store.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzhAfg15pALOj9GVz25:-Nzhcjgb2Wjp2oWCbTqK:b4okjni) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L11)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

it doesn't store txs, so the name is a bit confusing
</blockquote></details>

Changed to `tx_key`.
___
*[`crates/mempool/src/transaction_store.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzh9amaETi0bVUbJB-D:-Nzhd4ibDNnq_Nn7I_oM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L11)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

to
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzh9pjB2jtK6YOB3eiy:-Nzhijkn56BlYPz6dxIC:b-12vbyo) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L11)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider creating a struct
</blockquote></details>

Hmmm, Why do you think so?
It is not used anywhere else.
___
*[`crates/mempool/src/transaction_store.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzhAQAB-DBqpXlGYTjW:-NzhDHcZ9hVf62sTN4ml:b-dna0yr) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L17)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

For example, fee escalation.
___
*[`crates/mempool/src/transaction_store.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzhBdSn7ZqCbblf7XEp:-NzhiU0p5h6x6ScRA97t:bb59ula) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L34)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this better than receiving `tx_hash: TransactionHash` as an input?
same for `get` func
</blockquote></details>

Usually, in `get` and `remove` methods, keys are sent by reference.


<!-- Sent from Reviewable.io -->

2024-06-09 08:24 UTC, ayeletstarkware approved these changes
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzh9pjB2jtK6YOB3eiy:-Nzw3OF1CdlpzdrlobJq:be4igy3) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/transaction_store.rs#L11)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Hmmm, Why do you think so?
It is not used anywhere else.
</blockquote></details>

ok, tx key is nice
___
*[`crates/mempool/src/transaction_store.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzw4eA-7DSAtt3G6RKM:-Nzw4eA-7DSAtt3G6RKN:b-ynvjkv) ([raw file](https://github.com/starkware-libs/mempool/blob/42497f2b824e669925f6c81bd316aedd0d05e65c/crates/mempool/src/transaction_store.rs#L30)):*
> ```XML
>     pub fn remove(&mut self, tx_hash: &TransactionHash) -> Result<ThinTransaction, MempoolError> {
>         if let Some((address, nonce)) = self.tx_hash_to_tx_key.remove(tx_hash) {
>             if let Some(tree_map) = self.store.get_mut(&address) {
> ```

address_queue



_Code quote:_
```XML
tree_map
```


<!-- Sent from Reviewable.io -->

2024-06-10 05:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transaction_store.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/200#-Nzw4eA-7DSAtt3G6RKM:-O--_ya88x3xuK167A2o:bbxhlm8) ([raw file](https://github.com/starkware-libs/mempool/blob/42497f2b824e669925f6c81bd316aedd0d05e65c/crates/mempool/src/transaction_store.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

address_queue
</blockquote></details>

The code was changed.


<!-- Sent from Reviewable.io -->

2024-06-15 11:31 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 3 of 5 files reviewed, 13 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-QeIwFD6hxnGVA3Iwe:-O-QeIwFD6hxnGVA3Iwf:b-amz8dg) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/mempool.rs#L56)):*
> ```XML
> 
>                     // Insert the transaction into the tx_store.
>                     let res = mempool.tx_store.push(input.tx.clone());
> ```

Once the stroe becomes the owner of the transaction, we don't want a clone of it also in the txs_queue.
It should be changed in a separate PR.



_Code quote:_
```XML
                    let res = mempool.tx_store.push(input.tx.clone())
```


<!-- Sent from Reviewable.io -->

2024-06-15 11:33 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-QeIwFD6hxnGVA3Iwe:-O-Qf0jA7qHY8wgghZqS:b-f5yk4f) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/mempool.rs#L56)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Once the stroe becomes the owner of the transaction, we don't want a clone of it also in the txs_queue.
It should be changed in a separate PR.
</blockquote></details>

Ah wait its in https://reviewable.io/reviews/starkware-libs/mempool/195


<!-- Sent from Reviewable.io -->

2024-06-18 09:10 UTC, MohammadNassar1 reviewed
Implementing a transaction store data structure stores all transactions in the Mempool (staged, ready, or queued transactions).
It stores transactions, adds transactions to the DS in `new` and `add_tx`, and removes them in `get_txs`.

In the next PR, the transaction will be removed upon receiving a confirmation that the sent transactions were received by the batcher.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200#-:-O-eGOzY1hkjneYbRA5h:bvwmz7z)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzazeP67eJVQLxfuxRK:-O-e38bv7Cb6pluDbens:b-7j3iea) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/lib.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be private?
</blockquote></details>

It can be `pub(crate)`.
I've added a TODO.
___
*[`crates/mempool/src/mempool.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-QeIwFD6hxnGVA3Iwe:-O-e4pG7DPZ59xyEFoxv:b-rqokc9) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/mempool.rs#L56)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ah wait its in https://reviewable.io/reviews/starkware-libs/mempool/195
</blockquote></details>

You're right; this PR adds the tx store without changing `PrioritizedTransaction`.
___
*[`crates/mempool/src/mempool.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-Ktrz5BXdukS6dnYsz:-O-e7L1sD00-5lncoKcV:b-j7q9ww) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/mempool.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'm having second thoughts about panicking here. It's not a bug/assumption, and can certainly be considered invalid user input.

Maybe we should propagate the error?
</blockquote></details>

Sounds good.
Added a TODO, I'll do it in a separate PR.
___
*[`crates/mempool/src/priority_queue.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-Kmv8y3C6xKLNXAg_I:-O-e7_XiAYGX4rd7NpUF:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/priority_queue.rs#L79)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

FYI switched to VecDequeue [here](https://reviewable.io/reviews/starkware-libs/mempool/240#-)
, no need to change here.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_store.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L4w7DCwD5skykk3Ej:-O-e7nj_DwOu5pXewSu7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a short docstring, it should explicitely note that it supports (:party:) out-of-order txs.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L4UoU4-qiD5fF-XKd:-O-eQ5W_7-dXalciS7pL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add invariants to both fields, in particular, it should detail how they are coupled (removing from one implies removing from the other i think). Add other invariants if you can think of them.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-KpAt79z8A6xEZM2UL:-O-eQY_GCGfLxhbJxzmV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

ya it's longer, but does only one query here (entry is lazy), as opposed to two.
(if-let-else is almost always either outperformed or can be made shorter, by a match of let-else pattern.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 43 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L0_6G5G1ss3Y2Iiyb:-O-eTEKf50cLbX3tAUiB:bs7wumb) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L43)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Shorter, if you use it it might be nicer to add `hash_map::` to the previous match, for consistency.

Also panicking because this is a consistency bug, the user can't be blamed if their tx wasn't in storage.

This should be clarified as invariants in the struct def, see comment.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L8KE48PQWzyYa-YZd:-O-e83a922MzRCYQr1k4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L49)):*
> ```XML
> 
>     pub fn remove(&mut self, tx_hash: &TransactionHash) -> Result<ThinTransaction, MempoolError> {
>         // Remove the transaction from the store
> ```

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L6rPN5DHQ0gopS3Oi:-O-eV8wBEpN9XnWUnS5G:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`ok_or` + ? makes this a oneliner
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-LAS8QD8aICPS0J9hr:-O-eVJoM04BqbvQeoSql:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

assert! is_some
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-LA5qu4oPA_oyxtpGl:-O-eaRaaClJ_SwzOiT7T:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/transaction_store.rs#L67)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

plz switch to match and switch err into panic
</blockquote></details>

Done.
___
*[`crates/mempool_types/src/errors.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L78bSC46UKDRrGMBt:-O-e8BlZ5HNgr_X_QyDG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool_types/src/errors.rs#L8)):*
> ```XML
>     #[error("Duplicate transaction, of hash: {tx_hash}")]
>     DuplicateTransaction { tx_hash: TransactionHash },
>     #[error("Transaction of hash: {tx_hash} is not found")]
> ```

Done.
___
*[`crates/mempool_types/src/errors.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L7v1e66TACkpmsZOL:-O-eagsI2-hDES84uf0V:b-x1oqvz) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool_types/src/errors.rs#L10)):*
<details><summary><i>Previously, giladchase wrote…</i></ [...]

2024-06-18 15:13 UTC, ayeletstarkware reviewed
> Reviewed 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 4 of 5 files reviewed, 12 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 16 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-fslVq8uMWrj-8AXpT:-O-fslVq8uMWrj-8AXpU:bb4d14f) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L16)):*
> ```XML
>     store: HashMap<TransactionHash, ThinTransaction>,
>     // Transactions organized by account address, sorted by ascending nonce values.
>     txs_by_account: HashMap<ContractAddress, BTreeMap<Nonce, PrioritizedTransaction>>,
> ```

Why not use a more straightforward data structure since we assume no gaps now? Perhaps AddressPriorityQueue, so it would be easier to support when gaps are present.
@elintul 



_Code quote:_
```XML
BTreeMap<Nonce, PrioritizedTransaction>
```


<!-- Sent from Reviewable.io -->

2024-06-20 10:45 UTC, elintul reviewed
> Reviewed 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 4 of 5 files reviewed, 16 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzazeP67eJVQLxfuxRK:-O-p-zSrCVeYGU9I04Ts:b-9ya5d9) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/lib.rs#L3)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It can be `pub(crate)`.
I've added a TODO.
</blockquote></details>

Why not now?
___
*[`crates/mempool/src/transaction_store.rs` line 12 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pEM8DBKmWsVIXIQjL:-O-pEM8DBKmWsVIXIQjM:bl5qbyl) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L12)):*
> ```XML
> 
> #[derive(Clone, Debug, Default)]
> pub struct TransactionsStore {
> ```

Since Gilad finds "store" odd and "storage" implies persistency, while "pool" suggests neither order nor persistence.



_Suggestion:_
```XML
TransactionsPool
```
___
*[`crates/mempool/src/transaction_store.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pDnf64inyOQbqYaRY:-O-pDnf64inyOQbqYaRZ:b-yov9fj) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L13)):*
> ```XML
> #[derive(Clone, Debug, Default)]
> pub struct TransactionsStore {
>     // All transactions currently held in the mempool.
> ```

Moved up.
___
*[`crates/mempool/src/transaction_store.rs` line 21 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pC_pc5567LCQcP-d6:-O-pC_pd-kAK75ESp2HK:b-5bjos7) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L21)):*
> ```XML
>     // 2. When a transaction is added to `store`, it must also be added to `txs_by_account`.
>     // 3. When a transaction is removed from `store`, it must also be removed from
>     //    `txs_by_account`.
> ```

Please move up (before struct name) and make public (`///`).



_Suggestion:_
```XML
    /// Contains all transactions currently held in the mempool.
    // Invariant: both data structures are consistent regarding the existence of transactions: 
    // a transaction appears in one if and only if it appears in the other.
```
___
*[`crates/mempool_types/src/errors.rs` line 6 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-p0FraCd1mJVIP7pRh:-O-p0Frb8p3GPGDusXa-:b-cy1sr2) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool_types/src/errors.rs#L6)):*
> ```XML
> #[derive(Clone, Debug, Error)]
> pub enum MempoolError {
>     #[error("Duplicate transaction, of hash: {tx_hash}")]
> ```

For consistency.



_Suggestion:_
```XML
with
```


<!-- Sent from Reviewable.io -->

2024-06-20 11:11 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 4 of 5 files reviewed, 20 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 14 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pGw804q0tKiMlyhUA:-O-pGw804q0tKiMlyhUB:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L14)):*
> ```XML
> pub struct TransactionsStore {
>     // All transactions currently held in the mempool.
>     store: HashMap<TransactionHash, ThinTransaction>,
> ```





_Suggestion:_
```XML
    // Holds the complete transaction objects; it should be the sole entity that does so.
    pool: HashMap<TransactionHash, ThinTransaction>,
```
___
*[`crates/mempool/src/transaction_store.rs` line 21 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pC_pc5567LCQcP-d6:-O-pHMm50H0SGvxEuG3L:b90p0sq) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please move up (before struct name) and make public (`///`).
</blockquote></details>

Another invariant: "No duplicate transactions appear in the pool.".
___
*[`crates/mempool/src/transaction_store.rs` line 25 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pHpra-omQGf1EJRR3:-O-pHpra-omQGf1EJRR4:b-xjwdz4) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L25)):*
> ```XML
> 
> impl TransactionsStore {
>     // Insert transaction into the store, ensuring no duplicates
> ```

No need, the name (of method and arguments) is good enough, and the duplicates issue should be an invariant appearing in the doc. of the whole struct.
___
*[`crates/mempool/src/transaction_store.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pI2b46M-i9lLf-zxo:-O-pI2b46M-i9lLf-zxp:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L26)):*
> ```XML
> impl TransactionsStore {
>     // Insert transaction into the store, ensuring no duplicates
>     pub fn push(&mut self, tx: ThinTransaction) -> Result<(), MempoolError> {
> ```





_Suggestion:_
```XML
MempoolResult<()>
```
___
*[`crates/mempool/src/transaction_store.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pIA4M38ZrJ-5L4F9L:-O-pIA4M38ZrJ-5L4F9M:bnrr0vu) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L33)):*
> ```XML
>             Entry::Vacant(entry) => {
>                 entry.insert(tx.clone());
>             }
> ```

Rearrange the cases so that the positive flow appears first (except an early `return`,  after which the code is less indented).



_Code quote:_
```XML
            Entry::Occupied(_) => {
                return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
            }
            Entry::Vacant(entry) => {
                entry.insert(tx.clone());
            }
```


<!-- Sent from Reviewable.io -->

2024-06-20 11:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/mempool/200#-NzazeP67eJVQLxfuxRK:-O-pLhJBDoDuAABEcne8:b-hl6sob) ([raw file](https://github.com/starkware-libs/mempool/blob/63c6246260b4d14a63397768ec2178057da957be/crates/mempool/src/lib.rs#L3)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not now?
</blockquote></details>

Because in the next PRs I used these methods.
If I add `pub(crate)` I need to add  `#[allow(dead_code)]` and then in the next PRs to remove them.
___
*[`crates/mempool/src/transaction_store.rs` line 12 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pEM8DBKmWsVIXIQjL:-O-pMPsX9f41e_VtKzHq:bfk99ii) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L12)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Since Gilad finds "store" odd and "storage" implies persistency, while "pool" suggests neither order nor persistence.
</blockquote></details>

In Ethereum, the Mempool is referred to as the `TransactionPool`. Do you think it would be confusing to call our tx store `TransactionPool`?


<!-- Sent from Reviewable.io -->

2024-06-20 12:48 UTC, elintul requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 24 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 12 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pEM8DBKmWsVIXIQjL:-O-paqg51aR6j3N3zgO4:b-tfzqfr) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L12)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In Ethereum, the Mempool is referred to as the `TransactionPool`. Do you think it would be confusing to call our tx store `TransactionPool`?
</blockquote></details>

Our code is unrelated to Ethereum's (also both names do not appear in the same code), I think it's okay.
___
*[`crates/mempool/src/transaction_store.rs` line 25 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pd6am1w-YOhz4P72b:-O-pd6anBcV4FlDL-k3B:bv3tk39) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L25)):*
> ```XML
>     // 2. When a transaction is added to `store`, it must also be added to `txs_by_account`.
>     // 3. When a transaction is removed from `store`, it must also be removed from
>     //    `txs_by_account`.
> ```

This can be deleted now, the first invariant above says the same in a succinct way.



_Code quote:_
```XML
    // Invariants:
    // 1. Every transaction in `txs_by_account` must have a corresponding entry in `store`.
    // 2. When a transaction is added to `store`, it must also be added to `txs_by_account`.
    // 3. When a transaction is removed from `store`, it must also be removed from
    //    `txs_by_account`.
```
___
*[`crates/mempool/src/transaction_store.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pdqbN7wssmJN_xZMP:-O-pdqbN7wssmJN_xZMQ:b-h5s2g3) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L30)):*
> ```XML
> impl TransactionsStore {
>     pub fn push(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
>         match self.store.entry(tx.tx_hash) {
> ```

Define a `tx_hash` variable, so be used in the `panic` error message below.



_Code quote:_
```XML
tx.tx_hash
```
___
*[`crates/mempool/src/transaction_store.rs` line 31 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pdaxSEsiYCNVC8ygK:-O-pdaxTE7FHegjbNd0X:b-pu8ls7) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L31)):*
> ```XML
>     pub fn push(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
>         match self.store.entry(tx.tx_hash) {
>             Entry::Vacant(entry) => {
> ```

As Gilad suggested below; in all methods.



_Suggestion:_
```XML
hash_map::Entry
```
___
*[`crates/mempool/src/transaction_store.rs` line 31 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pf4T62cEbFwkC2Q7g:-O-pf4T62cEbFwkC2Q7h:brdr0w5) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L31)):*
> ```XML
>     pub fn push(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
>         match self.store.entry(tx.tx_hash) {
>             Entry::Vacant(entry) => {
> ```

In all locations.



_Suggestion:_
```XML
tx
```
___
*[`crates/mempool/src/transaction_store.rs` line 39 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pdKNa-5wggR257xdL:-O-pdKNa-5wggR257xdM:b-lqtqri) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L39)):*
> ```XML
>         }
> 
>         match self.txs_by_account.entry(tx.sender_address).or_default().entry(tx.nonce) {
> ```

Give this a name, so this line is easier to read: `txs_from_account_entry`; in all locations.



_Code quote:_
```XML
self.txs_by_account.entry(tx.sender_address).or_default()
```
___
*[`crates/mempool/src/transaction_store.rs` line 40 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pewsJ8nVVw13eWYiO:-O-pewsJ8nVVw13eWYiP:brdr0w5) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L40)):*
> ```XML
> 
>         match self.txs_by_account.entry(tx.sender_address).or_default().entry(tx.nonce) {
>             btree_map::Entry::Vacant(entry) => {
> ```

In all locations.



_Suggestion:_
```XML
txs_from_account
```
___
*[`crates/mempool/src/transaction_store.rs` line 44 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pdkoL3OthkEagfA-n:-O-pdkoL3OthkEagfA-o:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L44)):*
> ```XML
>             }
>             btree_map::Entry::Occupied(_) => {
>                 panic!("Consistency error: {tx:?} wasn't in storage but is in account storage")
> ```





_Suggestion:_
```XML
Transaction pool consistency error: transaction with hash {tx_hash} does not appear in main mapping, but it appears in the account mapping
```
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peLFPBoDs2Y5_69Wm:-O-peLFPBoDs2Y5_69Wn:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
> ```XML
>     }
> 
>     pub fn remove(&mut self, tx_hash: &TransactionHash) -> Result<ThinTransaction, MempoolError> {
> ```





_Suggestion:_
```XML
MempoolResult<ThinTransaction>
```
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O-peRBv3Z8_Dl_S5S7m:b-fawvmp) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
> ```XML
>     }
> 
>     pub fn remove(&mut self, tx_hash: &TransactionHash) -> Result<ThinTransaction, MempoolError> {
> ```

Why not by value? It's `Copy`able.
In all methods.



_Code quote:_
```XML
tx_hash: &TransactionHash
```
___
*[`crates/mempool/src/transaction_store.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pfSEo7oCMU02fUrIj:-O-pfSEp56yisR6SQthO:bbmmb69) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L67)):*
> ```XML
>             Entry::Vacant(_) => panic!(
>                 "Invariant violated: Trying to remove a transaction that does not exist in \
>                  txs_by_account."
> ```

Let's keep error messages consistent between `panic`s.
Also, refrain from using variable names (which might change) in error messages (also doc., comments); they might become outdated and thus confusing for future readers.



_Suggestion:_
```XML
                "Transaction pool consistency error: transaction with hash {tx_hash} appears in main mapping, but does not appear in the account mapping"
```
___
*[`crates/mempool/src/transaction_store.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pfzER9lHEW53U8gpm:-O-pfzER9lHEW53U8gpn:b-i3vukr) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L73)):*
> ```XML
>     }
> 
>     pub fn get(&self, tx_hash: &TransactionHash) -> Result<&ThinTransaction, MempoolError> {
> ```

How come it's possible to `return` a reference without using lifetimes?



_Suggestion:_
```XML
MempoolResult<&ThinTransaction>
` [...]

2024-06-20 12:50 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 24 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 16 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-fslVq8uMWrj-8AXpT:-O-pgUa6-SzwdjVJojl1:b-56seix) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L16)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why not use a more straightforward data structure since we assume no gaps now? Perhaps AddressPriorityQueue, so it would be easier to support when gaps are present.
@elintul
</blockquote></details>

Since we know we're going to use `BTreeMap`. I think it's okay here, and if it becomes complex, we'll change it.


<!-- Sent from Reviewable.io -->

2024-06-20 12:53 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 24 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool_types/src/errors.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L78bSC46UKDRrGMBt:-O-phLZt1JgRiipqmVKL:b3niqom) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool_types/src/errors.rs#L8)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think it's nice that it's formatted into the error message.


<!-- Sent from Reviewable.io -->

2024-06-20 12:54 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 24 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transaction_store.rs` line 12 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pEM8DBKmWsVIXIQjL:-O-phVXE36cvQ6OtSHkT:b-sjm744) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L12)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Our code is unrelated to Ethereum's (also both names do not appear in the same code), I think it's okay.
</blockquote></details>

Let's also rename the file.


<!-- Sent from Reviewable.io -->

2024-06-20 14:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 6 files reviewed, 14 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-phaalEyCvKCCPkJgm:-O-pscstA2njDynj9rFC:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/mempool.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's move these changes to another PR; the new file alone is quite big.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_store.rs` line 12 at r8](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pEM8DBKmWsVIXIQjL:-O-ptWVqBFoB-uxlHzDG:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/989dfe9e3e3f0d45e1749208f5f6ce86885a027d/crates/mempool/src/transaction_store.rs#L12)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's also rename the file.
</blockquote></details>

Done
___
*[`crates/mempool/src/transaction_store.rs` line 31 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pf4T62cEbFwkC2Q7g:-O-pqHtk-pZYfQYPS2Dd:bu6hsv3) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

In all locations.
</blockquote></details>

maybe `txs`? since it's an map of txs.
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O-prCFIB3_hdJ-74Zhc:blw7vcs) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not by value? It's `Copy`able.
In all methods.
</blockquote></details>

Usually, get and remove receive by ref.
___
*[`crates/mempool/src/transaction_store.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pfzER9lHEW53U8gpm:-O-prLxa1CEB2MEjNyVx:bbvb5nu) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come it's possible to `return` a reference without using lifetimes?
</blockquote></details>

Done.

I think it's working because the parameter `&self` gets its own lifetime. Then the return type `&ThinTransaction` will be inferred to have the same lifetime as `&self`.


<!-- Sent from Reviewable.io -->

2024-06-20 14:12 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 2 of 6 files reviewed, 14 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-phaalEyCvKCCPkJgm:-O-pzXHZ2AWSVMkI5Wjg:b-qqsqwi) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/mempool.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done
</blockquote></details>

New [PR](https://reviewable.io/reviews/starkware-libs/mempool/264)


<!-- Sent from Reviewable.io -->

2024-06-20 14:19 UTC, elintul requested changes
> Reviewed 3 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 5 of 6 files reviewed, 16 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/transactions_pool.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pzu3xANBQiDBymIE9:-O-pzu3yD70jBnBklCYn:bevg7gg) ([raw file](https://github.com/starkware-libs/mempool/blob/5c59cb693e32d7d128546f0aadf660ca0fe2ad50/crates/mempool/src/transactions_pool.rs#L17)):*
> ```XML
> pub struct TransactionsPool {
>     // Holds the complete transaction objects; it should be the sole entity that does so.
>     pool: HashMap<TransactionHash, ThinTransaction>,
> ```

Let's rename: `pool -> tx_pool`, for consistency with the other member. 
___
*[`crates/mempool/src/transactions_pool.rs` line 27 at r10](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-q-BRqElZT2R-546-o:-O-q-BRqElZT2R-546-p:b7kk4zh) ([raw file](https://github.com/starkware-libs/mempool/blob/5c59cb693e32d7d128546f0aadf660ca0fe2ad50/crates/mempool/src/transactions_pool.rs#L27)):*
> ```XML
>         match self.pool.entry(tx_hash) {
>             hash_map::Entry::Vacant(txs) => {
>                 txs.insert(tx.clone());
> ```

Why is cloning needed here? 
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O-q-wKr0BdHGkKTkpxe:b-cwx5y7) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Usually, get and remove receive by ref.
</blockquote></details>

Is this the way it is in builtin Rust data structures? 


<!-- Sent from Reviewable.io -->

2024-06-20 14:36 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: 5 of 6 files reviewed, 15 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/transactions_pool.rs` line 27 at r10](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-q-BRqElZT2R-546-o:-O-q2JegEFTnkWTALhr-:b2go2gx) ([raw file](https://github.com/starkware-libs/mempool/blob/5c59cb693e32d7d128546f0aadf660ca0fe2ad50/crates/mempool/src/transactions_pool.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is cloning needed here?
</blockquote></details>

Since `tx` is used later (when updating the `txs_by_account`).
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O-q3WPwEJ_KyxSoG3Vp:b-mnphkl) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the way it is in builtin Rust data structures?
</blockquote></details>

Actually I noticed that this is the signature for the DSs.
See [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove) for example.


<!-- Sent from Reviewable.io -->

2024-06-23 10:52 UTC, giladchase requested changes
> Reviewed 2 of 3 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 61 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-Ktrz5BXdukS6dnYsz:-O03cbhz-dX5umEJtEhi:b-jsm4rs) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool/src/mempool.rs#L61)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sounds good.
Added a TODO, I'll do it in a separate PR.
</blockquote></details>

Added in Ayelet's[ PR](https://reviewable.io/reviews/starkware-libs/mempool/72)
___
*[`crates/mempool/src/mempool.rs` line 25 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03cqG94Ab4Hya9FH7z:-O03cqGAB1NuSINrtL-Q:b9bcxfv) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/mempool.rs#L25)):*
> ```XML
> 
> impl Mempool {
>     // TODO(Mohammad): return `Result`, to consider invalid input.
> ```

you can remove this, since it is handled already in parallel PR



_Code quote:_
```XML
   // TODO(Mohammad): return `Result`, to consider invalid input.
```
___
*[`crates/mempool/src/transactions_pool.rs` line 22 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03dQ8x5349214BsgDi:-O03dQ8x5349214BsgDj:b-sgdkv) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L22)):*
> ```XML
> }
> 
> impl TransactionsPool {
> ```

Also file name, grammar thing i think



_Suggestion:_
```XML
TransactionPool
```
___
*[`crates/mempool/src/transactions_pool.rs` line 78 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03fSS9AUs5aVEC6QO5:-O03fSS9AUs5aVEC6QO6:b59s443) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L78)):*
> ```XML
>             None => Err(MempoolError::TransactionNotFound { tx_hash: *tx_hash }),
>         }
>     }
> ```

If args are `Copy` then pass by value, it should be considered a "free" copy



_Suggestion:_
```XML
    pub fn get(&self, tx_hash: TransactionHash) -> MempoolResult<&ThinTransaction> {
        self.tx_pool.get(&tx_hash).ok_or(MempoolError::TransactionNotFound { tx_hash })
    }
```
___
*[`crates/mempool_types/src/errors.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L78bSC46UKDRrGMBt:-O03fgpS3lK761YqrXRV:bz3ocq9) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool_types/src/errors.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it's nice that it's formatted into the error message.
</blockquote></details>

Sababa
___
*[`crates/mempool_types/src/errors.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-L7v1e66TACkpmsZOL:-O03fjmt42zoWNcCj0O4:b-7ekt3d) ([raw file](https://github.com/starkware-libs/mempool/blob/0f7462aa89f703feb017020bf3a97ebec8da3de5/crates/mempool_types/src/errors.rs#L10)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I get it.
</blockquote></details>

NVM elin didnt like :grimacing: 
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O03h1kt1Rq-kkeMe8kc:bdde27z) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually I noticed that this is the signature for the DSs.
See [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove) for example.
</blockquote></details>

Yes but note that Hashmap has no `Copy` bound on the Key, so it has ask for a reference instead.

So this is a subtle issue...

On one hand ppl expect get/remove from DSs to get args by ref.
But on the other hand, anyone well versed with SNAPI will know that TransactionHash is `Copy`, so it's  bit fishy to explicitly request to it :thinking:  I'd have been confused if I ran into it in the wild, and wouldn't have guesses that it is to conform to canonical get/remove.

I think going with `Copy` is better here, since IMO &TransactionHash seems more suspicious to me than remove(<non-ref-arg>).
But it can really go both ways.
___
*[`crates/mempool/src/transaction_store.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pfzER9lHEW53U8gpm:-O03g8DaA_oRicRiVUy2:b-19j5ag) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L73)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.

I think it's working because the parameter `&self` gets its own lifetime. Then the return type `&ThinTransaction` will be inferred to have the same lifetime as `&self`.
</blockquote></details>

Yep, rust only needs explicit lifetimes when it can infer lifetimes on its own, which usually happens when more than one lifetime is in play, in which case rust might need help knowing the relations between the two (which is longer / which is returned from the function if a reference is returned)


<!-- Sent from Reviewable.io -->

2024-06-23 10:57 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200#-:-O03jckb8qVIr76FORJO:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-23 11:23 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/mempool/src/transactions_pool.rs` line 27 at r10](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-q-BRqElZT2R-546-o:-O03BlSh9vIbckWnQL6G:b-7nsiqj) ([raw file](https://github.com/starkware-libs/mempool/blob/5c59cb693e32d7d128546f0aadf660ca0fe2ad50/crates/mempool/src/transactions_pool.rs#L27)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Since `tx` is used later (when updating the `txs_by_account`).
</blockquote></details>

Then I believe we should first make the queue not use the full transaction, so we won't clone here. Why are those PRs dependent of each other?
If we eventually decide to merge this PR first, please add a TODO to remove this clone, to let other readers (particularly, the reviewer) know it's temporary.
___
*[`crates/mempool/src/transactions_pool.rs` line 22 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03dQ8x5349214BsgDi:-O03opPE2n2PvjJnG3H9:bd89fxl) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also file name, grammar thing i think
</blockquote></details>

Yeah, the word "pool" already embeds the plural property.
___
*[`crates/mempool/src/transactions_pool.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03D0v9-Yf0wq0YjOmN:-O03D0v9-Yf0wq0YjOmO:b-y7mruv) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L32)):*
> ```XML
>                 return Err(MempoolError::DuplicateTransaction { tx_hash });
>             }
>         }
> ```

No need for the explicit `Occupied(_)` case using `if let`; also, it _is_ "entry" after all, my bad.



_Suggestion:_
```XML
        let tx_hash = tx.tx_hash;
        
        // Insert transaction to pool, if it is new.       
        if let hash_map::Entry::Vacant(entry) = self.tx_pool.entry(tx_hash) {
            entry.insert(tx.clone());
        } else {
            return Err(MempoolError::DuplicateTransaction { tx_hash });
        }
```
___
*[`crates/mempool/src/transactions_pool.rs` line 62 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O032zrmEOiQCDuLCJdK:-O032zrmEOiQCDuLCJdL:b-fz1qwp) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L62)):*
> ```XML
>                     txs_from_account.remove(&tx.nonce).is_some(),
>                     "Transaction pool consistency error: transaction with hash {tx_hash} appears \
>                      in main mapping, but does not appear in the account mapping"
> ```

Consider defining the error message once and formatting into it both locations (can be in another PR).



_Code quote:_
```XML
                    "Transaction pool consistency error: transaction with hash {tx_hash} appears \
                     in main mapping, but does not appear in the account mapping"
```
___
*[`crates/mempool/src/transaction_store.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-peRBv3Z8_Dl_S5S7l:-O033Hfz4XWPmTPYZsTW:b-u0xkgp) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L50)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually I noticed that this is the signature for the DSs.
See [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove) for example.
</blockquote></details>

I see, I think consistency with conventions is important. @giladchase - WDYT?


<!-- Sent from Reviewable.io -->

2024-06-23 14:27 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/transactions_pool.rs` line 27 at r10](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-q-BRqElZT2R-546-o:-O04TvMl6_74SAWJQ4AD:b-aasir8) ([raw file](https://github.com/starkware-libs/mempool/blob/5c59cb693e32d7d128546f0aadf660ca0fe2ad50/crates/mempool/src/transactions_pool.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then I believe we should first make the queue not use the full transaction, so we won't clone here. Why are those PRs dependent of each other?
If we eventually decide to merge this PR first, please add a TODO to remove this clone, to let other readers (particularly, the reviewer) know it's temporary.
</blockquote></details>

We need to implement the tx storage before changing the priorityTransaction to be able to send ThinTransaction in `get_txs` method.
I've added a TODO.
___
*[`crates/mempool/src/transactions_pool.rs` line 22 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03dQ8x5349214BsgDi:-O04Q7JX3KBZF0fH5PH1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L22)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yeah, the word "pool" already embeds the plural property.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transactions_pool.rs` line 78 at r11](https://reviewable.io/reviews/starkware-libs/mempool/200#-O03fSS9AUs5aVEC6QO5:-O04PGhk31dt8NHpIhd8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/59d98a74b38c81841998653103b744dc0d34bd34/crates/mempool/src/transactions_pool.rs#L78)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If args are `Copy` then pass by value, it should be considered a "free" copy
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_store.rs` line 73 at r9](https://reviewable.io/reviews/starkware-libs/mempool/200#-O-pfzER9lHEW53U8gpm:-O04Q0pq1TQf3Hb1Cyt7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/65a56ee3eba481a10e95bfc6ed6b56246650aeb7/crates/mempool/src/transaction_store.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, rust only needs explicit lifetimes when it can infer lifetimes on its own, which usually happens when more than one lifetime is in play, in which case rust might need help knowing the relations between the two (which is longer / which is returned from the function if a reference is returned)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-24 11:54 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200#-:-O095DYt6GpTuTeVBOuO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/transaction_pool.rs` line 26 at r12](https://reviewable.io/reviews/starkware-libs/mempool/200#-O08zXkj6xTsxz_Cy9cW:-O08zXkkAXonQO-F059h:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/72846c709bbcea537f63ab661767046eafae04e7/crates/mempool/src/transaction_pool.rs#L26)):*
> ```XML
>     pub fn push(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
>         let tx_hash = tx.tx_hash;
>         // Insert transaction to pool, if it is new.
> ```





_Suggestion:_
```XML
        let tx_hash = tx.tx_hash;
        
        // Insert transaction to pool, if it is new.
```


<!-- Sent from Reviewable.io -->

2024-06-24 11:54 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-24 11:55 UTC, merged