feat: add address priority queue
starkware-libs/mempool pull request #210
Opened 2024-06-04 11:34 UTC by ayeletstarkware

add address priority queue. Will be used in Mempool, multiple txs per account

2024-06-05 10:00 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzYHags4PUhO8v6P6Ql:-NzbpotLDCLCAQJ_patZ:b-896fix) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let's discuss F2F if we need this PR.
Maybe the TransactionStore PR can replace this one.
</blockquote></details>

Done.

___
___
*[`crates/mempool/src/priority_queue.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzYEFuJ6MJ4J7trZ6iu:-NzbLoGN0F0Qibv1mAsV:b9xvtei) ([raw file](https://github.com/starkware-libs/mempool/blob/3660514724ccd592c656905438e13d42aa7bf48c/crates/mempool/src/priority_queue.rs#L65)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why not use `MempoolError`?
</blockquote></details>

removed for now
___
*[`crates/mempool/src/priority_queue.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzYH-Kk6qNgjMgn-jAV:-NzbMUkn3yGlntfz1xw8:b9xvtei) ([raw file](https://github.com/starkware-libs/mempool/blob/3660514724ccd592c656905438e13d42aa7bf48c/crates/mempool/src/priority_queue.rs#L96)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you need the for loop to catch the tx with the same nonce?
We assume there are no holes so that you can calculate the tx location in o(1).
</blockquote></details>

removed for now
___
*[`crates/mempool/src/priority_queue.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzYGii13I5AUmuNDZ_M:-NzbpmsW55ACs4vwpzTX:b9xvtei) ([raw file](https://github.com/starkware-libs/mempool/blob/3660514724ccd592c656905438e13d42aa7bf48c/crates/mempool/src/priority_queue.rs#L103)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I don't think we need to support transaction overriding at this MS
</blockquote></details>

removed for now


<!-- Sent from Reviewable.io -->

2024-06-06 06:43 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/priority_queue.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGpU6C1f5n6C7Jrte:-NzgGpU6C1f5n6C7Jrtf:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L76)):*
> ```XML
>     pub fn top(&self) -> Option<ThinTransaction> {
>         self.0.first().cloned()
>     }
> ```





_Suggestion:_
```XML
    pub fn top(&self) -> Option<&ThinTransaction> {
        self.0.first()
    }
```
___
*[`crates/mempool/src/priority_queue.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGb2KEOx1GRBGxskT:-NzgGb2KEOx1GRBGxskU:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L79)):*
> ```XML
> 
>     pub fn pop(&mut self) -> Option<ThinTransaction> {
>         Some(self.0.remove(0))
> ```





_Suggestion:_
```XML
 self.0.pop()
```


<!-- Sent from Reviewable.io -->

2024-06-06 06:58 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGpU6C1f5n6C7Jrte:-NzgJvXKDM-IztYuJx2D:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L76)):*
> ```XML
>     pub fn top(&self) -> Option<ThinTransaction> {
>         self.0.first().cloned()
>     }
> ```

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGb2KEOx1GRBGxskT:-NzgJvn1-1LouiDpfB_Y:b-b6qnio) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L79)):*
> ```XML
> 
>     pub fn pop(&mut self) -> Option<ThinTransaction> {
>         Some(self.0.remove(0))
> ```

pop Removes the last element from a vector and returns it, or [`None`]


<!-- Sent from Reviewable.io -->

2024-06-06 07:21 UTC, MohammadNassar1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/priority_queue.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGb2KEOx1GRBGxskT:-NzgPioXAGUlATpUd42f:b-5tkah3) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L79)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

pop Removes the last element from a vector and returns it, or [`None`]
</blockquote></details>

Got it!
Please rename to `pop_front`
___
*[`crates/mempool/src/priority_queue.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgPp4u-1bcClfqzsSV:-NzgPp4v8r37fxg8kz_a:bqaxl6v) ([raw file](https://github.com/starkware-libs/mempool/blob/43f428f01285a5d60eddd92bc1ed89a477fe474b/crates/mempool/src/priority_queue.rs#L78)):*
> ```XML
>     }
> 
>     pub fn pop(&mut self) -> Option<ThinTransaction> {
> ```

When it returns `None`?
Maybe you need to check first if it's empty.



_Code quote:_
```XML
Option<
```


<!-- Sent from Reviewable.io -->

2024-06-06 07:47 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/mempool/210#-NzgGb2KEOx1GRBGxskT:-NzgV9_O0RW832-r8kff:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/6a23b8c0ac2aa090843f5406945cea3f674ed686/crates/mempool/src/priority_queue.rs#L79)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Got it!
Please rename to `pop_front`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 07:47 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 07:48 UTC, merged