feat: add declare specific size related stateless tx validator
starkware-libs/mempool pull request #225
Opened 2024-06-06 11:05 UTC by ArniStarkware

2024-06-06 11:05 UTC, ArniStarkware commented
* **#226** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/226?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#225** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/225?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-06 11:08 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-NzhE0XdEX1pykXqxEpW:brtphkf) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
> ```XML
>         let bytecode_size = contract_class.sierra_program.len();
>         let serialized_class = serde_json::to_string(&contract_class)
>             .expect("Unexpected error serializing contract class.");
> ```

I use expect here as I do not understand how the serialization may fail.

Should I use some safer mechanism?



_Code quote:_
```XML
        let serialized_class = serde_json::to_string(&contract_class)
            .expect("Unexpected error serializing contract class.");
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhDTWI7Pw8vxEFdGfm:-NzhDTWI7Pw8vxEFdGfn:b8k3kat) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L141)):*
> ```XML
>     raw_class_size: usize,
>     max_raw_class_size: usize,
> ) -> Result<(), DeclareTransactionError> {
> ```

We expect to use this function for validations after the compilation as well. We will move it when time comes.



_Code quote:_
```XML
fn validate_class_size(
    bytecode_language: String,
    bytecode_size: usize,
    max_bytecode_size: usize,
    raw_class_size: usize,
    max_raw_class_size: usize,
) -> Result<(), DeclareTransactionError> {
```


<!-- Sent from Reviewable.io -->

2024-06-10 05:58 UTC, Yael-Starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O--diu_3oSOmQ-0FVoz:b-rrszlo) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I use expect here as I do not understand how the serialization may fail.

Should I use some safer mechanism?
</blockquote></details>

Not sure what can be a failure reason, one thing I found online is a limit on recursion depth. Not sure if this is relevant for this case but I would prefer the safe error handling here.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhDTWI7Pw8vxEFdGfm:-O--i8iFDNruaOwvDiXI:b69cnpb) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L141)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We expect to use this function for validations after the compilation as well. We will move it when time comes.
</blockquote></details>

why check the same thing twice?
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--gAFH1rTFS0_G-Qj4:-O--gAFH1rTFS0_G-Qj5:b-ghjx5k) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L28)):*
> ```XML
>         max_signature_length: 1,
>         max_bytecode_size: 3,
>         max_raw_class_size: 408,
> ```

does these numbers have a meaning or are they random?
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--hFHy08OhaoavpCzX:-O--hFHy08OhaoavpCzY:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L174)):*
> ```XML
>     };
>     let mut sierra_program = vec![stark_felt!(1_u128), stark_felt!(3_u128), stark_felt!(0_u128)];
>     sierra_program.extend(vec![stark_felt!(12_u128); config_max_bytecode_size]);
> ```





_Suggestion:_
```XML
    let sierra_program = vec![stark_felt!(1_u128); onfig_max_bytecode_size+3];
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--hc6Z5yv3eD5pW-HQ:-O--hc6Z5yv3eD5pW-HR:b9rs4fo) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L191)):*
> ```XML
>             assert_eq!(bytecode_size, sierra_program_length);
>             assert_eq!(max_bytecode_size, config_max_bytecode_size);
>         }
> ```

nice! I wasn't aware of this syntax



_Code quote:_
```XML
        ) => {
            assert_eq!(bytecode_language, "Sierra");
            assert_eq!(bytecode_size, sierra_program_length);
            assert_eq!(max_bytecode_size, config_max_bytecode_size);
        }
```


<!-- Sent from Reviewable.io -->

2024-06-10 07:44 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O-03oR8-PIewgYfWW44:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Not sure what can be a failure reason, one thing I found online is a limit on recursion depth. Not sure if this is relevant for this case but I would prefer the safe error handling here.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhDTWI7Pw8vxEFdGfm:-O--yhCU0SlDW3voMMDM:beezs2e) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L141)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why check the same thing twice?
</blockquote></details>

On the other case - it will validate the `Casm` class size. In this PR this function is used to validate the `Sierra` class size.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--gAFH1rTFS0_G-Qj4:-O-04LSI-fJcQO_Gd8ky:bu4exku) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L28)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

does these numbers have a meaning or are they random?
</blockquote></details>

These are the minimal numbers for irrelevant cases to pass.
Fixed.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 174 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--hFHy08OhaoavpCzX:-O-05LrFAJIlyQG2TeI6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L174)):*
> ```XML
>     };
>     let mut sierra_program = vec![stark_felt!(1_u128), stark_felt!(3_u128), stark_felt!(0_u128)];
>     sierra_program.extend(vec![stark_felt!(12_u128); config_max_bytecode_size]);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 10:13 UTC, Yael-Starkware requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O-0b88yEILP8YJLnItp:b-amdvpe) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

would be prettier to use "?" instead of map_err.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--gAFH1rTFS0_G-Qj4:-O-0cEzP4iBxVOZYrzqP:be5b48d) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L28)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

These are the minimal numbers for irrelevant cases to pass.
Fixed.
</blockquote></details>

not sure I understand, these number are not test specific?
I'm asking because in test_declare_contract_class_size_too_long you have 3 felts in the sierra program , which equals the default max_bytecode_size that you defined here.
If these are test specific I think they shouldn't be in the default setting, but if they are general to any test then it's fine. 


<!-- Sent from Reviewable.io -->

2024-06-10 13:51 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-1HHF45uYONk43GEHR:-O-1HHF45uYONk43GEHS:b-ca45bi) ([raw file](https://github.com/starkware-libs/mempool/blob/c6f83ae342b9790d0d71b8993e3beddbac713815/crates/gateway/src/errors.rs#L57)):*
> ```XML
> #[derive(Debug, Error)]
> #[cfg_attr(test, derive(PartialEq))]
> pub enum DeclareTransactionError {
> ```

@dafnamatsry WDYT?



_Suggestion:_
```XML
StatelessDeclareTransactionValidatorError
```
___
*[`crates/gateway/src/starknet_api_test_utils.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-1Pd633naWe-Aqe9Vi:-O-1Pd633naWe-Aqe9Vj:blyrk91) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/starknet_api_test_utils.rs#L55)):*
> ```XML
>             };
>             external_declare_tx(declare_tx_args!(resource_bounds, signature, contract_class))
>         }
> ```

Used in the positive flow test.



_Code quote:_
```XML
        TransactionType::Declare => {
            let contract_class = ContractClass {
                sierra_program: vec![stark_felt!(1_u32); 3],
                ..ContractClass::default()
            };
            external_declare_tx(declare_tx_args!(resource_bounds, signature, contract_class))
        }
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O-1HZ7uCfUdunRIolgZ:bnkgzja) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

would be prettier to use "?" instead of map_err.
</blockquote></details>

This means I need to have a transparent error.
I don't want StatelessTransactionValidatorError to expose the inner serde json error.

Besides - `serde_json::Error` does not implement `PartialEq`.


But of you insist once more - I will make it happen.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-O--gAFH1rTFS0_G-Qj4:-O-1I5Bd2N21rX_9uC43:b-9t7tgv) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator_test.rs#L28)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand, these number are not test specific?
I'm asking because in test_declare_contract_class_size_too_long you have 3 felts in the sierra program , which equals the default max_bytecode_size that you defined here.
If these are test specific I think they shouldn't be in the default setting, but if they are general to any test then it's fine.
</blockquote></details>

Replaced with non-test-specific values - but with a healthy margin.

Tests unrelated to these values should not fail on these values.


<!-- Sent from Reviewable.io -->

2024-06-13 07:39 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-06-13 08:33 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: all files reviewed, 14 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/config.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-F_TBZCu0T3H7D4Gaf:-O-F_TBZCu0T3H7D4Gag:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/config.rs#L75)):*
> ```XML
>     pub max_bytecode_size: usize,
>     pub max_raw_class_size: usize,
> }
> ```





_Suggestion:_
```XML
pub struct StatelessTransactionValidatorConfig {
    // If true, validates that the resource bounds are not zero.
    pub validate_non_zero_l1_gas_fee: bool,
    pub validate_non_zero_l2_gas_fee: bool,

    pub max_calldata_length: usize,
    pub max_signature_length: usize,
    
    // Declare txs specific config.
    pub max_bytecode_size: usize,
    pub max_raw_class_size: usize,
}
```
___
*[`crates/gateway/src/errors.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-1HHF45uYONk43GEHR:-O-FMsGc2IljqyOncaaW:b-btvmvl) ([raw file](https://github.com/starkware-libs/mempool/blob/c6f83ae342b9790d0d71b8993e3beddbac713815/crates/gateway/src/errors.rs#L57)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@dafnamatsry WDYT?
</blockquote></details>

I don't think we need a specific type of Declare txs error. It can be under the `StatelessTransactionValidatorError`.
It complicates the code, and it is also confusing because it doesn't really include all the possible error (declare txs can also have errors that are general to all tx types).
___
*[`crates/gateway/src/errors.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPBxE0VziBy4ZxG_S:-O-FPBxF0UM3iAqT975S:bqm260z) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/errors.rs#L62)):*
> ```XML
>         "Declared contract class {bytecode_language} bytecode size is {bytecode_size}. It must be \
>          less then {max_bytecode_size}."
>     )]
> ```

Please use the same string that we have now in the pythonic GW.



_Code quote:_
```XML
    #[error(
        "Declared contract class {bytecode_language} bytecode size is {bytecode_size}. It must be \
         less then {max_bytecode_size}."
    )]
```
___
*[`crates/gateway/src/errors.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPLCh71ts6B0AlAAV:-O-FPLCh71ts6B0AlAAW:b-816h6l) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/errors.rs#L71)):*
> ```XML
>         "Declared contract class {bytecode_language} size is {contract_class_object_size}. It \
>          must be less then {max_contract_class_object_size}."
>     )]
> ```

Same.



_Code quote:_
```XML
    #[error(
        "Declared contract class {bytecode_language} size is {contract_class_object_size}. It \
         must be less then {max_contract_class_object_size}."
    )]
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O-FVCmoCkGMM9csXle-:b-vos2kk) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This means I need to have a transparent error.
I don't want StatelessTransactionValidatorError to expose the inner serde json error.

Besides - `serde_json::Error` does not implement `PartialEq`.


But of you insist once more - I will make it happen.
</blockquote></details>

I actually think that expect is more suitable here, since it is a bug of ours if it fails here.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhDTWI7Pw8vxEFdGfm:-O-FWtte-VEDeYrg4zom:b-9z3k37) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L141)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

On the other case - it will validate the `Casm` class size. In this PR this function is used to validate the `Sierra` class size.
</blockquote></details>

In the `Casm` class validation we also have bytecode and raw sizes?
In any case, I would prefer to have a dedicated `validate_casm_contract_class` as it may have additional specific validations to Casm.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPtaQ3rH4JwDvdQCd:-O-FPtaQ3rH4JwDvdQCe:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L30)):*
> ```XML
>         self.validate_tx_size(tx)?;
> 
>         if let ExternalTransaction::Declare(ExternalDeclareTransaction::V3(declare_tx)) = tx {
> ```





_Suggestion:_
```XML
if let ExternalTransaction::Declare(declare_tx)
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPlTQAx1wWuVS25Bw:-O-FPlTQAx1wWuVS25Bx:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L107)):*
> ```XML
>     fn validate_declare_tx(
>         &self,
>         tx: &ExternalDeclareTransactionV3,
> ```





_Suggestion:_
```XML
ExternalDeclareTransaction
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FQ3xx98ZSSbzj3BZo:-O-FQ3xx98ZSSbzj3BZp:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L111)):*
> ```XML
>         self.validate_class_length(&tx.contract_class)?;
> 
>         Ok(())
> ```





_Suggestion:_
```XML
        self.validate_class_length(&tx.contract_class)
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FWMve8UxFQsL5PMUG:-O-FWMve8UxFQsL5PMUH:b-2wt1x9) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L132)):*
> ```XML
>             raw_class_size,
>             self.config.max_raw_class_size,
>         )?)
> ```

Please move the checks here and delete `validate_class_size`.



_Code quote:_
```XML
        Ok(validate_class_size(
            "Sierra".to_string(),
            bytecode_size,
            self.config.max_bytecode_size,
            raw_class_size,
            self.config.max_raw_class_size,
        )?)
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FgB3CA9Nt7BW15YHb:-O-FgB3CA9Nt7BW15YHc:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator_test.rs#L25)):*
> ```XML
>         validate_non_zero_l2_gas_fee: true,
> 
>         max_calldata_length: 1,
> ```





_Suggestion:_
```XML
        validate_non_zero_l2_gas_fee: true,
        max_calldata_length: 1,
```
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FgGo94yExhi1XU-bu:-O-FgGo94yExhi1XU-bv:b-gsndgw) ([raw file](https://github.com/st [...]

2024-06-13 08:44 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 4 of 5 files reviewed, 15 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/gateway/src/errors.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FlJewCWIypADbh-bU:-O-FlJexCUbd6pwv8GQW:b-867xyf) ([raw file](https://github.com/starkware-libs/mempool/blob/f44a21c6720d6c61a286c0dce00372cd0849e54e/crates/gateway/src/errors.rs#L51)):*
> ```XML
>     #[error(transparent)]
>     DeclareTransactionError(#[from] DeclareTransactionError),
>     // TODO(Arni): Cosider a transparant error for serde_json::Error.
> ```

Please remove.



_Code quote:_
```XML
// TODO(Arni): Cosider a transparant error for serde_json::Error.
```


<!-- Sent from Reviewable.io -->

2024-06-13 11:39 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/config.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-F_TBZCu0T3H7D4Gaf:-O-G4QQv2gSesU1jwHza:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/config.rs#L75)):*
> ```XML
>     pub max_bytecode_size: usize,
>     pub max_raw_class_size: usize,
> }
> ```

Done.
___
*[`crates/gateway/src/errors.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-1HHF45uYONk43GEHR:-O-G4vOu12mXCNERCggb:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/c6f83ae342b9790d0d71b8993e3beddbac713815/crates/gateway/src/errors.rs#L57)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I don't think we need a specific type of Declare txs error. It can be under the `StatelessTransactionValidatorError`.
It complicates the code, and it is also confusing because it doesn't really include all the possible error (declare txs can also have errors that are general to all tx types).
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPBxE0VziBy4ZxG_S:-O-G7KayB1ZI64xgkCWy:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/errors.rs#L62)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please use the same string that we have now in the pythonic GW.
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPLCh71ts6B0AlAAV:-O-G7L9FAGa6oZn24aTj:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/errors.rs#L71)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 51 at r4](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FlJewCWIypADbh-bU:-O-G4ttl9DCcEkMp9NTQ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f44a21c6720d6c61a286c0dce00372cd0849e54e/crates/gateway/src/errors.rs#L51)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhE0XdEX1pykXqxEpV:-O-GE53GChIDIO8_OLkp:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L120)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I actually think that expect is more suitable here, since it is a bug of ours if it fails here.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/mempool/225#-NzhDTWI7Pw8vxEFdGfm:-O-FlkDk7_6XEPeFu4nm:b-fh46if) ([raw file](https://github.com/starkware-libs/mempool/blob/642c7a9a28be378089b7ccecd4d09655e8783f44/crates/gateway/src/stateless_transaction_validator.rs#L141)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In the `Casm` class validation we also have bytecode and raw sizes?
In any case, I would prefer to have a dedicated `validate_casm_contract_class` as it may have additional specific validations to Casm.
</blockquote></details>

Done.

We will extract that to a function if need be.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPtaQ3rH4JwDvdQCd:-O-GDXAY9uYZVZkOvyRQ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L30)):*
> ```XML
>         self.validate_tx_size(tx)?;
> 
>         if let ExternalTransaction::Declare(ExternalDeclareTransaction::V3(declare_tx)) = tx {
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FPlTQAx1wWuVS25Bw:-O-GC4tN8WZtez27c8AG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L107)):*
> ```XML
>     fn validate_declare_tx(
>         &self,
>         tx: &ExternalDeclareTransactionV3,
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FQ3xx98ZSSbzj3BZo:-O-GCAS3B5avUsqV8rGL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L111)):*
> ```XML
>         self.validate_class_length(&tx.contract_class)?;
> 
>         Ok(())
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 132 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FWMve8UxFQsL5PMUG:-O-G8Yq08ufrTsqWxlkd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator.rs#L132)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move the checks here and delete `validate_class_size`.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FgB3CA9Nt7BW15YHb:-O-GCGkJ24jAbbvSxTRz:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator_test.rs#L25)):*
> ```XML
>         validate_non_zero_l2_gas_fee: true,
> 
>         max_calldata_length: 1,
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FgGo94yExhi1XU-bu:-O-GA3zP629P6dHZ02dG:b-rutrea) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator_test.rs#L168)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why not use the default?
</blockquote></details>

Done. (was just fixed in a different PR).
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 174 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FhumsDFM1MUVSB-y3:-O-GCQVc7-56OwBkhHi7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator_test.rs#L174)):*
> ```XML
>     };
>     let sierra_program = vec![stark_felt!(1_u128); config_max_bytecode_size + 1];
>     let sierra_program_length = sierra_program.len();
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 191 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FhE7F-UQdspq-jiYg:-O-GDLfWAyA6abz7oSyL:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4295def8d1bd14e8ef44636e342cd736a4040e44/crates/gateway/src/stateless_transaction_validator_test.rs#L191)):*
> ```XML
>             assert_eq!(max_bytecode_size, config_max_bytecode_size);
>         }
>     )
> ```

Done.
___
*[`crates/gateway/src/stateless_transaction_validator_test.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-FiATw0jLpviz8u91o:-O-GDMLY68KVXnhWf7M7:b-896fix) ([raw file] [...]

2024-06-16 08:40 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225#-:-O-VC7BD7m6ArjS_4Ebm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-16 08:41 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-VCIeF9hEFRQvY9x6f:-O-VCIeG-ejBFcEAAPpw:bj2juu6) ([raw file](https://github.com/starkware-libs/mempool/blob/e606059412c21fc9f93a9c079e607c2f51a7296e/crates/gateway/src/errors.rs#L63)):*
> ```XML
>     },
>     #[error("Error serializing object: {object_name}")]
>     SerializationError { object_name: String },
> ```

Is it used?



_Code quote:_
```XML
SerializationError
```


<!-- Sent from Reviewable.io -->

2024-06-16 08:50 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/mempool/225#-O-VCIeF9hEFRQvY9x6f:-O-VDqRxCnpWOz6tQdXZ:bt8ef61) ([raw file](https://github.com/starkware-libs/mempool/blob/2da71c28fe442625b28c002c24cad5fd87edb0f8/crates/gateway/src/errors.rs#L63)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Is it used?
</blockquote></details>

No :). Removed.


<!-- Sent from Reviewable.io -->

2024-06-16 14:04 UTC, dafnamatsry approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/225)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-16 14:43 UTC, merged