test: components communication using http with hyper
starkware-libs/mempool pull request #263
Opened 2024-06-20 13:25 UTC by uriel-starkware

2024-06-20 14:19 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @uriel-starkware)

___
*[`Cargo.toml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzGetCIAU3EhFV2vg:-O-pzGetCIAU3EhFV2vh:b-crfs69) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.toml#L50)):*
> ```TOML
> derive_more = "0.99"
> futures = "0.3.30"
> hyper = { version = "0.14", features = ["full"] }
> ```

What are the other features that needed compared to `client` and `http1` ? Are there features in these crate that we don't need?



_Code quote:_
```TOML
features = ["full"]
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzx4Y8K6PRU7iL0Jo:-O-pzx4Y8K6PRU7iL0Jp:b-ooolt3) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L44)):*
> ```XML
> #[async_trait]
> impl ComponentATrait for ComponentAClientHttp {
>     async fn a_get_value(&self) -> ValueA {
> ```

Recall the return type should capture the client errors as well.



_Code quote:_
```XML
ValueA 
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O-q-N3zB4gTTIP48fLH:bz4we1x) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
> ```XML
>             .header("Content-Type", "application/octet-stream")
>             .body(Body::from(bincode::serialize(&a_get_value).unwrap()))
>             .unwrap();
> ```

What is being unwrapped here? When does this fail?



_Code quote:_
```XML
.unwrap();
```


<!-- Sent from Reviewable.io -->

2024-06-20 14:55 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.toml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzGetCIAU3EhFV2vg:-O-q4bImDsHkVX2cOxtZ:bjcjwy8) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.toml#L50)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What are the other features that needed compared to `client` and `http1` ? Are there features in these crate that we don't need?
</blockquote></details>

In my understanding, by limiting it to http1 as it was previously configured, we missed the possibility of using http2. I could change it to just have "http2", I just didn't bother to check what is the sufficest dependencies and went straight to full
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzx4Y8K6PRU7iL0Jo:-O-q5YgW4Fd2sHCxOTQH:b-ec4bbg) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Recall the return type should capture the client errors as well.
</blockquote></details>

I thought to do this in the next PR. If it bothers you, I will change it now.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O-q5nt34D2f051RfVQ7:bo5egqt) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

What is being unwrapped here? When does this fail?
</blockquote></details>

there're two unwrap in this snippet. the first is the unwrapping of the serialize. I can be sure 100% that it will not fail as I know what is the type I'm serializing.
the next unwrap is the creation of the hyper request. I really don't know what is to fail here and what to expect in case of a failure. I can add expect if you think it's necessary


<!-- Sent from Reviewable.io -->

2024-06-20 15:03 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O-q9X7x3FLT-xxuQF3i:b-yph941) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

there're two unwrap in this snippet. the first is the unwrapping of the serialize. I can be sure 100% that it will not fail as I know what is the type I'm serializing.
the next unwrap is the creation of the hyper request. I really don't know what is to fail here and what to expect in case of a failure. I can add expect if you think it's necessary
</blockquote></details>

actually after reading the description of the body function I can be assured that it will not fail because that the only way it can fail is if one of the previous functions configured something wrong. I only add a URI and a header statically so I know it will not fail.


<!-- Sent from Reviewable.io -->

2024-06-20 15:06 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O-qABU2B3MqL10m-RXD:bfkm8vh) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

actually after reading the description of the body function I can be assured that it will not fail because that the only way it can fail is if one of the previous functions configured something wrong. I only add a URI and a header statically so I know it will not fail.
</blockquote></details>

from description, only header can theoretically fail the request creation, the URI is not relevant. the only header I add is Content-Type and it's legal so not supposed to fail. (I wonder if I need it at all)


<!-- Sent from Reviewable.io -->

2024-06-23 07:18 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @uriel-starkware)

___
*[`Cargo.lock` line 474 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O02wNfS8ugz3qfuzKGr:-O02wNfS8ugz3qfuzKGs:bxanjqe) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.lock#L474)):*
> ```TOML
> version = "2.0.0-rc.3"
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "f11ea1a0346b94ef188834a65c068a03aec181c94896d481d7a0a40d85b0ce95"
> ```

Do we need to have two versions of `bincode`?



_Code quote:_
```TOML
[[package]]
name = "bincode"
version = "1.3.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b1f45e9417d87227c7a56d22e471c6206462cba514c7590c09aff4cf6d1ddcad"
dependencies = [
 "serde",
]

[[package]]
name = "bincode"
version = "2.0.0-rc.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f11ea1a0346b94ef188834a65c068a03aec181c94896d481d7a0a40d85b0ce95"
```
___
*[`Cargo.toml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzGetCIAU3EhFV2vg:-O02w6PEEO4qYMUFwT0l:b89umh0) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.toml#L50)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

In my understanding, by limiting it to http1 as it was previously configured, we missed the possibility of using http2. I could change it to just have "http2", I just didn't bother to check what is the sufficest dependencies and went straight to full
</blockquote></details>

Please add just the required features (e.g., `http2`).
___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O02wZGdCO7a-AOsmKvP:-O02wZGdCO7a-AOsmKvQ:b-ddq4p0) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
> ```TOML
> tonic = "0.11.0"
> prost = "0.12.6"
> bincode = "1.3.3"
> ```

Can you use the same `bincode` version as presented in the lock file?


<!-- Sent from Reviewable.io -->

2024-06-23 08:22 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O037uxkCwow-BP5sicE:bss7mf1) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

from description, only header can theoretically fail the request creation, the URI is not relevant. the only header I add is Content-Type and it's legal so not supposed to fail. (I wonder if I need it at all)
</blockquote></details>

Ack.
Please change both `unwrap`s to `expect`s with adequte messages (e.g., `Request serialization should succeed` and `Request builidng should succeed`).
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O038uwJ-56wfD16N-Nc:-O038uwJ-56wfD16N-Nd:b-6pn8a6) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L53)):*
> ```XML
>             .unwrap();
> 
>         let response = Client::new().request(req).await.expect("Could not connect to server");
> ```

Please add a todo to configure the number of retries before failing the request (iiuc this is part of the client creation parameters).



_Code quote:_
```XML
 Client::new().
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O039qLPDMoHwzmPx0EY:-O039qLPDMoHwzmPx0EZ:bt5rm48) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L105)):*
> ```XML
>         let body_bytes = hyper::body::to_bytes(req.into_body()).await?;
>         let request: ComponentARequest =
>             bincode::deserialize(&body_bytes).expect("Could not deserialize request from client");
> ```

Change to `x should have y` phrasing.



_Code quote:_
```XML
Could not deserialize request from client"
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A7FE71Je3HUHWKgT:-O03A7FE71Je3HUHWKgU:bqmbeoa) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
> ```XML
>             let mut component_guard = component.lock().await;
>             response = component_guard.handle_request(request).await;
>         }
> ```

Is this scoping needed?



_Code quote:_
```XML
        {
            let mut component_guard = component.lock().await;
            response = component_guard.handle_request(request).await;
        }
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A0OE1vBfsdvlQ_BR:-O03A0OE1vBfsdvlQ_BS:b-ut4zhf) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L112)):*
> ```XML
>             response = component_guard.handle_request(request).await;
>         }
>         let response = Response::builder()
> ```

Please use different names, here `response` serves two different purposes, which is confusing.



_Code quote:_
```XML
let response
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03AVzR5qDF0D2gqgFP:-O03AVzR5qDF0D2gqgFQ:b-d389ah) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L140)):*
> ```XML
>             IpAddr::V4(ip_address) => format!("http://{}:{}/", ip_address, port).parse().unwrap(),
>             IpAddr::V6(ip_address) => format!("http://[{}]:{}/", ip_address, port).parse().unwrap(),
>         };
> ```

Please extract to a function and call from the c'tor both here and for the A client.



_Code quote:_
```XML
        let uri = match ip_address {
            IpAddr::V4(ip_address) => format!("http://{}:{}/", ip_address, port).parse().unwrap(),
            IpAddr::V6(ip_address) => format!("http://[{}]:{}/", ip_address, port).parse().unwrap(),
        };
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Al4BCHdVcpBnOBJ1:-O03Al4BCHdVcpBnOBJ2:b-lbuwt) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L180)):*
> ```XML
>     socket: SocketAddr,
>     component: Arc<Mutex<ComponentB>>,
> }
> ```

Can be generic in the component ?



_Code quote:_
```XML
struct ComponentBServerHttp {
    socket: SocketAddr,
    component: Arc<Mutex<ComponentB>>,
}
```


<!-- Sent from Reviewable.io -->

2024-06-23 08:26 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BJgcBPOuubQiopmg:-O03BJgd0oTLfnSqcAT0:b-vl9zos) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L192)):*
> ```XML
>     pub async fn start(&mut self) {
>         let make_svc = make_service_fn(|_conn| {
>             let component = Arc::clone(&self.component);
> ```

Change to `self.component.clone()` throughout.



_Code quote:_
```XML
Arc::clone(&self.component)
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BQVT1NI73_bTT-0V:-O03BQVT1NI73_bTT-0W:bmp4aqy) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L195)):*
> ```XML
>             async move {
>                 Ok::<_, hyper::Error>(service_fn(move |req| {
>                     Self::handler(req, Arc::clone(&component))
> ```

Change to `component.clone()` (throughout



_Code quote:_
```XML
Arc::clone(&component)
```


<!-- Sent from Reviewable.io -->

2024-06-23 08:28 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzx4Y8K6PRU7iL0Jo:-O03CPbW8ZhwvS4kTUS3:b-hao0m7) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L44)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I thought to do this in the next PR. If it bothers you, I will change it now.
</blockquote></details>

Add a todo please, and address that later on (this will also require changing the trait + the other test).


<!-- Sent from Reviewable.io -->

2024-06-23 08:30 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Al4BCHdVcpBnOBJ1:-O03CyTY4rMhqAEB1Nem:b-7n4vf0) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L180)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can be generic in the component ?
</blockquote></details>

I think you'd need something like `<T: RequestHandler>`


<!-- Sent from Reviewable.io -->

2024-06-23 08:32 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 180 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Al4BCHdVcpBnOBJ1:-O03D714ENWtuXs22fBB:b-lxsvdq) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L180)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I think you'd need something like `<T: RequestHandler>`
</blockquote></details>

Probably will also need a generic parameter for the request for the deserialization.


<!-- Sent from Reviewable.io -->

2024-06-23 08:46 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03GZuF28aAAFOwfwnT:-O03GZuF28aAAFOwfwnU:bmnf1qw) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
> ```TOML
> tonic = "0.11.0"
> prost = "0.12.6"
> bincode = "1.3.3"
> ```

I suggest we define these eventually as part of the main toml file, and use the `.workspace` derivation feature in this local one. Please add a todo to change these.



_Code quote:_
```TOML
tonic = "0.11.0"
prost = "0.12.6"
bincode = "1.3.3"
```


<!-- Sent from Reviewable.io -->

2024-06-23 08:48 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 15 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Go8P4rok0OjCZCE-:-O03Go8P4rok0OjCZCE0:b-2x6ag4) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L26)):*
> ```XML
> pub enum ComponentAResponse {
>     Value(ValueA),
> }
> ```

Add a todo to move these to `common`



_Code quote:_
```XML
#[derive(Serialize, Deserialize, Debug)]
pub enum ComponentARequest {
    AGetValue,
}

#[derive(Serialize, Deserialize, Debug)]
pub enum ComponentAResponse {
    Value(ValueA),
}
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Gtni1PYQHg3i9EEg:-O03Gtni1PYQHg3i9EEh:b-2x6ag4) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L129)):*
> ```XML
> pub enum ComponentBResponse {
>     Value(ValueB),
> }
> ```

Add a todo to move these to `common`



_Code quote:_
```XML
#[derive(Serialize, Deserialize, Debug)]
pub enum ComponentBRequest {
    BGetValue,
}

#[derive(Serialize, Deserialize, Debug)]
pub enum ComponentBResponse {
    Value(ValueB),
}
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Gw7I1WtLZjGGJxEI:-O03Gw7I1WtLZjGGJxEJ:bymg1bp) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L133)):*
> ```XML
> struct ComponentBClientHttp {
>     uri: Uri,
> }
> ```

Add a todo to unify this with the A client (they're the same struct, but need to impl different traits).



_Code quote:_
```XML
struct ComponentBClientHttp {
    uri: Uri,
}
```


<!-- Sent from Reviewable.io -->

2024-06-23 09:00 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 16 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Ji2zDlF8h_Y0PNPv:-O03Ji2zDlF8h_Y0PNPw:b-fsn9vw) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L30)):*
> ```XML
> struct ComponentAClientHttp {
>     uri: Uri,
> }
> ```

Add a todo:
1. make generic
2. move to `common`



_Code quote:_
```XML
struct ComponentAClientHttp {
    uri: Uri,
}
```


<!-- Sent from Reviewable.io -->

2024-06-23 11:25 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 0 of 4 files reviewed, 16 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`Cargo.lock` line 474 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O02wNfS8ugz3qfuzKGr:-O02xhFt604mXONgSOyS:bt2qk05) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.lock#L474)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Do we need to have two versions of `bincode`?
</blockquote></details>

It seems that the rc version (stands for release candidate) is a dep of a dep. So I can't do a lot about the version there. I added the latest release to our cargo.toml file. If I change the version in our cargo.toml to the release candidate then cargo yells that it doesn't recognize the functions I use in that crate.
___
*[`Cargo.toml` line 50 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzGetCIAU3EhFV2vg:-O03P--T0E2JtIwZS5ZT:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/Cargo.toml#L50)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add just the required features (e.g., `http2`).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O02wZGdCO7a-AOsmKvP:-O031MH41MzMJx9mFLKv:b-6xoaza) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Can you use the same `bincode` version as presented in the lock file?
</blockquote></details>

see above comment
___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03GZuF28aAAFOwfwnT:-O03PWsS0svuMICk9vb6:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I suggest we define these eventually as part of the main toml file, and use the `.workspace` derivation feature in this local one. Please add a todo to change these.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Go8P4rok0OjCZCE-:-O03pvLf9YcqbRqDHP9d:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L26)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a todo to move these to `common`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Ji2zDlF8h_Y0PNPv:-O03SWQGDKt174k4eP84:bjhpnu2) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L30)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a todo:
1. make generic
2. move to `common`
</blockquote></details>

this one will only be generic and will not need to be moved to common
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-pzx4Y8K6PRU7iL0Jo:-O03TE6y5KDQ2lUeyzMY:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L44)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a todo please, and address that later on (this will also require changing the trait + the other test).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O-q-N3zB4gTTIP48fLG:-O03m_0P8QPOO3R6x9mM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L51)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ack.
Please change both `unwrap`s to `expect`s with adequte messages (e.g., `Request serialization should succeed` and `Request builidng should succeed`).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O038uwJ-56wfD16N-Nc:-O03mZmZC9i1bCK-dUbS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L53)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a todo to configure the number of retries before failing the request (iiuc this is part of the client creation parameters).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O039qLPDMoHwzmPx0EY:-O03n0S1EuD7S1Y0K6RU:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L105)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Change to `x should have y` phrasing.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A7FE71Je3HUHWKgT:-O03PryKCOWEYQBrfls0:b-kfhowe) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Is this scoping needed?
</blockquote></details>

for releasing the lock eariler than the function scope
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A0OE1vBfsdvlQ_BR:-O03pA6r3Yoq7hfjl18a:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L112)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please use different names, here `response` serves two different purposes, which is confusing.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Gtni1PYQHg3i9EEg:-O03pCaACysYtwwgm8lY:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L129)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Add a todo to move these to `common`
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 133 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Gw7I1WtLZjGGJxEI:-O03pJBC8fZ9H6VgUPO7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_ [...]

2024-06-23 11:41 UTC, Itay-Tsabary-Starkware requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03GZuF28aAAFOwfwnT:-O03rfhB3zalskyXPa7t:bxxw9ns) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please alphabetize the dependencies
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Ji2zDlF8h_Y0PNPv:-O03rnDDAErL2FlvLwkN:byxpqjo) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L30)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

this one will only be generic and will not need to be moved to common
</blockquote></details>

Right. But after an additional thought, the generic code should reside in `src`.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O039qLPDMoHwzmPx0EY:-O03sRUKC_FOveIH3YD9:buk1ljl) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L105)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not really.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A7FE71Je3HUHWKgT:-O03sWIV4VOt1JAuKNDi:b-xjkglw) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

for releasing the lock eariler than the function scope
</blockquote></details>

Please add a comment that explains that.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A0OE1vBfsdvlQ_BR:-O03saSl9VzeNdW-hHOy:b8wiili) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L112)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Different names that indicate the different meanings/purposes of these variables, not that are semantically different :-)
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03AVzR5qDF0D2gqgFP:-O03sm8sDsYgQPFqVds5:b-gnordp) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L140)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I deliberately duplicated it because in the next phase of generalizing it I will use it only here.
</blockquote></details>

I don't understand the motivation, but as long as this gets sorted eventually...
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BJgcBPOuubQiopmg:-O03t89A4Nj94jVnVe60:b-dxhcz3) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L192)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Can I reject this suggestion? I read somewhere this is the preferred way when using arc. By  writing it this way it makes it clearer that it's an arc clone and not the component clone. leaves less ambiguity this way
</blockquote></details>

1. Please share the reading material
2. I defintely see we having components that handle their concurrency on their own, hence we won't wrap them with `arc` to begin with
3. If you still prefer to leave as is (though I'd prefer you'll change), please add a TODO indicating to consider these.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BQVT1NI73_bTT-0V:-O03tg7pAK8dez4F8DnU:b3ks9) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L195)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

see above answer
</blockquote></details>

^
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03sHCD98LV-9HQJIro:-O03sHCE4kvA_w2iOWpp:blr55ck) ([raw file](https://github.com/starkware-libs/mempool/blob/6e576c85ee943df7788615b43bcea7ce5a295c0e/crates/mempool_infra/tests/component_server_client_http_test.rs#L58)):*
> ```XML
> 
>         // todo(uriel): add configuration to  control number of retries
>         let response = Client::new().request(req).await.expect("Could not connect to server");
> ```

This `expect` will be dropped when the fn starts returning errors.



_Code quote:_
```XML
"Could not connect to server"
```


<!-- Sent from Reviewable.io -->

2024-06-23 12:31 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/Cargo.toml` line 23 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03GZuF28aAAFOwfwnT:-O041UFICUlYrmp9WlMb:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/Cargo.toml#L23)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please alphabetize the dependencies
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03Ji2zDlF8h_Y0PNPv:-O0418QPCaM0yeeG-kX3:bjr800p) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L30)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Right. But after an additional thought, the generic code should reside in `src`.
</blockquote></details>

my mistake, it will be moved to src, not common
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O039qLPDMoHwzmPx0EY:-O040saZ1jY3BaEl89M-:b9szwv9) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L105)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Not really.
</blockquote></details>

oh oops
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A7FE71Je3HUHWKgT:-O040pZR5UQrtz_6TDyu:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a comment that explains that.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A0OE1vBfsdvlQ_BR:-O04-dmH2A_VlsB9McqL:bx3jmd0) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L112)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Different names that indicate the different meanings/purposes of these variables, not that are semantically different :-)
</blockquote></details>

oh ok haha
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03AVzR5qDF0D2gqgFP:-O04-_-EBw9k0-8PCo9Y:b5uq0gh) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L140)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

I don't understand the motivation, but as long as this gets sorted eventually...
</blockquote></details>

Will be sorted
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BJgcBPOuubQiopmg:-O03zRmI2zp6fof4aW5k:bc8cx2v) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L192)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

1. Please share the reading material
2. I defintely see we having components that handle their concurrency on their own, hence we won't wrap them with `arc` to begin with
3. If you still prefer to leave as is (though I'd prefer you'll change), please add a TODO indicating to consider these.
</blockquote></details>

1. https://doc.rust-lang.org/book/ch15-04-rc.html#using-rct-to-share-data
2. NP, but if this is the case, we will remove the arc<mutex>> wrapper entirely and let the component handle it. As long as the self.component is an Arc object I want it to be clear I clone the arc and not the deref component (which can impl a deep clone as far as I know)
3. I'll add a todo
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BQVT1NI73_bTT-0V:-O04-UlC8LcqvhqGJd9y:b32wed) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L195)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

^
</blockquote></details>

^^


<!-- Sent from Reviewable.io -->

2024-06-23 12:32 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BJgcBPOuubQiopmg:-O0442-3CyrSVUnlZYCH:bhdi3gg) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L192)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

1. https://doc.rust-lang.org/book/ch15-04-rc.html#using-rct-to-share-data
2. NP, but if this is the case, we will remove the arc<mutex>> wrapper entirely and let the component handle it. As long as the self.component is an Arc object I want it to be clear I clone the arc and not the deref component (which can impl a deep clone as far as I know)
3. I'll add a todo
</blockquote></details>

regarding 1. you will find the explanation in the last paragraph of the section I linked


<!-- Sent from Reviewable.io -->

2024-06-23 13:35 UTC, Itay-Tsabary-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03A7FE71Je3HUHWKgT:-O04IPSO-16tt74QCBxT:b-ayc0to) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment should start with a capital letter (non-blocking).
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/mempool/263#-O03BJgcBPOuubQiopmg:-O04IgcGAsmavzmL-HGF:bb6sh2i) ([raw file](https://github.com/starkware-libs/mempool/blob/5b73b600007500c82b66a38b01c630604745fd94/crates/mempool_infra/tests/component_server_client_http_test.rs#L192)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

regarding 1. you will find the explanation in the last paragraph of the section I linked
</blockquote></details>

Ack.
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/mempool/263#-O04IKsl-aVPFR7W_Jrc:-O04IKsl-aVPFR7W_Jrd:buh3h8c) ([raw file](https://github.com/starkware-libs/mempool/blob/bd045d073e1d7f03e8ec43b37ff05a3ec2f59406/crates/mempool_infra/tests/component_server_client_http_test.rs#L111)):*
> ```XML
>         let body_bytes = hyper::body::to_bytes(http_request.into_body()).await?;
>         let component_request: ComponentARequest =
>             bincode::deserialize(&body_bytes).expect("Request Deserialization should succeed");
> ```

lowercase d (non-blocking)



_Code quote:_
```XML
D
```
___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 274 at r3](https://reviewable.io/reviews/starkware-libs/mempool/263#-O04IleM8KGTvMYuswbt:-O04IleM8KGTvMYuswbu:b-m5bp2o) ([raw file](https://github.com/starkware-libs/mempool/blob/bd045d073e1d7f03e8ec43b37ff05a3ec2f59406/crates/mempool_infra/tests/component_server_client_http_test.rs#L274)):*
> ```XML
>     });
> 
>     task::yield_now().await;
> ```

Please add a todo to get rid of this


<!-- Sent from Reviewable.io -->

2024-06-23 13:36 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263#-:-O04Iv9Y9t84r1oqHRx7:bnfp4nl)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)



<!-- Sent from Reviewable.io -->

2024-06-23 13:36 UTC, Itay-Tsabary-Starkware approved these changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: all files reviewed, 2 unresolved discussions (waiting on @uriel-starkware)



<!-- Sent from Reviewable.io -->

2024-06-23 14:52 UTC, uriel-starkware reviewed
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @uriel-starkware)



<!-- Sent from Reviewable.io -->

2024-06-23 14:53 UTC, merged