test: generic client/server for component communication using hyper
starkware-libs/mempool pull request #274
Opened 2024-06-25 08:23 UTC by uriel-starkware

2024-06-25 10:44 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqNWV02kb1oCzhxhg:-O0DqNWV02kb1oCzhxhh:bullxv1) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L17)):*
> ```XML
> }
> 
> pub type ClientResult<Response> = Result<Response, ClientError>;
> ```

Move back to the bottom of the module. We sort by imporance, and this is not very important.



_Code quote:_
```XML
#[derive(Debug, Error)]
pub enum ClientError {
    #[error("Got an unexpected response type.")]
    UnexpectedResponse,
}

pub type ClientResult<Response> = Result<Response, ClientError>;
```
___
*[`crates/mempool_infra/src/component_client.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqYSP4-SYexJEG-pJ:-O0DqYSP4-SYexJEG-pK:b-n3t9dj) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L19)):*
> ```XML
> pub type ClientResult<Response> = Result<Response, ClientError>;
> 
> pub struct ComponentClientChannel<Request, Response>
> ```

Please revert this change; we'll address the names once the abstraction is ready (not yet).



_Code quote:_
```XML
ComponentClientChannel<
```
___
*[`crates/mempool_infra/src/component_client.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqufT5K72S39FTKD-:-O0DqufT5K72S39FTKD0:bu51izr) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L38)):*
> ```XML
>     // TODO(Tsabary, 1/5/2024): Consider implementation for messages without expected responses.
> 
>     pub async fn send(&self, request: Request) -> ClientResult<Response> {
> ```

Please revert this change.



_Code quote:_
```XML
ClientResult<Response> 
```
___
*[`crates/mempool_infra/src/component_definitions.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DrHSw6Y2Xnbpj09dY:-O0DrHSw6Y2Xnbpj09dZ:bu51izr) ([raw file](https://github.com/starkware-libs/mempool/blob/3a24fb1edf7bd78ecb2faff2f43f6400ba9795ce/crates/mempool_infra/src/component_definitions.rs#L7)):*
> ```XML
> pub trait ComponentRequestHandler<Request, Response> {
>     async fn handle_request(&mut self, request: Request) -> Response;
> }
> ```

Please revert this change.



_Code quote:_
```XML
#[async_trait]
pub trait ComponentRequestHandler<Request, Response> {
    async fn handle_request(&mut self, request: Request) -> Response;
}
```
___
*[`crates/mempool_infra/src/component_server.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DrMAZ5mZjq2obvIUm:-O0DrMAZ5mZjq2obvIUn:bu51izr) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L21)):*
> ```XML
> pub trait ComponentRequestHandler<Request, Response> {
>     async fn handle_request(&mut self, request: Request) -> Response;
> }
> ```

Please revert this change.



_Code quote:_
```XML
#[async_trait]
pub trait ComponentRequestHandler<Request, Response> {
    async fn handle_request(&mut self, request: Request) -> Response;
}
```
___
*[`crates/mempool_infra/src/component_server.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DsM35EwWeha_eMdNc:-O0DsM35EwWeha_eMdNd:b-kvbgse) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L58)):*
> ```XML
> }
> 
> pub struct ComponentServerHttp<Component> {
> ```

Why not make generic in `Request` and `Response` as well, similar to `ComponentServer`? 



_Code quote:_
```XML
<Component>
```


<!-- Sent from Reviewable.io -->

2024-06-25 13:58 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqNWV02kb1oCzhxhg:-O0Ee3g311K8H6nT0su1:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L17)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Move back to the bottom of the module. We sort by imporance, and this is not very important.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqYSP4-SYexJEG-pJ:-O0Ee5I50NNI97vCgw4m:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L19)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert this change; we'll address the names once the abstraction is ready (not yet).
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_client.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DqufT5K72S39FTKD-:-O0EerDh9PgHyIlGAj5a:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_client.rs#L38)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert this change.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DrMAZ5mZjq2obvIUm:-O0EetA168yveP5YOkfd:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L21)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert this change.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DsM35EwWeha_eMdNc:-O0EeufpEQ6VVt-L3bdp:b-xj1ki8) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L58)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why not make generic in `Request` and `Response` as well, similar to `ComponentServer`?
</blockquote></details>

Because struct ComponentServerHttp doesn't need to know what are the request/response types at creation. If I'll add the generics to the struct definition (using phantomData) then I put constraints on it that I think are unnecessary. The constraints on what are request/response in the case of the HTTP client are only relevant when starting the server.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DrHSw6Y2Xnbpj09dY:-O0Eg3PDAVyCrPrurmfR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3a24fb1edf7bd78ecb2faff2f43f6400ba9795ce/crates/mempool_infra/src/component_definitions.rs#L7)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please revert this change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 14:27 UTC, Itay-Tsabary-Starkware requested changes
> Reviewed 1 of 8 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 20 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiFjdB6CgH-DvqRCA:-O0EiFje1cUdDYo6p3EP:b-8aaepc) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L65)):*
> ```XML
>     }
> 
>     pub async fn send<Request, Response>(&self, component_request: Request) -> Response
> ```

The return type here should capture sending errors, see below.



_Code quote:_
```XML
Response
```
___
*[`crates/mempool_infra/src/component_client.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Ehp-z8O__IBPL3qzf:-O0Ehp-z8O__IBPL3qzg:br1ud0t) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L68)):*
> ```XML
>     where
>         Request: Serialize,
>         Response: for<'a> Deserialize<'a>,
> ```

Why are lifetimes required here?
___
*[`crates/mempool_infra/src/component_client.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiMK50iwWSiV7jiEw:-O0EiMK50iwWSiV7jiEx:beezc4j) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L73)):*
> ```XML
>             .header("Content-Type", "application/octet-stream")
>             .body(Body::from(
>                 serialize(&component_request).expect("Request serialization should succeed"),
> ```

Though I do not expect it to ever fail, this should return a suitable error.



_Code quote:_
```XML
.expect("Request serialization should succeed")
```
___
*[`crates/mempool_infra/src/component_client.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiXr8-8XLtryt6-UP:-O0EiXr8-8XLtryt6-UQ:beezc4j) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L75)):*
> ```XML
>                 serialize(&component_request).expect("Request serialization should succeed"),
>             ))
>             .expect("Request builidng should succeed");
> ```

Though I do not expect it to ever fail, this should return a suitable error.



_Code quote:_
```XML
.expect("Request builidng should succeed");
```
___
*[`crates/mempool_infra/src/component_client.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eia1v7TwsWhKcvLop:-O0Eia1v7TwsWhKcvLoq:bigt7kl) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L79)):*
> ```XML
>         // TODO(uriel): Add configuration to control number of retries
>         let http_response =
>             Client::new().request(http_request).await.expect("Could not connect to server");
> ```

This can fail, and should return a suitable error.



_Code quote:_
```XML
.expect("Could not connect to server")
```
___
*[`crates/mempool_infra/src/component_client.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eig4zE1wx1ZRw2msw:-O0Eig4zE1wx1ZRw2msx:bigt7kl) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L82)):*
> ```XML
>         let body_bytes = hyper::body::to_bytes(http_response.into_body())
>             .await
>             .expect("Could not get response from server");
> ```

This can fail, and should return a suitable error.



_Code quote:_
```XML
.expect("Could not get response from server");
```
___
*[`crates/mempool_infra/src/component_client.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EijmgAzLPNu6ZLcZ-:-O0Eijmh9pWFM0VGXvp-:bigt7kl) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L84)):*
> ```XML
>             .expect("Could not get response from server");
> 
>         bincode::deserialize(&body_bytes).expect("Response deserialization should succeed")
> ```

This can fail, and should return a suitable error.



_Code quote:_
```XML
.expect("Response deserialization should succeed")
```
___
*[`crates/mempool_infra/src/component_server.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DsM35EwWeha_eMdNc:-O0EiqB9--U7cEVuDGjJ:b-dp9oxv) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L58)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

Because struct ComponentServerHttp doesn't need to know what are the request/response types at creation. If I'll add the generics to the struct definition (using phantomData) then I put constraints on it that I think are unnecessary. The constraints on what are request/response in the case of the HTTP client are only relevant when starting the server.
</blockquote></details>

We have a technical issue where we're making some compromises in defining and bundling our types together.
Namely, the Request, Response, and Component generics are all tightly coupled -- it does not make much sense to have a Mempool Component paired up with GatewayRequest and BatcherResponse.
One way to strengthen this connection is by enforcing the relation at construction, rather then only at invocation. See the local ComponentServer version for comparison.

TL;DR: please make the struct generic in Request, Response as well.
___
*[`crates/mempool_infra/src/component_server.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EkJv1901uxaXVaqOC:-O0EkJv1901uxaXVaqOD:boqapo8) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L54)):*
> ```XML
> pub struct ComponentServerHttp<Component> {
>     socket: SocketAddr,
>     component: Arc<Mutex<Component>>,
> ```

Please add a todo:
Consider implementations where the concurrency control mechanism is implemented by the component instead of the server.



_Code quote:_
```XML
Arc<Mutex<Component>>,
```
___
*[`crates/mempool_infra/src/component_server.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EjfHm5fsFkDmkUhAe:-O0EjfHm5fsFkDmkUhAf:b-xfrgn4) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L67)):*
> ```XML
>     pub async fn start<Request, Response>(&mut self)
>     where
>         Request: for<'a> Deserialize<'a> + Send + 'static,
> ```

Ditto question regarding lifetimes.



_Code quote:_
```XML
for<'a> Deserialize<'a>
```
___
*[`crates/mempool_infra/src/component_server.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EjlOB5t0U2HgHQxA-:-O0EjlOB5t0U2HgHQxA0:b-j0x32d) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L67)):*
> ```XML
>     pub async fn start<Request, Response>(&mut self)
>     where
>         Request: for<'a> Deserialize<'a> + Send + 'static,
> ```

Are these still required after changing the struct generics?



_Code quote:_
```XML
 Send + 'static
```
___
*[`crates/mempool_infra/src/component_server.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EkoDI5P6w-hLj77JZ:-O0EkoDJC4ricHwR2lck:b-g7wop1) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L80)):*
> ```XML
>         });
> 
>         Server::bind(& [...]

2024-06-26 12:38 UTC, uriel-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 20 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiFjdB6CgH-DvqRCA:-O0JQh9d79bwERvhw_Ip:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L65)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

The return type here should capture sending errors, see below.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_client.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Ehp-z8O__IBPL3qzf:-O0FmCjx-SczOL_Zx5h6:b-emt9t2) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L68)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Why are lifetimes required here?
</blockquote></details>

Deserialize is a trait that needs to specify lifetime. in this case the lifetime you see is in the for<'a> syntax, which means for "all lifetimes" and is not referring to any lifetime specifically.
___
*[`crates/mempool_infra/src/component_client.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiMK50iwWSiV7jiEw:-O0JQgFgDXKRZ6ptdOrP:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L73)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Though I do not expect it to ever fail, this should return a suitable error.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_client.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiXr8-8XLtryt6-UP:-O0JQfau8EQi5hMrc_H7:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L75)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Though I do not expect it to ever fail, this should return a suitable error.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_client.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eia1v7TwsWhKcvLop:-O0JQefy-1kkV0nlD7wB:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L79)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This can fail, and should return a suitable error.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_client.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eig4zE1wx1ZRw2msw:-O0JQe9T9E2PZ6Lqw3O0:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L82)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This can fail, and should return a suitable error.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_client.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EijmgAzLPNu6ZLcZ-:-O0JQdOR01mpjvdO-002:b-et8br6) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L84)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

This can fail, and should return a suitable error.
</blockquote></details>

I want to do it as another PR, focusing now on the logic
___
*[`crates/mempool_infra/src/component_server.rs` line 58 at r2](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0DsM35EwWeha_eMdNc:-O0JPpN56EAJOImlsq41:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f8af511cbd6e4ea388f857df3c5b8f8d5dfc876b/crates/mempool_infra/src/component_server.rs#L58)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

We have a technical issue where we're making some compromises in defining and bundling our types together.
Namely, the Request, Response, and Component generics are all tightly coupled -- it does not make much sense to have a Mempool Component paired up with GatewayRequest and BatcherResponse.
One way to strengthen this connection is by enforcing the relation at construction, rather then only at invocation. See the local ComponentServer version for comparison.

TL;DR: please make the struct generic in Request, Response as well.
</blockquote></details>

Done.
___
*[`crates/mempool_infra/src/component_server.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EkJv1901uxaXVaqOC:-O0JP3Ot7RX1Sqej9QWZ:b-e25nad) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L54)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Please add a todo:
Consider implementations where the concurrency control mechanism is implemented by the component instead of the server.
</blockquote></details>

As a result of trying to answer your question regarding why the Send bound I implemented it already (well not entirely by componentA/B but I wrapped them in the test with arc<mutex<>> instead in the server logic
___
*[`crates/mempool_infra/src/component_server.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EjfHm5fsFkDmkUhAe:-O0FnNL21p85Id7fHuU1:b-mjarl3) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Ditto question regarding lifetimes.
</blockquote></details>

ditto answer
___
*[`crates/mempool_infra/src/component_server.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EjlOB5t0U2HgHQxA-:-O0FnWcD5DccV8pDpunS:b-on13wz) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L67)):*
<details><summary><i>Previously, Itay-Tsabary-Starkware wrote…</i></summary><blockquote>

Are these still required after changing the struct generics?
</blockquote></details>

By 'these' I understand you are referring to both Send and 'static bounds.
1. the Send is because in the handler function we have a variable of type Request that could be sent between threads when there is a yield (see that there is a await after init of component_request. Response does not need to be Send because after init of component_response there is no await so there is no fear of moving between threads.
2. the 'static bounds are necessary no matter what because the compiler doesn't know if the generic types (i.e. Request, Response and Component) are not references. Because it cannot be guaranteed that there are not of type &something then the 'static bound must be put. In any case it does not prevent from the user to use the generic structs with owned types like we do in the tests (component_a and component_b are not 'static references and it's working).

Anyway, to answer this question I had to try a few things and it lead me to throw the use of arc<mutex<>> and by tha [...]

2024-06-27 07:16 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 17 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_client.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiFjdB6CgH-DvqRCA:-O0NWJ3-B4n8071wSXVD:b-ib4wrw) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L65)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

This is part of the logic though, but ok. Since this is a significant api change, please add a todo in code to change that. 
___
*[`crates/mempool_infra/src/component_client.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiMK50iwWSiV7jiEw:-O0NX-vI1aRwUbSOdnWV:bdl7w6h) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L73)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

RE comment from above; please add a todo.
___
*[`crates/mempool_infra/src/component_client.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EiXr8-8XLtryt6-UP:-O0NX4Gn4SIb1Pgfx32O:bdl7w6h) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L75)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

RE comment from above; please add a todo.
___
*[`crates/mempool_infra/src/component_client.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eia1v7TwsWhKcvLop:-O0NX59d0EiP0eQV-K27:bdl7w6h) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L79)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

RE comment from above; please add a todo.
___
*[`crates/mempool_infra/src/component_client.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Eig4zE1wx1ZRw2msw:-O0NX5xWD8JMkpQzrvYx:bdl7w6h) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L82)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

RE comment from above; please add a todo.
___
*[`crates/mempool_infra/src/component_client.rs` line 84 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EijmgAzLPNu6ZLcZ-:-O0NX6fA-thvHW08nUni:bdl7w6h) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_client.rs#L84)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

RE comment from above; please add a todo.
___
*[`crates/mempool_infra/src/component_definitions.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0KcbYs6QD-IN0nRzkP:-O0KcbYs6QD-IN0nRzkQ:bh08kc7) ([raw file](https://github.com/starkware-libs/mempool/blob/5b54daf66a45ed7237fdbf75b63c3f252b31c887/crates/mempool_infra/src/component_definitions.rs#L5)):*
> ```XML
> 
> #[async_trait]
> pub trait ComponentRequestHandler<Request, Response>: Send + Sync {
> ```

Please explain why this is required. 
Also, I'm not sure this is the correct place to enforce these constraints, as we have other implementations that do not require these.



_Code quote:_
```XML
: Send + Sync
```
___
*[`crates/mempool_infra/src/component_server.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EkoDI5P6w-hLj77JZ:-O0NXdoh87wKU-wjtL3F:bda2x1z) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L80)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

returns a result, http server starts listening here, if it fails it returns an error.
</blockquote></details>

Please add a todo to propagate this error.
___
*[`crates/mempool_infra/src/component_server.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Ekz1LCLSbfaJ557sr:-O0NY87i3OcV4R6s3uNS:b9qlx7p) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L94)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

Add a todo.
___
*[`crates/mempool_infra/src/component_server.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Em7E_3BCHmWHNWKzW:-O0NYJKM5sobwoFVGvap:b9qlx7p) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L106)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

Add a todo.
___
*[`crates/mempool_infra/src/component_server.rs` line 108 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EmA5k1Gnok5vYUnT6:-O0NYJxu2wFIaJvxRwEQ:b9qlx7p) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L108)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

I want to do it as another PR, focusing now on the logic
</blockquote></details>

Add a todo.


<!-- Sent from Reviewable.io -->

2024-06-27 07:20 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 17 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EkJv1901uxaXVaqOC:-O0NZ6aFBZJVgMHnU_n2:b-iq7uhg) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L54)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

As a result of trying to answer your question regarding why the Send bound I implemented it already (well not entirely by componentA/B but I wrapped them in the test with arc<mutex<>> instead in the server logic
</blockquote></details>

Please make such changes in a different pr; these are out of scope for this one.


<!-- Sent from Reviewable.io -->

2024-06-27 07:22 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 17 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0EjlOB5t0U2HgHQxA-:-O0NZPEwCCulMcsVZcm4:b2yh4s) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L67)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

By 'these' I understand you are referring to both Send and 'static bounds.
1. the Send is because in the handler function we have a variable of type Request that could be sent between threads when there is a yield (see that there is a await after init of component_request. Response does not need to be Send because after init of component_response there is no await so there is no fear of moving between threads.
2. the 'static bounds are necessary no matter what because the compiler doesn't know if the generic types (i.e. Request, Response and Component) are not references. Because it cannot be guaranteed that there are not of type &something then the 'static bound must be put. In any case it does not prevent from the user to use the generic structs with owned types like we do in the tests (component_a and component_b are not 'static references and it's working).

Anyway, to answer this question I had to try a few things and it lead me to throw the use of arc<mutex<>> and by that I needed to just put bounds on the Component generic as now component_request does not need to survive after an await (that I had to use for acquiring the lock)
</blockquote></details>

This is challenging to keep track of what's been added when, and for what purpose. Please revert to the old version so we could have a meaningful discussion :pray: 


<!-- Sent from Reviewable.io -->

2024-06-27 07:25 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 17 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/src/component_server.rs` line 104 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0Elf7S0vIgKWEAjmtG:-O0N_BCW9IXst4SqN5XY:bjazfb5) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/src/component_server.rs#L104)):*
<details><summary><i>Previously, uriel-starkware wrote…</i></summary><blockquote>

2. done
1. needs clarification: Do you want me to make a const in each file? or make a const in a third file and both server.rs and client.rs will import it? If so, then which third file should hold the const?
</blockquote></details>

Yes, please wrap `application/octet-stream` as a const and place it in `crates/mempool_infra/src/component_definitions.rs`.


<!-- Sent from Reviewable.io -->

2024-06-27 07:27 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 18 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_http_test.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0N_PSsDn3HvYVrDQOo:-O0N_PSsDn3HvYVrDQOp:b-elpm81) ([raw file](https://github.com/starkware-libs/mempool/blob/5b54daf66a45ed7237fdbf75b63c3f252b31c887/crates/mempool_infra/tests/component_server_client_http_test.rs#L47)):*
> ```XML
> 
> #[async_trait]
> impl ComponentRequestHandler<ComponentARequest, ComponentAResponse> for Arc<Mutex<ComponentA>> {
> ```

Essentially you're suggesting to create a wrapper for the component, right? If so, make it an explicit one. That is, define a wrapper struct. Please defer this to a different pr, this one is already packed.



_Code quote:_
```XML
Arc<Mutex<ComponentA>>
```


<!-- Sent from Reviewable.io -->

2024-06-27 07:28 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 19 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_test.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0N_upcACXh0hmBZ_0c:-O0N_upcACXh0hmBZ_0d:b8pvos5) ([raw file](https://github.com/starkware-libs/mempool/blob/5b54daf66a45ed7237fdbf75b63c3f252b31c887/crates/mempool_infra/tests/component_server_client_test.rs#L40)):*
> ```XML
> }
> 
> #[async_trait]
> ```

It doesn't make sense to me that both the component and the wrapper need to impl this trait. This infers something is inaccurate in the abstraction.


<!-- Sent from Reviewable.io -->

2024-06-27 07:28 UTC, Itay-Tsabary-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/274)* status: 2 of 9 files reviewed, 20 unresolved discussions (waiting on @uriel-starkware)

___
*[`crates/mempool_infra/tests/component_server_client_test.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/mempool/274#-O0NaBro9SiJbaPtlVZj:-O0NaBro9SiJbaPtlVZk:b700kcx) ([raw file](https://github.com/starkware-libs/mempool/blob/e4435a434c22efedde10f58db6645f5593413af8/crates/mempool_infra/tests/component_server_client_test.rs#L56)):*
> ```XML
>             assert_eq!(value, expected_value);
>         }
>     }
> ```

Where did this logic go to?



_Code quote:_
```XML
    let (tx_a_main, mut rx_a_main) = channel::<ComponentAResponse>(1);

    let request_and_res_tx: ComponentRequestAndResponseSender<
        ComponentARequest,
        ComponentAResponse,
    > = ComponentRequestAndResponseSender { request: ComponentARequest::AGetValue, tx: tx_a_main };

    tx_a.send(request_and_res_tx).await.unwrap();

    let res = rx_a_main.recv().await.unwrap();
    match res {
        ComponentAResponse::Value(value) => {
            assert_eq!(value, expected_value);
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-07-02 11:48 UTC, closed without merging