feat: add routes test (semi-integration test)
starkware-libs/mempool pull request #28
Opened 2024-04-04 15:41 UTC by giladchase

- tests that routes behave the way we expect, shouldn't have too much logic here, just test status codes and return values. Proper integration/flow tests will be in their own testing file.
- add `tower` dependency that `axum` uses in order to simulate an HTTP request via the `oneshot` call: this simulates the HTTP request without having to spin up an actual server and perform IO.
- Currently add_transaction test is identical to the one in gateway_test.rs, but they'll diverge once real logic kicks in. At that point the routes test will only test for success codes in basic scenarios.
- is_alive is currently just a dummy test, since it isn't implemented yet.

2024-04-07 10:18 UTC, MohammadNassar1 requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/28)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus2sxT1bhtY2d38hAQ:-Nus2sxT1bhtY2d38hAR:b-wjp9zg) (no related file):*
Nice!

1. Why these tests are not part of `gateway_test`?
2. Are you planning to remove the identical test from `gateway_test`?

___
___
*[`crates/gateway/tests/routing_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus1Enp3paWWDZ4kr0I:-Nus1Enp3paWWDZ4kr0J:bob810n) ([raw file](https://github.com/starkware-libs/mempool/blob/2499b1bc79c913218857e14156f3d5a080c9e515/crates/gateway/tests/routing_test.rs#L17)):*
> ```XML
>     "DEPLOY_ACCOUNT"
> )]
> #[case("./src/json_files_for_testing/invoke_v3.json", "INVOKE")]
> ```

Why not "INVOKE_FUNCTION"?
This should be the expected type.



_Code quote:_
```XML
"INVOKE"
```
___
*[`crates/gateway/tests/routing_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus2PiD8_yaqIYm7p5F:-Nus2PiD8_yaqIYm7p5G:bvzjebb) ([raw file](https://github.com/starkware-libs/mempool/blob/2499b1bc79c913218857e14156f3d5a080c9e515/crates/gateway/tests/routing_test.rs#L22)):*
> ```XML
>     let tx_json = fs::read_to_string(json_file_path).unwrap();
>     let request = Request::post("/add_transaction")
>         .header("content-type", "application/json")
> ```

Could you explain why you added this header?



_Code quote:_
```XML
.header("content-type", "application/json")
```


<!-- Sent from Reviewable.io -->

2024-04-07 14:36 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/28)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/gateway/tests/routing_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus1Enp3paWWDZ4kr0I:-NusyMcR8yb7Xx2EwNxl:b-ubkbik) ([raw file](https://github.com/starkware-libs/mempool/blob/2499b1bc79c913218857e14156f3d5a080c9e515/crates/gateway/tests/routing_test.rs#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why not "INVOKE_FUNCTION"?
This should be the expected type.
</blockquote></details>

Just a dummy value for now, until we implement `add_transaction` properly, it will be deleted very soon.
___
*[`crates/gateway/tests/routing_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus2PiD8_yaqIYm7p5F:-NusyRgwAdQic_CwzBe6:b-ph4f0b) ([raw file](https://github.com/starkware-libs/mempool/blob/2499b1bc79c913218857e14156f3d5a080c9e515/crates/gateway/tests/routing_test.rs#L22)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you explain why you added this header?
</blockquote></details>

Looks like axum needs this explicitly in order to accept the JSON payload of the POST request.

Without this, the server hits 415, which means that it is refusing the request, probably being pedantic and not wanting to assume the string payload is a JSON without being told.


<!-- Sent from Reviewable.io -->

2024-04-07 14:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/28)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/28#-Nus2sxT1bhtY2d38hAQ:-NuszOYn0XsKI2dCOnAH:b-d1h49o) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Nice!

1. Why these tests are not part of `gateway_test`?
2. Are you planning to remove the identical test from `gateway_test`?
</blockquote></details>

1. Cause it's an [integration test](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html#integration-testing) of sorts. Tests in `tests/` directory are compiled in separate crates, which simulates how our users will interact with our API.
2. Nope, the `add_transaction` test in gateway_test will evolve into a real (probably multiple) tests that test add_transaction functionality; and the routing test here will evolve into a very basic e2e test, that just sends a tx and checks that it was processed via add_transaction. Maybe once we have a proper flow test it will be removed, but for now its a sanity check that our gateway actually works.

___


<!-- Sent from Reviewable.io -->

2024-04-10 08:00 UTC, giladchase reviewed
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-04-10 08:00 UTC, merged