Implement API Gateway skeleton and unit tests
starkware-libs/mempool pull request #3
Opened 2024-03-14 09:13 UTC by ayeletstarkware

2024-03-14 09:33 UTC, ArniStarkware requested changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswGpZa-5nFtk_F2kKz:-NswGpZa-5nFtk_F2kL-:bx1f3tz) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L31)):*
> ```XML
>         let make_svc = make_service_fn(|_conn| async {
>             Ok::<_, Infallible>(service_fn(Self::handle_request))
>         });
> ```

is svc an abbriviation?
I suggest we avoid those unless it is super clear. Otherwise document?



_Code quote:_
```XML
        let make_svc = make_service_fn(|_conn| async {
            Ok::<_, Infallible>(service_fn(Self::handle_request))
        });
```
___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswHL-UB3ERwEqV9h6G:-NswHL-UB3ERwEqV9h6H:b3kpken) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L36)):*
> ```XML
>             .serve(make_svc)
>             .await
>             .map_err(|_| GatewayError::ServerError);
> ```

Does this work?

Is the return value interesting in any way?



_Suggestion:_
```XML
        Server::bind(&addr)
            .serve(make_svc)
            .await
            .map_err(|_| GatewayError::ServerError);
```
___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NswI_THAXvihJLJhF7e:b-34t9eg) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
> ```XML
>         };
>         response
>     }
> ```

What am I missing? How come this method has no `self`?



_Code quote:_
```XML
    async fn handle_request(request: Request<Body>) -> Result<Response<Body>, GatewayError> {
        let (parts, _body) = request.into_parts();
        let response = match (parts.method, parts.uri.path()) {
            (Method::GET, "/is_alive") => is_alive(),
            _ => Ok(Response::builder()
                .status(404)
                .body(Body::from(NOT_FOUND_RESPONSE))
                .map_err(|_| GatewayError::InternalServerError)?),
        };
        response
    }
```
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswIlC97lnW4_n1nJWS:-NswIlC97lnW4_n1nJWT:b-34t9eg) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L59)):*
> ```XML
>         .body(Body::from("Server is alive"))
>         .map_err(|_| GatewayError::InternalServerError)
> }
> ```

What am I missing? How come this method has no `self`?



_Code quote:_
```XML
fn is_alive() -> Result<Response<Body>, GatewayError> {
    Response::builder()
        .status(200)
        .body(Body::from("Server is alive"))
        .map_err(|_| GatewayError::InternalServerError)
}
```


<!-- Sent from Reviewable.io -->

2024-03-14 09:46 UTC, ArniStarkware commented
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswIlC97lnW4_n1nJWS:-NswLHQt893jQrK2taxc:bmfvm18) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What am I missing? How come this method has no `self`?
</blockquote></details>

This method will always succeed, as it does not actually query an instance of the gateway to see if it is alive.
Either explain that and add a Todo or make it into a method.


<!-- Sent from Reviewable.io -->

2024-03-19 08:55 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswHL-UB3ERwEqV9h6G:-NtBtaCkBkc6-f5DysuG:b-hp0ucw) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this work?

Is the return value interesting in any way?
</blockquote></details>

When trying your solution I get "unused `std::result::Result` that must be used"
Tried another solution. Is it better now?
___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtBtuTT7pGSep480ez9:b-9bqa1p) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What am I missing? How come this method has no `self`?
</blockquote></details>

I think we'll need to use `self` when using the gateway's configurations to set up the server. The decision to place `handle_request` under `impl gateway` is worth reconsidering. What do you think?


<!-- Sent from Reviewable.io -->

2024-03-19 09:48 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswHL-UB3ERwEqV9h6G:-NtL5Zr-79VJ09C32H2w:b-vw6nmh) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

When trying your solution I get "unused `std::result::Result` that must be used"
Tried another solution. Is it better now?
</blockquote></details>

Ok - another connected issue. Is the error being raised here? I think it is not.

Maybe this one (with the question mark - it also alters the behavior hopefully for the better.)?
In any case, your original solution is better, other than the fact that the error is not raised.

```
        Server::bind(&addr)
            .serve(make_svc)
            .await
            .map_err(|_| GatewayError::ServerError)?;
```



<!-- Sent from Reviewable.io -->

2024-03-19 10:11 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 5 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, @elintul, and @staticmethod)

___
*[`crates/gateway/Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtGeCkL4Fr-nI48LNZT:-NtGeCkL4Fr-nI48LNZU:bcep0fm) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/Cargo.toml#L5)):*
> ```TOML
> version = "0.1.0"
> edition = "2021"
> ```

if we have a main cargo.toml now move these there
___
*[`crates/gateway/src/gateway.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtL9WNW1GzYh-LYOqLE:-NtL9WNW1GzYh-LYOqLF:b-489v5v) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L3)):*
> ```XML
> use crate::errors::GatewayError;
> use hyper::service::{make_service_fn, service_fn};
> use hyper::{Body, Method, Request, Response, Server};
> ```

Have you considered using `axum` instead of `hyper` for this?
They seem to be working on top of `hyper` and incur less boilerplate (see their usage in papyrus for example). 



_Code quote:_
```XML
use hyper::service::{make_service_fn, service_fn};
use hyper::{Body, Method, Request, Response, Server};
```
___
*[`crates/gateway/src/gateway.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKu27a7Dz6xxbb1oAO:-NtKu27a7Dz6xxbb1oAP:b-s8qqg4) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L14)):*
> ```XML
> 
> pub struct GatewayConfig {
>     pub config: String,
> ```

You meant for this to be some dummy value?

For dummy values you use ZSTs (zero sized struct, that is `struct GatewayConfig;`.
Moreover, for non-test code we probably shouldn't add components that don't have immediate use (google YAGNI).

This isn't the case here however, because we can already add some things here that are relevant in your code, like server address (see comments below).



_Code quote:_
```XML
    pub config: String,
```
___
*[`crates/gateway/src/gateway.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKtG-1ExEMVneTSEaK:-NtKtG-1ExEMVneTSEaL:bjjle0p) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L15)):*
> ```XML
> pub struct GatewayConfig {
>     pub config: String,
> }
> ```

Could you move this section further down in the file plz? 

Order of items in a file should be by importance, so configX should be below X stuff.



_Code quote:_
```XML
pub struct GatewayConfig {
    pub config: String,
}
```
___
*[`crates/gateway/src/gateway.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKuc89AEwJwgh8oAy5:-NtKuc89AEwJwgh8oAy6:b-93oish) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L24)):*
> ```XML
>     pub fn new(gateway_config: GatewayConfig) -> Self {
>         Self { gateway_config }
>     }
> ```

`new` constructor is typically intended for situations where the struct's public constructor isn't available (when there are private fields).
This is true for constructors in general, they should only be present if there is some custom construction logic.
___
*[`crates/gateway/src/gateway.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKy1_z3yzvc0dCrXqF:-NtKy1_z3yzvc0dCrXqG:b-50ywjp) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L26)):*
> ```XML
>     }
> 
>     pub async fn build_server(&self) -> Result<(), GatewayError> {
> ```

Add `GatewayResult`



_Code quote:_
```XML
Result<(), GatewayError>
```
___
*[`crates/gateway/src/gateway.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKwp8Q14NQFI2sVVJF:-NtKwp8RAWoj5qD-q7qg:b-zdsqpu) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L27)):*
> ```XML
> 
>     pub async fn build_server(&self) -> Result<(), GatewayError> {
>         let addr = SocketAddr::from(([127, 0, 0, 1], 8080));
> ```

This should take the address from the config.

This might be a good value for a mock though, when we end up writing one, but even then we might opt for 0.0.0.0 instead of 127.0.0.1 (lookup the difference between the two)



_Code quote:_
```XML
     let addr = SocketAddr::from(([127, 0, 0, 1], 8080));
```
___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtLATbC7oEYAzicK8Zo:bnsxake) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
>What am I missing? How come this method has no `self`?

Associated method (like a @staticmethod).

This is less common in rust, free functions are preferred over associated functions unless the function references `Self` in some way (usually constructors or using associated consts).
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswIlC97lnW4_n1nJWS:-NtLAwcn5bXkxTmoP-Xo:buesfwu) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This method will always succeed, as it does not actually query an instance of the gateway to see if it is alive.
Either explain that and add a Todo or make it into a method.
</blockquote></details>

Yep.
Better put `unimplemented!()` if you can't implement it fully just yet.
Rationale: this looks like a bug for readers, also users might waste time going over this code without realizing it's a placeholder.


<!-- Sent from Reviewable.io -->

2024-03-19 10:20 UTC, ArniStarkware commented
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtLCxEL4y1_pQKsO3iU:b-hcaz) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>What am I missing? How come this method has no `self`?

Associated method (like a @staticmethod).

This is less common in rust, free functions are preferred over associated functions unless the function references `Self` in some way (usually constructors or using associated consts).
</blockquote></details>

My question is about the logic. The method `handle_request` should know what request it is handling *and* who is handling it (I assumed `self`).


<!-- Sent from Reviewable.io -->

2024-03-19 13:11 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @staticmethod)

___
*[`crates/gateway/Cargo.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtGeCkL4Fr-nI48LNZT:-NtLpJ8m3KofUWvvnLeC:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/Cargo.toml#L5)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

if we have a main cargo.toml now move these there
</blockquote></details>

Done.
___
*[`crates/gateway/src/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NsxYjo5-Snj-Z_L9urr:-NtLXYTz1ntuaSgeDlOu:biwjx4x) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/errors.rs#L9)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Is there a way to add a test that will cause these Errors to be raised?
</blockquote></details>

  
`InternalServerError` is checked in `test_invalid_request`. I haven't tested `ServerError` because, so far, `is_alive` has never failed.
___
*[`crates/gateway/src/gateway.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtL9WNW1GzYh-LYOqLE:-NtLpKuS9AVMPddjJYOv:b-nkfdtq) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Have you considered using `axum` instead of `hyper` for this?
They seem to be working on top of `hyper` and incur less boilerplate (see their usage in papyrus for example).
</blockquote></details>

Will consider it in a different PR.
___
*[`crates/gateway/src/gateway.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKu27a7Dz6xxbb1oAO:-NtLU3GM9su-X3X0qSN7:b-ucfknh) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You meant for this to be some dummy value?

For dummy values you use ZSTs (zero sized struct, that is `struct GatewayConfig;`.
Moreover, for non-test code we probably shouldn't add components that don't have immediate use (google YAGNI).

This isn't the case here however, because we can already add some things here that are relevant in your code, like server address (see comments below).
</blockquote></details>

Thanks!
___
*[`crates/gateway/src/gateway.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKtG-1ExEMVneTSEaK:-NtLRude6gUIrYkj1mod:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L15)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Could you move this section further down in the file plz? 

Order of items in a file should be by importance, so configX should be below X stuff.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKuc89AEwJwgh8oAy5:-NtLRmc-AVWo2Fj0nR_P:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`new` constructor is typically intended for situations where the struct's public constructor isn't available (when there are private fields).
This is true for constructors in general, they should only be present if there is some custom construction logic.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKy1_z3yzvc0dCrXqF:-NtLPdGc4c5AwLaTOnm-:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add `GatewayResult`
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtKwp8Q14NQFI2sVVJF:-NtLROZ84ybyeZg56gQp:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This should take the address from the config.

This might be a good value for a mock though, when we end up writing one, but even then we might opt for 0.0.0.0 instead of 127.0.0.1 (lookup the difference between the two)
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswHL-UB3ERwEqV9h6G:-NtLOhXBBsw_v1F6ypn3:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L36)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Ok - another connected issue. Is the error being raised here? I think it is not.

Maybe this one (with the question mark - it also alters the behavior hopefully for the better.)?
In any case, your original solution is better, other than the fact that the error is not raised.

```
        Server::bind(&addr)
            .serve(make_svc)
            .await
            .map_err(|_| GatewayError::ServerError)?;
```

</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtLWbfhB95eiHo9Es0a:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

My question is about the logic. The method `handle_request` should know what request it is handling *and* who is handling it (I assumed `self`).
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswIlC97lnW4_n1nJWS:-NtLO6Hs6qen61FtaaDH:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep.
Better put `unimplemented!()` if you can't implement it fully just yet.
Rationale: this looks like a bug for readers, also users might waste time going over this code without realizing it's a placeholder.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-19 13:50 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @elintul, @giladchase, and @staticmethod)

___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtLy0CdEOQ6wryyEMYp:b-d8rlf0) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please give this function the same treatment `is_alive()` is getting. (With the same rational @giladchase mentioned). 


<!-- Sent from Reviewable.io -->

2024-03-19 15:36 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @staticmethod)

___
*[`crates/gateway/src/gateway.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswI_THAXvihJLJhF7d:-NtMLrao22V0Y8t3r-CP:b-xac9ud) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L51)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please give this function the same treatment `is_alive()` is getting. (With the same rational @giladchase mentioned).
</blockquote></details>

Done. Reference:
https://github.com/microsoft/vscode/blob/9a2716e2fbb7e00f983d4e2fe35af9cd2bfc37f3/cli/src/commands/serve_web.rs#L16


<!-- Sent from Reviewable.io -->

2024-03-19 16:42 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtM_mpZCITqji5HKMmf:-NtM_mpZCITqji5HKMmg:b-ctgqmq) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L43)):*
> ```XML
> 
> #[derive(Clone)]
> struct HandleContext {}
> ```

Please document.
`Holds the routing info to...` 



_Code quote:_
```XML
#[derive(Clone)]
struct HandleContext {}
```


<!-- Sent from Reviewable.io -->

2024-03-20 08:53 UTC, giladchase requested changes
> Reviewed 1 of 5 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`Cargo.toml` line 14 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxU1y51VXb9JdluAa:-NtPxU1y51VXb9JdluAb:b-vxqqm4) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/Cargo.toml#L14)):*
> ```TOML
> [workspace.dependencies]
> hyper = "0.13.9"
> tokio = { version = "0.2", features = ["full"] }
> ```

What does this give us?



_Code quote:_
```TOML
 features = ["full"] 
```
___
*[`crates/gateway/Cargo.toml` line 12 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPvaioAD6ns6JMK-xx:-NtPvaioAD6ns6JMK-xy:b-eurkta) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/Cargo.toml#L12)):*
> ```TOML
> 
> [lib]
> name = "gateway_lib"
> ```

What does this do?



_Code quote:_
```TOML
[lib]
name = "gateway_lib"
```
___
*[`crates/gateway/src/gateway.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/mempool/3#-NswIlC97lnW4_n1nJWS:-NtPy2lR6H-maX_8558g:bdpitq0) ([raw file](https://github.com/starkware-libs/mempool/blob/39ac4d7f49343ccfad9d0a5da2bf473309fe2da0/crates/gateway/src/gateway.rs#L59)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant unimplemented! as the entire function, adding it as dead code is somewhat confusing :sweat_smile: 
Either that or what Arni said, add a todo (without the if true thing)
___
*[`crates/gateway/src/gateway.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPzPMqEJ-YTw3WopcE:-NtPzPMr4JYoa2yFFli0:bkq83um) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L22)):*
> ```XML
>     pub async fn build_server(&self) -> GatewayResult {
>         let addr = SocketAddr::from_str(&self.gateway_config.bind_address)
>             .map_err(|_| GatewayError::ServerError)?;
> ```

1. Try making this one fail :)
The trace will say:
```
called `Result::unwrap()` on an `Err` value: ServerError
```
Which is somewhat hard to debug.

There's a missing abstraction.

Add GatewayConfigError thiserror enum with 
```rust
    #[error("Server address is not an IP address: {0}")]
    InvalidServerAddress(String),
```

then add to GatewayError:
```rust
#[transparent]
ConfigError(#[from] GatewayConfigError)
```

finally make the line into
```rust
        let addr = SocketAddr::from_str(&self.gateway_config.bind_address).or_else(|_| {
            GatewayConfigError::InvalidServerAddress(self.gateway_config.bind_address.clone())
        })?;
```
where the `?` will implicitly cast the GatewayConfigError `into` GatewayError.

2. Revisit the other `.map_err(|_| GatewayError::ServerError)?;` and do the same process: make them fail (for sanity), then improve the error message into something that'll give the person debugging this in production the  relevant information to fix the bug.



_Code quote:_
```XML
        let addr = SocketAddr::from_str(&self.gateway_config.bind_address)
            .map_err(|_| GatewayError::ServerError)?;
```
___
*[`crates/gateway/src/gateway.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxg6w7Vfc_Xik46Fz:-NtPxg6w7Vfc_Xik46G-:b-mcspd8) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L67)):*
> ```XML
>             .status(200)
>             .body(Body::from("Server is alive"))
>             .map_err(|_| GatewayError::InternalServerError);
> ```

Lets encapsulate this in a some function, will make it easier to move to switch from hyper if we decide to do so.



_Code quote:_
```XML
        return Response::builder()
            .status(200)
            .body(Body::from("Server is alive"))
            .map_err(|_| GatewayError::InternalServerError);
```


<!-- Sent from Reviewable.io -->

2024-03-20 14:04 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 14 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxU1y51VXb9JdluAa:-NtQ9xtC1Fk_aELOgxBu:bcne7sd) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/Cargo.toml#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What does this give us?
</blockquote></details>

It enables all Tokio features, following the usage pattern found in the Microsoft repository.
___
*[`crates/gateway/Cargo.toml` line 12 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPvaioAD6ns6JMK-xx:-NtQCaCA-_b1N1cLnhRg:b4pkl4) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/Cargo.toml#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

Apparently nothing
___
*[`crates/gateway/src/gateway.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPzPMqEJ-YTw3WopcE:-NtQtZHG-h2VtAHN-ZOK:b-78hdjp) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

1. Try making this one fail :)
The trace will say:
```
called `Result::unwrap()` on an `Err` value: ServerError
```
Which is somewhat hard to debug.

There's a missing abstraction.

Add GatewayConfigError thiserror enum with 
```rust
    #[error("Server address is not an IP address: {0}")]
    InvalidServerAddress(String),
```

then add to GatewayError:
```rust
#[transparent]
ConfigError(#[from] GatewayConfigError)
```

finally make the line into
```rust
        let addr = SocketAddr::from_str(&self.gateway_config.bind_address).or_else(|_| {
            GatewayConfigError::InvalidServerAddress(self.gateway_config.bind_address.clone())
        })?;
```
where the `?` will implicitly cast the GatewayConfigError `into` GatewayError.

2. Revisit the other `.map_err(|_| GatewayError::ServerError)?;` and do the same process: make them fail (for sanity), then improve the error message into something that'll give the person debugging this in production the  relevant information to fix the bug.
</blockquote></details>

1 - I get the following error when using `or_else`, so I used map_err



_Code snippet:_
```XML
using `Result.or_else(|x| Err(y))`, which is more succinctly expressed as `map_err(|x| y)`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bind_instead_of_map
`#[warn(clippy::bind_instead_of_map)]` on by defaultclippyClick for full compiler diagnostic
gateway.rs(28, 20): try: `SocketAddr::from_str(&self.gateway_config.bind_address).map_err(|_| GatewayError::ConfigError(GatewayConfigError::InvalidServerBindAddress(self.gateway_config.bind_address.clone())))`
```
___
*[`crates/gateway/src/gateway.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtM_mpZCITqji5HKMmf:-NtQhUfsDzZfmllcQzoS:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L43)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please document.
`Holds the routing info to...`
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxg6w7Vfc_Xik46Fz:-NtQp9418P4xH-H1wo2l:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L67)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets encapsulate this in a some function, will make it easier to move to switch from hyper if we decide to do so.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 07:51 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`Cargo.toml` line 14 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxU1y51VXb9JdluAa:-NtUwU5CAAgwjdDLWJHH:b-ig7cs7) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/Cargo.toml#L14)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

It enables all Tokio features, following the usage pattern found in the Microsoft repository.
</blockquote></details>

I'd rather be incremental if possible.
VSCode probably uses many features which we (for now) don't need, let's remove `all` if possible and reintroduce on demand.
___
*[`crates/gateway/Cargo.toml` line 12 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPvaioAD6ns6JMK-xx:-NtUwl5S04sLXsWpXzgx:b32vhw) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/Cargo.toml#L12)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Apparently nothing
</blockquote></details>

:)
___
*[`crates/gateway/src/gateway.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPzPMqEJ-YTw3WopcE:-NtUxIWf81EGQBYxhu-6:b5hb75a) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L22)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

1 - I get the following error when using `or_else`, so I used map_err
</blockquote></details>

Ya yr right, but you can remove the `GatewayError::ConfigError()` part, only `GatewayConfigerror::InvalidServerBindAddress` is needed.
Ping me if you want me to explain why that works.
___
*[`crates/gateway/src/gateway.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtUybGh4V2Y9adw5x8t:-NtUybGh4V2Y9adw5x8u:b-fkio30) ([raw file](https://github.com/starkware-libs/mempool/blob/465fd778fe521f9bc6583e8b515d96d04988579b/crates/gateway/src/gateway.rs#L73)):*
> ```XML
> }
> 
> fn build_generic_response(
> ```

Succinctness



_Suggestion:_
```XML
fn response(
```
___
*[`crates/gateway/src/gateway.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtUynd07vvs5YxVg1u4:-NtUynd1-DpLHZ68JrBO:bb6h01h) ([raw file](https://github.com/starkware-libs/mempool/blob/465fd778fe521f9bc6583e8b515d96d04988579b/crates/gateway/src/gateway.rs#L81)):*
> ```XML
>         .status(status)
>         .body(Body::from(body_content))
>         .map_err(|_| error)
> ```

Add to GatewayError
```rust
#[error(transparent)]
HTTPError(#[from] hyper::http::Error)
```
GatewayError needs to know about all errors coming from this interface



_Suggestion:_
```XML
    Ok(Response::builder()
        .status(status)
        .body(Body::from(body_content))?)
```


<!-- Sent from Reviewable.io -->

2024-03-21 11:59 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 14 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPxU1y51VXb9JdluAa:-NtVsFdOANb80Tnaw6Us:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/Cargo.toml#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'd rather be incremental if possible.
VSCode probably uses many features which we (for now) don't need, let's remove `all` if possible and reintroduce on demand.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtPzPMqEJ-YTw3WopcE:-NtVrPRY7lS4jucd2Agg:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/236945fd67caa1b53d7f500baf389a3ff9a15ac8/crates/gateway/src/gateway.rs#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya yr right, but you can remove the `GatewayError::ConfigError()` part, only `GatewayConfigerror::InvalidServerBindAddress` is needed.
Ping me if you want me to explain why that works.
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtUybGh4V2Y9adw5x8t:-NtVpykj5VpDkfo7TNKa:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/465fd778fe521f9bc6583e8b515d96d04988579b/crates/gateway/src/gateway.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Succinctness
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway.rs` line 81 at r5](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtUynd07vvs5YxVg1u4:-NtVqbmyDbKSd42suzgM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/465fd778fe521f9bc6583e8b515d96d04988579b/crates/gateway/src/gateway.rs#L81)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add to GatewayError
```rust
#[error(transparent)]
HTTPError(#[from] hyper::http::Error)
```
GatewayError needs to know about all errors coming from this interface
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-24 09:21 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`crates/gateway/src/errors.rs` line 12 at r6](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntjkozk7U7T9gAiSHzH:-Ntjkozk7U7T9gAiSHzI:buzc58k) ([raw file](https://github.com/starkware-libs/mempool/blob/b66023d665e57e68bf1c6c84d4814780a5d4007f/crates/gateway/src/errors.rs#L12)):*
> ```XML
>     InternalServerError,
>     #[error("Invalid transaction format")]
>     InvalidTransactionFormat,
> ```

unused?



_Code quote:_
```XML
    #[error("Invalid transaction format")]
    InvalidTransactionFormat,
```
___
*[`crates/gateway/src/gateway.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtjktE05rMbO-MpvLhZ:-NtjktE05rMbO-MpvLh_:b-4qq8ij) ([raw file](https://github.com/starkware-libs/mempool/blob/b66023d665e57e68bf1c6c84d4814780a5d4007f/crates/gateway/src/gateway.rs#L35)):*
> ```XML
>             .serve(make_service)
>             .await
>             .map_err(|_| GatewayError::ServerStartError)?;
> ```

and add a `from` in the error enum



_Suggestion:_
```XML
        Server::bind(&addr)
            .serve(make_service)
            .await?;
```


<!-- Sent from Reviewable.io -->

2024-03-25 09:37 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/errors.rs` line 12 at r6](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntjkozk7U7T9gAiSHzH:-NtoteJg0UCk2E6Lb-r9:b31ql8m) ([raw file](https://github.com/starkware-libs/mempool/blob/b66023d665e57e68bf1c6c84d4814780a5d4007f/crates/gateway/src/errors.rs#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

unused?
</blockquote></details>

unused in this PR. will be added again in the next one. 
___
*[`crates/gateway/src/gateway.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/mempool/3#-NtjktE05rMbO-MpvLhZ:-Ntoxy6H710c3vIsMkz9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b66023d665e57e68bf1c6c84d4814780a5d4007f/crates/gateway/src/gateway.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

and add a `from` in the error enum
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 09:41 UTC, ArniStarkware approved these changes
> Reviewed 2 of 5 files at r5, 2 of 3 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-03-25 14:59 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway.rs` line 44 at r7](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntq67Yb0hAPAa8e6RLJ:-Ntq67Yb0hAPAa8e6RLK:b-hbbfhn) ([raw file](https://github.com/starkware-libs/mempool/blob/eed3f44c8dbecfa891adf06d880e0951aecf055c/crates/gateway/src/gateway.rs#L44)):*
> ```XML
> /// Stores routing information for request's handling.
> #[derive(Clone)]
> struct HandleContext {}
> ```

Non-blocking.

Sorry for being inconsistent.


Now that we simply set `is_alive` as `unimplemented!`, there is no need for this struct.
Let us delete it for now, and add it when the need arises.
___
*[`crates/gateway/src/gateway.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntq6gX-E8omKVW1_iaw:-Ntq6gX-E8omKVW1_iax:bo1rmk6) ([raw file](https://github.com/starkware-libs/mempool/blob/eed3f44c8dbecfa891adf06d880e0951aecf055c/crates/gateway/src/gateway.rs#L59)):*
> ```XML
> 
> // This function hasn't been implemented yet. It might need a HandleContext parameter to verify if
> // the server is alive.
> ```

Non-blocking.

Delete this comment if the `HandleContext` parameter is removed.


<!-- Sent from Reviewable.io -->

2024-03-27 07:12 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r5, 1 of 3 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3#-:-NtykDDB9WTAZ3f21L95:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`Cargo.toml` line 28 at r8](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntyil032HgnI5dk_4md:-Ntyil032HgnI5dk_4me:b72whyg) ([raw file](https://github.com/starkware-libs/mempool/blob/7643196d59c247577701061b62c767032d942eb6/Cargo.toml#L28)):*
> ```TOML
> serde = { version = "1.0.193", features = ["derive"] }
> serde_json = "1.0"
> assert_matches = "1.5.0"
> ```

alph., also in the crate's cargo.toml



_Code quote:_
```TOML
hyper = "0.13.9"
tokio = { version = "0.2", features = ["macros"] }
thiserror = "1.0"
starknet_api = "0.8.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
assert_matches = "1.5.0"
```
___
*[`crates/gateway/src/gateway.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntyjqu8CPGECysg4p0f:-Ntyjqu8CPGECysg4p0g:b-g08yw4) ([raw file](https://github.com/starkware-libs/mempool/blob/7643196d59c247577701061b62c767032d942eb6/crates/gateway/src/gateway.rs#L44)):*
> ```XML
>     let response = match (parts.method, parts.uri.path()) {
>         (Method::GET, "/is_alive") => is_alive(),
>         _ => response(StatusCode::NOT_FOUND, NOT_FOUND_RESPONSE.to_string()),
> ```

minor could we have used `StatusCode::NOT_FOUND` instead of our own stringy version?
Not critical for now though, we might be moving to axum anyway...



_Code quote:_
```XML
        _ => response(StatusCode::NOT_FOUND, NOT_FOUND_RESPONSE.to_string()),
```


<!-- Sent from Reviewable.io -->

2024-03-27 08:14 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`Cargo.toml` line 28 at r8](https://reviewable.io/reviews/starkware-libs/mempool/3#-Ntyil032HgnI5dk_4md:-NtyyB7E4mcls5kf1s_w:b-5qdfm8) ([raw file](https://github.com/starkware-libs/mempool/blob/7643196d59c247577701061b62c767032d942eb6/Cargo.toml#L28)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

alph., also in the crate's cargo.toml
</blockquote></details>

Done in the next PR.


<!-- Sent from Reviewable.io -->

2024-03-27 08:14 UTC, merged