feat: skip validation of an invoke transaction after deploy account
starkware-libs/mempool pull request #345
Opened 2024-07-02 13:07 UTC by Yael-Starkware

2024-07-03 14:57 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0t5HfvEi4J74yPKCsP:-O0t5HfvEi4J74yPKCsQ:b-z68m7z) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/Cargo.toml#L39)):*
> ```TOML
> # TODO(YaelD, 28/5/2024): The special Blockifier version is needed in order to be aligned with the
> # starknet-api version. This should be removed once we have a mono-repo.
> blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "3511cd37" }
> ```

Do not merge until the blockifier commit is pushed to main-mempool!
also revert this change!


<!-- Sent from Reviewable.io -->

2024-07-03 15:00 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @dafnamatsry)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0t5HfvEi4J74yPKCsP:-O0t67ukAbOfjsW0rQxS:b-bau4ju) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/Cargo.toml#L39)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Do not merge until the blockifier commit is pushed to main-mempool!
also revert this change!
</blockquote></details>

The PR that should be merge before this one: https://reviewable.io/reviews/starkware-libs/blockifier/2034#-


<!-- Sent from Reviewable.io -->

2024-07-04 09:54 UTC, ArniStarkware requested changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wvX0TE1XjT15_Uvk2:-O0wvX0TE1XjT15_Uvk3:beu3728) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator.rs#L72)):*
> ```XML
>             self.config.max_nonce_for_validation_skip,
>         )?;
>         println!("skip_validate: {:?}", skip_validate);
> ```

Delete, please.



_Code quote:_
```XML
        println!("skip_validate: {:?}", skip_validate);
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wx-uj2nQlD5uLMgkC:-O0wx-uj2nQlD5uLMgkD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L103)):*
> ```XML
>     external_invoke_tx(invoke_tx_args!{nonce: Nonce(StarkFelt::TWO)}),
>     false
> )]
> ```





_Suggestion:_
```XML
#[case::should_not_skip_validation_nonce_over_max_nonce_for_skip(
    external_invoke_tx(invoke_tx_args!{nonce: Nonce(StarkFelt::TWO)}),
    false
)]
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wxALmD9RS4XOyYatH:-O0wxALmD9RS4XOyYatI:b-ikeqs4) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L104)):*
> ```XML
>     false
> )]
> #[case::should_not_skip_validation_deploy_account(deploy_account_tx(), false)]
> ```

What do you think?



_Suggestion:_
```XML
#[case::should_not_skip_validation_non_invoke(deploy_account_tx(), false)]
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wz1DxEqM2B07Y56ZH:-O0wz1DxEqM2B07Y56ZI:b-5q8nxu) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L129)):*
> ```XML
>         assert!(result.is_ok());
>     } else {
>         assert!(result.is_err());
> ```

Do we want to make sure the error is as expected?
Is there an error dedicated to skip validation?



_Code quote:_
```XML
        assert!(result.is_err());
```


<!-- Sent from Reviewable.io -->

2024-07-04 12:56 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wvX0TE1XjT15_Uvk2:-O0x_0Ct1NKqt5FafKX9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator.rs#L72)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Delete, please.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wx-uj2nQlD5uLMgkC:-O0x_9vR3LEaiA2JCHZs:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L103)):*
> ```XML
>     external_invoke_tx(invoke_tx_args!{nonce: Nonce(StarkFelt::TWO)}),
>     false
> )]
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wxALmD9RS4XOyYatH:-O0x_BJ43rpvK1bEBHQQ:bi06l9c) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L104)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What do you think?
</blockquote></details>

yes done
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wz1DxEqM2B07Y56ZH:-O0xIRTQBil1lJMQL0oY:brcbioe) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L129)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we want to make sure the error is as expected?
Is there an error dedicated to skip validation?
</blockquote></details>

skip_validate doesn't return an error, since validations are skipped it returns ok at (almost) all times.

The exact error returned from the blockifier is very complex and I'm not Sure we want to get into the implementation details of the blockifier, but I did  add a check for the general type.
wdyt??


<!-- Sent from Reviewable.io -->

2024-07-04 13:13 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0wz1DxEqM2B07Y56ZH:-O0xrxbGAc6lHDELcggs:b8eau52) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/crates/gateway/src/stateful_transaction_validator_test.rs#L129)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

skip_validate doesn't return an error, since validations are skipped it returns ok at (almost) all times.

The exact error returned from the blockifier is very complex and I'm not Sure we want to get into the implementation details of the blockifier, but I did  add a check for the general type.
wdyt??
</blockquote></details>

I like it.


<!-- Sent from Reviewable.io -->

2024-07-04 13:34 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0t5HfvEi4J74yPKCsP:-O0xx32B0twOsJV3I0DL:b-7rl0kd) ([raw file](https://github.com/starkware-libs/mempool/blob/4ea220effe3d26072cce31966d0a678df9434bd4/Cargo.toml#L39)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The PR that should be merge before this one: https://reviewable.io/reviews/starkware-libs/blockifier/2034#-
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-07-04 14:10 UTC, dafnamatsry requested changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0xReNM2BACUZByPRIP:-O0xReNM2BACUZByPRIQ:bubrwb9) ([raw file](https://github.com/starkware-libs/mempool/blob/d9b06e38ad7acb46c4437ae17a4f741aecd987be/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
> ```XML
>             state,
>             block_context,
>             self.config.max_nonce_for_validation_skip,
> ```

Do we need to keep this config? Is it ever going to be not 1?



_Code quote:_
```XML
self.config.max_nonce_for_validation_skip,
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0y45aeAspXQvrwgY69:-O0y45aeAspXQvrwgY6A:bougtp9) ([raw file](https://github.com/starkware-libs/mempool/blob/3dcdf26e6d974cb52a29fe70a098486fd7c2d611/crates/gateway/src/stateful_transaction_validator.rs#L85)):*
> ```XML
>     max_nonce_for_validation_skip: Nonce,
> ) -> StatefulTransactionValidatorResult<bool> {
>     if let RPCTransaction::Invoke(RPCInvokeTransaction::V3(tx)) = tx {
> ```

Consider using match case here:

```
match tx {
    Declare | Deploy => false,
    Invoke(V3(tx)) => { ... }
}
```
This way we make sure future invoke versions won't fall under the false case.


<!-- Sent from Reviewable.io -->

2024-07-07 06:51 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0xReNM2BACUZByPRIP:-O1AtoAO5aISLd0tz7I7:b7dyo8v) ([raw file](https://github.com/starkware-libs/mempool/blob/d9b06e38ad7acb46c4437ae17a4f741aecd987be/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we need to keep this config? Is it ever going to be not 1?
</blockquote></details>

I don't think it will ever be not 1, but still didn't want to close the option , you think we should delete it completely?
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0y45aeAspXQvrwgY69:-O1AxaCK0hIXXY8xjv4g:bn76tmh) ([raw file](https://github.com/starkware-libs/mempool/blob/3dcdf26e6d974cb52a29fe70a098486fd7c2d611/crates/gateway/src/stateful_transaction_validator.rs#L85)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider using match case here:

```
match tx {
    Declare | Deploy => false,
    Invoke(V3(tx)) => { ... }
}
```
This way we make sure future invoke versions won't fall under the false case.
</blockquote></details>

done.
it is a bit longer now.


<!-- Sent from Reviewable.io -->

2024-07-07 06:53 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1Axlf_4U8RP2OSZMEF):*
branch needs to be rebase the it can't work due to sync issues between blockifier and papyrus, waiting for a fix from Papyrus


<!-- Sent from Reviewable.io -->

2024-07-07 08:27 UTC, dafnamatsry requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 3 of 5 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/345#-O0xReNM2BACUZByPRIP:-O1B0OCbCfiz0L6vFhJd:bd6s9va) ([raw file](https://github.com/starkware-libs/mempool/blob/d9b06e38ad7acb46c4437ae17a4f741aecd987be/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I don't think it will ever be not 1, but still didn't want to close the option , you think we should delete it completely?
</blockquote></details>

Ok, let's keep it.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BGlFAA64FUG37fDOT:-O1BGlFAA64FUG37fDOU:b-z3ru2g) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L39)):*
> ```XML
>         // StatefulTransactionValidator and update it only once a new block is created.
>         let latest_block_info = get_latest_block_info(state_reader_factory)?;
>         let prev_block_number = latest_block_info.block_number;
> ```

I think `latest` is more accurate.



_Code quote:_
```XML
prev_block_number
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BGIkzEuZyOCuxLJ5C:-O1BGIkzEuZyOCuxLJ5D:b-q0081w) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L71)):*
> ```XML
>         let skip_validate = skip_stateful_validations(
>             external_tx,
>             &state_reader_factory.get_state_reader(prev_block_number),
> ```

Just pass the account nonce using `validator.get_nonce(tx.sender_address)`



_Code quote:_
```XML
&state_reader_factory.get_state_reader(prev_block_number)
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B-YvF0EdfRLbF0vWl:-O1B-YvF0EdfRLbF0vWm:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L100)):*
> ```XML
>             } else {
>                 Ok(false)
>             }
> ```





_Suggestion:_
```XML
            Ok(tx.nonce >= Nonce(StarkFelt::ONE)
                && tx.nonce <= max_nonce_for_validation_skip
                && account_nonce == Nonce(StarkFelt::ZERO))
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B-KhD2Mw1fny_fR7O:-O1B-KhD2Mw1fny_fR7P:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L103)):*
> ```XML
>         }
>         RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(_))
>         | RPCTransaction::Declare(RPCDeclareTransaction::V3(_)) => Ok(false),
> ```





_Suggestion:_
```XML
        RPCTransaction::DeployAccount(_)
        | RPCTransaction::Declare(_) => Ok(false),
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BI0v5CzDS7S-OJ7jA:-O1BI0v5CzDS7S-OJ7jB:b-815m13) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L96)):*
> ```XML
> }
> 
> #[rstest]
> ```

Please add a test case for account nonce != 0 (i.e. account nonce == tx nonce == 1).
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B3OQc1Z4KOOUqE2Eq:-O1B3OQc1Z4KOOUqE2Er:bm4by5f) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L110)):*
> ```XML
>     #[case] should_pass_validation: bool,
> ) {
>     let block_context = &BlockContext::create_for_testing();
> ```

Please put it in a test fixture, and use it in the other test as well.



_Code quote:_
```XML
let block_context = &BlockContext::create_for_testing();
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B3ijqER439J7NUprF:-O1B3ijr6gxrDI67rcVw:bgryxch) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L125)):*
> ```XML
>             chain_info: block_context.chain_info().clone().into(),
>         },
>     };
> ```

Same. I think it can be a in test fixture.



_Code quote:_
```XML
    let stateful_validator = StatefulTransactionValidator {
        config: StatefulTransactionValidatorConfig {
            max_nonce_for_validation_skip: Nonce(StarkFelt::ONE),
            validate_max_n_steps: block_context.versioned_constants().validate_max_n_steps,
            max_recursion_depth: block_context.versioned_constants().max_recursion_depth,
            chain_info: block_context.chain_info().clone().into(),
        },
    };
```
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BBJVT1_mxCvEGpopy:-O1BBJVT1_mxCvEGpopz:b-o9lsd7) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L134)):*
> ```XML
>         // executed also when skip_validate is true.
>         assert_matches!(result, Err(StatefulTransactionValidatorError::StatefulValidatorError(err)) 
>             if !matches!(err, StatefulValidatorError::TransactionPreValidationError(_)));
> ```

@yair-starkware  is adding a mock blockifier validator to be used in this test. Once it is added you can just check that validate was called or not.



_Code quote:_
```XML
    if should_pass_validation {
        assert_matches!(result, Ok(_));
    } else {
        // To be sure that the validations were actually skipped, we check that the error came from
        // the blockifier stateful validations, and not from the pre validations since those are
        // executed also when skip_validate is true.
        assert_matches!(result, Err(StatefulTransactionValidatorError::StatefulValidatorError(err))
            if !matches!(err, StatefulValidatorError::TransactionPreValidationError(_)));
```


<!-- Sent from Reviewable.io -->

2024-07-08 06:04 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BGlFAA64FUG37fDOT:-O1Fimnc0zd4R_QQ7bpG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think `latest` is more accurate.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BGIkzEuZyOCuxLJ5C:-O1FkBQc-aUTwcz36PIG:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L71)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Just pass the account nonce using `validator.get_nonce(tx.sender_address)`
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B-YvF0EdfRLbF0vWl:-O1FkMhA8GC8rAFkevp0:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L100)):*
> ```XML
>             } else {
>                 Ok(false)
>             }
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B-KhD2Mw1fny_fR7O:-O1FkRL2ENYl7WHPu42X:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator.rs#L103)):*
> ```XML
>         }
>         RPCTransaction::DeployAccount(RPCDeployAccountTransaction::V3(_))
>         | RPCTransaction::Declare(RPCDeclareTransaction::V3(_)) => Ok(false),
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BI0v5CzDS7S-OJ7jA:-O1FuPGaE5hRMqjZhc7h:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L96)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please add a test case for account nonce != 0 (i.e. account nonce == tx nonce == 1).
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 110 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B3OQc1Z4KOOUqE2Eq:-O1FoO0TCGGPWjQ3keKU:bkys4gf) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L110)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please put it in a test fixture, and use it in the other test as well.
</blockquote></details>

Turns out blockifier has this fixure, I used it in the stateful _validator fixture.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 125 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1B3ijqER439J7NUprF:-O1FpluY2qhun6gPfj4M:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L125)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same. I think it can be a in test fixture.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BBJVT1_mxCvEGpopy:-O1Fpnyi9iUf59EnY-4e:b9z78bh) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L134)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

@yair-starkware  is adding a mock blockifier validator to be used in this test. Once it is added you can just check that validate was called or not.
</blockquote></details>

validate is always called, but with a skip_validate flag, since there are some un-skipped pre-validation checks. maybe the mock can also say if validation was skipped or not.


<!-- Sent from Reviewable.io -->

2024-07-08 06:40 UTC, dafnamatsry requested changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BBJVT1_mxCvEGpopy:-O1G0PzC0XASRZY5ML8_:b2ezj6f) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L134)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

validate is always called, but with a skip_validate flag, since there are some un-skipped pre-validation checks. maybe the mock can also say if validation was skipped or not.
</blockquote></details>

I believe that using the mock, it is possible to check the value of `skip_validate` passed to `validate`.
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 145 at r5](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1G2iM08RBbm5-f5_Bu:-O1G2iM08RBbm5-f5_Bv:b-xamq3d) ([raw file](https://github.com/starkware-libs/mempool/blob/67f7a22431899286a5ad398d8fa11f2b5bc4a28e/crates/gateway/src/stateful_transaction_validator_test.rs#L145)):*
> ```XML
> }
> 
> fn empty_state_reader_factory() -> TestStateReaderFactory {
> ```

what is the difference between this and `local_test_state_reader_factory`?
I think there are enough use cases to generalise the state reader factory initialisation in tests.

Having said that, with the mock blockifier validator, it would probably not be necessary at all.



_Code quote:_
```XML
empty_state_reader_factory()
```


<!-- Sent from Reviewable.io -->

2024-07-08 08:31 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 134 at r4](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1BBJVT1_mxCvEGpopy:-O1GSrC903Tnkk6nH3g2:bba7uhv) ([raw file](https://github.com/starkware-libs/mempool/blob/152b4205a83b7b72b91d08140d5064420e43822b/crates/gateway/src/stateful_transaction_validator_test.rs#L134)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I believe that using the mock, it is possible to check the value of `skip_validate` passed to `validate`.
</blockquote></details>

awesome!
___
*[`crates/gateway/src/stateful_transaction_validator_test.rs` line 145 at r5](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1G2iM08RBbm5-f5_Bu:-O1GSYLP63d7nx05jid0:b-5n3w0f) ([raw file](https://github.com/starkware-libs/mempool/blob/67f7a22431899286a5ad398d8fa11f2b5bc4a28e/crates/gateway/src/stateful_transaction_validator_test.rs#L145)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

what is the difference between this and `local_test_state_reader_factory`?
I think there are enough use cases to generalise the state reader factory initialisation in tests.

Having said that, with the mock blockifier validator, it would probably not be necessary at all.
</blockquote></details>

the empty_state_reader_factory makes the transaction invalid, so it passes only if we skip validations.
with `local_test_state_reader_factory` , it will be valid so it will pass anyway.

nice about the mock, so lets modify all tests after the mock is done.


<!-- Sent from Reviewable.io -->

2024-07-08 10:17 UTC, Yael-Starkware reviewed
@dafnamatsry  I will remove the max_nonce_for_validaiton_skip in a separate PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345#-:-O1GqDVf30GOhPzQ-5jD:b-2dwupm)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-09 05:07 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1KseoXE3vwxfkt9LF2:-O1KseoXE3vwxfkt9LF3:bcspwej) ([raw file](https://github.com/starkware-libs/mempool/blob/00f80014f4d96cb4a03e78429574560cce05994e/crates/gateway/src/stateful_transaction_validator.rs#L83)):*
> ```XML
>     tx: &RPCTransaction,
>     account_nonce: Nonce,
>     max_nonce_for_validation_skip: Nonce,
> ```

removed this parameter from here, and will delete the field from the actual config in a separate PR


<!-- Sent from Reviewable.io -->

2024-07-09 07:17 UTC, ArniStarkware reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @Yael-Starkware, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1KseoXE3vwxfkt9LF2:-O1LL_D20IqXXKAjzKla:b-7tlyet) ([raw file](https://github.com/starkware-libs/mempool/blob/00f80014f4d96cb4a03e78429574560cce05994e/crates/gateway/src/stateful_transaction_validator.rs#L83)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

removed this parameter from here, and will delete the field from the actual config in a separate PR
</blockquote></details>

Do we not want this number to be configurable anymore? I missed this decision. 


<!-- Sent from Reviewable.io -->

2024-07-09 08:33 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @yair-starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 83 at r7](https://reviewable.io/reviews/starkware-libs/mempool/345#-O1KseoXE3vwxfkt9LF2:-O1Lc0-GBgz0z9d0Y1he:b5rvs07) ([raw file](https://github.com/starkware-libs/mempool/blob/00f80014f4d96cb4a03e78429574560cce05994e/crates/gateway/src/stateful_transaction_validator.rs#L83)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we not want this number to be configurable anymore? I missed this decision.
</blockquote></details>

yes, the requirement is to have only nonce=1 support, no need to support more than that atm.


<!-- Sent from Reviewable.io -->

2024-07-10 07:38 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345#-:-O1Q_5t6C5oK4VvXzgzR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-11 07:23 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345#-:-O1VfD2v5nvSA1cLwmWt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-11 08:17 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/345)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-11 08:31 UTC, merged