refactor: mock batcher as a service
starkware-libs/mempool pull request #349
Opened 2024-07-02 15:20 UTC by ayeletstarkware

- Refactored `IntegrationTestSetup` to use the batcher as a service.
- Created `BatcherCommand` for messages sent to the batcher, triggering it to start. Currently, it only prints the connection but will later be used to get messages from the mempool.
- Refactored the end-to-end test not to ask for transactions, preventing it from failing (this is temporary).

2024-07-04 09:16 UTC, giladchase requested changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/349)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/mempool/349#-O0x-sEm6qtEtKOujqjt:-O0x-sEm6qtEtKOujqju:b5o31d8) ([raw file](https://github.com/starkware-libs/mempool/blob/9a2b06cc706663244e9c31aff291070b8cdbc550/crates/tests-integration/src/integration_test_setup.rs#L59)):*
> ```XML
> 
>         // Build Batcher.
>         let (tx_batcher, rx_batcher) = channel::<BatcherCommand>(32);
> ```

Reuse the`const` above, you can rename it to `message_queue_size` (in this PR is fine, it is only used locally).



_Code quote:_
```XML
32
```
___
*[`crates/tests-integration/src/integration_test_setup.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/mempool/349#-O0x04r_4XLeKpuZ2m4b:-O0x04r_4XLeKpuZ2m4c:bu6m9ra) ([raw file](https://github.com/starkware-libs/mempool/blob/9a2b06cc706663244e9c31aff291070b8cdbc550/crates/tests-integration/src/integration_test_setup.rs#L59)):*
> ```XML
> 
>         // Build Batcher.
>         let (tx_batcher, rx_batcher) = channel::<BatcherCommand>(32);
> ```

The docs suggest that unbounded sends are compatible with async, they don't have an await due [to this](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedSender.html#method.send).

Can you plz create a PR on top of this one that switches both this and the above channels with bounded senders? 
If it is impossible to use unbounded for both due to type constraints, then leave them as is for consistency.



_Code quote:_
```XML
        let (tx_batcher, rx_batcher) = channel::<BatcherCommand>(32)
```
___
*[`crates/tests-integration/src/mock_batcher.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/mempool/349#-O0x0ogX3MWNmFc4QnRo:-O0x0ogX3MWNmFc4QnRp:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9a2b06cc706663244e9c31aff291070b8cdbc550/crates/tests-integration/src/mock_batcher.rs#L17)):*
> ```XML
> impl MockBatcher {
>     pub fn new(
>         trigger_receiver: Receiver<BatcherCommand>,
> ```





_Suggestion:_
```XML
        rx_commands: Receiver<BatcherCommand>,
```
___
*[`crates/tests-integration/src/mock_batcher.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/mempool/349#-O0x0aiH5JRkbei8wnWF:-O0x0aiH5JRkbei8wnWG:b-iskt27) ([raw file](https://github.com/starkware-libs/mempool/blob/9a2b06cc706663244e9c31aff291070b8cdbc550/crates/tests-integration/src/mock_batcher.rs#L30)):*
> ```XML
>         while let Some(message) = self.trigger_receiver.recv().await {
>             match message {
>                 BatcherCommand::GetTxs(n_txs, sender) => {
> ```

Maybe more readable? not sure



_Suggestion:_
```XML
tx_response
```


<!-- Sent from Reviewable.io -->

2024-07-04 14:08 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/349)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/mempool/349#-O0x04r_4XLeKpuZ2m4b:-O0y-66bA5Xw65O-c3Kg:bdk7oo1) ([raw file](https://github.com/starkware-libs/mempool/blob/9a2b06cc706663244e9c31aff291070b8cdbc550/crates/tests-integration/src/integration_test_setup.rs#L59)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The docs suggest that unbounded sends are compatible with async, they don't have an await due [to this](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedSender.html#method.send).

Can you plz create a PR on top of this one that switches both this and the above channels with bounded senders? 
If it is impossible to use unbounded for both due to type constraints, then leave them as is for consistency.
</blockquote></details>

needs infra's approval so not going to happen


<!-- Sent from Reviewable.io -->

2024-07-07 13:35 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/349#-:-O1CP1SiBW5jJ3-xxfOc:bnfp4nl)* status: 0 of 28 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-08 07:43 UTC, Itay-Tsabary-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 25 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/349#-:-O1GI1lf7Xnw6NuuayYH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 09:15 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 25 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/349#-:-O1Gc-173_zxA6vAfPfN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-07-08 09:59 UTC, merged