feat: support skip_validate in mempool
starkware-libs/mempool pull request #376
Opened 2024-07-07 08:32 UTC by Yael-Starkware

2024-07-07 08:59 UTC, dafnamatsry requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BPpLn1ZCREoCiU3gP:-O1BPpLn1ZCREoCiU3gQ:b-30zic5) (no related file):*
Please add @elintul or @giladchase 

___
___
*[`crates/mempool/src/transaction_pool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BNCQS8AglKoYZnU9A:-O1BNCQTBdarx41zqCFS:b-gxfy0a) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L24)):*
> ```XML
> 
> impl TransactionPool {
>     pub fn insert(&mut self, tx: ThinTransaction, account_nonce: Nonce) -> MempoolResult<()> {
> ```

I think `insert` should do only and insert without any other checks.

Please move this check outside of the `TransactionPool`. 



_Code quote:_
```XML
 pub fn insert
```
___
*[`crates/mempool/src/transaction_pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BO9bW53Zm0CfCaCol:-O1BO9bW53Zm0CfCaCom:bh6yefj) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L52)):*
> ```XML
>         tx: &ThinTransaction,
>         account_nonce: Nonce,
>     ) -> MempoolResult<()> {
> ```

`Transaction pool` is a data structure for transactions and as such should not implement the "business logic".
You can implement `has_deploy_account_tx(sender_addrees)` instead.



_Code quote:_
```XML
    pub fn account_deployed(
        &self,
        tx: &ThinTransaction,
        account_nonce: Nonce,
    ) -> MempoolResult<()> {
```
___
*[`crates/mempool/src/transaction_pool.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BOgVf514s8-aCrQj2:-O1BOgVf514s8-aCrQj3:b-gh3elg) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L55)):*
> ```XML
>         // If tx nonce = 1 and account nonce = 0, the gateway have skipped validations and this
>         // means that the account may not have been deployed yet and we need to check it now.
>         if tx.nonce == Nonce(StarkFelt::ONE) && account_nonce == Nonce(StarkFelt::ZERO) {
> ```

Note that in the GW we have this nonce configurable. The same should be here.
Alternatively, you can add maybe a boolean as an input to the mempool to check for DeployAccount tx.



_Code quote:_
```XML
tx.nonce == Nonce(StarkFelt::ONE)
```


<!-- Sent from Reviewable.io -->

2024-07-08 08:02 UTC, elintul approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/mempool/src/mempool_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BVX4g0xlyM1N4fumQ:-O1BVX4hBtXC1U0I-AUW:bi8a78z) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/mempool_test.rs#L21)):*
> ```XML
> /// 2. add_tx_input!(tip: 1, tx_hash: StarkFelt::TWO, address: "0x3")
> /// 3. add_tx_input!(tip:1 , tx_hash: StarkFelt::TWO)
> macro_rules! add_tx_input {
> ```

Revert whitespace changes, make sure your formatter is configured correctly?



_Code quote:_
```XML
add_tx_input
```


<!-- Sent from Reviewable.io -->

2024-07-08 08:13 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BNCQS8AglKoYZnU9A:-O1GOwa24xPLI9_BaIn4:b-kqlge0) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think `insert` should do only and insert without any other checks.

Please move this check outside of the `TransactionPool`.
</blockquote></details>

I agree, this check it out of scope for the pool itself and is part of the mempool logic.


<!-- Sent from Reviewable.io -->

2024-07-08 08:15 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BOgVf514s8-aCrQj2:-O1GPDYL9wx16TdFspP1:b-e1gmjo) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L55)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that in the GW we have this nonce configurable. The same should be here.
Alternatively, you can add maybe a boolean as an input to the mempool to check for DeployAccount tx.
</blockquote></details>

Q: why is it configurable? Is there a (future) usecase where nonce > 1 for this feature?


<!-- Sent from Reviewable.io -->

2024-07-08 08:19 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GPpT2C4dW0cpqoHPa:-O1GPpT2C4dW0cpqoHPb:b-qcdz7x) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
> ```XML
>                 .unwrap_or(&BTreeMap::new())
>                 .get(&Nonce(StarkFelt::ZERO))
>                 .ok_or(MempoolError::UndeployedAccount { sender_address: tx.sender_address })?;
> ```

This isn't an error that indicates a negative flow, why not return a boolean?



_Code quote:_
```XML
UndeployedAccount
```


<!-- Sent from Reviewable.io -->

2024-07-08 08:22 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GQU5gEuvtQZmOxdTr:-O1GQU5gEuvtQZmOxdTs:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L48)):*
> ```XML
>     }
> 
>     pub fn account_deployed(
> ```





_Suggestion:_
```XML
account_was_deployed
```
___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GQjV0C_tZ1sb6XZD5:-O1GQjV0C_tZ1sb6XZD6:b-3phcig) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
> ```XML
>                 .unwrap_or(&BTreeMap::new())
>                 .get(&Nonce(StarkFelt::ZERO))
>                 .ok_or(MempoolError::UndeployedAccount { sender_address: tx.sender_address })?;
> ```

Seems like `AccountTransactionIndex` is missing an API we need. :)
Please add `get(&self, address: ContractAddress, nonce: Nonce) -> Option<&TransactionReference>` to it in a separate PR.



_Code quote:_
```XML
            self.txs_by_account
                .0
                .get(&tx.sender_address)
                .unwrap_or(&BTreeMap::new())
                .get(&Nonce(StarkFelt::ZERO))
                .ok_or(MempoolError::UndeployedAccount { sender_address: tx.sender_address })?;
```


<!-- Sent from Reviewable.io -->

2024-07-08 08:22 UTC, elintul reviewed
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-08 08:25 UTC, elintul reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-08 14:14 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BVX4g0xlyM1N4fumQ:-O1H0ZE11QhxliYIZ_0f:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/mempool_test.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Revert whitespace changes, make sure your formatter is configured correctly?
</blockquote></details>

done.
___
*[`crates/mempool/src/transaction_pool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BNCQS8AglKoYZnU9A:-O1HbSf39xg8PjCElVYJ:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I agree, this check it out of scope for the pool itself and is part of the mempool logic.
</blockquote></details>

done.
___
*[`crates/mempool/src/transaction_pool.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GQU5gEuvtQZmOxdTr:-O1HbBY9ApQYjhD4njsg:b-bwv6y0) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L48)):*
> ```XML
>     }
> 
>     pub fn account_deployed(
> ```

changed the name to has_deploy_account_tx , since the account was actually not deployed yet. 
___
*[`crates/mempool/src/transaction_pool.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BO9bW53Zm0CfCaCol:-O1HbA_W47qvIgk7QOkM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L52)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`Transaction pool` is a data structure for transactions and as such should not implement the "business logic".
You can implement `has_deploy_account_tx(sender_addrees)` instead.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_pool.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1BOgVf514s8-aCrQj2:-O1Hb28u4PFR71uZbuK4:btq6j9l) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L55)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Q: why is it configurable? Is there a (future) usecase where nonce > 1 for this feature?
</blockquote></details>

discussed with @dafnamatsry and I think we can remove the configuration
___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GPpT2C4dW0cpqoHPa:-O1HaqZjDvcG6flm36Xe:bgspo92) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This isn't an error that indicates a negative flow, why not return a boolean?
</blockquote></details>

it is a negative flow if invoke doesn't have a deploy account tx.
___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GQjV0C_tZ1sb6XZD5:-O1HawpG-jmahlvbyI0C:b5ykwam) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Seems like `AccountTransactionIndex` is missing an API we need. :)
Please add `get(&self, address: ContractAddress, nonce: Nonce) -> Option<&TransactionReference>` to it in a separate PR.
</blockquote></details>

added in a separate PR
https://reviewable.io/reviews/starkware-libs/mempool/402


<!-- Sent from Reviewable.io -->

2024-07-09 13:50 UTC, elintul reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-09 13:51 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GPpT2C4dW0cpqoHPa:-O1MkkHj9D2cHlHcOoX4:b-3zg09g) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is a negative flow if invoke doesn't have a deploy account tx.
</blockquote></details>

Does the user have something to do with the error, or do we simply match over `Ok/Err` in our internal business logic? If the latter, we should return a boolean from this method.


<!-- Sent from Reviewable.io -->

2024-07-10 08:48 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnS3WAaut3M-2kFSm:-O1QnS3WAaut3M-2kFSn:bk5xp23) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L92)):*
> ```XML
>     }
> 
>     pub fn has_deploy_account_tx(
> ```

`has` implies that it returns a boolean. but it return a `Result`. Consider `verify` instead.
Plus, we do the verification only in a specific case, and the name should indicate that.



_Code quote:_
```XML
has_deploy_account_tx
```
___
*[`crates/mempool/src/mempool.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QffVQEpelWKtw9zfk:-O1QffVQEpelWKtw9zfl:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L98)):*
> ```XML
>     ) -> MempoolResult<()> {
>         // If tx nonce = 1 and account nonce = 0, the gateway have skipped validations and this
>         // means that the account may not have been deployed yet and we need to check it now.
> ```





_Suggestion:_
```XML
        // If the tx nonce is 1 and the account nonce is 0, the account was not deployed yet, and the gateway has skipped validations.
        // In this case, we verify that a deploy account tx exists in the pool.
```
___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1QhTb42VQTpzRpA82i:bihnw79) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
> ```XML
>         // means that the account may not have been deployed yet and we need to check it now.
>         // TODO(Yael 8/7/2024): This is only relevant for invoke tx, check the type once available.
>         if tx.nonce == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO) {
> ```

Please move this check to a common crate (I think we should crate one), as it appears both here and in the GW.

(In a separate PR)



_Code quote:_
```XML
 tx.nonce == Nonce(Felt::ONE) && account_nonce == Nonce(Felt::ZERO)
```


<!-- Sent from Reviewable.io -->

2024-07-10 08:52 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnRM115ITOf1GxG_k:-O1QnRM115ITOf1GxG_l:b-gx0g0v) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L104)):*
> ```XML
>                 .tx_pool
>                 .get_by_address_and_nonce(tx.sender_address, Nonce(Felt::ZERO))
>                 .is_some()
> ```

I think it suffices to only check if the sender_address even exists in the pool.

If it exists, then it must be Nonce(0), since otherwise it wouldn't have passed `has_deploy_account_tx`?

nit-picking: if all we want to know is `is_some` then a `containts_* -> bool` might fit better.

nit-picking 2 (also maybe not directly related to this PR): why does get_by_address_and_nonce return option and the rest of the API of pool returns Errors? 



_Code quote:_
```XML
                .get_by_address_and_nonce(tx.sender_address, Nonce(Felt::ZERO))
                .is_some()
```
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1Qog2g1EfCrIEUJ8_D:-O1Qog2g1EfCrIEUJ8_E:bbs9nav) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L187)):*
> ```XML
>         tip: 0,
>         tx_hash: 0,
>         sender_address: TEST_SENDER_ADDRESS,
> ```

Does this address have any special meaning? if not then you can use 1_u8 I think, because 0x1000 looks meaningful.



_Code quote:_
```XML
        sender_address: TEST_SENDER_ADDRESS,
```
___
*[`crates/mempool/src/mempool_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QpxRfBBz43pL1hj8O:-O1QpxRfBBz43pL1hj8P:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L196)):*
> ```XML
>         Err(MempoolError::UndeployedAccount { sender_address })
>         if sender_address == input.tx.sender_address
>     );
> ```





_Suggestion:_
```XML
    assert_eq!(
        result,
        Err(MempoolError::UndeployedAccount { sender_address: contract_address!(TEST_SENDER_ADDRESS) })
    );
```
___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GPpT2C4dW0cpqoHPa:-O1QhWZq-rsxhadkY0ml:b-fpob8l) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Does the user have something to do with the error, or do we simply match over `Ok/Err` in our internal business logic? If the latter, we should return a boolean from this method.
</blockquote></details>

IIUC the user has something to do, this error means that the user send invokes immediately while forgotting to deploy.
Which is probably a bug in the user's wallet (or more accurately the user is the wallet here?).


<!-- Sent from Reviewable.io -->

2024-07-10 10:13 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1R6kYR5QCWIdOVHtZW:bjaczez) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please move this check to a common crate (I think we should crate one), as it appears both here and in the GW.

(In a separate PR)
</blockquote></details>

Following our discussion a few days ago. @elintul and me were just discussing whether to pass a value form gateway that tells the mempool to verify the the deploy_account tx exists. 

@giladchase wdyt?  There are two options here:
1. check if tx_nonce=1 and account_nonce=0, if true , check for deploy account. as implemented here.
2. get an indication from the gateway the it needs to perform the check for deploy account.


<!-- Sent from Reviewable.io -->

2024-07-10 10:50 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnS3WAaut3M-2kFSm:-O1R9SCm6cufUFOzOVp4:b-eizaj6) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

`has` implies that it returns a boolean. but it return a `Result`. Consider `verify` instead.
Plus, we do the verification only in a specific case, and the name should indicate that.
</blockquote></details>

how is verify_tx?
other future checks could fit here too
___
*[`crates/mempool/src/mempool.rs` line 98 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QffVQEpelWKtw9zfk:-O1R9REqCUqCTiCROFOC:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L98)):*
> ```XML
>     ) -> MempoolResult<()> {
>         // If tx nonce = 1 and account nonce = 0, the gateway have skipped validations and this
>         // means that the account may not have been deployed yet and we need to check it now.
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 196 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QpxRfBBz43pL1hj8O:-O1R9hAF9-ntKTtRzWya:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L196)):*
> ```XML
>         Err(MempoolError::UndeployedAccount { sender_address })
>         if sender_address == input.tx.sender_address
>     );
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-10 10:52 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1RGPDABTn80UJqYwU2:-O1RGPDABTn80UJqYwU3:b-uynn94) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L83)):*
> ```XML
>         let tx = input.tx;
>         let tx_reference = TransactionReference::new(&tx);
>         self.has_deploy_account_tx(&tx, input.account.state.nonce)?;
> ```

@giladchase do you think this line should appear here or in add_tx() ?



_Code quote:_
```XML
has_deploy_account_tx
```


<!-- Sent from Reviewable.io -->

2024-07-10 11:52 UTC, elintul reviewed
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-07-10 13:22 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1RGPDABTn80UJqYwU2:-O1Rn2bR2FiUUjTRLrQT:b-wcoxze) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L83)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

@giladchase do you think this line should appear here or in add_tx() ?
</blockquote></details>

add_tx, since insert doesn't need to know about this high-level check.
Also we don't want `new`, which also uses insert, to be exposed to this I think.


<!-- Sent from Reviewable.io -->

2024-07-10 13:30 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnS3WAaut3M-2kFSm:-O1RpgjDBTe3ZTYCxEXx:b-uxt110) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

how is verify_tx?
other future checks could fit here too
</blockquote></details>

I'd maybe go with `should_insert`.
___
*[`crates/mempool/src/mempool_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1RpStx4r--K7DUs6yL:-O1RpSty6AwgnbXHCnTb:br36vbp) ([raw file](https://github.com/starkware-libs/mempool/blob/9a6abdf37d33ef9705c3097ddec7aa30d8f6dc4a/crates/mempool/src/mempool_test.rs#L26)):*
> ```XML
> /// 1. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8, tx_nonce: 4)
> /// 2. add_tx_input!(tip: 1, tx_hash: 2, sender_address: 3_u8)
> /// 3. add_tx_input!(tip: 1, tx_hash: 2)
> ```

Please revert whitespaces changes; make sure your formatter is well-defined.
Also, it there are changes needed to this macro, please separate them to another PR.


<!-- Sent from Reviewable.io -->

2024-07-10 13:32 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1RpStx4r--K7DUs6yL:-O1Rq7AE5WKX4CHtbBMM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9a6abdf37d33ef9705c3097ddec7aa30d8f6dc4a/crates/mempool/src/mempool_test.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please revert whitespaces changes; make sure your formatter is well-defined.
Also, it there are changes needed to this macro, please separate them to another PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-10 13:39 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-07-10 13:48 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1RGPDABTn80UJqYwU2:-O1RqPzHDh5jryvKggbC:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

add_tx, since insert doesn't need to know about this high-level check.
Also we don't want `new`, which also uses insert, to be exposed to this I think.
</blockquote></details>

done
___
*[`crates/mempool/src/mempool.rs` line 92 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnS3WAaut3M-2kFSm:-O1RqQlK2fBZ09T_hUum:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd maybe go with `should_insert`.
</blockquote></details>

done
___
*[`crates/mempool/src/mempool.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnRM115ITOf1GxG_k:-O1RswYz8mM7Cq6yowrK:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L104)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think it suffices to only check if the sender_address even exists in the pool.

If it exists, then it must be Nonce(0), since otherwise it wouldn't have passed `has_deploy_account_tx`?

nit-picking: if all we want to know is `is_some` then a `containts_* -> bool` might fit better.

nit-picking 2 (also maybe not directly related to this PR): why does get_by_address_and_nonce return option and the rest of the API of pool returns Errors?
</blockquote></details>

done
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1Qog2g1EfCrIEUJ8_D:-O1RrGPw7vTMZEblEra_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L187)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Does this address have any special meaning? if not then you can use 1_u8 I think, because 0x1000 looks meaningful.
</blockquote></details>

Done.
___
*[`crates/mempool/src/transaction_pool.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1GPpT2C4dW0cpqoHPa:-O1RsucjBb-TziLGUWlP:b2nhysk) ([raw file](https://github.com/starkware-libs/mempool/blob/5aef0b421cee859e121fb4da84c22effd5787066/crates/mempool/src/transaction_pool.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

IIUC the user has something to do, this error means that the user send invokes immediately while forgotting to deploy.
Which is probably a bug in the user's wallet (or more accurately the user is the wallet here?).
</blockquote></details>

ack


<!-- Sent from Reviewable.io -->

2024-07-11 04:30 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1V28q82f-r7NhlO9fm:b-ki06tp) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Following our discussion a few days ago. @elintul and me were just discussing whether to pass a value form gateway that tells the mempool to verify the the deploy_account tx exists. 

@giladchase wdyt?  There are two options here:
1. check if tx_nonce=1 and account_nonce=0, if true , check for deploy account. as implemented here.
2. get an indication from the gateway the it needs to perform the check for deploy account.
</blockquote></details>

leaning towards (2), less coupling, but i'm really not sure, we need to know what common for a mempool to do/know, Elin's looking into it
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1Qog2g1EfCrIEUJ8_D:-O1V2N0D3bV6SRcI-Ys1:b-5jacf2) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L187)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Tnx, also move it as an inline const inside the test plz, since other tests are using different addresses then that (or in a separate PR make other tests all use this address)


<!-- Sent from Reviewable.io -->

2024-07-11 07:43 UTC, dafnamatsry requested changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1VjbNqCwJOCvU10Ay6:b-jplu1u) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

leaning towards (2), less coupling, but i'm really not sure, we need to know what common for a mempool to do/know, Elin's looking into it
</blockquote></details>

leaning towards (2) as well.
Whatever we decide, can be done in a separate PR.
___
*[`crates/mempool/src/mempool.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnRM115ITOf1GxG_k:-O1VhN64D5Cdsw8hKv5z:b-5qlyi4) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L104)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

@giladchase Why it has to be Nonce(0)? The mempool can accept future nonces... Or do you assume that if we have txs for this account, they passed validation so there is a deployed account for them?
In any way, @Yael-Starkware Please update the comment to explain that. 


<!-- Sent from Reviewable.io -->

2024-07-11 08:43 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1VxBAn2VigXVyZrj5r:b-85w432) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

leaning towards (2) as well.
Whatever we decide, can be done in a separate PR.
</blockquote></details>

ok will do in a separate PR, added a TODO there and will get right onto it.
___
*[`crates/mempool/src/mempool.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnRM115ITOf1GxG_k:-O1VxWp4BaHG-JZjt_BO:b-v0iy0e) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L104)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

@giladchase Why it has to be Nonce(0)? The mempool can accept future nonces... Or do you assume that if we have txs for this account, they passed validation so there is a deployed account for them?
In any way, @Yael-Starkware Please update the comment to explain that.
</blockquote></details>

changed the comment to explain it, the comment will be modified once I implement the todo.
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1Qog2g1EfCrIEUJ8_D:-O1Ve7hk04wBmOH1v3qm:b5nfywd) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L187)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Tnx, also move it as an inline const inside the test plz, since other tests are using different addresses then that (or in a separate PR make other tests all use this address)
</blockquote></details>

will do in a separate PR. I already have another PR with a test using this const


<!-- Sent from Reviewable.io -->

2024-07-11 11:31 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/mempool/src/mempool.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QnRM115ITOf1GxG_k:-O1WMX2U8IaWLMqxkevI:b-w1kko6) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L104)):*
>Or do you assume that if we have txs for this account, they passed validation so there is a deployed account for them?

Yep


<!-- Sent from Reviewable.io -->

2024-07-11 12:08 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1QhTb42VQTpzRpA82h:-O1WgP5RA-6pTxIFP2Jy:b-dxey5n) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool.rs#L100)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

ok will do in a separate PR, added a TODO there and will get right onto it.
</blockquote></details>

done in PR:
https://reviewable.io/reviews/starkware-libs/mempool/450#-
___
*[`crates/mempool/src/mempool_test.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/mempool/376#-O1Qog2g1EfCrIEUJ8_D:-O1WgJ_p1GuwuVW9PeN7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/f7cefedb6d8fa98265ad75a555c2a859352c6ae5/crates/mempool/src/mempool_test.rs#L187)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

will do in a separate PR. I already have another PR with a test using this const
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-14 07:30 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376#-:-O1k8daN03PkgKFlz9co:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-16 06:49 UTC, dafnamatsry approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/376)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-10-27 07:03 UTC, elintul commented
Moving this feature to the next MS; my team will take it.

2024-10-27 07:03 UTC, closed without merging