feat: add stateful validations
starkware-libs/mempool pull request #42
Opened 2024-04-10 14:10 UTC by Yael-Starkware

2024-04-11 08:46 UTC, dafnamatsry requested changes
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_validator.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvAh_lQCONaPJOS_G7f:-NvAh_lQCONaPJOS_G7g:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L31)):*
> ```XML
> 
> impl<S: StateReader> StatefulValidator<S> {
>     pub fn new(config: StatefulValidatorConfig, state_reader: S, block_info: BlockInfo) -> Self {
> ```





_Suggestion:_
```XML
latest_block_info
```
___
*[`crates/gateway/src/stateful_validator.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBFLWw4a8TYOT_m65k:-NvBFLWw4a8TYOT_m65l:b-dnxqe7) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L42)):*
> ```XML
>     pub fn run_validate(
>         self,
>         tx: Transaction,
> ```

We should use the new `ExternalTransaction` struct Mohammed added to Starknet API.



_Code quote:_
```XML
Transaction
```
___
*[`crates/gateway/src/transaction_validator_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBIv0K3nqKd5g88d12:-NvBIv0K3nqKd5g88d13:b-32ity5) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L88)):*
> ```XML
>     let result = tx_validator.validate(tx);
> 
>     assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
> ```

why the change?



_Code quote:_
```XML
format!("{:?}", result), format!("{:?}"
```


<!-- Sent from Reviewable.io -->

2024-04-11 09:19 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_validator.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBRdqR7NXXxkz8QDZ0:-NvBRdqR7NXXxkz8QDZ1:b-6m76n2) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L24)):*
> ```XML
> }
> 
> pub struct StatefulValidator<S: StateReader> {
> ```

Rename to `StatefulTransactionValidator`, to be consistent with Arni's naming of `StatelessTransactionValidator`.
(the file should also be renamed.)



_Code quote:_
```XML
StatefulValidator
```


<!-- Sent from Reviewable.io -->

2024-04-11 13:11 UTC, ArniStarkware commented
*[`crates/gateway/src/transaction_validator_test.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvCGmX1EDjtCvYZg4E_:-NvCGmX1EDjtCvYZg4Ea:b-fjd5k7) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L0)):*
This file is renamed and no longer relevant for your PR.
Please open another file - `stateful_transaction_validater_test.rs`


<!-- Sent from Reviewable.io -->

2024-04-16 05:52 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/transaction_validator_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBIv0K3nqKd5g88d12:-NvBVr4WDFjIYQUrKFY9:bibc0eh) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L88)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

why the change?
</blockquote></details>

I added TransactionExecutionError to the TransactionValidatorError enum and it does not implement PartialEq , so we can't compare the error like that anymore.
___
*[`crates/gateway/src/stateful_validator.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBRdqR7NXXxkz8QDZ0:-NvBVpGO2nzvMXQ15_mR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L24)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Rename to `StatefulTransactionValidator`, to be consistent with Arni's naming of `StatelessTransactionValidator`.
(the file should also be renamed.)
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_validator.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvAh_lQCONaPJOS_G7f:-NvBVpgtE39ggTXOc0iR:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L31)):*
> ```XML
> 
> impl<S: StateReader> StatefulValidator<S> {
>     pub fn new(config: StatefulValidatorConfig, state_reader: S, block_info: BlockInfo) -> Self {
> ```

Done.
___
*[`crates/gateway/src/stateful_validator.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBFLWw4a8TYOT_m65k:-NvBW97t1uN8Dvs6RERH:bb4wyqt) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L42)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

We should use the new `ExternalTransaction` struct Mohammed added to Starknet API.
</blockquote></details>

done. following the discussions yesterday, I'm converting from ExternalTransaction to AccountTransaction.
___
*[`crates/gateway/src/stateful_validator.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvCCu8U-mSZdU6Suvxg:-Nv_SeNu73qDRokyaIbs:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/stateful_validator.rs#L58)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

You should use `VersionedConstatns::latest_constants_with_overrides`.
The values for this function should come from some config.

See how they do it in the [PyBlockifier](https://github.com/starkware-libs/blockifier/blob/e9eb19edf874ff18f44ac29c95abb4e3af8978f5/crates/native_blockifier/src/py_validator.rs#L40-L43).
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-16 05:56 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvCGmX1EDjtCvYZg4E_:-Nv_TO6ZCNLi05k3dYNu:b-y3gcu5) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This file is renamed and no longer relevant for your PR.
Please open another file - `stateful_transaction_validater_test.rs`
</blockquote></details>

I am still using the same error type. So you think we should separate error types as well.


<!-- Sent from Reviewable.io -->

2024-04-16 07:52 UTC, ArniStarkware requested changes
> Reviewed 2 of 6 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 4 of 9 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`Cargo.toml` line 24 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_lQNl6ORQPGFW_RvX:-Nv_lQNl6ORQPGFW_RvY:b9qlx7p) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/Cargo.toml#L24)):*
> ```TOML
> assert_matches = "1.5.0"
> axum = "0.6.12"
> blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "a45b9513"}
> ```

Add a todo.



_Suggestion:_
```TOML
# TODO(YaelD, 1/5/2024): Use a fixed version once the StarkNet API is stable.
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "a45b9513"}
```
___
*[`crates/gateway/src/errors.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_lpnG67vPe_fViaBJ:-Nv_lpnG67vPe_fViaBK:bwju2ji) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/errors.rs#L41)):*
> ```XML
>     #[error(transparent)]
>     TransactionExecutionError(#[from] TransactionExecutionError),
> }
> ```

Motivation. These errors are never shared.



_Suggestion:_
```XML
#[derive(Debug, Error)]
#[cfg_attr(test, derive(PartialEq))] // ? 
pub enum StatelessTransactionValidatorError {
    #[error("Expected a positive amount of {resource:?}. Got {resource_bounds:?}.")]
    ZeroFee {
        resource: Resource,
        resource_bounds: ResourceBounds,
    },
    #[error("The resource bounds mapping is missing a resource {resource:?}.")]
    MissingResource { resource: Resource },
}

// Maybe this enum should simply be called: `TransactionValidatorError`.
#[derive(Debug, Error)]
#[cfg_attr(test, derive(Eq))] // ?
pub enum StatefulTransactionValidatorError {
    #[error("Block number {block_number:?} is out of range.")]
    BlockNumberOutOfRange { block_number: BlockNumber },
    #[error(transparent)]
    StarknetApiError(#[from] StarknetApiError),
    #[error(transparent)]
    StatefulValidatorError(#[from] StatefulValidatorError),
    #[error(transparent)]
    TransactionExecutionError(#[from] TransactionExecutionError),
}
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_rgkc8Bz5G-edGKT1:-Nv_rgkc8Bz5G-edGKT2:bgfwm30) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L41)):*
> ```XML
> }
> 
> pub struct StatefulTransactionValidator<S: StateReader + Clone> {
> ```

Why does the `state_reader` need to implement `Clone`?



_Code quote:_
```XML
pub struct StatefulTransactionValidator<S: StateReader + Clone>
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_sk0g3pCjZdwE0eR7:-Nv_sk0hCwE-rVaN0i8t:bt5z9pv) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L89)):*
> ```XML
>             block_context,
>             self.config.max_nonce_for_validation_skip,
>         );
> ```

Move this into the `new` method of `StatefulTransactionValidator`. 
Change the `StatefulTransactionValidator` to have a `BlockifierStatefulValidator` as a member. 
(I think this will solve the `Clone` issue). 



_Code quote:_
```XML
        let mut validator = BlockifierStatefulValidator::create(
            state,
            block_context,
            self.config.max_nonce_for_validation_skip,
        );
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_pO0X5Mt0XuTNzBFc:-Nv_pO0X5Mt0XuTNzBFd:b-fwk17m) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L149)):*
> ```XML
>                 );
>                 Ok(AccountTransaction::DeployAccount(deploy_account_tx))
>             }
> ```

I did not read the code you added here :(
Let us have a PR dedicated to it when the time comes. 

This means we don't need to consider `optional_class_info` in this PR. 



_Suggestion:_
```XML
            ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => {todo!("Deal with declare tx.")}
            ExternalTransaction::DeployAccount(ExternalDeployAccountTransaction::V3(tx)) => {todo!("Deal with deploy account tx."}
```
___
*[`crates/gateway/src/transaction_validator_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBIv0K3nqKd5g88d12:-Nv_oWSnB-GjduKWV0iT:b-qt8r0y) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L88)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I added TransactionExecutionError to the TransactionValidatorError enum and it does not implement PartialEq , so we can't compare the error like that anymore.
</blockquote></details>

Please link an example of how it is used in blockifier (Which is a bad practice over there as well - but what can you do?)
___
*[`crates/gateway/src/transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvCGmX1EDjtCvYZg4E_:-Nv_kr_b8qIJxdbZTPM-:b-q1yvgo) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I am still using the same error type. So you think we should separate error types as well.
</blockquote></details>

I think so. Does the list of errors have a shared part?


<!-- Sent from Reviewable.io -->

2024-04-16 08:24 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator.rs` line 149 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_pO0X5Mt0XuTNzBFc:-Nva-XPy4cmTYWJQJl63:b-kp6z4d) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L149)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I did not read the code you added here :(
Let us have a PR dedicated to it when the time comes. 

This means we don't need to consider `optional_class_info` in this PR.
</blockquote></details>

Retracted.


<!-- Sent from Reviewable.io -->

2024-04-16 09:01 UTC, dafnamatsry requested changes
Please add @giladchase as a reviewer

> Reviewed 2 of 6 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-Nva7o3X3sEbn1FJW2lA:b-b5smd9)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6lo_6Wrpeg4FWFs1:-Nva6lo_6Wrpeg4FWFs2:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L64)):*
> ```XML
>     pub fn run_validate(
>         &self,
>         external_tx: ExternalTransaction,
> ```





_Suggestion:_
```XML
&ExternalTransaction
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva58DP1ofkgBn04Y_p:-Nva58DP1ofkgBn04Y_q:bbvox8n) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L82)):*
> ```XML
>             BlockContext::new_unchecked(&block_info, &self.config.chain_info, &versioned_constants);
>         let global_contract_cache =
>             GlobalContractCache::new(self.config.global_contract_cache_size);
> ```

Do we create a global_contract_cache per tx? Is this how it is supposed to be?

Not for this PR, but should think about adding some kind of global cache.



_Code quote:_
```XML
GlobalContractCache::new
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva2z0r2ElZQfkn9i0m:-Nva2z0r2ElZQfkn9i0n:b6y53na) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
> ```XML
>     }
> 
>     fn external_tx_to_account_tx(
> ```

This can be implemented as a utility function, even in a separate `utils.rs` file (there is no use of self here).



_Code quote:_
```XML
external_tx_to_account_tx
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6fcZ0tm3p4IVEFo1:-Nva6fcZ0tm3p4IVEFo2:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L99)):*
> ```XML
>     fn external_tx_to_account_tx(
>         &self,
>         external_tx: ExternalTransaction,
> ```





_Suggestion:_
```XML
&ExternalTransaction
```


<!-- Sent from Reviewable.io -->

2024-04-16 10:58 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 8 of 9 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`Cargo.toml` line 24 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_lQNl6ORQPGFW_RvX:-NvaLE8WD4vHllAIcv8T:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/Cargo.toml#L24)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a todo.
</blockquote></details>

done.
___
*[`crates/gateway/src/errors.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_lpnG67vPe_fViaBJ:-NvaPp_a4_Narv32LXV_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/errors.rs#L41)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Motivation. These errors are never shared.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_rgkc8Bz5G-edGKT1:-NvaUKnY9cEsIzmzfkZ3:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L41)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why does the `state_reader` need to implement `Clone`?
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6lo_6Wrpeg4FWFs1:-NvaQ7ew02Ko4MBjTkbI:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L64)):*
> ```XML
>     pub fn run_validate(
>         &self,
>         external_tx: ExternalTransaction,
> ```

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva58DP1ofkgBn04Y_p:-NvaUVWJC1VSIwWuKpNC:bfdqxg4) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L82)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Do we create a global_contract_cache per tx? Is this how it is supposed to be?

Not for this PR, but should think about adding some kind of global cache.
</blockquote></details>

adding a comment. done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 89 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nv_sk0g3pCjZdwE0eR7:-NvaY_9DBUrEjWW3nbyo:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L89)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Move this into the `new` method of `StatefulTransactionValidator`. 
Change the `StatefulTransactionValidator` to have a `BlockifierStatefulValidator` as a member. 
(I think this will solve the `Clone` issue).
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva2z0r2ElZQfkn9i0m:-NvaRYN932utwkg_8vLP:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L97)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

This can be implemented as a utility function, even in a separate `utils.rs` file (there is no use of self here).
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6fcZ0tm3p4IVEFo1:-NvaRY4rBWT7jL7-bbCl:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L99)):*
> ```XML
>     fn external_tx_to_account_tx(
>         &self,
>         external_tx: ExternalTransaction,
> ```

Done.
___
*[`crates/gateway/src/transaction_validator_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBIv0K3nqKd5g88d12:-NvaYeHS1Ul76Ef_z-2e:b-nysnjk) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L88)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please link an example of how it is used in blockifier (Which is a bad practice over there as well - but what can you do?)
</blockquote></details>

not needed anymore since I separated the error types.
___
*[`crates/gateway/src/transaction_validator_test.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvCGmX1EDjtCvYZg4E_:-NvaRdENAZXT2YEXBe9t:b-bb108) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I think so. Does the list of errors have a shared part?
</blockquote></details>

not atm


<!-- Sent from Reviewable.io -->

2024-04-17 10:51 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva58DP1ofkgBn04Y_p:-NvffRdw9ctNflNbAj7x:b1tq8b9) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L82)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

adding a comment. done.
</blockquote></details>

What happened to `GlobalContractCache`? Where is the comment?


<!-- Sent from Reviewable.io -->

2024-04-17 10:54 UTC, ArniStarkware reviewed
> Reviewed 1 of 7 files at r1, 5 of 7 files at r4, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva58DP1ofkgBn04Y_p:-NvfgBd32tWhnJEfuA3D:b-jjetq8) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L82)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What happened to `GlobalContractCache`? Where is the comment?
</blockquote></details>

` CachedState::new` no longer requires a `GlobalContractCache`? Nice.
___
*[`crates/gateway/src/transaction_validator_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvBIv0K3nqKd5g88d12:-Nvan3-08UNAdWsoNQl-:b-ihrhpg) ([raw file](https://github.com/starkware-libs/mempool/blob/23867506835f034115d9d68a0bc31391c1428e58/crates/gateway/src/transaction_validator_test.rs#L88)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not needed anymore since I separated the error types.
</blockquote></details>

Also, since there is no test for the stateful validator in this repo yet.
I did start working on the blockifier's stateful validator tests.


<!-- Sent from Reviewable.io -->

2024-04-17 10:57 UTC, ArniStarkware reviewed
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 9 of 11 files reviewed, 8 unresolved discussions (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-17 11:17 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvflWV_8sy8Izum3v6K:-NvflWV_8sy8Izum3v6L:b8b25vt) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L50)):*
> ```XML
>         latest_block_info: BlockInfo,
>     ) -> Self {
>         let state = CachedState::new(state_reader);
> ```

Why not?



_Suggestion:_
```XML
    pub fn new(
        config: &StatefulTransactionValidatorConfig,
        state: CachedState<S>,
        // TODO(yael 2/4/24): get block_info from the state.
        latest_block_info: BlockInfo,
    ) -> Self {
```


<!-- Sent from Reviewable.io -->

2024-04-17 11:18 UTC, ArniStarkware commented
*[`crates/gateway/src/stateful_transaction_validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvflcwp1CP3UYqSmB5P:-Nvflcwp1CP3UYqSmB5Q:bxx17vb) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L42)):*
> ```XML
>         let mut validator = Self::new(config, state_reader, latest_block_info);
>         validator.run_validate(external_tx, deploy_account_tx_hash, optional_class_info)
>     }
> ```

With respect to the next comment.



_Suggestion:_
```XML
    pub fn create_and_run_validate(
        config: &StatefulTransactionValidatorConfig,
        state: CachedState<S>,
        latest_block_info: BlockInfo,
        external_tx: &ExternalTransaction,
        deploy_account_tx_hash: Option<TransactionHash>,
        optional_class_info: Option<ClassInfo>,
    ) -> StatefulTransactionValidatorResult<()> {
        let mut validator = Self::new(config, state, latest_block_info);
        validator.run_validate(external_tx, deploy_account_tx_hash, optional_class_info)
    }
```


<!-- Sent from Reviewable.io -->

2024-04-17 12:39 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva58DP1ofkgBn04Y_p:-NvfvWEpETzJLYbxQZh6:bwgp48m) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L82)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

` CachedState::new` no longer requires a `GlobalContractCache`? Nice.
</blockquote></details>

right! :) 
but I will talk to Yoni to understanf how this affects our StateReader implementation
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvflcwp1CP3UYqSmB5P:-Nvg2gV66R06Kp672B6s:b-ba7jdf) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L42)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

With respect to the next comment.
</blockquote></details>

why do you think this is better?
I think the creation of the CachedState should be encapsulated inside this function.


<!-- Sent from Reviewable.io -->

2024-04-17 12:41 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvflcwp1CP3UYqSmB5P:-Nvg3myg3hcGbpDxEnmm:bd3yxvs) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L42)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

why do you think this is better?
I think the creation of the CachedState should be encapsulated inside this function.
</blockquote></details>

it is something that the blockifier requires.


<!-- Sent from Reviewable.io -->

2024-04-18 06:07 UTC, dafnamatsry requested changes
> Reviewed 1 of 6 files at r2, 6 of 7 files at r4, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvflcwp1CP3UYqSmB5P:-Nvjk3FCEJvVc-PmaeBN:b-5327cj) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L42)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is something that the blockifier requires.
</blockquote></details>

I agree with Yael, and as you commented the whole StateReader creation will eventually be encapsulated here...
___
*[`crates/gateway/src/utils.rs` line 21 at r7](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvjmTVC9zr-x_Vvo4c0:-NvjmTVC9zr-x_Vvo4c1:bbyifix) ([raw file](https://github.com/starkware-libs/mempool/blob/5da2e13fae064e8852c45926cc6375337a036277/crates/gateway/src/utils.rs#L21)):*
> ```XML
>     external_tx: &ExternalTransaction,
>     optional_class_info: Option<ClassInfo>,
> ) -> StatefulTransactionValidatorResult<AccountTransaction> {
> ```

Can it be just `AccountTransaction`?



_Code quote:_
```XML
StatefulTransactionValidatorResult<AccountTransaction>
```


<!-- Sent from Reviewable.io -->

2024-04-18 06:13 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvflWV_8sy8Izum3v6K:-NvjpKnX6BwrctBCINdw:b-w2ufq0) ([raw file](https://github.com/starkware-libs/mempool/blob/a55bd6433c91430782caffb720cf908752d0393a/crates/gateway/src/stateful_transaction_validator.rs#L50)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

see previous comment
___
*[`crates/gateway/src/utils.rs` line 21 at r7](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvjmTVC9zr-x_Vvo4c0:-NvjpZ560S5HRTXe5acn:b-cadv4n) ([raw file](https://github.com/starkware-libs/mempool/blob/5da2e13fae064e8852c45926cc6375337a036277/crates/gateway/src/utils.rs#L21)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can it be just `AccountTransaction`?
</blockquote></details>

there is an error to propagate from here: 
let declare_tx = BlockifierDeclareTransaction::new(declare_tx, tx_hash, class_info)?;


<!-- Sent from Reviewable.io -->

2024-04-18 06:44 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-18 08:28 UTC, ArniStarkware approved these changes
> Reviewed 1 of 6 files at r2, 1 of 3 files at r3, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-18 12:41 UTC, giladchase requested changes
> Reviewed 1 of 7 files at r1, 1 of 7 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/gateway/src/errors.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvkv70GDrUkV3_Tjqa-:-Nvkv70GDrUkV3_Tjqa0:b-agkic6) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/errors.rs#L50)):*
> ```XML
> pub enum StatefulTransactionValidatorError {
>     #[error("Block number {block_number:?} is out of range.")]
>     BlockNumberOutOfRange { block_number: BlockNumber },
> ```

For consistency with names of out-of-range errors in papyrus and blockifier.



_Suggestion:_
```XML
    OutOfRangeBlockNumber { block_number: BlockNumber },
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6fcZ0tm3p4IVEFo1:-NvlBKjGA9mv5NVtq5rr:b-57tb6b) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L99)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Assuming `&ExternalTransaction` references an instance owned by the Gateway instance (inside `add_transaction` I guess?), then this might not work once we start running the validator in a separate thread.

In general, all values passed into a task that is to be executed in another thread should either transfer ownership of the value to the thread, be `&'static` or passed inside an `Arc`.
This is because regular (== non-`'static`) `&` references require the compiler to track the lifetime, which doesn't work across threads.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 24 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvksIfp1uGn-qjjYE5o:-NvksIfq6fWUf-zK31Ek:b-2c4a5g) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L24)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub chain_info: ChainInfo,
> }
> ```

Consider moving down, order of "things" in the file should be [by importance](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#order-of-items).
(But we haven't agreed to follow this style yet so non-blocking.)



_Code quote:_
```XML
pub struct StatefulTransactionValidatorConfig {
    pub max_nonce_for_validation_skip: Nonce,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub chain_info: ChainInfo,
}
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvksl_SBSfNE_0V14Jf:-Nvksl_SBSfNE_0V14Jg:b-4pxtgu) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L33)):*
> ```XML
>     pub fn new(config: StatefulTransactionValidatorConfig) -> Self {
>         Self { config }
>     }
> ```

No invariant on the `config` that we need to protect.
(Where "invariant" is like a vector that we assume is sorted or a hashmap that we assume contains certain keys.)



_Suggestion:_
```XML
    pub config: StatefulTransactionValidatorConfig,
}

impl StatefulTransactionValidator {
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvktdEJ4MLEVR9LxxZy:-NvktdEJ4MLEVR9LxxZz:b-7j8ey7) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L39)):*
> ```XML
>         // TODO(yael 17/4/24): the state_reader should be created inside the function taking
>         // latest_block_number.
>         state_reader: S,
> ```

sugar



_Suggestion:_
```XML
    pub fn run_validate(
        &self,
        // TODO(yael 17/4/24): the state_reader should be created inside the function taking
        // latest_block_number.
        state_reader: impl StateReader,
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 51 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkuSh1-2B4cyMibIwK:-NvkuSh24KR1auDxb1Ll:b-q65eto) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L51)):*
> ```XML
>             self.config.max_recursion_depth,
>         );
>         let mut block_info = latest_block_info;
> ```

But don't bother if this is temp code (which might be implied from the TODO?)



_Suggestion:_
```XML
        //TODO(yael 17/4/24): the latest_block_info should be read from the storage.
        mut block_info: BlockInfo,
        external_tx: &ExternalTransaction,
        deploy_account_tx_hash: Option<TransactionHash>,
        optional_class_info: Option<ClassInfo>,
    ) -> StatefulTransactionValidatorResult<()> {
        let state = CachedState::new(state_reader);
        let versioned_constants = VersionedConstants::latest_constants_with_overrides(
            self.config.validate_max_n_steps,
            self.config.max_recursion_depth,
        );
        
```
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkvQOV2ih3ARJcfRJ8:-NvkvQOV2ih3ARJcfRJ9:b-um8z20) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
> ```XML
>         )?;
>         let block_context =
>             BlockContext::new_unchecked(&block_info, &self.config.chain_info, &versioned_constants);
> ```

Why can't use `pre_process_block` to create `Blockcontext`?



_Code quote:_
```XML
            BlockContext::new_unchecked(&block_info, &self.config.chain_info, &versioned_constants);
```
___
*[`crates/gateway/src/utils.rs` line 18 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkydxYBDQXhKemI4r3:-NvkydxYBDQXhKemI4r4:bo58rih) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L18)):*
> ```XML
> };
> 
> pub fn external_tx_to_account_tx(
> ```

@MohammadNassar1 If you have a moment can you TAL at the cast? 



_Code quote:_
```XML
pub fn external_tx_to_account_tx(
```
___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkyOdDC_RPUKI0if-7:-NvkyOdDC_RPUKI0if-8:bfpjqm9) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
> ```XML
> pub fn external_tx_to_account_tx(
>     external_tx: &ExternalTransaction,
>     optional_class_info: Option<ClassInfo>,
> ```

I think `ContractClass` appears twice here, once in `ExternalTransaction::Declare` and once in `ClassInfo`, is that intentional?
Or is that because `external_tx` is a reference, so we gotta clone the ContractClass anyway?

BTW performace-wise this isn't critical, because deep down ContractClass is an Arc anyway, it's more about the coupling between them that requires that `expect` later below  



_Code quote:_
```XML
    external_tx: &ExternalTransaction,
    optional_class_info: Option<ClassInfo>,
```
___
*[`crates/gateway/src/utils.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkxDP97iwZ1EfddoyE:-NvkxDP97iwZ1EfddoyF:bp1py89) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L26)):*
> ```XML
>         ExternalTransaction::Declare(ExternalDeclareTransaction::V3(tx)) => {
>             let declare_tx = DeclareTransaction::V3(DeclareTransactionV3 {
>    [...]

2024-04-21 09:25 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/errors.rs` line 50 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvkv70GDrUkV3_Tjqa-:-NvzkJIK9GIIYC1I8unw:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/errors.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For consistency with names of out-of-range errors in papyrus and blockifier.
</blockquote></details>

Done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nva6fcZ0tm3p4IVEFo1:-NvzltpH3KKPJySdU0Wp:bxp2pg5) ([raw file](https://github.com/starkware-libs/mempool/blob/9d1fb9206b512f6aa8c7f0d9d86274a3569b8650/crates/gateway/src/stateful_transaction_validator.rs#L99)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Assuming `&ExternalTransaction` references an instance owned by the Gateway instance (inside `add_transaction` I guess?), then this might not work once we start running the validator in a separate thread.

In general, all values passed into a task that is to be executed in another thread should either transfer ownership of the value to the thread, be `&'static` or passed inside an `Arc`.
This is because regular (== non-`'static`) `&` references require the compiler to track the lifetime, which doesn't work across threads.
</blockquote></details>

Got it! good point.
I think that we will handle these things once we start working with threads.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 24 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvksIfp1uGn-qjjYE5o:-NvzkSZP1CJpgdU9FnWj:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Consider moving down, order of "things" in the file should be [by importance](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#order-of-items).
(But we haven't agreed to follow this style yet so non-blocking.)
</blockquote></details>

done.
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nvksl_SBSfNE_0V14Jf:-NvzkeFq6m10FDfvEZeh:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L33)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No invariant on the `config` that we need to protect.
(Where "invariant" is like a vector that we assume is sorted or a hashmap that we assume contains certain keys.)
</blockquote></details>

done
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvktdEJ4MLEVR9LxxZy:-NvzkfQo-B6pyIdbxzzd:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

sugar
</blockquote></details>

done
___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkvQOV2ih3ARJcfRJ8:-NvzkrX963c-3EdyMbkl:b-ietwm7) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Why can't use `pre_process_block` to create `Blockcontext`?
</blockquote></details>

good point, I need to get the block hash of 10 blocks ago though. I don't think this is required for the PoC, will add a TODO and add this once the RPC reads will get some structure.
___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkyOdDC_RPUKI0if-7:-NvzxE7g2DtZDRasrK0G:bgkaw3g) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think `ContractClass` appears twice here, once in `ExternalTransaction::Declare` and once in `ClassInfo`, is that intentional?
Or is that because `external_tx` is a reference, so we gotta clone the ContractClass anyway?

BTW performace-wise this isn't critical, because deep down ContractClass is an Arc anyway, it's more about the coupling between them that requires that `expect` later below
</blockquote></details>

as @MohammadNassar1 explained to me,  these are two different CoontractClass type
the ContractClass for external is sierra , and for accountTransaction is casm
___
*[`crates/gateway/src/utils.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkxDP97iwZ1EfddoyE:-Nvzue3R5btlrkidXcV7:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nit: use FIXME instead of TODO; former is for must-haves and the latter for nice-to-haves
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-04-21 09:48 UTC, MohammadNassar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nw-28TnBTIlQSHWFBCm:-Nw-28TnBTIlQSHWFBCn:bmi59h2) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
> ```XML
> pub fn external_tx_to_account_tx(
>     external_tx: &ExternalTransaction,
>     optional_class_info: Option<ClassInfo>,
> ```

How do you pass this argument?
I think you need to create this argument from the external class by compiling the contract.



_Code quote:_
```XML
optional_class_info: Option<ClassInfo>,
```
___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkyOdDC_RPUKI0if-7:-Nw-2SO778h2aBrBmcfG:btslsn) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

as @MohammadNassar1 explained to me,  these are two different CoontractClass type
the ContractClass for external is sierra , and for accountTransaction is casm
</blockquote></details>

Correct.
But note that in GW we get an external class, and then we need to compile the contract to get the other type.
___
*[`crates/gateway/src/utils.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nw-1QDu6t2nTFcDogxg:-Nw-1QDu6t2nTFcDogxh:b2mi5sp) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L22)):*
> ```XML
>     optional_class_info: Option<ClassInfo>,
> ) -> StatefulTransactionValidatorResult<AccountTransaction> {
>     let tx_hash = TransactionHash::default(); //TODO(yael 15/4/24): make TransactionHasher public in starknet-api
> ```

First, create the declare_tx, and then use this method to calculate tx hash:
declare_tx.calculate_transaction_hash()
See an example in [this](https://reviewable.io/reviews/starkware-libs/starknet-api/230) PR.



_Code quote:_
```XML
let tx_hash = TransactionHash::default(); //TODO(yael 15/4/24): make TransactionHasher public in starknet-api
```


<!-- Sent from Reviewable.io -->

2024-04-21 09:50 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nw-28TnBTIlQSHWFBCm:-Nw-31vkEQ3lo6YiUNfI:b-3hcr01) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

How do you pass this argument?
I think you need to create this argument from the external class by compiling the contract.
</blockquote></details>

I added a FIXME (aka TODO) now for this.


<!-- Sent from Reviewable.io -->

2024-04-21 10:08 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 6 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/utils.rs` line 18 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkydxYBDQXhKemI4r3:-Nw-76XI50KU-UhKdRfF:bb7f2mf) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@MohammadNassar1 If you have a moment can you TAL at the cast?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-04-21 11:50 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 6 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/utils.rs` line 20 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkyOdDC_RPUKI0if-7:-Nw-TyYz-q8o4EeCjiwh:bfe4tps) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L20)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct.
But note that in GW we get an external class, and then we need to compile the contract to get the other type.
</blockquote></details>

ack. waiting for this code to be ready. not for the Poc anyway.
___
*[`crates/gateway/src/utils.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-Nw-1QDu6t2nTFcDogxg:-Nw-Tx59-4vxp4iswYbL:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/utils.rs#L22)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

First, create the declare_tx, and then use this method to calculate tx hash:
declare_tx.calculate_transaction_hash()
See an example in [this](https://reviewable.io/reviews/starkware-libs/starknet-api/230) PR.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-04-25 10:36 UTC, ArniStarkware approved these changes
> Reviewed 1 of 4 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 5 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-04-30 05:57 UTC, MohammadNassar1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-30 05:57 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

LGTMed the conversion part.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-Nwh_2ni4Q86lT9wBy29:bklb4po)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-30 06:48 UTC, ArniStarkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-01 09:58 UTC, giladchase reviewed
Looks like this hit a bug in udeps: when compiling from source, as we currently do in the CI, this hits the compilation error.
But when installation from crates.io, there error doesn't appear.

PTAL a fix for this, which installs udeps via crates.io in the CI rather then compiling from source.
It seemed to fix the issue here

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-Nwn4wFw3_WrQTRcwfzI:b-c3or76)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-05-01 10:05 UTC, giladchase reviewed
https://github.com/starkware-libs/mempool/pull/82

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-Nwn_pAQ-1U99AFlsWsO:ba2nk69)* status: all files reviewed, 4 unresolved discussions (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-05-01 10:37 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-NwnipuC3Mont7s1aG9g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkvQOV2ih3ARJcfRJ8:-NwniT6H0UEPdY6MFhPp:b-ccbuur) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

good point, I need to get the block hash of 10 blocks ago though. I don't think this is required for the PoC, will add a TODO and add this once the RPC reads will get some structure.
</blockquote></details>

Good point yourself


<!-- Sent from Reviewable.io -->

2024-05-01 12:25 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/stateful_transaction_validator.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/mempool/42#-NvkvQOV2ih3ARJcfRJ8:-NwEJSFK79-diFnKt0JH:b-uvnkpw) ([raw file](https://github.com/starkware-libs/mempool/blob/a58063fba0f391b3c3373632ce910c307a337874/crates/gateway/src/stateful_transaction_validator.rs#L58)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

good point, I need to get the block hash of 10 blocks ago though. I don't think this is required for the PoC, will add a TODO and add this once the RPC reads will get some structure.
</blockquote></details>

after discussing with @dafnamatsry , updating the block_hash of block-10 may be a separate task from the validator, will continue to discuss separately.


<!-- Sent from Reviewable.io -->

2024-05-01 13:23 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/42#-:-NwoIdgv69YzS3aYT5WI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-05-01 13:38 UTC, merged