refactor: gateway compiler handle declare tx
starkware-libs/mempool pull request #439
Opened 2024-07-11 07:45 UTC by ArniStarkware

2024-07-11 07:45 UTC, ArniStarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/439?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#439** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/439?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#391** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/391?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#298](https://github.com/starkware-libs/mempool/pull/298) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/298?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/383?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#392](https://github.com/starkware-libs/mempool/pull/392) <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/392?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ArniStarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-11 10:59 UTC, Yael-Starkware requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1WQdD20zJs-8AL7G1y:-O1WQdD38cVaCEKqGhXI:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/4d7678f151315467b15a380aa33d1680ca6ff546/crates/gateway/src/compilation.rs#L46)):*
> ```XML
>         self.validate_casm_class(&casm_contract_class)?;
> 
>         build_result_class_info(
> ```





_Suggestion:_
```XML
into_class_info
```


<!-- Sent from Reviewable.io -->

2024-07-11 11:32 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1WQdD20zJs-8AL7G1y:-O1WZCsC-x_exW7WANQf:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/4d7678f151315467b15a380aa33d1680ca6ff546/crates/gateway/src/compilation.rs#L46)):*
> ```XML
>         self.validate_casm_class(&casm_contract_class)?;
> 
>         build_result_class_info(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-14 07:23 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k3hbQ8EkI4M7Thvgk:-O1k3hbR0h-GPBaFcmXQ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation.rs#L118)):*
> ```XML
> fn validate_compiled_class_hash(
>     casm_contract_class: &CasmContractClass,
>     suppled_compiled_class_hash: CompiledClassHash,
> ```





_Suggestion:_
```XML
supplied_compiled_class_hash
```
___
*[`crates/gateway/src/compilation_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k40pn0whYgoD9uZBJ:-O1k40pn0whYgoD9uZBK:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L25)):*
> ```XML
> 
> #[rstest]
> fn test_compile_contract_class_compiled_class_hash_missmatch(
> ```





_Suggestion:_
```XML
mismatch
```
___
*[`crates/gateway/src/compilation_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k4CJ5AtIfsJGnnFG8:-O1k4CJ5AtIfsJGnnFG9:b-d3ch7q) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L37)):*
> ```XML
>         GatewayError::CompiledClassHashMismatch { supplied, hash_result }
>         if supplied == supplied_hash && hash_result == expected_hash_result
>     );
> ```

you can use assert_eq here



_Code quote:_
```XML
    assert_matches!(
        result.unwrap_err(),
        GatewayError::CompiledClassHashMismatch { supplied, hash_result }
        if supplied == supplied_hash && hash_result == expected_hash_result
    );
```
___
*[`crates/gateway/src/compilation_test.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k4e5r9jmdw0gLsCoN:-O1k4e5r9jmdw0gLsCoO:bb7od0r) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L55)):*
> ```XML
>             AllowedLibfuncsError::SierraProgramError
>         ))
>     )
> ```

same



_Code quote:_
```XML
    assert_matches!(
        result.unwrap_err(),
        GatewayError::CompilationError(CompilationUtilError::AllowedLibfuncsError(
            AllowedLibfuncsError::SierraProgramError
        ))
    )
```
___
*[`crates/gateway/src/gateway.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k5Vb365As42BkOCVm:-O1k5Vb365As42BkOCVn:b4dlbb7) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/gateway.rs#L131)):*
> ```XML
>     let optional_class_info = match &tx {
>         RPCTransaction::Declare(declare_tx) => {
>             Some(gateway_compiler.handle_declare_tx(declare_tx)?)
> ```

not sure about the name, it is a bit too general
declare_tx_is handled also in the stateful and stateless validator.

how about process_declare_tx / calculate_class_info ?



_Code quote:_
```XML
handle_declare_tx
```


<!-- Sent from Reviewable.io -->

2024-07-14 08:00 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k3hbQ8EkI4M7Thvgk:-O1k9KrM0MY13iIl-Gy8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation.rs#L118)):*
> ```XML
> fn validate_compiled_class_hash(
>     casm_contract_class: &CasmContractClass,
>     suppled_compiled_class_hash: CompiledClassHash,
> ```

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k40pn0whYgoD9uZBJ:-O1k9QTk7Nqba295mb5x:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L25)):*
> ```XML
> 
> #[rstest]
> fn test_compile_contract_class_compiled_class_hash_missmatch(
> ```

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k4CJ5AtIfsJGnnFG8:-O1k9uT5-Gm--6f5m76Z:bblk9fe) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L37)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

you can use assert_eq here
</blockquote></details>

The enum `GatewayError` can not derive PartialEq (it contains many variants that do not support it, like `JoinError`). 
___
*[`crates/gateway/src/compilation_test.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k4e5r9jmdw0gLsCoN:-O1kALDC-W5b33uWLJYz:b-816h6l) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/compilation_test.rs#L55)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

same
</blockquote></details>

Same.
___
*[`crates/gateway/src/gateway.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k5Vb365As42BkOCVm:-O1kAbdEB-mh05q0BNS7:b-7fg3fj) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/gateway.rs#L131)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure about the name, it is a bit too general
declare_tx_is handled also in the stateful and stateless validator.

how about process_declare_tx / calculate_class_info ?
</blockquote></details>

1. Done.
2. I think part of the issue is that the struct is called `gateway_compiler`. Do you have a better suggestion for a name for it?
3. We look for a verb that says "doing this component's job on a declare tx". 


<!-- Sent from Reviewable.io -->

2024-07-14 09:10 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/gateway/src/gateway.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1k5Vb365As42BkOCVm:-O1kV-jv23Rhc3Kyg_EO:bmkkbqo) ([raw file](https://github.com/starkware-libs/mempool/blob/69da6def6448e6f07d0f61cde3166d68d8f4e26d/crates/gateway/src/gateway.rs#L131)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. Done.
2. I think part of the issue is that the struct is called `gateway_compiler`. Do you have a better suggestion for a name for it?
3. We look for a verb that says "doing this component's job on a declare tx".
</blockquote></details>

All it does is compilation and validation of the related fields , right?
so maybe Compiler is fine.
why is the word gateway needed? since it uses gateway size limits?  
sounds ok to me.


<!-- Sent from Reviewable.io -->

2024-07-14 13:22 UTC, yair-starkware reviewed
> Reviewed 1 of 6 files at r1, 4 of 9 files at r3, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/gateway/src/compilation.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1lNu0y95yj5oUScL9C:-O1lNu0z2zU8flz4uY6X:benikn8) ([raw file](https://github.com/starkware-libs/mempool/blob/620444a026553031b6ca9828a31dc6fb05b05621/crates/gateway/src/compilation.rs#L107)):*
> ```XML
>     sierra_program_len: usize,
>     abi_len: usize,
> ) -> GatewayResult<ClassInfo> {
> ```

Consider implementing as a TryFrom trait
```
pub type SierraProgramLen = usize;
pub AbiLen = usize;
impl TryFrom<(CasmContractClass, SierraProgramLen, AbiLen)> for ClassInfo
```



_Code quote:_
```XML
fn into_class_info(
    casm_contract_class: CasmContractClass,
    sierra_program_len: usize,
    abi_len: usize,
) -> GatewayResult<ClassInfo> {
```


<!-- Sent from Reviewable.io -->

2024-07-14 14:01 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/mempool/439#-O1lNu0y95yj5oUScL9C:-O1lWx1-8NkGujQnjEHf:btai6k) ([raw file](https://github.com/starkware-libs/mempool/blob/620444a026553031b6ca9828a31dc6fb05b05621/crates/gateway/src/compilation.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider implementing as a TryFrom trait
```
pub type SierraProgramLen = usize;
pub AbiLen = usize;
impl TryFrom<(CasmContractClass, SierraProgramLen, AbiLen)> for ClassInfo
```
</blockquote></details>

It is odd to write a `try_into` from a tuple of structs, which uses the `new` method of `ClassInfo`, isn't it?

Here is another design.


<!-- Sent from Reviewable.io -->

2024-07-15 07:47 UTC, ArniStarkware reviewed
+reviewer:@dafnamatsry 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439#-:-O1pM7FgBxaRqgu0Fodv:brl3ymz)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @dafnamatsry and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 14:55 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439#-:-O1qt9324zdmUGddBMPc:bnfp4nl)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-07-18 09:08 UTC, dafnamatsry requested changes
> Reviewed 1 of 6 files at r4, 2 of 4 files at r6, 1 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 7 of 11 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O244ZofD-iJsDosU3Ja:-O244ZofD-iJsDosU3Jb:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L56)):*
> ```XML
>     fn compile(
>         &self,
>         cairo_lang_contract_class: CairoLangContractClass,
> ```





_Suggestion:_
```XML
cairo_lang_contract_class: &CairoLangContractClass
```
___
*[`crates/gateway/src/compilation.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O242JzJ-ffk79L_Elg6:-O242JzJ-ffk79L_Elg7:bi41hcq) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L66)):*
> ```XML
>                 Err(GatewayError::CompilationError(CompilationUtilError::CompilationPanic))
>             }
>         }
> ```

Please use `map_err`.



_Code quote:_
```XML
        match catch_unwind_result {
            Ok(compilation_result) => Ok(compilation_result?),
            Err(_) => {
                // TODO(Arni): Log the panic.
                Err(GatewayError::CompilationError(CompilationUtilError::CompilationPanic))
            }
        }
```
___
*[`crates/gateway/src/compilation.rs` line 104 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24-t_VCj4YaIJM3PME:-O24-t_W8C1MX-qs4gID:bryaejo) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L104)):*
> ```XML
> /// Validates that the compiled class hash of the compiled contract class matches the supplied
> /// compiled class hash.
> fn validate_compiled_class_hash(
> ```

Should it be also a method of the `Compiler` like `validate_casm_class`?



_Code quote:_
```XML
validate_compiled_class_hash
```
___
*[`crates/gateway/src/compilation.rs` line 106 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O23xqEVBoug4m9Bf2hL:-O23xqEVBoug4m9Bf2hM:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L106)):*
> ```XML
> fn validate_compiled_class_hash(
>     casm_contract_class: &CasmContractClass,
>     supplied_compiled_class_hash: CompiledClassHash,
> ```





_Suggestion:_
```XML
&CompiledClassHash
```
___
*[`crates/gateway/src/compilation_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2436hoE38NSTwblXeC:-O2436hoE38NSTwblXeD:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L30)):*
> ```XML
> ) {
>     let supplied_hash = CompiledClassHash::default();
>     let expected_hash_result = compiled_class_hash;
> ```





_Suggestion:_
```XML
    let wrong_supplied_hash = CompiledClassHash::default();
    let expected_hash = compiled_class_hash;
```
___
*[`crates/gateway/src/compilation_test.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24420z8Ck-siAGqtvi:-O24420z8Ck-siAGqtvj:b-71gold) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L32)):*
> ```XML
>     let expected_hash_result = compiled_class_hash;
> 
>     let result = validate_compiled_class_hash(&casm_contract_class, supplied_hash);
> ```

Please call `process_declare_tx` which is the public API of the compiler, and the one we want to test.



_Code quote:_
```XML
let result = validate_compiled_class_hash(&casm_contract_class, supplied_hash);
```
___
*[`crates/gateway/src/compilation_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O243WWC8pUry9Qplaor:-O243WWDBXU9X3J-QePa:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L45)):*
> ```XML
>     mut contract_class: RpcContractClass,
> ) {
>     // Create a currupted contract class.
> ```





_Suggestion:_
```XML
corrupted
```
___
*[`crates/gateway/src/compilation_test.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O244D5PCNNV0LzJmZPa:-O244D5PCNNV0LzJmZPb:bpzsnf0) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L49)):*
> ```XML
> 
>     let cairo_lang_contract_class = into_contract_class_for_compilation(&contract_class);
>     let result = gateway_compiler.compile(cairo_lang_contract_class);
> ```

Same here. call `process_declare_tx`.



_Code quote:_
```XML
gateway_compiler.compile
```
___
*[`crates/gateway/src/compilation_test.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O243hYTCAiUnWYZrCS5:-O243hYTCAiUnWYZrCS6:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L59)):*
> ```XML
> 
> #[rstest]
> fn test_handle_declare_tx(gateway_compiler: GatewayCompiler) {
> ```





_Suggestion:_
```XML
test_process_declare_tx_success
```


<!-- Sent from Reviewable.io -->

2024-07-18 11:22 UTC, dafnamatsry reviewed
> Reviewed 1 of 6 files at r1, 2 of 9 files at r3, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 10 of 11 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-18 12:41 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 10 of 11 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @dorimedini-starkware, and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 56 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O244ZofD-iJsDosU3Ja:-O24SthT-T298PV_GTKV:b-g59553) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L56)):*
> ```XML
>     fn compile(
>         &self,
>         cairo_lang_contract_class: CairoLangContractClass,
> ```

The function: `CasmContractClass::from_contract_class` (from the cairo-lang crate) takes ownership of the `CairoLangContractClass`
___
*[`crates/gateway/src/compilation.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O242JzJ-ffk79L_Elg6:-O24XBjqEnSmVt433PY6:b-c0dlx) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please use `map_err`.
</blockquote></details>

Done.
(Thank @dorimedini-starkware - for making us not overthink stuff).
___
*[`crates/gateway/src/compilation.rs` line 104 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24-t_VCj4YaIJM3PME:-O24fZVC6Km_3vRPqP_w:b-2b4cdg) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L104)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Should it be also a method of the `Compiler` like `validate_casm_class`?
</blockquote></details>

I did not make it a method as it does not use `self`. I have no objection.
___
*[`crates/gateway/src/compilation.rs` line 106 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O23xqEVBoug4m9Bf2hL:-O24g-aj0b4_j2CTDRL9:bj2il5h) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L106)):*
> ```XML
> fn validate_compiled_class_hash(
>     casm_contract_class: &CasmContractClass,
>     supplied_compiled_class_hash: CompiledClassHash,
> ```

Done. 
Does not make much of a difference as this struct implements `Copy`. 
___
*[`crates/gateway/src/compilation_test.rs` line 30 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2436hoE38NSTwblXeC:-O24gQNTEuVLdOye-ZWB:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L30)):*
> ```XML
> ) {
>     let supplied_hash = CompiledClassHash::default();
>     let expected_hash_result = compiled_class_hash;
> ```

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24420z8Ck-siAGqtvi:-O24qVlCDXoFLNeAIs8a:bbhuffi) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L32)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please call `process_declare_tx` which is the public API of the compiler, and the one we want to test.
</blockquote></details>

I disagree. This is a unit test for the `validate_compiled_class_hash` function.
(the declare tx is irrelevant).

This was the original intent for this refactor, per @yair-starkware 's suggestion.
___
*[`crates/gateway/src/compilation_test.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O243WWC8pUry9Qplaor:-O24qH9UDtJKtb8WP6M-:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L45)):*
> ```XML
>     mut contract_class: RpcContractClass,
> ) {
>     // Create a currupted contract class.
> ```

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O244D5PCNNV0LzJmZPa:-O24qhFB3DEfMk83_1PI:bhwbf8w) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Same here. call `process_declare_tx`.
</blockquote></details>

This is a unit test for `compile`.

(the declare tx is irrelevant).
___
*[`crates/gateway/src/compilation_test.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O243hYTCAiUnWYZrCS5:-O24r-KR4rDRqGfMk4U-:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L59)):*
> ```XML
> 
> #[rstest]
> fn test_handle_declare_tx(gateway_compiler: GatewayCompiler) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-18 13:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 8 of 11 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 66 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O242JzJ-ffk79L_Elg6:-O24vY1BBOVLk8LdJLmu:be9k6mg) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L66)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
(Thank @dorimedini-starkware - for making us not overthink stuff).
</blockquote></details>

:saluting_face: 


<!-- Sent from Reviewable.io -->

2024-07-22 10:38 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 104 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24-t_VCj4YaIJM3PME:-O2OZIeO6lGawqrEvDsz:b-7obace) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation.rs#L104)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The other validate_* method gets self, but does not use it, so just make them consistent with each other.
</blockquote></details>

Done*.
The method, `compile` still keeps its `self`. In the following PR: #348 `compile` uses `self`.
___
*[`crates/gateway/src/compilation_test.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O24420z8Ck-siAGqtvi:-O2OajHl8N1z9RRirHV_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L32)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Discussed f2f.
</blockquote></details>

Done.
___
*[`crates/gateway/src/compilation_test.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/mempool/439#-O244D5PCNNV0LzJmZPa:-O2OaETz5bDLsF6dKWWC:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/81954d08e4849efdb77383688fde304db181d3e1/crates/gateway/src/compilation_test.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Discussed f2f.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 06:35 UTC, dafnamatsry requested changes
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2TC7VQ3N5BLrBNq7lt:-O2TC7VQ3N5BLrBNq7lu:bx5lhif) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/gateway/src/compilation.rs#L54)):*
> ```XML
> 
>     // TODO(Arni): Pass the compilation args from the config.
>     // TODO(Arni): Pass the compiler with dependancy injection.
> ```

Note that the compiler should be injected to `process_declare_tx` and not here, which is the actual compile implementation.



_Code quote:_
```XML
// TODO(Arni): Pass the compiler with dependancy injection.
```
___
*[`crates/gateway/src/compilation_test.rs` line 29 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2TETcs5dco4vxsuDIQ:-O2TETcs5dco4vxsuDIR:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/gateway/src/compilation_test.rs#L29)):*
> ```XML
> 
>     tx.compiled_class_hash = supplied_hash;
>     let declare_tx = RPCDeclareTransaction::V3(tx);
> ```





_Suggestion:_
```XML
    let expected_hash = tx.compiled_class_hash;
    let wrong_supplied_hash = CompiledClassHash::default();
    tx.compiled_class_hash = wrong_supplied_hash;

    let declare_tx = RPCDeclareTransaction::V3(tx);
```
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 95 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2THQMp4U0bdab_yFhA:-O2THQMp4U0bdab_yFhB:b-880hvm) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L95)):*
> ```XML
> 
> /// Get the contract class used for testing.
> #[fixture]
> ```

Not used as a fixture anymore I think. Also `compiled_class_hash()`



_Code quote:_
```XML
#[fixture]
```


<!-- Sent from Reviewable.io -->

2024-07-23 10:49 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @yair-starkware)

___
*[`crates/gateway/src/compilation.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2TC7VQ3N5BLrBNq7lt:-O2U7abi43TX-cgAhHTu:b9pojai) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/gateway/src/compilation.rs#L54)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Note that the compiler should be injected to `process_declare_tx` and not here, which is the actual compile implementation.
</blockquote></details>

Moved the todo to a more relevant place.
___
*[`crates/gateway/src/compilation_test.rs` line 29 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2TETcs5dco4vxsuDIQ:-O2Tg5ih161L-SX_lTkF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/gateway/src/compilation_test.rs#L29)):*
> ```XML
> 
>     tx.compiled_class_hash = supplied_hash;
>     let declare_tx = RPCDeclareTransaction::V3(tx);
> ```

Done.
___
*[`crates/mempool_test_utils/src/starknet_api_test_utils.rs` line 95 at r10](https://reviewable.io/reviews/starkware-libs/mempool/439#-O2THQMp4U0bdab_yFhA:-O2TgXMh8tqzKDXOADiF:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/33642fbe3e5d4b92b86efcbd79be630cd50d32a8/crates/mempool_test_utils/src/starknet_api_test_utils.rs#L95)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not used as a fixture anymore I think. Also `compiled_class_hash()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 11:01 UTC, dafnamatsry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439#-:-O2UFGvw89Gu3pX145ei:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-23 12:07 UTC, dafnamatsry approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/439)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2024-07-23 13:54 UTC, merged