feat: add custom accounts to test rpc state reader
starkware-libs/mempool pull request #454
Opened 2024-07-11 13:49 UTC by giladchase

Make `spawn_test_rpc_state_reader` get an iterator of accounts and have count the number of occurrences by itself, instead of getting specific numbers per account.

To keep the diff small, the map of contract->n_instances_of_contract is cast back to the old type immediately.
Subsequent PRs will remove this cast and make the whole flow use the map.

2024-07-11 13:50 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/tests-integration/src/state_reader.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1X2gIj5EZlZHjj0P__:-O1X2gIk9yEN_IIS7XKX:b-4qmi9b) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/state_reader.rs#L64)):*
> ```XML
>     // map feature contracts to n_instances inside the account array
>     let mut account_to_n_instances: IndexMap<FeatureContract, usize> =
>         IndexMap::from_iter(accounts.into_iter().counts());
> ```

This line will compile once [this Blockifier PR](https://reviewable.io/reviews/starkware-libs/blockifier/2077) is merged.



_Code quote:_
```XML
        IndexMap::from_iter(accounts.into_iter().counts());
```


<!-- Sent from Reviewable.io -->

2024-07-14 06:08 UTC, Yael-Starkware requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqaJwCZlqjJ3YpkfL:-O1jqaJwCZlqjJ3YpkfM:b-dzmlx7) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/integration_test_setup.rs#L34)):*
> ```XML
>         let default_account_contract =
>             FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
>         let accounts = std::iter::repeat(default_account_contract).take(n_accounts);
> ```

I think creating the IndexMap here, to begin with, will be simpler, and then you can remove the conversion to indexMap that follows,



_Code quote:_
```XML
let accounts = std::iter::repeat(default_account_contract).take(n_accounts);
```
___
*[`crates/tests-integration/src/state_reader.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqIIrB3gkTOE8V9hh:-O1jqIIrB3gkTOE8V9hi:b-6hz3af) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/state_reader.rs#L58)):*
> ```XML
> /// A variable number of identical accounts and test contracts are initialized and funded.
> pub async fn spawn_test_rpc_state_reader(
>     accounts: impl IntoIterator<Item = FeatureContract>,
> ```

as commented above, 
why not get here the account_to_n_instances IndexMap in the first place? 
And then remove the conversion to IndexMap.



_Code quote:_
```XML
accounts:
```
___
*[`crates/tests-integration/src/state_reader.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jpf9p9OlBryzffjAN:-O1jpf9p9OlBryzffjAO:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/state_reader.rs#L70)):*
> ```XML
>     for contract in [
>         FeatureContract::TestContract(CairoVersion::Cairo0),
>         FeatureContract::TestContract(CairoVersion::Cairo0),
> ```





_Suggestion:_
```XML
CairoVersion::Cairo1
```


<!-- Sent from Reviewable.io -->

2024-07-15 06:00 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqaJwCZlqjJ3YpkfL:-O1kpFWx2QEmfOVn5Vtg:b-aw35n3) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/integration_test_setup.rs#L34)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think creating the IndexMap here, to begin with, will be simpler, and then you can remove the conversion to indexMap that follows,
</blockquote></details>

I agree it's inefficient, but we should hide non-intuitive implementation details like instance_ids from the API, which makes the API easier to understand for the user (the testwriter).

I suggest merging this version first, if OK by you then immediately think about refactoring. This approach keeps the current stack simpler and allows us to improve working code, rather than divergent components.
___
*[`crates/tests-integration/src/state_reader.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jpf9p9OlBryzffjAN:-O1oyWbc9SkeQ1zULdX4:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/state_reader.rs#L70)):*
> ```XML
>     for contract in [
>         FeatureContract::TestContract(CairoVersion::Cairo0),
>         FeatureContract::TestContract(CairoVersion::Cairo0),
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 09:06 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqaJwCZlqjJ3YpkfL:-O1pcoET6kd7Gt0waLjw:bgal1sa) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/integration_test_setup.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I agree it's inefficient, but we should hide non-intuitive implementation details like instance_ids from the API, which makes the API easier to understand for the user (the testwriter).

I suggest merging this version first, if OK by you then immediately think about refactoring. This approach keeps the current stack simpler and allows us to improve working code, rather than divergent components.
</blockquote></details>

but the API is new(n_accounts), and that pretty straightforward. if someone needs to change the internal functions , they will have to understand the logic anyway.

Sure we can discuss later
___
*[`crates/tests-integration/src/state_reader.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqIIrB3gkTOE8V9hh:-O1pdExx1idxQRFfJ0B8:bb7oryy) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/state_reader.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No one will understand why such a structure is needed I think, except us two and Dori, it is too arcane, not natural ("why does a state-reader need a hashmap of feature to n-instances? can't it fund them without this?")

Perhaps an abstraction is needed for this, but this is out of scope here I think, since this is still a stabilization PR.

I suggest discussing a refactor after we stabilize the test.
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2024-07-15 12:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqaJwCZlqjJ3YpkfL:-O1q9uEG4u5YmtutC18M:b9unnfj) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/integration_test_setup.rs#L34)):*
>but the API is new(n\_accounts), and that pretty straightforward

`new(n_accounts)` is only part of the API, and in fact it is the one not currently used (but will be used soon).

Right now we're using `new_for_accounts_contracts(accounts)`.

Also, I don't see how this follows your previous message :thinking:  you suggested passing a hashmap as an arg, and if a user is using new(n_accounts), they'll still need to pass a hashmap, only now it'll have one key.

> if someone needs to change the internal functions , they will have to understand the logic anyway.

Not all of the logic. 
The whole stack of SetupIntegrationTest and the state reader initialization is quite big, and if someone needs to change something small there, it should be easy for them to jump in and do it, without having to any implementation details they don't need to.
In particular, the whole instance_id thing is quite unintuitive, and it'd be best to hide that one as much as possible, otherwise the tax on developer time will be big in the long run.


<!-- Sent from Reviewable.io -->

2024-07-15 12:44 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @giladchase)

___
*[`crates/tests-integration/src/integration_test_setup.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/mempool/454#-O1jqaJwCZlqjJ3YpkfL:-O1qPukN9XEki1F9IDCj:b2nhysk) ([raw file](https://github.com/starkware-libs/mempool/blob/21295972d979cd8ad234916ae6c8e11b91f4cf0d/crates/tests-integration/src/integration_test_setup.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>but the API is new(n\_accounts), and that pretty straightforward

`new(n_accounts)` is only part of the API, and in fact it is the one not currently used (but will be used soon).

Right now we're using `new_for_accounts_contracts(accounts)`.

Also, I don't see how this follows your previous message :thinking:  you suggested passing a hashmap as an arg, and if a user is using new(n_accounts), they'll still need to pass a hashmap, only now it'll have one key.

> if someone needs to change the internal functions , they will have to understand the logic anyway.

Not all of the logic. 
The whole stack of SetupIntegrationTest and the state reader initialization is quite big, and if someone needs to change something small there, it should be easy for them to jump in and do it, without having to any implementation details they don't need to.
In particular, the whole instance_id thing is quite unintuitive, and it'd be best to hide that one as much as possible, otherwise the tax on developer time will be big in the long run.
</blockquote></details>

ack


<!-- Sent from Reviewable.io -->

2024-07-15 12:44 UTC, Yael-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: 2 of 13 files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-07-15 13:16 UTC, giladchase reviewed
> Reviewed 3 of 5 files at r1, 1 of 9 files at r2, 6 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2024-07-15 13:16 UTC, merged