feat: implement mempool struct and get_tx function
starkware-libs/mempool pull request #46
Opened 2024-04-11 11:07 UTC by ayeletstarkware

2024-04-14 12:36 UTC, giladchase requested changes
Can you plz switch priority_queue to be pub(crate) in lib.rs? (and remove the todo above it in lib.rs)
It was made public only because it wasn't used yet, but now that it is, it can be pub(crate).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46#-:-NvRLxF0A8IQfaqy_GHg:b-79a5yt)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRMEYVCZCnRDbf6Yw8:-NvRMEYVCZCnRDbf6Yw9:b-7ilvfu) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool.rs#L18)):*
> ```XML
>     /// Transactions are guaranteed to be unique across calls until `commit_block` is invoked.
>     // TODO: the last part about commit_block is incorrect if we delete txs in get_txs and then push back.
>     pub fn get_tx(&mut self, n_txs: usize) -> MempoolResult<Vec<InternalTransaction>> {
> ```

typo?



_Suggestion:_
```XML
get_txs
```
___
*[`crates/mempool/src/mempool_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRamfC7gX0NEHtQZ3s:-NvRamfC7gX0NEHtQZ3t:buyg9mt) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L30)):*
> ```XML
>             ),
>         ])
>         .expect("Resource bounds mapping has unexpected structure."),
> ```

You can unwrap here (it's a test and the reason why this should work is clear)



_Code quote:_
```XML
        .expect("Resource bounds mapping has unexpected structure."),
```
___
*[`crates/mempool/src/priority_queue.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRaXQyACWso56680cN:-NvRaXQz1vpHCpoulqlZ:b254rmo) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L18)):*
> ```XML
>     pub fn new() -> Self {
>         PriorityQueue(BTreeSet::new())
>     }
> ```

This use case is covered by `PriorityQueue::default()`.
___
*[`crates/mempool/src/priority_queue.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRR7P47qvdwomtV5rZ:-NvRR7P47qvdwomtV5r_:bklj2lj) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L25)):*
> ```XML
>     }
> 
>     pub fn pop(&mut self, n_txs: usize) -> Vec<InternalTransaction> {
> ```

`pop` is canonically a 1-element op, so we need a new name for `n_txs`.

Looking at `BTreeSet`'s API (this is always a good idea when looking for naming things / what's the common approach) it seems like `split_off` is the closest thing to what we want, so we can copy the name, and also use it instead of iterate+pop pattern.



_Code quote:_
```XML
    pub fn pop(&mut self, n_txs: usize) -> Vec<InternalTransaction> {
```


<!-- Sent from Reviewable.io -->

2024-04-14 12:37 UTC, giladchase reviewed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-04-14 12:38 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRbFEn4a9StM_ufjew:-NvRbFEn4a9StM_ufjex:bf5n3fl) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L15)):*
> ```XML
> };
> 
> pub fn create_internal_invoke_tx_for_testing(
> ```

Do we have something like this in SNAPI? 
If we don't, please add it there 


<!-- Sent from Reviewable.io -->

2024-04-14 14:26 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRzreK2k8U3uhwJ3IW:-NvRzreK2k8U3uhwJ3IX:bf9xqpu) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L52)):*
> ```XML
> #[case(3, 3)] // Requesting exactly the number of transactions in the queue
> #[case(5, 3)] // Requesting more transactions than are in the queue
> #[case(2, 2)] // Requesting fewer transactions than are in the queue
> ```

The second arg can be inferred from the first + the number of transactions (3).



_Code quote:_
```XML
#[case(3, 3)] // Requesting exactly the number of transactions in the queue
#[case(5, 3)] // Requesting more transactions than are in the queue
#[case(2, 2)] // Requesting fewer transactions than are in the queue
```
___
*[`crates/mempool/src/mempool_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRbamJEmDcX3A8Zws7:-NvRbamJEmDcX3A8Zws8:b-frwnil) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L61)):*
> ```XML
>     priority_queue.push(tx1.clone());
>     priority_queue.push(tx2.clone());
>     priority_queue.push(tx3.clone());
> ```

We should have a `From` constructor for this in the PriorityQueue. 
Add it in a separate PR, I'll LGTM it quickly.



_Code quote:_
```XML
    let mut priority_queue = PriorityQueue::new();
    priority_queue.push(tx1.clone());
    priority_queue.push(tx2.clone());
    priority_queue.push(tx3.clone());
```
___
*[`crates/mempool/src/mempool_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRblaW6QbGg7h0BsoC:-NvRblaW6QbGg7h0BsoD:bphi69r) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L61)):*
> ```XML
>     priority_queue.push(tx1.clone());
>     priority_queue.push(tx2.clone());
>     priority_queue.push(tx3.clone());
> ```

Add a TODO to switch this into something that uses the Mempool's API, rather than manipulating its internals.
(We don't have add_tx in this PRs scope yet, which is why I'm not asking to do it now).



_Code quote:_
```XML
    let mut priority_queue = PriorityQueue::new();
    priority_queue.push(tx1.clone());
    priority_queue.push(tx2.clone());
    priority_queue.push(tx3.clone());
```
___
*[`crates/mempool/src/mempool_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRzxWE2f5qcH3Rm84q:-NvRzxWE2f5qcH3Rm84r:b-qtfn05) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L75)):*
> ```XML
>     if requested_txs > 2 {
>         assert_eq!(txs[2], tx3);
>     }
> ```

This can be a ~oneliner.
It'll help to define an array of txs in tip-sorted order, then you'll be able to compare txs with a prefix of this sorted array.



_Code quote:_
```XML
    if requested_txs > 0 {
        assert_eq!(txs[0], tx2);
    }
    if requested_txs > 1 {
        assert_eq!(txs[1], tx1);
    }
    if requested_txs > 2 {
        assert_eq!(txs[2], tx3);
    }
```


<!-- Sent from Reviewable.io -->

2024-04-15 07:56 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRbFEn4a9StM_ufjew:-NvVd-Ss7o_Yc1PPyCFk:bhnwk7e) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L15)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we have something like this in SNAPI? 
If we don't, please add it there
</blockquote></details>

added a todo
___
*[`crates/mempool/src/mempool_test.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRzreK2k8U3uhwJ3IW:-NvVkQdzEP_IFp-cC5y9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L52)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The second arg can be inferred from the first + the number of transactions (3).
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRbamJEmDcX3A8Zws7:-NvVbtYQ9MUhrx4crxPy:bhnwk7e) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We should have a `From` constructor for this in the PriorityQueue. 
Add it in a separate PR, I'll LGTM it quickly.
</blockquote></details>

added a todo
___
*[`crates/mempool/src/mempool_test.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRblaW6QbGg7h0BsoC:-NvVkJQ8BCuLz8LL_zEW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a TODO to switch this into something that uses the Mempool's API, rather than manipulating its internals.
(We don't have add_tx in this PRs scope yet, which is why I'm not asking to do it now).
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRzxWE2f5qcH3Rm84q:-NvVkK-F0An1DbnId_t9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This can be a ~oneliner.
It'll help to define an array of txs in tip-sorted order, then you'll be able to compare txs with a prefix of this sorted array.
</blockquote></details>

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRaXQyACWso56680cN:-NvV_Yi40wR6CioPUtP8:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This use case is covered by `PriorityQueue::default()`.
</blockquote></details>

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRR7P47qvdwomtV5rZ:-NvVam8k9tE6Ejb9LsU7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`pop` is canonically a 1-element op, so we need a new name for `n_txs`.

Looking at `BTreeSet`'s API (this is always a good idea when looking for naming things / what's the common approach) it seems like `split_off` is the closest thing to what we want, so we can copy the name, and also use it instead of iterate+pop pattern.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 13:42 UTC, giladchase requested changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvRzxWE2f5qcH3Rm84q:-NvWy8w47QhQLtA0jka5:b-83sjoh) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/mempool_test.rs#L75)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
___
*[`crates/mempool/src/mempool_test.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvWxxju2ufolTy-l4aU:-NvWxxju2ufolTy-l4aV:bj7cd1k) ([raw file](https://github.com/starkware-libs/mempool/blob/e2b7e8de5b3c3b291367f332a96c7a2ef15f8917/crates/mempool/src/mempool_test.rs#L69)):*
> ```XML
> 
>     let sorted_txs = vec![tx2, tx1, tx3];
>     assert_eq!(txs.len(), requested_txs.min(3));
> ```

Extract to variable with a good name / comment explaining it.



_Code quote:_
```XML
requested_txs.min(3)
```
___
*[`crates/mempool/src/priority_queue.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvWzVeB67qZGHJRQUQO:-NvWzVeB67qZGHJRQUQP:b-5g55u4) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L29)):*
> ```XML
>         for _ in 0..n_txs {
>             match self.pop_last().map(|tx| tx.0) {
>                 Some(tx) => txs.push(tx),
> ```

Can delegate to BTreeSet's `split_off` here instead of the loop?



_Code quote:_
```XML
        for _ in 0..n_txs {
            match self.pop_last().map(|tx| tx.0) {
                Some(tx) => txs.push(tx),
                None => break,
            }
        }
```
___
*[`crates/mempool/src/priority_queue.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvWzCcHCK_nXdWme8B7:-NvWzCcHCK_nXdWme8B8:b-y4svy1) ([raw file](https://github.com/starkware-libs/mempool/blob/e2b7e8de5b3c3b291367f332a96c7a2ef15f8917/crates/mempool/src/priority_queue.rs#L16)):*
> ```XML
> 
> impl PriorityQueue {
>     #[cfg(test)]
> ```

intentional?
Don't we need `push` to add stuff to the queue?



_Code quote:_
```XML
 #[cfg(test)]
```


<!-- Sent from Reviewable.io -->

2024-04-18 09:48 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nvk_SMWAeg6zAKViWZ_:-Nvk_SMWAeg6zAKViWZa:b53e70x) ([raw file](https://github.com/starkware-libs/mempool/blob/a0af41677494af24b4bd4c2f43e73ac23bd53c1c/crates/mempool/src/mempool_test.rs#L57)):*
> ```XML
>     let tx1 = create_internal_invoke_tx_for_testing(Tip(50), TransactionHash(StarkFelt::ONE));
>     let tx2 = create_internal_invoke_tx_for_testing(Tip(100), TransactionHash(StarkFelt::TWO));
>     let tx3 = create_internal_invoke_tx_for_testing(Tip(10), TransactionHash(StarkFelt::THREE));
> ```

It could help clarify the expected behavior.



_Suggestion:_
```XML
    let tx_tip_50 = create_internal_invoke_tx_for_testing(Tip(50), TransactionHash(StarkFelt::ONE));
    let tx_tip_100 = create_internal_invoke_tx_for_testing(Tip(100), TransactionHash(StarkFelt::TWO));
    let tx_tip_10 = create_internal_invoke_tx_for_testing(Tip(10), TransactionHash(StarkFelt::THREE));
```


<!-- Sent from Reviewable.io -->

2024-04-18 10:47 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvWzVeB67qZGHJRQUQO:-Nvk_P9J4G_yu4YPeH29:b6rdt1i) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think not. 
BTree's `split_off` method divides the collection into two at a specified value, returning a new collection containing all elements greater than or equal to that value. In our case, we should mention that we are splitting the transaction by a specific tip, not by the number of transactions.
</blockquote></details>

I have led you astray with the naming then :smiling_face_with_tear: 

Sorry...

It should be named `pop_last_chunk`.
There's isn't really an idiomatic name for this I guess, because typically this will be implemented via the `drain` iterator (which is an iterator that removes elements from a collection).
But this isn't available for BtreeSet unfortunately.
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-NvknkqJ6zsTYeevayl3:b-kszdoe) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
> ```XML
>             match self.pop_last().map(|tx| tx.0) {
>                 Some(tx) => txs.push(tx),
>                 None => break,
> ```

Can be streamlined via `(0..n_txs).filter_map`, without looping.



_Code quote:_
```XML
        let mut txs = Vec::new();
        for _ in 0..n_txs {
            match self.pop_last().map(|tx| tx.0) {
                Some(tx) => txs.push(tx),
                None => break,
            }
        }
        txs
```


<!-- Sent from Reviewable.io -->

2024-04-18 14:15 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvWzVeB67qZGHJRQUQO:-Nvl4NZX9jYWRdjzImUZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L29)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I have led you astray with the naming then :smiling_face_with_tear: 

Sorry...

It should be named `pop_last_chunk`.
There's isn't really an idiomatic name for this I guess, because typically this will be implemented via the `drain` iterator (which is an iterator that removes elements from a collection).
But this isn't available for BtreeSet unfortunately.
</blockquote></details>

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-NvlZ-cbD6xkyzScYDRP:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can be streamlined via `(0..n_txs).filter_map`, without looping.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 15:28 UTC, MohammadNassar1 requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool_test.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvlnmtH2yYKcg3OCiug:-NvlnmtH2yYKcg3OCiuh:b-lcnqer) ([raw file](https://github.com/starkware-libs/mempool/blob/d12a9c7d02b29917a69ea1a00b40f99628a7d1de/crates/mempool/src/mempool_test.rs#L57)):*
> ```XML
> fn test_get_txs(#[case] requested_txs: usize) {
>     let account_state1 = AccountState {
>         contract_address: ContractAddress(PatriciaKey::from(0u128)),
> ```

Please fix the rest addresses.



_Suggestion:_
```XML
contract_address: contract_address!("0x0"),
```


<!-- Sent from Reviewable.io -->

2024-04-21 08:53 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nvzr4fX4APEcHQybOHw:-Nvzr4fX4APEcHQybOHx:beais3g) ([raw file](https://github.com/starkware-libs/mempool/blob/d12a9c7d02b29917a69ea1a00b40f99628a7d1de/crates/mempool/src/mempool.rs#L60)):*
> ```XML
>     ) -> MempoolResult<()> {
>         todo!();
>     }
> ```

Should this be here? or merge conflict?



_Code quote:_
```XML
    /// Adds a new transaction to the mempool.
    /// TODO: support fee escalation and transactions with future nonces.
    pub fn add_tx(
        &mut self,
        _tx: InternalTransaction,
        _account_state: AccountState,
    ) -> MempoolResult<()> {
        todo!();
    }
```
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-NvzpqzF-t0U5kSr6NUl:b-tiiqh8) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:fire: 

One more thing we can do here: I think we don't really need to `collect` here, only get_txs needs to `collect`, because they are returning the data to the user.

Moreover, If we return an iterator here, `get_txs` can chain its `remove` action onto it (with `map` I guess?), instead of having to iterate the vector again, and only then call collect.
Becaues iterators are evaluated lazily, the whole chain of pop_last_chunk and get_txs will iterate the txs only once.

That said, if it gets ugly leave it :grimacing: 


<!-- Sent from Reviewable.io -->

2024-04-21 08:55 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-NvzrM1xEoVW5ETIgKXw:b-mh01po) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:fire: 

One more thing we can do here: I think we don't really need to `collect` here, only get_txs needs to `collect`, because they are returning the data to the user.

Moreover, If we return an iterator here, `get_txs` can chain its `remove` action onto it (with `map` I guess?), instead of having to iterate the vector again, and only then call collect.
Becaues iterators are evaluated lazily, the whole chain of pop_last_chunk and get_txs will iterate the txs only once.

That said, if it gets ugly leave it :grimacing:
</blockquote></details>

But if you do add it, it'll probably need a `'_` lifetime somewhere; if that's the case add a comment saying that this is an optimization (so people can revert to the current version with the early collect as needed).


<!-- Sent from Reviewable.io -->

2024-04-21 10:58 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nvzr4fX4APEcHQybOHw:-Nw-73ns3S-MaIcxsC6h:bvky29z) ([raw file](https://github.com/starkware-libs/mempool/blob/d12a9c7d02b29917a69ea1a00b40f99628a7d1de/crates/mempool/src/mempool.rs#L60)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be here? or merge conflict?
</blockquote></details>

I changed the order of the PRs to avoid merge conflicts.
___
*[`crates/mempool/src/mempool_test.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvlnmtH2yYKcg3OCiug:-Nw-6zRLDxm2jkih62Mo:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/d12a9c7d02b29917a69ea1a00b40f99628a7d1de/crates/mempool/src/mempool_test.rs#L57)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please fix the rest addresses.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-21 12:58 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46#-:-Nw-jDQdCcTrnglsPlD_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-02 04:45 UTC, giladchase requested changes
> Reviewed 1 of 3 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/Cargo.toml` line 20 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwoFABFD2jAv8CvGKkt:-NwoFABGE3yjH5ZOqWMl:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/Cargo.toml#L20)):*
> ```TOML
> assert_matches.workspace = true
> rstest.workspace = true
> tokio.workspace = true
> ```





_Suggestion:_
```TOML
starknet_api.workspace = true
thiserror.workspace = true


[dev-dependencies]
assert_matches.workspace = true
rstest.workspace = true
starknet_api = { workspace = true, features = ["testing"] }
tokio.workspace = true
```
___
*[`crates/mempool/src/mempool.rs` line 20 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwoG3mw6uLEX1yecMC_:-NwoG3mw6uLEX1yecMCa:b4vc0h5) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L20)):*
> ```XML
> pub struct Mempool {
>     priority_queue: PriorityQueue,
>     state: HashMap<ContractAddress, Nonce>,
> ```

Add a docstring (with a ///)  before each of the field that documents the invariant on them, explaining why they're private.
For example, the docstring on the pq will describe the coupling between its values and the values inside state.
The docstring of one may refer to the other, in case they come up too similar



_Code quote:_
```XML
    priority_queue: PriorityQueue,
    state: HashMap<ContractAddress, Nonce>,
```
___
*[`crates/mempool/src/mempool.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrVFz6BApg4kC-Z8I5:-NwrVFz6BApg4kC-Z8I6:b-omckcn) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L35)):*
> ```XML
>                     .insert(account_state.contract_address, account_state.nonce);
>                 new_transactions.push(tx);
>             }
> ```

This means that if there are multiple txs from the same contract address then the first will be taken and the rest will be ignored.

Due to our assumptions on nonces for the first milestone, we can indeed assume that this contractor will be unique on contract_addresses, but let's add an assert that makes sure (better than returning an error here because it's a bug if this happens).



_Code quote:_
```XML
            if mempool.state.get(&account_state.contract_address).is_none() {
                mempool
                    .state
                    .insert(account_state.contract_address, account_state.nonce);
                new_transactions.push(tx);
            }
```
___
*[`crates/mempool/src/mempool.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nwra_Ey8KmDveV7b6VG:-Nwra_Ey8KmDveV7b6VH:bn3uw63) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L39)):*
> ```XML
>         mempool.priority_queue = PriorityQueue::from(new_transactions);
>         mempool
>     }
> ```

This can be refactored a bit:
1. `inputs` can be a `impl IntoIterator`, which will then take any type that implements into_iter (including an intoIterator instance by itself).
2. I think we can lose `new_transactions` by using priorityQueue::from_iter and by inserting into the `state` (and asserting for uniqueness) inside a `map` over the inputs.

It'll save two extra passes on the inputs, and might be simpler logic, but let me know if it ends up less readable.



_Code quote:_
```XML
    pub fn new(inputs: Vec<MempoolInput>) -> Self {
        let mut mempool = Mempool::default();
        let mut new_transactions = Vec::new();
        for input in inputs {
            let account_state = &input.account_state;
            let tx = input.tx;
            if mempool.state.get(&account_state.contract_address).is_none() {
                mempool
                    .state
                    .insert(account_state.contract_address, account_state.nonce);
                new_transactions.push(tx);
            }
        }
        mempool.priority_queue = PriorityQueue::from(new_transactions);
        mempool
    }
```
___
*[`crates/mempool/src/priority_queue.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrQ0dm2BTxBxMr6o0i:-NwrQ0dm2BTxBxMr6o0j:b-tg70un) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/priority_queue.rs#L32)):*
> ```XML
>         ))
>     }
> }
> ```

Lets make this also a FromIterator instead of a From



_Code quote:_
```XML
impl From<Vec<InternalTransaction>> for PriorityQueue {
    fn from(transactions: Vec<InternalTransaction>) -> Self {
        PriorityQueue(BTreeSet::from_iter(
            transactions.into_iter().map(PQTransaction),
        ))
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-02 08:22 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/Cargo.toml` line 20 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwoFABFD2jAv8CvGKkt:-Nws9gWA1AMd0GR0TGht:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/Cargo.toml#L20)):*
> ```TOML
> assert_matches.workspace = true
> rstest.workspace = true
> tokio.workspace = true
> ```

Done.
___
*[`crates/mempool/src/mempool.rs` line 20 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwoG3mw6uLEX1yecMC_:-NwsDm5AE9GWuGtfQZl9:bwcs3cl) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L20)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a docstring (with a ///)  before each of the field that documents the invariant on them, explaining why they're private.
For example, the docstring on the pq will describe the coupling between its values and the values inside state.
The docstring of one may refer to the other, in case they come up too similar
</blockquote></details>

added a todo. will add in the next PR cause there were some changes.
___
*[`crates/mempool/src/mempool.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrVFz6BApg4kC-Z8I5:-NwsIYe68mkhBw8Dzd_u:b5d261x) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This means that if there are multiple txs from the same contract address then the first will be taken and the rest will be ignored.

Due to our assumptions on nonces for the first milestone, we can indeed assume that this contractor will be unique on contract_addresses, but let's add an assert that makes sure (better than returning an error here because it's a bug if this happens).
</blockquote></details>

Done. There's no display implementation for the contract address, so I didn't specify which contract address is duplicated. Is this acceptable since it's only for this milestone? Should I implement a display feature, or is there another way to do this?
___
*[`crates/mempool/src/mempool.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nwra_Ey8KmDveV7b6VG:-NwsO8ja6jRcFRt3FKGW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This can be refactored a bit:
1. `inputs` can be a `impl IntoIterator`, which will then take any type that implements into_iter (including an intoIterator instance by itself).
2. I think we can lose `new_transactions` by using priorityQueue::from_iter and by inserting into the `state` (and asserting for uniqueness) inside a `map` over the inputs.

It'll save two extra passes on the inputs, and might be simpler logic, but let me know if it ends up less readable.
</blockquote></details>

Done.
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-NwsOHVu2Q9pFiJGi1_6:b-epkztm) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

But if you do add it, it'll probably need a `'_` lifetime somewhere; if that's the case add a comment saying that this is an optimization (so people can revert to the current version with the early collect as needed).
</blockquote></details>

pass? 😬
___
*[`crates/mempool/src/priority_queue.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrQ0dm2BTxBxMr6o0i:-NwsOFeR6UuVlgnHcX7q:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/priority_queue.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Lets make this also a FromIterator instead of a From
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 08:09 UTC, giladchase requested changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrVFz6BApg4kC-Z8I5:-Nx6n-5T43zeizzLGIzi:b-sbs83p) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done. There's no display implementation for the contract address, so I didn't specify which contract address is duplicated. Is this acceptable since it's only for this milestone? Should I implement a display feature, or is there another way to do this?
</blockquote></details>

Yep use debug print (with `{<thing_to_debug_print>:?}`, also better print the whole entry, rather than just the contractaddress, will make the debugging easier.
___
*[`crates/mempool/src/mempool.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nwra_Ey8KmDveV7b6VG:-Nx6kYdcD_nQxQOMtE-j:bir1lud) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice! :fire: 
A few nits:
1. instead of the get+is_none in the assert, you can do the `insert` first, then assert that the return value from the `insert`[ is none](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert). It might seem odd to "pollute" the map this way, but we are panicking anyway in the next line so it doesn't matter either way,
2. In the assert error message plz debug-print the retrieved instance (which is returned from `insert`).
3.  Can the signature be `new(inputs: impl IntoIterator<item = MempoolInput>)`? more sugary 
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-Nx6mAuS3uPBnq09JxEp:blbslq0) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

pass? 😬
</blockquote></details>

jj add `TODO(gilad): remove collect` there plz then?


<!-- Sent from Reviewable.io -->

2024-05-05 11:53 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrVFz6BApg4kC-Z8I5:-Nx7IAGo7UIbYNT48w7u:b-2ey4k8) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep use debug print (with `{<thing_to_debug_print>:?}`, also better print the whole entry, rather than just the contractaddress, will make the debugging easier.
</blockquote></details>

Done. added a test as well.
___
*[`crates/mempool/src/mempool.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nwra_Ey8KmDveV7b6VG:-Nx7TxXwDJGq0hkBXriT:bugl3uw) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nice! :fire: 
A few nits:
1. instead of the get+is_none in the assert, you can do the `insert` first, then assert that the return value from the `insert`[ is none](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert). It might seem odd to "pollute" the map this way, but we are panicking anyway in the next line so it doesn't matter either way,
2. In the assert error message plz debug-print the retrieved instance (which is returned from `insert`).
3.  Can the signature be `new(inputs: impl IntoIterator<item = MempoolInput>)`? more sugary
</blockquote></details>

1. done
2. The retrieved instance is the old value of the key, which is the nonce. I printed the whole input, which contains the tx and the account state. 
3. done
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-Nx6x-0C34QpZFagAsy3:bdzdm1z) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

jj add `TODO(gilad): remove collect` there plz then?
</blockquote></details>

added. lets do it together in a different PR?


<!-- Sent from Reviewable.io -->

2024-05-05 13:17 UTC, giladchase approved these changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/mempool/src/mempool.rs` line 35 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-NwrVFz6BApg4kC-Z8I5:-Nx7sRpzAWdmB8sETkUy:bo9bm4q) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L35)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done. added a test as well.
</blockquote></details>

nit: more meaningful name for `result`? 
Also make it a bit clearer in the comment that insert returns the previous entry, it isn't obvious to ppl who don't know this behavior.
___
*[`crates/mempool/src/mempool.rs` line 39 at r7](https://reviewable.io/reviews/starkware-libs/mempool/46#-Nwra_Ey8KmDveV7b6VG:-Nx7tLrWEQS5LTUDk1jw:b-pujcdy) ([raw file](https://github.com/starkware-libs/mempool/blob/084c3af134346ca8ad4de180e7c3d21914372402/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

1. done
2. The retrieved instance is the old value of the key, which is the nonce. I printed the whole input, which contains the tx and the account state. 
3. done
</blockquote></details>

nice!
Re 2: Let's print both, something like "can't add {new_input:?} cause {contract_address} already exists with value {old_val}", again, to make debugging easier (we _will_ hit this at some point I think)
___
*[`crates/mempool/src/priority_queue.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/mempool/46#-NvknkqJ6zsTYeevayl2:-Nx7tmCu95wT7GCG3mBC:b-7jl67j) ([raw file](https://github.com/starkware-libs/mempool/blob/fddee6078e26878abdecc4cabefeefaafbc58262/crates/mempool/src/priority_queue.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

added. lets do it together in a different PR?
</blockquote></details>

sagur


<!-- Sent from Reviewable.io -->

2024-05-06 05:04 UTC, giladchase requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/46#-NxBG6IK6bb_FYj_CKPn:-NxBG6IK6bb_FYj_CKPo:b4bvp8d) ([raw file](https://github.com/starkware-libs/mempool/blob/11e84886ae814749c63b3c065098bf788600765e/crates/mempool/src/mempool.rs#L24)):*
> ```XML
> 
> impl Mempool {
>     pub fn new<I>(inputs: impl IntoIterator<Item = MempoolInput>) -> Self {
> ```

No need for the generic, it is already created through the `impl` syntax below.
In other words:
```rust
fn foo(bar: impl Fluf)
```
is sugar for
```rust
fn foo<F: Fluf>(bar: F)
```

That extra template arg is what forced you to annotate all the `new` statements.



_Suggestion:_
```XML
    pub fn new(inputs: impl IntoIterator<Item = MempoolInput>) -> Self {
```
___
*[`crates/mempool/src/mempool_test.rs` line 135 at r10](https://reviewable.io/reviews/starkware-libs/mempool/46#-NxBGddd5GtUMdl2jejW:-NxBGddd5GtUMdl2jejX:b-4fbt8q) ([raw file](https://github.com/starkware-libs/mempool/blob/11e84886ae814749c63b3c065098bf788600765e/crates/mempool/src/mempool_test.rs#L135)):*
> ```XML
> #[rstest]
> #[should_panic(
>     expected = "Can't add Invoke(InternalInvokeTransaction { tx: V3(InvokeTransactionV3 { resource_bounds: ResourceBoundsMapping({L1Gas: ResourceBounds { max_amount: 0, max_price_per_unit: 0 }, L2Gas: ResourceBounds { max_amount: 0, max_price_per_unit: 0 }}), tip: Tip(50), signature: TransactionSignature([]), nonce: Nonce(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\")), sender_address: ContractAddress(PatriciaKey(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\"))), calldata: Calldata([]), nonce_data_availability_mode: L1, fee_data_availability_mode: L1, paymaster_data: PaymasterData([]), account_deployment_data: AccountDeploymentData([]) }), tx_hash: TransactionHash(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000001\")), only_query: false }) to the mempool. Contract address: ContractAddress(PatriciaKey(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\"))) already exists in the mempool."
> ```

Few notes:
a) Looking at this message now, I think it might be better to reorganize it a bit: the important part of the message, the duplicate entry thing, is only at the end of the message and hard to find. I think it should be reformatted so that all the text you wrote is in the beginning, and the debug print is at the end. This aligns with users expectation of error message: message first and (possibly skippable) details later.

b) Point (a) will allow you to better utilize should_panic's ability to only take a substring. So once the message is reformatted, you can select the most indicative short substring and only add that in the `expected` field.



_Code quote:_
```XML
    expected = "Can't add Invoke(InternalInvokeTransaction { tx: V3(InvokeTransactionV3 { resource_bounds: ResourceBoundsMapping({L1Gas: ResourceBounds { max_amount: 0, max_price_per_unit: 0 }, L2Gas: ResourceBounds { max_amount: 0, max_price_per_unit: 0 }}), tip: Tip(50), signature: TransactionSignature([]), nonce: Nonce(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\")), sender_address: ContractAddress(PatriciaKey(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\"))), calldata: Calldata([]), nonce_data_availability_mode: L1, fee_data_availability_mode: L1, paymaster_data: PaymasterData([]), account_deployment_data: AccountDeploymentData([]) }), tx_hash: TransactionHash(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000001\")), only_query: false }) to the mempool. Contract address: ContractAddress(PatriciaKey(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000000\"))) already exists in the mempool."
```


<!-- Sent from Reviewable.io -->

2024-05-06 10:22 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/mempool/46#-NxBG6IK6bb_FYj_CKPn:-NxCQ8GE16ZGYahX2FI_:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/11e84886ae814749c63b3c065098bf788600765e/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No need for the generic, it is already created through the `impl` syntax below.
In other words:
```rust
fn foo(bar: impl Fluf)
```
is sugar for
```rust
fn foo<F: Fluf>(bar: F)
```

That extra template arg is what forced you to annotate all the `new` statements.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 135 at r10](https://reviewable.io/reviews/starkware-libs/mempool/46#-NxBGddd5GtUMdl2jejW:-NxCQ7_L82BPfdvogmuV:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/11e84886ae814749c63b3c065098bf788600765e/crates/mempool/src/mempool_test.rs#L135)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Few notes:
a) Looking at this message now, I think it might be better to reorganize it a bit: the important part of the message, the duplicate entry thing, is only at the end of the message and hard to find. I think it should be reformatted so that all the text you wrote is in the beginning, and the debug print is at the end. This aligns with users expectation of error message: message first and (possibly skippable) details later.

b) Point (a) will allow you to better utilize should_panic's ability to only take a substring. So once the message is reformatted, you can select the most indicative short substring and only add that in the `expected` field.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 12:29 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/46#-:-NxCsQ4NCXytvRpjUPb0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-05-06 12:56 UTC, merged