feat: implement add_tx in mempool struct
starkware-libs/mempool pull request #47
Opened 2024-04-11 12:00 UTC by ayeletstarkware

2024-04-14 11:20 UTC, giladchase reviewed
Plz add duplicate check: if the same tx is added twice, it should return an error (+ add a TODO: about supporting fee escalation).

To check if the tx was already added we need to add a state abstraction to the mempool: a mapping between ContractAddress to some abstraction that represents what we know of this account. 
Right now "what we know of this account" is just nonce, so it can just be a nonce for now.

So in other words, if you get a tx from contract address X with nonce Y, you should check if that already exists in the map (which implies that a tx already exists in the mempool), and if it is return an error.
(When implementing `get_txs`, we'll delete the retrieves entries from the map).

I think there is also the issue of how much balance the account has that needs to be checked, but I think that might be a gateway thing? We'lll ask Elin tomorrow.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47#-:-NvRIXRIBeSgNasxSQYV:b1x0vyv)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-04-15 09:07 UTC, MohammadNassar1 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzna9C8VU9-RxDqWE:-NvVzna9C8VU9-RxDqWF:b-25ahrd) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L18)):*
> ```XML
>     /// Transactions are guaranteed to be unique across calls until `commit_block` is invoked.
>     // TODO: the last part about commit_block is incorrect if we delete txs in get_txs and then push back.
>     pub fn get_tx(&mut self, n_txs: usize) -> MempoolResult<Vec<InternalTransaction>> {
> ```

get_txns



_Code quote:_
```XML
get_tx
```
___
*[`crates/mempool/src/mempool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzXR88Y_l3fIoKvOC:-NvVzXR88Y_l3fIoKvOD:bg70lqy) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L24)):*
> ```XML
>     /// Adds a new transaction to the mempool.
>     /// TODO: support fee escalation and transactions with future nonces.
>     pub fn add_tx(&mut self, tx: InternalTransaction) -> MempoolResult<()> {
> ```

I suggest to change it to add_txns



_Code quote:_
```XML
pub fn add_tx(&mut self, tx: InternalTransaction) -> MempoolResult<()> {
```


<!-- Sent from Reviewable.io -->

2024-04-16 12:30 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzna9C8VU9-RxDqWE:-NvWS80a7AqBBIYqnJzA:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L18)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

get_txns
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzXR88Y_l3fIoKvOC:-NvasdA_6ixg6Cs9UzJ2:bgfk0v3) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I suggest to change it to add_txns
</blockquote></details>

its not needed


<!-- Sent from Reviewable.io -->

2024-04-16 15:28 UTC, MohammadNassar1 requested changes
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzXR88Y_l3fIoKvOC:-NvbSTS17wCL76X0e1hb:b-irlsxq) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

its not needed
</blockquote></details>

Don't we expect to send a vector of transactions?
___
*[`crates/mempool/src/mempool.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbTChaCJSsWg14Ub0Y:-NvbTChaCJSsWg14Ub0Z:bstxwm7) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L19)):*
> ```XML
> pub struct Mempool {
>     priority_queue: PriorityQueue,
>     state: HashMap<ContractAddress, Nonce>,
> ```

The state will include more stuff.
Consider using a struct.



_Code quote:_
```XML
state: HashMap<ContractAddress, Nonce>,
```
___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbVpSwDHAgnonY2MCw:-NvbVpSwDHAgnonY2MCx:bdawcsy) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L39)):*
> ```XML
>         &mut self,
>         tx: InternalTransaction,
>         account_state: &AccountState,
> ```

Do we receive `account_state` when adding tx?
Please note that you can retrieve the contract address and nonce from the tx.



_Code quote:_
```XML
account_state: &AccountState,
```


<!-- Sent from Reviewable.io -->

2024-04-17 07:45 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvVzXR88Y_l3fIoKvOC:-Nvf018WDh7eXQ8FYIEm:b-ge4uco) ([raw file](https://github.com/starkware-libs/mempool/blob/a0ace164d15fdd30d5e41cf6541883155f4b1c3f/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Don't we expect to send a vector of transactions?
</blockquote></details>

no. explained f2f
___
*[`crates/mempool/src/mempool.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbTChaCJSsWg14Ub0Y:-Nvf-o6JDG3GQ8DTE4qd:bozdota) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L19)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The state will include more stuff.
Consider using a struct.
</blockquote></details>

it's going to change on the next milestone
___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbVpSwDHAgnonY2MCw:-Nvf-MUSEqsbrbnYxXzi:bsntt14) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do we receive `account_state` when adding tx?
Please note that you can retrieve the contract address and nonce from the tx.
</blockquote></details>

Yes, we can get this information from the transaction, but the account state will be synchronized with the current nonce of the account.


<!-- Sent from Reviewable.io -->

2024-04-18 15:36 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 6 files at r2, 2 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbVpSwDHAgnonY2MCw:-Nvlp2IY4KhEeKlYrjv7:b-ttxupv) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Yes, we can get this information from the transaction, but the account state will be synchronized with the current nonce of the account.
</blockquote></details>

Non-blocking - Does the gateway update the state? Also, why this update occur through the `add_tx` interface?
___
*[`crates/mempool/src/mempool_test.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nvlq-YOAKQsYgBAF1Xs:-Nvlq-YOAKQsYgBAF1Xt:b-hfpv1m) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L128)):*
> ```XML
>     assert_eq!(txs.len(), max_requested_txs);
>     assert_eq!(txs, sorted_txs[..max_requested_txs].to_vec());
>     assert_eq!(txs, sorted_txs[..max_requested_txs].to_vec());
> ```

remove?



_Code quote:_
```XML
assert_eq!(txs, sorted_txs[..max_requested_txs].to_vec());
```
___
*[`crates/mempool/src/mempool_test.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nvlq4UA1P0l8hr9Fa9o:-Nvlq4UA1P0l8hr9Fa9p:b-qngabp) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L140)):*
> ```XML
> fn test_add_tx() {
>     let account_state1 = AccountState {
>         contract_address: ContractAddress(PatriciaKey::from(0u128)),
> ```

use contract_address macro instead.



_Code quote:_
```XML
ContractAddress(PatriciaKey::from(0u128)),
```
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvlqKCUEp5kGt6C5xcz:-NvlqKCUEp5kGt6C5xd-:b-vnn1om) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L195)):*
> ```XML
>         TransactionHash(StarkFelt::ONE),
>         ContractAddress(PatriciaKey::from(0u128)),
>     );
> ```

Please use a clone.



_Code quote:_
```XML
    let same_tx = create_internal_invoke_tx_for_testing(
        Tip(50),
        TransactionHash(StarkFelt::ONE),
        ContractAddress(PatriciaKey::from(0u128)),
    );
```


<!-- Sent from Reviewable.io -->

2024-04-21 12:15 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvbVpSwDHAgnonY2MCw:-Nw-_7Vk7MVctYRlSr_b:b-pzygk6) ([raw file](https://github.com/starkware-libs/mempool/blob/88577ff1b14898e171109f544931892cbfd594a9/crates/mempool/src/mempool.rs#L39)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Non-blocking - Does the gateway update the state? Also, why this update occur through the `add_tx` interface?
</blockquote></details>

Talked F2F
___
*[`crates/mempool/src/mempool_test.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nvlq-YOAKQsYgBAF1Xs:-Nw-KdUy8VzUnr89gZNW:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L128)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nvlq4UA1P0l8hr9Fa9o:-Nw-KM1C4-k6qjgxM57s:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L140)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

use contract_address macro instead.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvlqKCUEp5kGt6C5xcz:-Nw-KWAE8pFQ08Mt6M33:bwos9e9) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please use a clone.
</blockquote></details>

Done, but why?


<!-- Sent from Reviewable.io -->

2024-04-21 13:02 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47#-:-Nw-jxXl6c6EeeEaoxee:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/mempool/47#-NvlqKCUEp5kGt6C5xcz:-Nw-jSiq0y1fcQoqC1wl:bxj9vgv) ([raw file](https://github.com/starkware-libs/mempool/blob/acc00fef85dbd9a12401b34561cba1ad04cd1638/crates/mempool/src/mempool_test.rs#L195)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done, but why?
</blockquote></details>

It's easy to notice that the transactions are identical now.


<!-- Sent from Reviewable.io -->

2024-04-30 08:50 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 6 files at r2, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/errors.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiBd3c6zFNwLivKFkb:-NwiBd3d3AehIlEyvZo7:b-faeg9d) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/errors.rs#L5)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum MempoolError {
>     #[error("Duplicate transaction")]
> ```

Where will this string appear? Do we want to add more information for debugging, e.g. transaction hash?



_Code quote:_
```XML
"Duplicate transaction"
```


<!-- Sent from Reviewable.io -->

2024-04-30 08:59 UTC, elintul reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiCen7-iLmxt-kGplU:-NwiCen7-iLmxt-kGplV:b66giex) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L11)):*
> ```XML
> // transactions with future nonces will need to be stored, and potentially indexed on block commits.
> #[derive(Clone, Debug, Default, derive_more::Deref, derive_more::DerefMut)]
> pub struct PriorityQueue(BTreeSet<PQTransaction>);
> ```

Perhaps rename to `TransactionQueue` or `TransactionPriorityQueue`, for a more informative name?



_Code quote:_
```XML
PriorityQueue
```
___
*[`crates/mempool/src/priority_queue.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiD3W49fgkUMUDMjrv:-NwiD3W49fgkUMUDMjrw:brq4m8j) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L11)):*
> ```XML
> // transactions with future nonces will need to be stored, and potentially indexed on block commits.
> #[derive(Clone, Debug, Default, derive_more::Deref, derive_more::DerefMut)]
> pub struct PriorityQueue(BTreeSet<PQTransaction>);
> ```

Perhaps `PrioritisedTransaction`?



_Code quote:_
```XML
PQTransaction
```
___
*[`crates/mempool/src/priority_queue.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiCyq-0-itvXcp5Zjq:-NwiCyq-0-itvXcp5Zjr:b35wp6m) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L13)):*
> ```XML
> pub struct PriorityQueue(BTreeSet<PQTransaction>);
> 
> impl PriorityQueue {
> ```

Do we want a trait?



_Code quote:_
```XML
impl PriorityQueue
```
___
*[`crates/mempool/src/priority_queue.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiDOFp5Zajb4aMGkOp:-NwiDOFp5Zajb4aMGkOq:bhlu55) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L38)):*
> ```XML
> 
> impl PQTransaction {
>     fn tip(&self) -> Tip {
> ```

Add a TODO to move this getter to SN API?



_Code quote:_
```XML
fn tip(&self) -> Tip
```
___
*[`crates/mempool/src/priority_queue.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiDVLr2uCPiQ8ZhhgX:-NwiDVLr2uCPiQ8ZhhgY:bno7651) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L56)):*
> ```XML
> }
> 
> // Compare transactions based on their tip only, which implies `Eq`, because `tip` is uint.
> ```

WDYM here?



_Code quote:_
```XML
which implies `Eq`, because `tip` is uint.
```
___
*[`crates/mempool/src/priority_queue.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiDalI8hnyyg2AOIav:-NwiDalI8hnyyg2AOIaw:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L63)):*
> ```XML
> }
> 
> /// Marks PQTransaction as capable of strict equality comparisons, signaling to the compiler it
> ```





_Suggestion:_
```XML
this struct
```


<!-- Sent from Reviewable.io -->

2024-04-30 09:03 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiDplnET2IS7At2ylW:-NwiDplo0lf9IvEoCfnA:b-ev1hpf) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L19)):*
> ```XML
> #[derive(Default)]
> pub struct Mempool {
>     priority_queue: PriorityQueue,
> ```

Maybe `txs_queue`?



_Code quote:_
```XML
priority_queue
```
___
*[`crates/mempool/src/mempool.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiE1XZCgFXeJqlOtJ5:-NwiE1XZCgFXeJqlOtJ6:bachg9y) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L20)):*
> ```XML
> pub struct Mempool {
>     priority_queue: PriorityQueue,
>     state: HashMap<ContractAddress, Nonce>,
> ```

Should this be `AccountState`?
I see now that it includes the address, a bit cumbersome. What's the reason for this?
Perhaps `AccountState` can consist of an address and a small struct of `InnerState` with nonce and balance?



_Code quote:_
```XML
Nonce
```
___
*[`crates/mempool/src/mempool.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiEFJOCu-xncOo6GAP:-NwiEFJOCu-xncOo6GAQ:b-p3gy03) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L84)):*
> ```XML
> #[derive(Default)]
> pub struct AccountState {
>     pub contract_address: ContractAddress,
> ```

It's clear it's the address of the account, shorter names are better if the context is known.



_Suggestion:_
```XML
address
```


<!-- Sent from Reviewable.io -->

2024-04-30 09:14 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 17 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGULV80KWvVt5gGCt:-NwiGULV80KWvVt5gGCu:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L26)):*
> ```XML
>     pub fn new(inputs: Vec<MempoolInput>) -> Self {
>         let mut mempool = Mempool::default();
>         let mut new_transactions = Vec::new();
> ```





_Suggestion:_
```XML
new_txs
```
___
*[`crates/mempool/src/mempool.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGquZ5LlMgSvHNgy0:-NwiGquZ5LlMgSvHNgy1:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L27)):*
> ```XML
>         let mut mempool = Mempool::default();
>         let mut new_transactions = Vec::new();
>         for input in inputs {
> ```





_Suggestion:_
```XML

for input in inputs {
```
___
*[`crates/mempool/src/mempool.rs` line 29 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiG_loDRWFTQfXbjk9:-NwiG_loDRWFTQfXbjkA:bhjws3z) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L29)):*
> ```XML
>         for input in inputs {
>             let account_state = &input.account_state;
>             let tx = input.tx;
> ```

Why is this variable needed?



_Code quote:_
```XML
let tx = input.tx;
```
___
*[`crates/mempool/src/mempool.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGdjpBLlbeR-HQ1Q3:-NwiGdjpBLlbeR-HQ1Q4:b-kfzfw3) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L30)):*
> ```XML
>             let account_state = &input.account_state;
>             let tx = input.tx;
>             if mempool.state.get(&account_state.contract_address).is_none() {
> ```

Give this a name: `first_tx_from_account`, or something similar.
Also, why do yo check `is_none()`, instead of `contains_key`?



_Code quote:_
```XML
mempool.state.get(&account_state.contract_address).is_none()
```
___
*[`crates/mempool/src/mempool.rs` line 38 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGt3q2dJmkMbPvRSt:-NwiGt3r9bhzpQt1zAEH:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L38)):*
> ```XML
>         }
>         mempool.priority_queue = PriorityQueue::from(new_transactions);
>         mempool
> ```





_Suggestion:_
```XML
        mempool.priority_queue = PriorityQueue::from(new_transactions);
        
        mempool
```
___
*[`crates/mempool/src/mempool.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGwkj1RvyNwPsTcKY:-NwiGwkj1RvyNwPsTcKZ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L49)):*
> ```XML
>             self.state.remove(&tx.contract_address());
>         }
>         Ok(txs)
> ```





_Suggestion:_
```XML
        }
        
        Ok(txs)
```


<!-- Sent from Reviewable.io -->

2024-04-30 11:58 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul)

___
*[`crates/mempool/src/errors.rs` line 5 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiBd3c6zFNwLivKFkb:-NwiOKcXEGl2nPC9gVnz:b2vjk7b) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/errors.rs#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where will this string appear? Do we want to add more information for debugging, e.g. transaction hash?
</blockquote></details>

done, relying on this PR:
https://reviewable.io/reviews/starkware-libs/starknet-api/238
___
*[`crates/mempool/src/mempool.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiE1XZCgFXeJqlOtJ5:-NwiUqgA7lQNlIDWP0v3:bb6un1j) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L20)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should this be `AccountState`?
I see now that it includes the address, a bit cumbersome. What's the reason for this?
Perhaps `AccountState` can consist of an address and a small struct of `InnerState` with nonce and balance?
</blockquote></details>

Done
___
*[`crates/mempool/src/mempool.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGdjpBLlbeR-HQ1Q3:-Nwiqvn57kI9x4xqovPG:b-rdcujh) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name: `first_tx_from_account`, or something similar.
Also, why do yo check `is_none()`, instead of `contains_key`?
</blockquote></details>

contains key + insert doesn't go together according to clippy lints
how's this solution?


<!-- Sent from Reviewable.io -->

2024-04-30 14:38 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiCen7-iLmxt-kGplU:-Nwis1qADnlw5sqiD7Iw:b-d3se1e) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/priority_queue.rs#L11)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps rename to `TransactionQueue` or `TransactionPriorityQueue`, for a more informative name?
</blockquote></details>

priority_queue.rs's changes are in #78 


<!-- Sent from Reviewable.io -->

2024-05-01 08:52 UTC, elintul reviewed
> Reviewed 2 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`Cargo.toml` line 35 at r6](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwnL5fz5G7k_1Bf1Q8W:-NwnL5g-2WrF8gCTPrb9:b-tte3fu) ([raw file](https://github.com/starkware-libs/mempool/blob/a3643e1e241d7cc27370a1923638bd22442f81b6/Cargo.toml#L35)):*
> ```TOML
> serde_json = "1.0"
> # TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
> starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", rev = "84fe030" }
> ```

What are the PRs we are waiting for in SN API?



_Code quote:_
```TOML
84fe030
```


<!-- Sent from Reviewable.io -->

2024-05-01 08:56 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`Cargo.toml` line 35 at r6](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwnL5fz5G7k_1Bf1Q8W:-NwnMY-c6Ll0tTVCaKXG:b-oufemq) ([raw file](https://github.com/starkware-libs/mempool/blob/a3643e1e241d7cc27370a1923638bd22442f81b6/Cargo.toml#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What are the PRs we are waiting for in SN API?
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/starknet-api/238


<!-- Sent from Reviewable.io -->

2024-05-01 09:54 UTC, elintul reviewed
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`crates/mempool/src/errors.rs` line 6 at r6](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwnZfMt6jljei1pl4mK:-NwnZfMt6jljei1pl4mL:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/a3643e1e241d7cc27370a1923638bd22442f81b6/crates/mempool/src/errors.rs#L6)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum MempoolError {
>     #[error("This transaction has already been processed: tx_hash={tx_hash}")]
> ```





_Suggestion:_
```XML
Duplicate transaction, of hash: {tx_hash}
```
___
*[`crates/mempool/src/mempool.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwnNyBNB7uDFZAJy1xd:-NwnNyBNB7uDFZAJy1xe:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/a3643e1e241d7cc27370a1923638bd22442f81b6/crates/mempool/src/mempool.rs#L64)):*
> ```XML
>         self.state.insert(account.address, account.state);
>         self.txs_queue.push(tx);
>         Ok(())
> ```





_Suggestion:_
```XML
        }
        
        self.state.insert(account.address, account.state);
        self.txs_queue.push(tx);
        
        Ok(())
```


<!-- Sent from Reviewable.io -->

2024-05-05 15:51 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGdjpBLlbeR-HQ1Q3:-Nx8P2n3A3WVq2fqVxJY:b-of2yks) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L30)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

contains key + insert doesn't go together according to clippy lints
how's this solution?
</blockquote></details>

you can "greedily" insert and use the fact that insert returns the previous value if it exists, or None otherwise.
It's OK to pollute the map since we're panicking anyway; also saves a lookup.
___
*[`crates/mempool/src/mempool.rs` line 49 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8IFMwAYmXxQYbYmtv:-Nx8IFMwAYmXxQYbYmtw:b-6x5oml) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool.rs#L49)):*
> ```XML
>     /// Transactions are guaranteed to be unique across calls until `commit_block` is invoked.
>     // TODO: the last part about commit_block is incorrect if we delete txs in get_txs and then push back.
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<InternalTransaction>> {
> ```

Plz add a TODO to consider renaming this func: a get_ function that mutates self is misleading, it should probably also be something like pop_, but this change requires approval so TODO



_Code quote:_
```XML
    pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<InternalTransaction>> {
```
___
*[`crates/mempool/src/mempool.rs` line 60 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8J0SrD6EZWP6lwkJe:-Nx8J0SrD6EZWP6lwkJf:bgvubyp) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool.rs#L60)):*
> ```XML
>     /// Adds a new transaction to the mempool.
>     /// TODO: support fee escalation and transactions with future nonces.
>     pub fn add_tx(&mut self, tx: InternalTransaction, account: &Account) -> MempoolResult<()> {
> ```

We need ownership + we expect to get these things from RPC, which cannot pass refs IIUC. 
In other words, the only owner for this value would be the networking handler func, which probably wont have a use for this value after passing it to the mempool



_Suggestion:_
```XML
 account: Account
```
___
*[`crates/mempool/src/mempool.rs` line 69 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8MLOYCT4LdJyz4PC8:-Nx8MLOYCT4LdJyz4PC9:b-nhz3rf) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool.rs#L69)):*
> ```XML
>         self.txs_queue.push(tx);
> 
>         Ok(())
> ```

only does one lookup instead of two



_Suggestion:_
```XML
        match self.state.entry(account.address) {
            Occupied(_) => Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash() })
            Vacant(vacant_entry) => {
              vacant_entry.insert(account.address, account.state);
              self.txs_queue.push(tx);
              Ok(())
            }
        }
```
___
*[`crates/mempool/src/mempool_test.rs` line 173 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8GbtT4kVIGneB7bNu:-Nx8GbtT4kVIGneB7bNv:b-utanj7) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool_test.rs#L173)):*
> ```XML
>         mempool.txs_queue.pop_last().unwrap(),
>         PQTransaction(tx_tip_50_address_0)
>     );
> ```

Add one more tx plz with a different tip to make it clear that this is sorted by tip, otherwise it looks like LIFO



_Code quote:_
```XML
    let mut mempool = Mempool::default();
    assert!(mempool
        .add_tx(tx_tip_50_address_0.clone(), &account1)
        .is_ok());
    assert!(mempool
        .add_tx(tx_tip_100_address_1.clone(), &account2)
        .is_ok());

    assert_eq!(mempool.state.len(), 2);
    mempool.state.contains_key(&account1.address);
    mempool.state.contains_key(&account2.address);

    assert_eq!(
        mempool.txs_queue.pop_last().unwrap(),
        PQTransaction(tx_tip_100_address_1)
    );
    assert_eq!(
        mempool.txs_queue.pop_last().unwrap(),
        PQTransaction(tx_tip_50_address_0)
    );
```
___
*[`crates/mempool/src/mempool_test.rs` line 179 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8H8TEESPICmi3uBVT:-Nx8H8TEESPICmi3uBVU:b-oizze9) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool_test.rs#L179)):*
> ```XML
> fn test_add_same_tx() {
>     let account = Account {
>         address: contract_address!("0x0"),
> ```

Isn't this covered also by `Default:default()`



_Code quote:_
```XML
 address: contract_address!("0x0"),
```


<!-- Sent from Reviewable.io -->

2024-05-06 12:02 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 30 at r5](https://reviewable.io/reviews/starkware-libs/mempool/47#-NwiGdjpBLlbeR-HQ1Q3:-NxCbWlo9orV33wk51HX:b-6dx5u1) ([raw file](https://github.com/starkware-libs/mempool/blob/b4ff84a6a613c713c974fd7c2584b5e3a9ab5fb3/crates/mempool/src/mempool.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

you can "greedily" insert and use the fact that insert returns the previous value if it exists, or None otherwise.
It's OK to pollute the map since we're panicking anyway; also saves a lookup.
</blockquote></details>

yep, already changed in previous PR
___
*[`crates/mempool/src/mempool.rs` line 60 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8J0SrD6EZWP6lwkJe:-NxCdMAqEgbjideIHNip:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool.rs#L60)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We need ownership + we expect to get these things from RPC, which cannot pass refs IIUC. 
In other words, the only owner for this value would be the networking handler func, which probably wont have a use for this value after passing it to the mempool
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 69 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8MLOYCT4LdJyz4PC8:-NxCh7082WE0CXIgdO3N:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool.rs#L69)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

only does one lookup instead of two
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 173 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8GbtT4kVIGneB7bNu:-NxCl9HZ2535Sw2O62dl:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool_test.rs#L173)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add one more tx plz with a different tip to make it clear that this is sorted by tip, otherwise it looks like LIFO
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 179 at r8](https://reviewable.io/reviews/starkware-libs/mempool/47#-Nx8H8TEESPICmi3uBVT:-NxCkQy-CpoSu1JHTQ1c:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/74b3e14a39b76c5f0ced96c0425f7184614ece47/crates/mempool/src/mempool_test.rs#L179)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Isn't this covered also by `Default:default()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 13:39 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r7, 3 of 5 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/47#-:-NxD7M3a3CZwEMEgEcyI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-05-06 14:41 UTC, merged