feat: add stateless validations functionality to add_transaction
starkware-libs/mempool pull request #48
Opened 2024-04-11 13:25 UTC by ArniStarkware

2024-04-16 07:54 UTC, Yael-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/gateway/src/gateway.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nv_t50e8vGLCEEBTB5F:-Nv_t50e8vGLCEEBTB5G:blwrs4w) ([raw file](https://github.com/starkware-libs/mempool/blob/3c4470f9d129c0ac5dba4eb32f840c6a9f9453c5/crates/gateway/src/gateway.rs#L78)):*
> ```XML
>     // Send response.
>     match transaction {
>         ExternalTransaction::Declare(_) => "DECLARE".to_owned(),
> ```

not sure I understand , why the response is the transaction type?
___
*[`crates/gateway/src/gateway_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nv_tHCd-e5sEoI_vgN6:-Nv_tHCd-e5sEoI_vgN7:b6k2agl) ([raw file](https://github.com/starkware-libs/mempool/blob/3c4470f9d129c0ac5dba4eb32f840c6a9f9453c5/crates/gateway/src/gateway_test.rs#L33)):*
> ```XML
>         validate_non_zero_l1_gas_fee: true,
>         validate_non_zero_l2_gas_fee: true,
>     };
> ```

iirc , you just defined this as a const in the previous PR



_Code quote:_
```XML
    let stateless_transaction_validator_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: true,
    };
```


<!-- Sent from Reviewable.io -->

2024-04-16 11:31 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nv_t50e8vGLCEEBTB5F:-Nva2RQS7ujcTeBXzRV9:b-3tb4af) ([raw file](https://github.com/starkware-libs/mempool/blob/3c4470f9d129c0ac5dba4eb32f840c6a9f9453c5/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand , why the response is the transaction type?
</blockquote></details>

This part did not change (It only technically changed).

This is a placeholder for the response. When we will submit the transaction into the mempool - we will think about this part.
___
*[`crates/gateway/src/gateway_test.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nv_tHCd-e5sEoI_vgN6:-NvaeFvY9UJAKQtyPA8_:b-l22tk9) ([raw file](https://github.com/starkware-libs/mempool/blob/3c4470f9d129c0ac5dba4eb32f840c6a9f9453c5/crates/gateway/src/gateway_test.rs#L33)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

iirc , you just defined this as a const in the previous PR
</blockquote></details>

Indeed, but 1)  it has a very different meaning in this context. 2) It is no longer the same (we added the max_allowed_calldata_length etc).
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-NvaeddA0mOCnljatqwv:-NvaeddA0mOCnljatqww:b-b9d44i) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/stateless_transaction_validator.rs#L30)):*
> ```XML
>         }
>     }
> }
> ```

This is for the test `test_routes` to pass.



_Code quote:_
```XML
impl Default for StatelessTransactionValidatorConfig {
    fn default() -> Self {
        Self {
            validate_non_zero_l1_gas_fee: false,
            validate_non_zero_l2_gas_fee: false,
            max_calldata_length: 1000,
        }
    }
}
```
___
*[`crates/gateway/tests/routing_test.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-NvaekxW8CFNn12T4RBq:-NvaekxXE8EVTRE42x71:b-dber2m) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/tests/routing_test.rs#L26)):*
> ```XML
>     // Note: The function add transaction is becoming non-trivial.
>     //  This is the resaon for the change in the default value of
>     //  StatelessTransactionValidatorConfig.
> ```

@giladchase: I see that in the original PR: #28, creating this test you commented that this test is about testing the routing only - not about testing the expected result. You wrote you expect this test to change once we start adding logic to the `add_transaction` function.

Well - this is precisely what this PR is doing. 



_Code quote:_
```XML
    // Note: The function add transaction is becoming non-trivial.
    //  This is the resaon for the change in the default value of
    //  StatelessTransactionValidatorConfig.
```


<!-- Sent from Reviewable.io -->

2024-04-18 09:14 UTC, giladchase requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk-MwD6bO8iS3o0dFf:-Nvk-MwD6bO8iS3o0dFg:bktapc6) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/gateway.rs#L20)):*
> ```XML
> pub struct Gateway {
>     pub config: GatewayConfig,
>     pub stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
> ```

Can this be a `stateless_validations` field in `GatewayConfig`?



_Code quote:_
```XML
  pub stateless_transaction_validator_config: StatelessTransactionValidatorConfig,
```
___
*[`crates/gateway/src/gateway.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk2qzh6yTrZwUT51-S:-Nvk2qzh6yTrZwUT51-T:b-efygrw) ([raw file](https://github.com/starkware-libs/mempool/blob/18186d8020bab16097d213c1f45b83e789757e3f/crates/gateway/src/gateway.rs#L49)):*
> ```XML
> async fn add_transaction(Json(transaction): Json<ExternalTransaction>) -> impl IntoResponse {
>     match transaction {
>         ExternalTransaction::Declare(_) => "DECLARE",
> ```

I think you need to use `with_state` in order to pass state into the router (and remove the TODO).

Refs: [docs](https://docs.rs/axum/latest/axum/struct.Router.html#method.with_state), [this blog](https://www.shuttle.rs/blog/2023/12/06/using-axum-rust), or crates.io's[ own code](https://github.com/rust-lang/crates.io/blob/4a2900888eeb0b80d65913c37da022fc7700a1b3/src/router.rs#L176) for fully fleshed-out example.

That said, if it's too much work for the POC (I'm not sure TBH), then can be kept as is. 



_Code quote:_
```XML
    let add_transaction_handler = |external_transaction| {
        add_transaction(stateless_transaction_validator_config, external_transaction)
    };

    Router::new()
        .route("/is_alive", get(is_alive))
        .route("/add_transaction", post(add_transaction))
        .route("/add_transaction", post(add_transaction_handler))
    // TODO: when we need to configure the router, like adding banned ips, add it here via
    // `with_state`.
```
___
*[`crates/gateway/src/gateway_test.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk43of0VBKt2MhLRk-:-Nvk43of0VBKt2MhLRk0:b-6v2fmh) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/gateway_test.rs#L35)):*
> ```XML
>         validate_non_zero_l2_gas_fee: true,
>         ..Default::default()
>     };
> ```

Do we need negative flow for each parameterized case? That is, does the "negative logic" diverge between each case?
Asking cause it might be better to add a simple short negative test for one of them instead of adding it here. 



_Code quote:_
```XML
    // Negative flow.
    let stateless_transaction_validator_config = StatelessTransactionValidatorConfig {
        validate_non_zero_l1_gas_fee: true,
        validate_non_zero_l2_gas_fee: true,
        ..Default::default()
    };
```
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-NvaeddA0mOCnljatqwv:-NvkIrIcA_BXK_CVsTRe:b7xjwe3) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/stateless_transaction_validator.rs#L30)):*
> max_calldata_length: 1000,

Does this make sense as a default/initial/unit value? I'm not sure, because usually `Default` are trivial'ish values.

Also, if this is only useful for a test, then it should be a `create_for_testing` I think 
___
*[`crates/gateway/tests/routing_test.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-NvaekxW8CFNn12T4RBq:-NvkTMcaCuDzMeg_gBZy:bpaknes) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/tests/routing_test.rs#L26)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@giladchase: I see that in the original PR: #28, creating this test you commented that this test is about testing the routing only - not about testing the expected result. You wrote you expect this test to change once we start adding logic to the `add_transaction` function.

Well - this is precisely what this PR is doing.
</blockquote></details>

+1 on spying the original PR :heart: 

It's fine to change this test without the Note, but not critical.


<!-- Sent from Reviewable.io -->

2024-04-18 09:44 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk-MwD6bO8iS3o0dFf:-Nvk_SfF0iecBtPa3pk9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/gateway.rs#L20)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be a `stateless_validations` field in `GatewayConfig`?
</blockquote></details>

Done.
___
*[`crates/gateway/src/gateway_test.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk43of0VBKt2MhLRk-:-NvkY_JX5her_ELLQls9:b-7tg84q) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/gateway_test.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we need negative flow for each parameterized case? That is, does the "negative logic" diverge between each case?
Asking cause it might be better to add a simple short negative test for one of them instead of adding it here.
</blockquote></details>

There are tests specifically for the stateless transaction validator in crates/gateway/src/stateless_transaction_validator_test.rs

The only logic I wanted to test here is that we get the serialized error as a response.
___
*[`crates/gateway/src/stateless_transaction_validator.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-NvaeddA0mOCnljatqwv:-NvkWQLT1yASZJy52daF:bgkx0e2) ([raw file](https://github.com/starkware-libs/mempool/blob/dcbc074674b7df5450c949a4ec2c1ef08f9c3594/crates/gateway/src/stateless_transaction_validator.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> max_calldata_length: 1000,

Does this make sense as a default/initial/unit value? I'm not sure, because usually `Default` are trivial'ish values.

Also, if this is only useful for a test, then it should be a `create_for_testing` I think
</blockquote></details>

Reverted. I misunderstood `test_routes`


<!-- Sent from Reviewable.io -->

2024-04-18 11:33 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nvk2qzh6yTrZwUT51-S:-NvkyczP37aMvWK4MsI9:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/18186d8020bab16097d213c1f45b83e789757e3f/crates/gateway/src/gateway.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think you need to use `with_state` in order to pass state into the router (and remove the TODO).

Refs: [docs](https://docs.rs/axum/latest/axum/struct.Router.html#method.with_state), [this blog](https://www.shuttle.rs/blog/2023/12/06/using-axum-rust), or crates.io's[ own code](https://github.com/rust-lang/crates.io/blob/4a2900888eeb0b80d65913c37da022fc7700a1b3/src/router.rs#L176) for fully fleshed-out example.

That said, if it's too much work for the POC (I'm not sure TBH), then can be kept as is.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-21 11:31 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nw-NOe_5br7nZeZKgFe:-Nw-NOe_5br7nZeZKgFf:b7zvf8p) ([raw file](https://github.com/starkware-libs/mempool/blob/dac1cf315b422ec502ed3f436b621d67dc4d39e0/crates/gateway/src/gateway.rs#L66)):*
> ```XML
>     if let Err(error) = stateless_validator.validate(&transaction) {
>         return error.to_string();
>     }
> ```

Please implement IntoResponse for the returned errors.



_Code quote:_
```XML
    if let Err(error) = stateless_validator.validate(&transaction) {
        return error.to_string();
    }
```
___
*[`crates/gateway/src/gateway.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nw-OnAG6lRcXyeZ3ZJS:-Nw-OnAG6lRcXyeZ3ZJT:b-u3fxy2) ([raw file](https://github.com/starkware-libs/mempool/blob/dac1cf315b422ec502ed3f436b621d67dc4d39e0/crates/gateway/src/gateway.rs#L78)):*
> ```XML
>         ExternalTransaction::DeployAccount(_) => "DEPLOY_ACCOUNT".to_owned(),
>         ExternalTransaction::Invoke(_) => "INVOKE".to_owned(),
>     }
> ```

Can this part be removed now?



_Code quote:_
```XML
    // Send response.
    match transaction {
        ExternalTransaction::Declare(_) => "DECLARE".to_owned(),
        ExternalTransaction::DeployAccount(_) => "DEPLOY_ACCOUNT".to_owned(),
        ExternalTransaction::Invoke(_) => "INVOKE".to_owned(),
    }
```


<!-- Sent from Reviewable.io -->

2024-04-21 13:40 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nw-NOe_5br7nZeZKgFe:-Nw-lz7q4tNRv1nKHlD6:b-2w1iwt) ([raw file](https://github.com/starkware-libs/mempool/blob/dac1cf315b422ec502ed3f436b621d67dc4d39e0/crates/gateway/src/gateway.rs#L66)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Please implement IntoResponse for the returned errors.
</blockquote></details>

Done.
Note that the return type of `add_transaction` is now: `axum::response::Response`.
___
*[`crates/gateway/src/gateway.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/mempool/48#-Nw-OnAG6lRcXyeZ3ZJS:-Nw-mRhz1WVAq-3rMQIz:bxt44f) ([raw file](https://github.com/starkware-libs/mempool/blob/dac1cf315b422ec502ed3f436b621d67dc4d39e0/crates/gateway/src/gateway.rs#L78)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can this part be removed now?
</blockquote></details>

Not yet. I tried making this part of the code's goal more explicit.

In any case - this is out of the scope of this PR.


<!-- Sent from Reviewable.io -->

2024-04-24 11:10 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/48)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/gateway.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/mempool/48#-NwEeGla3JOhfknU5SyS:-NwEeGla3JOhfknU5SyT:b-msnevl) ([raw file](https://github.com/starkware-libs/mempool/blob/028c16e65bf3c28d6294658bcefca9fe826e00f8/crates/gateway/src/gateway.rs#L56)):*
> ```XML
>     State(config): State<GatewayConfig>,
>     Json(transaction): Json<ExternalTransaction>,
> ) -> impl IntoResponse {
> ```

I am following this [post](https://www.shuttle.rs/blog/2023/12/06/using-axum-rust#:~:text=the%200.7%20changes.-,Routing%20in%20Axum,-Axum%20follows%20the) as the template to handling responses.



_Code quote:_
```XML
) -> impl IntoResponse {
```


<!-- Sent from Reviewable.io -->

2024-04-25 08:28 UTC, ArniStarkware commented
I have split this PR into two PRs:
#70 - just dealing with return types for the gateway.
#71 - Adding the stateless validations to `add_transaction`

If someone finds the split better - let the other reviewers know.




<!-- Sent from Reviewable.io -->

2024-04-30 08:12 UTC, ArniStarkware commented
I have split this PR in two: 
#70 - Set up the return types of the gateway to match the Axum pattern.
#71 - Add the stateless validations to the gateway.





<!-- Sent from Reviewable.io -->

2024-05-06 12:01 UTC, ArniStarkware commented
#71 was merged.

2024-05-06 12:01 UTC, closed without merging