feat: add tokio executor
starkware-libs/mempool pull request #50
Opened 2024-04-14 08:39 UTC by giladchase

- Add a naive task executor, currently utilizing tokio for both CPU and IO
tasks.
- Tokio promises two separate threadpools for spawn_blocking and spawn,
which should prevent starvation, but not sure how this affects
latency.
- Added a semaphore to limit parallel CPU tasks just in case we have latency
issues (additional tasks over the limit will be queued until a thread
frees up). Moreover, papyrus' mdbx db has a hard limit on concurrent
connections, but it's probably high enough to not require using the
semaphore (4800?).
- More tests coming up.

TODO: when we start managing tokio runtimes explicitly, we might
have to modify the executor to be aware of the runtime.

2024-04-15 07:56 UTC, MohammadNassar1 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvVfuf81QhZA3g1CoOA:-NvVfuf81QhZA3g1CoOB:b-h7vnzj) ([raw file](https://github.com/starkware-libs/mempool/blob/a7ce09561417564d421aa3b814e35e5b70a4988b/crates/task_executor/src/bounded_tokio_executor.rs#L55)):*
> ```XML
> 
>         let future = async move {
>             let _permit_revoked_on_drop = semaphore.acquire_owned().await.unwrap();
> ```

It can be acquired before the async scope.



_Code quote:_
```XML
let _permit_revoked_on_drop = semaphore.acquire_owned().await.unwrap();
```
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvVgPB2CphxNdD0hshW:-NvVgPB2CphxNdD0hshX:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/a7ce09561417564d421aa3b814e35e5b70a4988b/crates/task_executor/src/bounded_tokio_executor.rs#L56)):*
> ```XML
>         let future = async move {
>             let _permit_revoked_on_drop = semaphore.acquire_owned().await.unwrap();
>             spawn_blocking(task).await
> ```





_Suggestion:_
```XML
task()
```


<!-- Sent from Reviewable.io -->

2024-04-16 11:05 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaY0iTEoqMY5TJNJis:-NvaY0iU1jGWIOYtwDQf:b-gs5h2l) ([raw file](https://github.com/starkware-libs/mempool/blob/28cc1c731435c093b0d2bb086014b044db95ea73/crates/task_executor/src/bounded_tokio_executor.rs#L9)):*
> ```XML
> #[derive(Clone)]
> pub struct BoundedTokioExecutor {
>     blocking_tasks_semaphore: Arc<Semaphore>,
> ```

IIUC the size of the thread pool used by tokio::spawn_blocking is configurable.
https://docs.rs/tokio/1.37.0/tokio/runtime/struct.Builder.html#method.max_blocking_threads
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaVx8xDuKIKVk_4-f2:-NvaVx8xDuKIKVk_4-f3:b7bia12) ([raw file](https://github.com/starkware-libs/mempool/blob/28cc1c731435c093b0d2bb086014b044db95ea73/crates/task_executor/src/bounded_tokio_executor.rs#L26)):*
> ```XML
>     /// Spawns a blocking task, ensuring it acquires a permit from the semaphore to limit
>     /// the number of concurrent executions.
>     /// Note: tokio manages spawn_blocking tasks on a separate threadpool from the IO tasks,
> ```

What does it mean? Maybe asynchronous tasks?



_Code quote:_
```XML
IO tasks
```


<!-- Sent from Reviewable.io -->

2024-04-16 13:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvVfuf81QhZA3g1CoOA:-Nvaz7yG1ILRwLe7PX79:b-nbt6gl) ([raw file](https://github.com/starkware-libs/mempool/blob/a7ce09561417564d421aa3b814e35e5b70a4988b/crates/task_executor/src/bounded_tokio_executor.rs#L55)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It can be acquired before the async scope.
</blockquote></details>

I think that'll require making the function async, which we can't do because it's a trait method and rust doesn't support async trait methods.
That's why I'm returning a Future rather than the result of its execution.
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvVgPB2CphxNdD0hshW:-NvazWGj56QWfFr3OqZE:bv1kzjl) ([raw file](https://github.com/starkware-libs/mempool/blob/a7ce09561417564d421aa3b814e35e5b70a4988b/crates/task_executor/src/bounded_tokio_executor.rs#L56)):*
> ```XML
>         let future = async move {
>             let _permit_revoked_on_drop = semaphore.acquire_owned().await.unwrap();
>             spawn_blocking(task).await
> ```

I think it has to be `task`, because spawn_blocking should be the one to call the `FnOnce` argument (after creating a new thread).
If I switch it to `task()`, then `spawn_blocking` argument will be the return value of `task()`, which is `T`.
(Verified this with the compiler just now :sweat_smile: )
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaY0iTEoqMY5TJNJis:-Nvay0Bb-5NvcV6mS3F-:boxgqi9) ([raw file](https://github.com/starkware-libs/mempool/blob/95d450c879a3af9058140e42d99c58600810e11c/crates/task_executor/src/bounded_tokio_executor.rs#L9)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

IIUC the size of the thread pool used by tokio::spawn_blocking is configurable.
https://docs.rs/tokio/1.37.0/tokio/runtime/struct.Builder.html#method.max_blocking_threads
</blockquote></details>

Ohhh nice!  :star_struck: 

That means I should remove the semaphore and the semaphore test right? Is there any other reason for them now?

(After adding a configurable `max_blocking_threads` arg to the constructor of the struct and using it.)
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaVx8xDuKIKVk_4-f2:-NvayaP3CHiZ-lNmoH6N:b-dqlwc5) ([raw file](https://github.com/starkware-libs/mempool/blob/95d450c879a3af9058140e42d99c58600810e11c/crates/task_executor/src/bounded_tokio_executor.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

What does it mean? Maybe asynchronous tasks?
</blockquote></details>

Ya in a previous iteration i called the API "spawn_cpu_task" and "spawn_io_task" but decided aginst it, so of course I forgot about the comment :smiling_face_with_tear:.


<!-- Sent from Reviewable.io -->

2024-04-17 05:43 UTC, elintul reviewed
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @MohammadNassar1)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nve_3SE5YQNy4QqmUjx:-Nve_3SFDvXMO8G0kFQD:bmx28cu) ([raw file](https://github.com/starkware-libs/mempool/blob/a6a9b32acc92fb6c577c4e0641aa4f8a7fdd12f9/crates/task_executor/src/bounded_tokio_executor.rs#L8)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct BoundedTokioExecutor {
> ```

WDYM by bounded? Please add a short docstring.



_Code quote:_
```XML
Bounded
```


<!-- Sent from Reviewable.io -->

2024-04-18 07:54 UTC, dafnamatsry requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaY0iTEoqMY5TJNJis:-NvkBR1k05b89QVOdi7T:b-vow2j1) ([raw file](https://github.com/starkware-libs/mempool/blob/95d450c879a3af9058140e42d99c58600810e11c/crates/task_executor/src/bounded_tokio_executor.rs#L9)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ohhh nice!  :star_struck: 

That means I should remove the semaphore and the semaphore test right? Is there any other reason for them now?

(After adding a configurable `max_blocking_threads` arg to the constructor of the struct and using it.)
</blockquote></details>

Yes, I think you can remove it...


<!-- Sent from Reviewable.io -->

2024-05-08 11:55 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @MohammadNassar1)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvaY0iTEoqMY5TJNJis:-NwsKNJc8OX0gOet-mpI:b-wstyjv) ([raw file](https://github.com/starkware-libs/mempool/blob/95d450c879a3af9058140e42d99c58600810e11c/crates/task_executor/src/bounded_tokio_executor.rs#L9)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Yes, I think you can remove it...
</blockquote></details>

Throttling removed altogether.
___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nve_3SE5YQNy4QqmUjx:-NxN2VnO-4J6JGL07KNH:boateuu) ([raw file](https://github.com/starkware-libs/mempool/blob/a6a9b32acc92fb6c577c4e0641aa4f8a7fdd12f9/crates/task_executor/src/bounded_tokio_executor.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM by bounded? Please add a short docstring.
</blockquote></details>

Removed now, the idea was to throttle the num of CPU bound tasks that are run in parallel.
Removed until we benchmark and actually justify it's necessity.


<!-- Sent from Reviewable.io -->

2024-05-22 10:11 UTC, elintul approved these changes
> Reviewed 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @ittaysw, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-22 12:28 UTC, giladchase reviewed
update: Added `Handle` field to `TokioExecutor` struct. This change ensures that all async/blocking tasks are managed by that specified tokio runtime Handle (which is a fixed event loop, scheduler, blocking task pool, etc.). 

Before this change, the `spawn` and `spawn_blocking` methods used Tokio's default task functions, which run on whatever parent handle that called them, which doesn't satisfy our requirement from the executor, which is that all async/cpu-bound tasks are run through it. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50#-:-NyVDV9O3Kzj3JVN_xfD:b-txt414)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, @ittaysw, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-05-22 13:09 UTC, MohammadNassar1 approved these changes
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @ittaysw)

___
*[`crates/task_executor/src/bounded_tokio_executor.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/mempool/50#-NvVgPB2CphxNdD0hshW:-NvbXF719jF-sipLhl4F:b-w74m) ([raw file](https://github.com/starkware-libs/mempool/blob/a7ce09561417564d421aa3b814e35e5b70a4988b/crates/task_executor/src/bounded_tokio_executor.rs#L56)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think it has to be `task`, because spawn_blocking should be the one to call the `FnOnce` argument (after creating a new thread).
If I switch it to `task()`, then `spawn_blocking` argument will be the return value of `task()`, which is `T`.
(Verified this with the compiler just now :sweat_smile: )
</blockquote></details>

Ops sorry


<!-- Sent from Reviewable.io -->

2024-05-23 08:39 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @ittaysw, and @MohammadNassar1)

___
*[`crates/task_executor/src/tokio_executor.rs` line 58 at r10](https://reviewable.io/reviews/starkware-libs/mempool/50#-NyZ_x1A2jj2BFoT7vDZ:-NyZ_x1A2jj2BFoT7vD_:bppwwk9) ([raw file](https://github.com/starkware-libs/mempool/blob/336270ac387f399207c50da772a1ff6ba842851c/crates/task_executor/src/tokio_executor.rs#L58)):*
> ```XML
>         F::Output: Send + 'static,
>     {
>         self.handle.spawn(future)
> ```

Note: this introduces a bit of duplication with `spawn` (both are simply wrappers around the same `self.handle.spawn(future)`.
This can be resolved by making `spawn` call `spawn_with_handle` under the hood, but that might create confusion for readers.

Alternatively, we could make a private function that returns a JoinHandle that both `spawn` and `spawn_with_handle` call. However, that function would be identical to `spawn_with_handle`, which could again cause some confusion.

Not sure, though, WDYT? 



_Code quote:_
```XML
        self.handle.spawn(future)
```


<!-- Sent from Reviewable.io -->

2024-05-27 11:20 UTC, elintul reviewed
> Reviewed 1 of 1 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, @ittaysw, and @MohammadNassar1)

___
*[`crates/task_executor/src/tokio_executor.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nytltv75Duz9HcGejmc:-Nytltv75Duz9HcGejmd:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/92b0979e3ab3c07ec71940659df1712810ad717a/crates/task_executor/src/tokio_executor.rs#L10)):*
> ```XML
> pub struct TokioExecutor {
>     // Invariant: The handle must remain private to ensure all tasks are spawned
>     // via TokioExecutor, maintaining control and consistency.
> ```





_Suggestion:_
```XML
via `TokioExecutor`
```


<!-- Sent from Reviewable.io -->

2024-05-28 07:39 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @ittaysw)

___
*[`crates/task_executor/src/tokio_executor.rs` line 58 at r10](https://reviewable.io/reviews/starkware-libs/mempool/50#-NyZ_x1A2jj2BFoT7vDZ:-Nyy6s3j1aqAd0_TUsXW:b-d9ivwt) ([raw file](https://github.com/starkware-libs/mempool/blob/387de4b832533ba43db8e24f0e95d717bef2980f/crates/task_executor/src/tokio_executor.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Note: this introduces a bit of duplication with `spawn` (both are simply wrappers around the same `self.handle.spawn(future)`.
This can be resolved by making `spawn` call `spawn_with_handle` under the hood, but that might create confusion for readers.

Alternatively, we could make a private function that returns a JoinHandle that both `spawn` and `spawn_with_handle` call. However, that function would be identical to `spawn_with_handle`, which could again cause some confusion.

Not sure, though, WDYT?
</blockquote></details>

Intuitively, I'd like to encourage correct usage of the executor, by not allowing the user to call the wrong `spawn`.
Why not make `spawn[_blocking]` spawn the tasks in the context of `self.handle`, and not expose `spawn_with_handle`?
___
*[`crates/task_executor/src/tokio_executor.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nyy0AiN7RfZbvWhNNoT:-Nyy0AiN7RfZbvWhNNoU:btqyca0) ([raw file](https://github.com/starkware-libs/mempool/blob/f50b3475c6be0eb36738ddba5b04ec6bad373f6b/crates/task_executor/src/tokio_executor.rs#L10)):*
> ```XML
> pub struct TokioExecutor {
>     // Invariant: The handle must remain private to ensure all tasks are spawned
>     // via TokioExecutor, maintaining control and consistency.
> ```

Rephrasing suggestion, after talking F2F.

The following sentence from your comment above is also good: "This change ensures that all async/blocking tasks are managed by that specified tokio runtime Handle (which is a fixed event loop, scheduler, blocking task pool, etc.)."



_Suggestion:_
```XML
    // Invariant: the handle must remain private to ensure all task spawned via this
    // executor originate from the same handle, maintaining control and consistency.
```


<!-- Sent from Reviewable.io -->

2024-05-28 09:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, and @ittaysw)

___
*[`crates/task_executor/src/tokio_executor.rs` line 58 at r10](https://reviewable.io/reviews/starkware-libs/mempool/50#-NyZ_x1A2jj2BFoT7vDZ:-Nyy_4nm445P-On55m4K:b-k24wz3) ([raw file](https://github.com/starkware-libs/mempool/blob/387de4b832533ba43db8e24f0e95d717bef2980f/crates/task_executor/src/tokio_executor.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Intuitively, I'd like to encourage correct usage of the executor, by not allowing the user to call the wrong `spawn`.
Why not make `spawn[_blocking]` spawn the tasks in the context of `self.handle`, and not expose `spawn_with_handle`?
</blockquote></details>

I see your point, i thought about it as well, but if we do this it might make readers think that spawn is interchangeable with spawn_with_handle, which is not the intention. 


<!-- Sent from Reviewable.io -->

2024-05-28 09:44 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @giladchase, and @ittaysw)

___
*[`crates/task_executor/src/tokio_executor.rs` line 58 at r10](https://reviewable.io/reviews/starkware-libs/mempool/50#-NyZ_x1A2jj2BFoT7vDZ:-Nyy_dYx00cluyOoQ18g:b-ucfkn4) ([raw file](https://github.com/starkware-libs/mempool/blob/387de4b832533ba43db8e24f0e95d717bef2980f/crates/task_executor/src/tokio_executor.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I see your point, i thought about it as well, but if we do this it might make readers think that spawn is interchangeable with spawn_with_handle, which is not the intention.
</blockquote></details>

Thanks.
___
*[`crates/task_executor/src/tokio_executor.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nyy0AiN7RfZbvWhNNoT:-Nyy_Z2-0Dz4QLzmvsMn:b-fb5ebl) ([raw file](https://github.com/starkware-libs/mempool/blob/f50b3475c6be0eb36738ddba5b04ec6bad373f6b/crates/task_executor/src/tokio_executor.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Rephrasing suggestion, after talking F2F.

The following sentence from your comment above is also good: "This change ensures that all async/blocking tasks are managed by that specified tokio runtime Handle (which is a fixed event loop, scheduler, blocking task pool, etc.)."
</blockquote></details>

WDYT about my doc. suggestion?


<!-- Sent from Reviewable.io -->

2024-05-28 10:37 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware, @dafnamatsry, @elintul, and @ittaysw)

___
*[`crates/task_executor/src/tokio_executor.rs` line 10 at r11](https://reviewable.io/reviews/starkware-libs/mempool/50#-Nyy0AiN7RfZbvWhNNoT:-NyyjWVU039NPs8GbD9d:b-lva1cm) ([raw file](https://github.com/starkware-libs/mempool/blob/f50b3475c6be0eb36738ddba5b04ec6bad373f6b/crates/task_executor/src/tokio_executor.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about my doc. suggestion?
</blockquote></details>

WHoops sorry, the push failed.
Fixed now.


<!-- Sent from Reviewable.io -->

2024-05-28 11:31 UTC, dafnamatsry approved these changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r6, 1 of 1 files at r9, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/50)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @ittaysw)



<!-- Sent from Reviewable.io -->

2024-05-29 03:59 UTC, merged