feat: rpc state reader
starkware-libs/mempool pull request #64
Opened 2024-04-24 10:25 UTC by Yael-Starkware

2024-04-25 09:28 UTC, ArniStarkware commented
*[`tmp1.patch` line 0 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJ_NHL-T_E5LIkytgI:-NwJ_NHMCxodAqFlR-mD:bau1lax) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/tmp1.patch#L0)):*
What is this file? It seems like something related to the `git diff`


<!-- Sent from Reviewable.io -->

2024-04-25 10:16 UTC, ArniStarkware requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_objects.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJa7Cw3ntFNr_4U96J:-NwJa7Cw3ntFNr_4U96K:bbdu1vn) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L12)):*
> ```XML
>     #[serde(rename = "pending")]
>     Pending,
> }
> ```

Tag for what? Document/ Rename.
This is like the [block identifier](https://github.com/starkware-industries/starkware/blob/65b800686f19f769197ee592423194eb18744c35/src/starkware/starknet/services/api/feeder_gateway/response_objects.py#L69), isn't it? 



_Code quote:_
```XML
#[derive(Deserialize, Serialize)]
pub enum Tag {
    /// The most recent fully constructed block
    #[serde(rename = "latest")]
    Latest,
    /// Currently constructed block
    #[serde(rename = "pending")]
    Pending,
}
```
___
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJarCyEowOUZCVnYhk:-NwJarCyEowOUZCVnYhl:b1y0zxv) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
> ```XML
>     Tag(Tag),
>     // There are additional options in the spec that are not implemented here
> }
> ```

Are you sure this is `block_id` and not `block_number`/ `block_idintifier`?
The name `block id` is used for the offset where the block is saved in aerospike (not that this number is relevant in this context). If it is the replacement of BlockIdentifier, please rename it accordingly.  



_Suggestion:_
```XML
#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub enum BlockIdentifier {
    Tag(Tag),
    // There are additional options in the spec that are not implemented here
}
```
___
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJbTx74x6LKdOAVLa6:-NwJbTx74x6LKdOAVLa7:b-jgkll9) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
> ```XML
>     Tag(Tag),
>     // There are additional options in the spec that are not implemented here
> }
> ```

Why two structs? Maybe this can be squashed. 

See: about [block number](https://github.com/starkware-libs/starknet-api/blob/fa2cf6d6da46c43efe141e9ffc044ae9ebbf4541/src/block.rs#L136).



_Suggestion:_
```XML
#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub enum BlockIdentifier {
    /// The most recent fully constructed block
    #[serde(rename = "latest")]
    Latest,
    /// Currently constructed block
    #[serde(rename = "pending")]
    Pending,
    // There are additional options in the spec that are not implemented here
    // Is block number relevant here?
    BlockNumber(u64) // There is a block number struct in starknet-api. 
}
```
___
*[`crates/gateway/src/rpc_objects.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJcsqx5rQY9eNwdn_p:-NwJcsqx5rQY9eNwdn_q:b8ftjlp) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L32)):*
> ```XML
>     Success(RpcSuccessResponse),
>     Error(RpcErrorResponse),
> }
> ```

Does this make sense? 



_Suggestion:_
```XML
pub type RpcResponse = Result<RpcSuccessResponse, RpcErrorResponse>;
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJg6906bWal86TMXOA:-NwJg691CE0xX6pkiWbt:b-dkj5dz) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L27)):*
> ```XML
>     pub fn new(chain_id: ChainId) -> Self {
>         let url = match chain_id.0.as_str() {
>             "SN_MAIN" => "https://papyrus-for-mempool-mainnet.sw-dev.io/rpc/v0_6".to_string(),
> ```

Will the version change?
If so, extract the URLs into variables and add a separate version variable. concatenate the strings using The rust [URL create](https://docs.rs/url/latest/url/) (note the `join` method).



_Code quote:_
```XML
"https://papyrus-for-mempool-mainnet.sw-dev.io/rpc/v0_6"
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJh6N574sZT2MIa2m7:-NwJh6N574sZT2MIa2m8:b-o9by9s) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L32)):*
> ```XML
>                 "https://papyrus-for-mempool-integration-sepolia.sw-dev.io/rpc/v0_6".to_string()
>             }
>             _ => panic!("Unsupported chain id"),
> ```

Should this panic? Really asking - it might be ok. 



_Code quote:_
```XML
            _ => panic!("Unsupported chain id"),
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJkDM53dZgXEiwG2NR:-NwJkDM53dZgXEiwG2NS:b3e88bp) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L65)):*
> ```XML
>                 RpcResponse::Success(rpc_success_response) => Ok(rpc_success_response.result),
>                 RpcResponse::Error(rpc_error_response) => match rpc_error_response.error.code {
>                     24 => Err(StateError::StateReadError("Block not found".to_string())),
> ```

Where are these error codes coming from? Is there an enum we can import?



_Code quote:_
```XML
24 
```
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJfl7X0dHtAsAZCCzI:-NwJfl7X0dHtAsAZCCzJ:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader_test.rs#L44)):*
> ```XML
>         format!("{}", res.unwrap_err()),
>         format!("{}", expected_error)
>     );
> ```





_Suggestion:_
```XML
    let expected_error = format!(
        "Contract address not found, request: {}",
        json!({
        "jsonrpc": "2.0",
        "id": 0,
        "method": "starknet_getNonce",
        "params": json!(GetNonceParams {
            block_id: BlockId::Tag(Tag::Latest),
            contract_address,
        })})
    );
    assert_matches!(
        res,
        Err(StateError::StateReadError(state_reader_error))
        if state_reader_error == expected_error
    );
```


<!-- Sent from Reviewable.io -->

2024-04-30 09:39 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`tmp1.patch` line  at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJ_NHL-T_E5LIkytgI:-NwiLTZGCjkROgUD6Jxs:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/tmp1.patch#L)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

What is this file? It seems like something related to the `git diff`
</blockquote></details>

Done.
___
*[`crates/gateway/src/rpc_objects.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJa7Cw3ntFNr_4U96J:-Nwi4d7u1a3ZidMY5MXs:b1zluk9) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L12)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Tag for what? Document/ Rename.
This is like the [block identifier](https://github.com/starkware-industries/starkware/blob/65b800686f19f769197ee592423194eb18744c35/src/starkware/starknet/services/api/feeder_gateway/response_objects.py#L69), isn't it?
</blockquote></details>

changed the name to BlockTag as it appears in the spec
___
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJarCyEowOUZCVnYhk:-Nwi4kNA7VpOvpA9iBRH:b40cffc) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Are you sure this is `block_id` and not `block_number`/ `block_idintifier`?
The name `block id` is used for the offset where the block is saved in aerospike (not that this number is relevant in this context). If it is the replacement of BlockIdentifier, please rename it accordingly.
</blockquote></details>

BlockId is the name in the spec, trying to be consistent with that
___
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJbTx74x6LKdOAVLa6:-Nwi5Dv4D6tmd88CO8yd:b-lexbw7) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Why two structs? Maybe this can be squashed. 

See: about [block number](https://github.com/starkware-libs/starknet-api/blob/fa2cf6d6da46c43efe141e9ffc044ae9ebbf4541/src/block.rs#L136).
</blockquote></details>

I'm trying to be consistent with the spec structure, 
the block id is an enum of blockTag, BlockNumber and blockHash, but currently we only use BlockTag so I didn't want to add additional options. it can be added in the future.
___
*[`crates/gateway/src/rpc_objects.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJcsqx5rQY9eNwdn_p:-Nwi5sWZAjduNcli1wZQ:bda8cf) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this make sense?
</blockquote></details>

since I'm using Serde to deserealize this object, it can't be a result type.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJg6906bWal86TMXOA:-NwiAsZq8088-PRCggQU:b6tzri6) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L27)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Will the version change?
If so, extract the URLs into variables and add a separate version variable. concatenate the strings using The rust [URL create](https://docs.rs/url/latest/url/) (note the `join` method).
</blockquote></details>

Done.
I used simple string concatenation since the URL create brought now error types into scope and is makes things more complicated IMO.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJh6N574sZT2MIa2m7:-NwhtMzF0QMEbkZSyGTl:b-wyc3yi) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L32)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Should this panic? Really asking - it might be ok.
</blockquote></details>

yes, this means that we configured a wrong chain_id, we can't really progress with that.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJkDM53dZgXEiwG2NR:-NwiC1wPC01Gls1g7WQE:b-g2j8r0) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L65)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Where are these error codes coming from? Is there an enum we can import?
</blockquote></details>

no enum, numbers are coming from the spec. I defined constants for now since enum requires defining a custom deserealization. added a todo for later.
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJfl7X0dHtAsAZCCzI:-NwiCV6n1OfMsksZ0M8V:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader_test.rs#L44)):*
> ```XML
>         format!("{}", res.unwrap_err()),
>         format!("{}", expected_error)
>     );
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 09:45 UTC, ArniStarkware commented
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJbTx74x6LKdOAVLa6:-NwiNqLA9hdcX5zRvLVt:bph5xgd) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I'm trying to be consistent with the spec structure, 
the block id is an enum of blockTag, BlockNumber and blockHash, but currently we only use BlockTag so I didn't want to add additional options. it can be added in the future.
</blockquote></details>

Add a link to the spec to the code? Or is it too dynamic to be in code. At least link in this thread :   )


<!-- Sent from Reviewable.io -->

2024-04-30 09:47 UTC, Yael-Starkware reviewed
@ArniStarkware 
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64#-:-NwiOiYN0jOeN-yjI_tb:b-snei9o)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-04-30 09:47 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/rpc_objects.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJbTx74x6LKdOAVLa6:-NwiOnUPEmuHuPvdQFd9:bio3xli) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_objects.rs#L19)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a link to the spec to the code? Or is it too dynamic to be in code. At least link in this thread :   )
</blockquote></details>

added above.


<!-- Sent from Reviewable.io -->

2024-04-30 09:49 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJg6906bWal86TMXOA:-NwiOSjD49SSGryawhr-:b-8yy4rx) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L27)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
I used simple string concatenation since the URL create brought now error types into scope and is makes things more complicated IMO.
</blockquote></details>

I insist. Use the URL crate. URLs should be handled using the appropriate tools.


<!-- Sent from Reviewable.io -->

2024-04-30 12:58 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJg6906bWal86TMXOA:-Nwj4OAc8DakpRS7UkBd:b-vhrt04) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L27)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I insist. Use the URL crate. URLs should be handled using the appropriate tools.
</blockquote></details>

ok! done.


<!-- Sent from Reviewable.io -->

2024-05-01 08:29 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwJg6906bWal86TMXOA:-NwnGNQVEFWhHDyNy54l:b-501bnb) ([raw file](https://github.com/starkware-libs/mempool/blob/725dda93ee84cd7fdbed784babb1229f4d2e23e9/crates/gateway/src/rpc_state_reader.rs#L27)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

ok! done.
</blockquote></details>

after discussing f2f, the Url will be constructed in the config phase. I removed the new function.


<!-- Sent from Reviewable.io -->

2024-05-02 05:54 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 84 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwrrQGi-AcbN68nRTkW:-NwrrQGi-AcbN68nRTkX:b4dky85) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L84)):*
> ```XML
>     fn get_nonce_at(&self, contract_address: ContractAddress) -> StateResult<Nonce> {
>         let get_nonce_params = GetNonceParams {
>             block_id: BlockId::Tag(BlockTag::Latest),
> ```

pass self.block_number instead of latest


<!-- Sent from Reviewable.io -->

2024-05-02 07:36 UTC, dafnamatsry requested changes
> Reviewed 1 of 4 files at r2, 2 of 3 files at r5, 1 of 1 files at r6, 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 4 of 10 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 39 at r5](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nwnd59I3O85PI90X06e:-Nwnd59I3O85PI90X06f:b-i2mqk1) ([raw file](https://github.com/starkware-libs/mempool/blob/a3d748e44f045a9f243a43c72ec558accb180ec8/crates/gateway/src/rpc_state_reader.rs#L39)):*
> ```XML
>             })?;
> 
>         if response.status().is_success() {
> ```

Put the negative case first:

```
if !response.status().is_success() {
   Err(...)
}

let response_text = response...
...
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwrsTYS7cAyeJeLmr2z:-NwrsTYS7cAyeJeLmr3-:bp6mwpw) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L45)):*
> ```XML
> 
>             let rpc_response: RpcResponse = serde_json::from_str(&response_text)
>                 .map_err(|_| StateError::StateReadError("Bad rpc response".to_string()))?;
> ```

I see the Response struct has a `json()` method (https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json).
I found this example in Papyrus that uses it: https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_node/examples/get_transaction_hash.rs#L296



_Code quote:_
```XML
            let response_text = response
                .text()
                .map_err(|_| StateError::StateReadError("Bad rpc response".to_string()))?;

            let rpc_response: RpcResponse = serde_json::from_str(&response_text)
                .map_err(|_| StateError::StateReadError("Bad rpc response".to_string()))?;
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwryQos2O_tYhuxAT2j:-NwryQot-dTvmFtPNCba:b5nf1kw) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L49)):*
> ```XML
>             match rpc_response {
>                 RpcResponse::Success(rpc_success_response) => Ok(rpc_success_response.result),
>                 RpcResponse::Error(rpc_error_response) => match rpc_error_response.error.code {
> ```

Isn't this case covered in the `response.status().is_success()?`



_Code quote:_
```XML
RpcResponse::Error(rpc_error_response)
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 73 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nws-AzZC6TrQ6cZfoen:-Nws-Az_01fObc6VinzS:bgbscyd) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L73)):*
> ```XML
> 
> impl StateReader for RpcStateReader {
>     #[allow(unused_variables)]
> ```

I think another option is to prefix the variable names with `_`.



_Code quote:_
```XML
#[allow(unused_variables)]
```
___
*[`crates/gateway/src/rpc_state_reader.rs` line 94 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nws2IZiDT_5gK3mpUC0:-Nws2IZiDT_5gK3mpUC1:bjgqxvt) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L94)):*
> ```XML
>         });
> 
>         let result = self.send_rpc_request(request_body)?;
> ```

Consider defining and returning the result as`serde_json::Value` from `send_rpc_request`. Then you won't need to convert it to json here...
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwsAoqH5tP-c0yf9ONe:-NwsAoqH5tP-c0yf9ONf:b-divi3w) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader_test.rs#L26)):*
> ```XML
> 
> #[test]
> fn test_rpc_get_nonce() {
> ```

In unit tests, it's best to avoid depending on the actual remote RPC server. This should be done in an integration test.
We need some mock rpc client here. Try taking a look at mockito: https://docs.rs/mockito/latest/mockito/


<!-- Sent from Reviewable.io -->

2024-05-02 14:13 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 2 of 10 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @giladchase)

___
*[`crates/gateway/src/rpc_state_reader.rs` line 39 at r5](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nwnd59I3O85PI90X06e:-Nwt3Pbz9wcsCmNnXtUx:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/a3d748e44f045a9f243a43c72ec558accb180ec8/crates/gateway/src/rpc_state_reader.rs#L39)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Put the negative case first:

```
if !response.status().is_success() {
   Err(...)
}

let response_text = response...
...
```
</blockquote></details>

Done.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwrsTYS7cAyeJeLmr2z:-Nwt4XJT5r3lAvhDGHfh:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L45)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I see the Response struct has a `json()` method (https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json).
I found this example in Papyrus that uses it: https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_node/examples/get_transaction_hash.rs#L296
</blockquote></details>

Done.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwryQos2O_tYhuxAT2j:-Nwt2aZz5PUQbvuErQ7A:bg89325) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L49)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Isn't this case covered in the `response.status().is_success()?`
</blockquote></details>

response.status().is_success() is checking that the communication between the server and client succeeded, while this error derive from the request parameters (while the communication was successful).
___
*[`crates/gateway/src/rpc_state_reader.rs` line 73 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nws-AzZC6TrQ6cZfoen:-Nwt0oEF7XuxMYPSGm6r:bdxil71) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L73)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think another option is to prefix the variable names with `_`.
</blockquote></details>

These will be deleted anyway once the functions are implemented (in the following PRs).
___
*[`crates/gateway/src/rpc_state_reader.rs` line 84 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwrrQGi-AcbN68nRTkW:-Nwt4ccUCemUEzh3Ki5l:b-7rl0jd) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L84)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

pass self.block_number instead of latest
</blockquote></details>

done.
___
*[`crates/gateway/src/rpc_state_reader.rs` line 94 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nws2IZiDT_5gK3mpUC0:-Nwt5_Wn-Q42GuKS1hZZ:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader.rs#L94)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Consider defining and returning the result as`serde_json::Value` from `send_rpc_request`. Then you won't need to convert it to json here...
</blockquote></details>

Done.
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwsAoqH5tP-c0yf9ONe:-Nwt0cRv0ljpDYFBW4_P:bu5x5u) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader_test.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

In unit tests, it's best to avoid depending on the actual remote RPC server. This should be done in an integration test.
We need some mock rpc client here. Try taking a look at mockito: https://docs.rs/mockito/latest/mockito/
</blockquote></details>

after discussing f2f it was decided to remove these tests.
the state reader will be tested as part of the integration test


<!-- Sent from Reviewable.io -->

2024-05-05 08:00 UTC, Yael-Starkware commented
* **#64** <a href="https://app.graphite.dev/github/pr/starkware-libs/mempool/64?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Yael-Starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-05 08:24 UTC, dafnamatsry requested changes
> Reviewed 1 of 6 files at r3, 2 of 4 files at r7, 1 of 1 files at r8, 3 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwsAoqH5tP-c0yf9ONe:-Nx6pVoF8E0B-SvFSdNd:b-7gigi7) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader_test.rs#L26)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

after discussing f2f it was decided to remove these tests.
the state reader will be tested as part of the integration test
</blockquote></details>

I think you can revert this file...
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nx6qTbo9i7sUB898ROi:-Nx6qTbo9i7sUB898ROj:b-38ol8h) ([raw file](https://github.com/starkware-libs/mempool/blob/e353288675ba1e7be5231a73c6bab0fa248744c6/crates/gateway/src/rpc_state_reader_test.rs#L67)):*
> ```XML
> 
> #[test]
> fn test_rpc_get_block_info() {
> ```

Should it be here?



_Code quote:_
```XML
test_rpc_get_block_info()
```


<!-- Sent from Reviewable.io -->

2024-05-05 09:40 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)

___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/mempool/64#-NwsAoqH5tP-c0yf9ONe:-Nx76N8167OLNjok5NEd:b7rc921) ([raw file](https://github.com/starkware-libs/mempool/blob/b7769636b3b2fe6c49d83baaf60c42928a16e22d/crates/gateway/src/rpc_state_reader_test.rs#L26)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

I think you can revert this file...
</blockquote></details>

Oh sorry I already deleted it , but kept it aside for testing , and now it accidentally got in again.
deleting. 
___
*[`crates/gateway/src/rpc_state_reader_test.rs` line 67 at r9](https://reviewable.io/reviews/starkware-libs/mempool/64#-Nx6qTbo9i7sUB898ROi:-Nx772nM3AYUbyu3_oDo:b-qc63mx) ([raw file](https://github.com/starkware-libs/mempool/blob/e353288675ba1e7be5231a73c6bab0fa248744c6/crates/gateway/src/rpc_state_reader_test.rs#L67)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Should it be here?
</blockquote></details>

deleted the file.


<!-- Sent from Reviewable.io -->

2024-05-05 10:05 UTC, ArniStarkware approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/64)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry and @giladchase)



<!-- Sent from Reviewable.io -->

2024-05-05 10:23 UTC, merged