feat: adds AddressPriorityQueue to Mempool
starkware-libs/mempool pull request #72
Opened 2024-04-25 13:28 UTC by ayeletstarkware

A hashmap of ContractAddress to AddressStore has been added to the Mempool, enabling the handling of multiple transactions from each contract address. However, only one transaction from each account can be in the Mempool's txs_queue at a time.

Struct AddressStore:
- Implemented by Vec<ThinTransaction>
- Contains the following functions: push, top, pop_front, is_empty, contains, len

Mempool Changes:
A new field in Mempool, address_to_store, was added. This field maintains a hashmap mapping each address to its address store transactions. It replaces the previous state field and assumes an ordered list without gaps. 
- The state is not needed for now because it was used to ensure no gaps, and nonces are assumed to be in the correct order.
- Functions in Mempool (new, add_tx, and get_txs) have been updated to utilize this new address store.

Tests:
- Checks have been implemented to prevent duplicate transactions from being sent.
- Transactions are removed from the Mempool's priority queues when processed.

Not Implemented Yet:
In the next PR, I will implement support in get_txs such that if n_txs is greater than the number of transactions in txs_queue, it will also check and add transactions from address_to_store. This means the result of get_txs might contain a few transactions from the same address.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/72)

2024-05-19 10:57 UTC, giladchase reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/mempool/72#-NyFRYuN9Kt9A6b0ddwy:-NyFRYuN9Kt9A6b0ddwz:b3s8y3a) ([raw file](https://github.com/starkware-libs/mempool/blob/b838eefbece8788a26ea43eaf2d19bdd7e735688/crates/mempool/src/mempool.rs#L26)):*
> ```XML
> 
> impl Mempool {
>     pub fn new(inputs: Vec<MempoolInput>) -> Self {
> ```

I think maybe parts of this have already been merged? in a separate PR? not sure, can you rebase plz?


<!-- Sent from Reviewable.io -->

2024-06-06 07:39 UTC, elintul reviewed
> Reviewed 2 of 8 files at r2, 5 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-06 07:42 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgU6LABuvmfBvUmjkV:-NzgU6LABuvmfBvUmjkW:b28lw4j) (no related file):*
Implemented AddressPriorityQueue in mempool, which affected three functions:
add_tx, new, get_txs
The related tests for each function are:
add_tx - test_add_tx
new - test_new, test_new with_duplicate_tx
get_tx - test_get_txs

removed `test_mempool_initialization_with_duplicate_sender_addresses` because we support few txs from the same sender address


priority queue checked are checked in #210 

___


<!-- Sent from Reviewable.io -->

2024-06-13 08:57 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 8 files at r2, 1 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 11 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/Cargo.toml` line 17 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FdOkX2PPZ1J87v38a:-O-FdOkX2PPZ1J87v38b:b-c6gbp5) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/Cargo.toml#L17)):*
> ```TOML
> starknet_api.workspace = true
> starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
> thiserror.workspace = true
> ```

Please remove it; it's not in use.



_Code quote:_
```TOML
thiserror.workspace = true
```
___
*[`crates/mempool/src/mempool.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FfvYe3fruQgoEYvr-:-O-FfvYe3fruQgoEYvr0:bvx39yv) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L20)):*
> ```XML
> pub mod mempool_test;
> 
> #[derive(Debug)]
> ```

Can be removed. See below my suggestion to replace `assert_match`



_Code quote:_
```XML
#[derive(Debug)]
```
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgE9D542JI-O-Wde2:-O-FgE9E4woAfmLk0fRR:b-4dryx7) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
> ```XML
>     // TODO: add docstring explaining visibility and coupling of the fields.
>     txs_queue: TransactionPriorityQueue,
>     address_to_queue: HashMap<ContractAddress, AddressPriorityQueue>,
> ```

I don't think `AddressPriorityQueue` is a good name.
It's a tx store.



_Code quote:_
```XML
 AddressPriorityQueue
```
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgUr77NPvFeiRItqG:-O-FgUr77NPvFeiRItqH:b-4rupni) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
> ```XML
>     // TODO: add docstring explaining visibility and coupling of the fields.
>     txs_queue: TransactionPriorityQueue,
>     address_to_queue: HashMap<ContractAddress, AddressPriorityQueue>,
> ```

Please use HashMap instead of a vector.
This way, we'll also support multi-nonces with holes.



_Code quote:_
```XML
AddressPriorityQueue
```
___
*[`crates/mempool/src/mempool.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fl2uE5JepqtWfLctf:-O-Fl2uF7FUwCcJOqzQT:b348lux) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L52)):*
> ```XML
>     // back. TODO: Consider renaming to `pop_txs` to be more consistent with the standard library.
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
>         let txs = self.txs_queue.pop_last_chunk(n_txs);
> ```

Question: If `n_txs` is larger than the PQ size, do you pop txs after updating the PQ from `AddressPriorityQueue`?



_Code quote:_
```XML
 let txs = self.txs_queue.pop_last_chunk(n_txs);
```
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FncTm0FGrzfYa1a1_:-O-FncTnEIPBXobJHy72:bth98p1) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L106)):*
> ```XML
> 
>         address_queue.push(tx.clone());
>         self.state.insert(account.sender_address, account.state);
> ```

Can you please explain why you need the state?



_Code quote:_
```XML
 self.state.insert(account.sender_address, account.state);
```
___
*[`crates/mempool/src/mempool.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FnJTt0EbNZfplx1iO:-O-FnJTuCJNeNK3Dyh2c:b-k1an9e) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L108)):*
> ```XML
>         self.state.insert(account.sender_address, account.state);
> 
>         if let Some(state) = self.state.get(&tx.sender_address) {
> ```

It seems that you are storing data in the state and then retrieving it from the state. You might be able to optimize this process.



_Code quote:_
```XML
        self.state.insert(account.sender_address, account.state);

        if let Some(state) = self.state.get(&tx.sender_address) {
```
___
*[`crates/mempool/src/mempool_test.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fo-I47slgawZ0u0D8:-O-Fo-I58H-6rWinRLAf:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool_test.rs#L51)):*
> ```XML
> 
> #[test]
> fn test_new_with_duplicate_tx() {
> ```





_Suggestion:_
```XML
test_mempool_new_method_with_duplicate_tx
```
___
*[`crates/mempool/src/mempool_test.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FfrL-EJRS8q9fc0ne:-O-FfrL-EJRS8q9fc0nf:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool_test.rs#L60)):*
> ```XML
>         Mempool::new(inputs),
>         Err(MempoolError::DuplicateTransaction { tx_hash: TransactionHash(StarkFelt::ONE) })
>     );
> ```





_Suggestion:_
```XML
      assert!(matches!(
        Mempool::new(inputs),
        Err(MempoolError::DuplicateTransaction { tx_hash: TransactionHash(StarkFelt::ONE) })
    ));
```
___
*[`crates/mempool/src/mempool_test.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fnui4C1BG5Op_KJOy:-O-Fnui4C1BG5Op_KJOz:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool_test.rs#L64)):*
> ```XML
> 
> #[test]
> fn test_new() {
> ```





_Suggestion:_
```XML
test_mempool_new_method
```


<!-- Sent from Reviewable.io -->

2024-06-13 09:27 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 9 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/Cargo.toml` line 17 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FdOkX2PPZ1J87v38a:-O-FonpL1VojPImObiRt:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/Cargo.toml#L17)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please remove it; it's not in use.
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgE9D542JI-O-Wde2:-O-FpOZ45PnrVJsO9ElQ:b-e4dz2x) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I don't think `AddressPriorityQueue` is a good name.
It's a tx store.
</blockquote></details>

why not? It is a pq for each account
perhaps AccountStore?
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgUr77NPvFeiRItqG:-O-FpXND3u_ebbIZ7diG:b-8lglan) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please use HashMap instead of a vector.
This way, we'll also support multi-nonces with holes.
</blockquote></details>

This will be supported in a future PR, and the flow and the tests will be updated accordingly. added a TODO above `struct AddressPriorityQueue`
___
*[`crates/mempool/src/mempool.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fl2uE5JepqtWfLctf:-O-FqhPg37Rwe7Z45lEG:bnt0lxu) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L52)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Question: If `n_txs` is larger than the PQ size, do you pop txs after updating the PQ from `AddressPriorityQueue`?
</blockquote></details>

nope
should I support that?
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FncTm0FGrzfYa1a1_:-O-Fu6elBsm67kFGIDmq:b-avsasg) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you please explain why you need the state?
</blockquote></details>

The state receives information from the gateway (via `add_tx`) or from the `new` method's input. It is updated in `get_tx` and is used to decide whether a transaction should be pushed to the mempool priority queue.
___
*[`crates/mempool/src/mempool.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FnJTt0EbNZfplx1iO:-O-Fu3la7kaTbYJMR5Ca:b-hawxea) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L108)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It seems that you are storing data in the state and then retrieving it from the state. You might be able to optimize this process.
</blockquote></details>

how so?
___
*[`crates/mempool/src/mempool_test.rs` line 51 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fo-I47slgawZ0u0D8:-O-FrMIU3HFEs4k5PmM7:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool_test.rs#L51)):*
> ```XML
> 
> #[test]
> fn test_new_with_duplicate_tx() {
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 64 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fnui4C1BG5Op_KJOy:-O-FrSXbEoHmG3opTzJe:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool_test.rs#L64)):*
> ```XML
> 
> #[test]
> fn test_new() {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 09:36 UTC, giladchase reviewed
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgU6LABuvmfBvUmjkV:-O-Fx-vd5Z85vXfhZv50:b-f0o60e) (no related file):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Implemented AddressPriorityQueue in mempool, which affected three functions:
add_tx, new, get_txs
The related tests for each function are:
add_tx - test_add_tx
new - test_new, test_new with_duplicate_tx
get_tx - test_get_txs

removed `test_mempool_initialization_with_duplicate_sender_addresses` because we support few txs from the same sender address


priority queue checked are checked in #210
</blockquote></details>

Note that i added a [PR](https://reviewable.io/reviews/starkware-libs/mempool/240) that privatizes the inner of `AddressPriorityQueue`, since it has an invariant.

If it's merged, then you'll need to initialize with `default()`.

___


<!-- Sent from Reviewable.io -->

2024-06-13 10:20 UTC, MohammadNassar1 requested changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgE9D542JI-O-Wde2:-O-G4pBW6f1h0QR89Lt4:b43bukz) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why not? It is a pq for each account
perhaps AccountStore?
</blockquote></details>

Only a single tx can be prioritized per account.
Others are considered to be not ready.

In my PR, I used `TransactionStore`.
___
*[`crates/mempool/src/mempool.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fl2uE5JepqtWfLctf:-O-G5fwR150SH6G-GBGL:b-8xx9d0) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L52)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

nope
should I support that?
</blockquote></details>

Yes, please.
and please add a test for such a scenario.
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FncTm0FGrzfYa1a1_:-O-G5rg382cOWKVwxT4d:bki0cr) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The state receives information from the gateway (via `add_tx`) or from the `new` method's input. It is updated in `get_tx` and is used to decide whether a transaction should be pushed to the mempool priority queue.
</blockquote></details>

Let's discuss it F2F.
___
*[`crates/mempool/src/mempool.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FnJTt0EbNZfplx1iO:-O-G68HvE8P_sNBGwSLQ:bocc72g) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L108)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

how so?
</blockquote></details>

Here:
` if let Some(state) = self.state.get(&tx.sender_address) {`
you'll receive the `account.state` you've updated in `insert` right?
so you don't need to retrieve.


<!-- Sent from Reviewable.io -->

2024-06-13 12:03 UTC, giladchase requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/gateway/src/gateway_test.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FxWXL63A3IzXEi8hw:-O-FxWXL63A3IzXEi8hx:bcsdcf) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/gateway/src/gateway_test.rs#L51)):*
> ```XML
>     // TODO: Add fixture.
> 
>     let mempool = Mempool::new([]).unwrap();
> ```

Add a fixture like in mempool_test.rs plz (I don't think they can be shared unfortunately)



_Code quote:_
```XML
    let mempool = Mempool::new([]).unwrap();
```
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgE9D542JI-O-Wde2:-O-GK1VyD9M99DYWLl0E:be9e9gp) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Only a single tx can be prioritized per account.
Others are considered to be not ready.

In my PR, I used `TransactionStore`.
</blockquote></details>

Maybe just `txs`? 
Or `TransactionStorage`, store might sound like a place where one buys transactions :sweat_smile: 
@elintul WDYT?
___
*[`crates/mempool/src/mempool.rs` line 34 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GTda-8i1FzmwTu3qW:-O-GTda-8i1FzmwTu3qX:b-iun0g0) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L34)):*
> ```XML
>             address_to_queue: HashMap::default(),
>             state: HashMap::default(),
>         };
> ```

+ add derive 



_Suggestion:_
```XML
        let mut mempool = Mempool::default();
```


<!-- Sent from Reviewable.io -->

2024-06-13 13:05 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 18 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GWh8I12X5IXmn2hdv:-O-GWh8I12X5IXmn2hdw:bzapk11) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L45)):*
> ```XML
>     pub fn empty() -> MempoolResult<Self> {
>         Mempool::new([])
>     }
> ```

One of them rare "unwrap is ok in production" moments.
If we can't initialize an empty mempool properly we deserve to crash :sweat_smile: 



_Suggestion:_
```XML
    pub fn empty() -> Self {
        Mempool::new([]).unwrap()
    }
```
___
*[`crates/mempool/src/mempool.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GYlIh1Ea_SzYi6tnY:-O-GYlIh1Ea_SzYi6tnZ:bwt5vpj) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L57)):*
> ```XML
>                 address_queue.pop_front();
>                 self.state
>                     .insert(tx.sender_address, AccountState { nonce: tx.nonce.try_increment()? });
> ```

@MohammadNassar1 in the case where the sender_address is removed from address_queue, should its state also be removed? 



_Code quote:_
```XML
                self.state
                    .insert(tx.sender_address, AccountState { nonce: tx.nonce.try_increment()? });
```
___
*[`crates/mempool/src/mempool.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GZ-Y171XWdsHBlpD8:-O-GZ-Y171XWdsHBlpD9:b-48osip) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L69)):*
> ```XML
>                 }
>             }
>         }
> ```

Can this be simplified? Nesting feels too deep here I think 



_Code quote:_
```XML
        for tx in &txs {
            if let Some(address_queue) = self.address_to_queue.get_mut(&tx.sender_address) {
                address_queue.pop_front();
                self.state
                    .insert(tx.sender_address, AccountState { nonce: tx.nonce.try_increment()? });

                if address_queue.is_empty() {
                    self.address_to_queue.remove(&tx.sender_address);
                } else if let Some(next_tx) = address_queue.top() {
                    if let Some(sender_state) = self.state.get(&tx.sender_address) {
                        if sender_state.nonce == next_tx.nonce {
                            self.txs_queue.push(next_tx.clone());
                        }
                    }
                }
            }
        }
```
___
*[`crates/mempool/src/mempool.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-G_nEU0nQ00DxOGmoX:-O-G_nEU0nQ00DxOGmoY:bmdwxfy) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L95)):*
> ```XML
>     }
> 
>     fn handle_tx(&mut self, tx: ThinTransaction, account: Account) -> MempoolResult<()> {
> ```

maybe `insert_tx`, handle seems too vague



_Code quote:_
```XML
handle_tx(
```
___
*[`crates/mempool/src/mempool.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GU50J6_4xdm9fjs0x:-O-GU50J6_4xdm9fjs0y:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L99)):*
> ```XML
>             .address_to_queue
>             .entry(tx.sender_address)
>             .or_insert_with(|| AddressPriorityQueue(Vec::new()));
> ```





_Suggestion:_
```XML
            .or_default()
```
___
*[`crates/mempool/src/mempool_test.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GdzIW-xPoeFRuDPXl:-O-GdzIX9qliZRkQ-Tcv:b-1oagcz) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L1)):*
> ```XML
> use std::panic;
> ```

what's this for?



_Code quote:_
```XML
use std::panic;
```
___
*[`crates/mempool/src/mempool_test.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GcF4F77dgaqxVIpwS:-O-GcF4F77dgaqxVIpwT:b45h) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L52)):*
> ```XML
> 
> #[test]
> fn test_mempool_new_method_with_duplicate_tx() {
> ```





_Suggestion:_
```XML
fn test_new_with_duplicate_tx() {
```
___
*[`crates/mempool/src/mempool_test.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GcP9n8DHVPzLH8rWE:-O-GcP9n8DHVPzLH8rWF:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L65)):*
> ```XML
> 
> #[test]
> fn test_mempool_new_method() {
> ```





_Suggestion:_
```XML
fn test_new_success() {
```
___
*[`crates/mempool/src/mempool_test.rs` line 66 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GdLufB6AFvOC0hU25:-O-GdLufB6AFvOC0hU26:byw628d) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L66)):*
> ```XML
> #[test]
> fn test_mempool_new_method() {
>     let (tx0, account0) =
> ```

Do we need 4 txs here? can it be less? or is there some internal logic between their values? if their random data then 3 is enough.
___
*[`crates/mempool/src/mempool_test.rs` line 86 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Ge5DHEbEdWhwbyqI9:-O-Ge5DHEbEdWhwbyqIA:b-pxyxq1) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L86)):*
> ```XML
>     ];
> 
>     let mempool = Mempool::new(inputs).unwrap();
> ```

:pregnant_man:
Lets make a private mempool constructor test-util in this module,
call it `setup_mempool_new` have it take a slice of (tip,hash), which it'll use the logic below to construct the txs and insert them into the mempool.

It can be used in almost all tests here, both the ones that test `new` (which will become 2-line tests if we have a `check_mempool_state` checker, see thread below), and in the other tests as well (it's ok to use `new` in non-new unit tests, since it's a constructor).



_Code quote:_
```XML
    let (tx0, account0) =
        add_tx_input!(Tip(50), TransactionHash(StarkFelt::ZERO), contract_address!("0x0"));
    let (tx1, account1) =
        add_tx_input!(Tip(60), TransactionHash(StarkFelt::ONE), contract_address!("0x1"));
    let (tx2, account2) =
        add_tx_input!(Tip(70), TransactionHash(StarkFelt::TWO), contract_address!("0x2"));
    let (tx3, _) = add_tx_input!(
        Tip(80),
        TransactionHash(StarkFelt::THREE),
        contract_address!("0x0"),
        Nonce(StarkFelt::ONE)
    );

    let inputs = vec![
        MempoolInput { tx: tx0.clone(), account: account0 },
        MempoolInput { tx: tx1.clone(), account: account1 },
        MempoolInput { tx: tx2.clone(), account: account2 },
        MempoolInput { tx: tx3.clone(), account: account0 },
    ];

    let mempool = Mempool::new(inputs).unwrap();
```
___
*[`crates/mempool/src/mempool_test.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Gchc2BRjxCEPPZ_fb:-O-Gchc2BRjxCEPPZ_fc:bhweqpx) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L100)):*
> ```XML
>     assert!(mempool.txs_queue.contains(&PrioritizedTransaction(tx1)));
>     assert!(mempool.txs_queue.contains(&PrioritizedTransaction(tx2)));
>     assert!(!mempool.txs_queue.contains(&PrioritizedTransaction(tx3)));
> ```

See if you can extend `check_mempool_txs_eq` into `check_mempool`, which verifies addre [...]

2024-06-13 13:07 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 18 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool_test.rs` line 86 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Ge5DHEbEdWhwbyqI9:-O-GhKkO9nm9AeQ2FHw2:bygpu4u) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:pregnant_man:
Lets make a private mempool constructor test-util in this module,
call it `setup_mempool_new` have it take a slice of (tip,hash), which it'll use the logic below to construct the txs and insert them into the mempool.

It can be used in almost all tests here, both the ones that test `new` (which will become 2-line tests if we have a `check_mempool_state` checker, see thread below), and in the other tests as well (it's ok to use `new` in non-new unit tests, since it's a constructor).
</blockquote></details>

Can be in a separate PR afterwards


<!-- Sent from Reviewable.io -->

2024-06-13 15:03 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 17 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/gateway/src/gateway_test.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FxWXL63A3IzXEi8hw:-O-GoEQR-eo9_cAlokyz:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/gateway/src/gateway_test.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a fixture like in mempool_test.rs plz (I don't think they can be shared unfortunately)
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FgE9D542JI-O-Wde2:-O-GM08O9rZOGgMWCKqp:b-u9gxns) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe just `txs`? 
Or `TransactionStorage`, store might sound like a place where one buys transactions :sweat_smile: 
@elintul WDYT?
</blockquote></details>

Changed to `AddressStore` for now. 
___
*[`crates/mempool/src/mempool.rs` line 52 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Fl2uE5JepqtWfLctf:-O-GLUH1AzYEH1mXtk9x:bhnbg3u) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L52)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yes, please.
and please add a test for such a scenario.
</blockquote></details>

added a TODO
___
*[`crates/mempool/src/mempool.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FncTm0FGrzfYa1a1_:-O-Gn1W20QiDewP6ikEK:bsaqkfg) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L106)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Let's discuss it F2F.
</blockquote></details>

removed state
___
*[`crates/mempool/src/mempool.rs` line 108 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-FnJTt0EbNZfplx1iO:-O-Gn3QS05FM3CqvXf9g:bsaqkfg) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L108)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Here:
` if let Some(state) = self.state.get(&tx.sender_address) {`
you'll receive the `account.state` you've updated in `insert` right?
so you don't need to retrieve.
</blockquote></details>

removed state
___
*[`crates/mempool/src/mempool.rs` line 34 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GTda-8i1FzmwTu3qW:-O-GqKjxBzDYk7W0JR-U:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

+ add derive
</blockquote></details>

Done.
___
*[`crates/mempool/src/mempool.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GWh8I12X5IXmn2hdv:-O-GqXV64b286-Mgcolu:b6z82cz) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L45)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

One of them rare "unwrap is ok in production" moments.
If we can't initialize an empty mempool properly we deserve to crash :sweat_smile:
</blockquote></details>

:open_mouth:
___
*[`crates/mempool/src/mempool.rs` line 69 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GZ-Y171XWdsHBlpD8:-O-Gr2s34B6BeMe4DGad:bvk8t44) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L69)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be simplified? Nesting feels too deep here I think
</blockquote></details>

It looks nicer now, and it will soon be changed to support cases where `n_txs` is greater than the number of transactions in `txs_queue`.
___
*[`crates/mempool/src/mempool.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-G_nEU0nQ00DxOGmoX:-O-GrsIZ9LobDzmTO_aJ:b-w6xw3s) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L95)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

maybe `insert_tx`, handle seems too vague
</blockquote></details>

not ideal but ok
___
*[`crates/mempool/src/mempool.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GU50J6_4xdm9fjs0x:-O-GsBbrA7uwZy5pSz5r:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L99)):*
> ```XML
>             .address_to_queue
>             .entry(tx.sender_address)
>             .or_insert_with(|| AddressPriorityQueue(Vec::new()));
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GdzIW-xPoeFRuDPXl:-O-GsFb7ADubNifwwfAz:b-ubp414) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

what's this for?
</blockquote></details>

apparently nothing
___
*[`crates/mempool/src/mempool_test.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GcP9n8DHVPzLH8rWE:-O-GnTFL9HfornGoFFGO:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L65)):*
> ```XML
> 
> #[test]
> fn test_mempool_new_method() {
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 66 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GdLufB6AFvOC0hU25:-O-GsRK91bK25AsEODEX:b3mo07t) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L66)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we need 4 txs here? can it be less? or is there some internal logic between their values? if their random data then 3 is enough.
</blockquote></details>

Three transactions are from different accounts, and the fourth is from the first. I removed the third transaction, so there are now two accounts and three transactions. 

 In get_txs, there are also four tx, but it will be changed soon.
___
*[`crates/mempool/src/mempool_test.rs` line 86 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Ge5DHEbEdWhwbyqI9:-O-H4Uag-SzzUuCoT__S:b93jw7i) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can be in a separate PR afterwards
</blockquote></details>

different PR
___
*[`crates/mempool/src/mempool_test.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Gchc2BRjxCEPPZ_fb:-O-H4VvJ1HeaKdJJRT9L:b93jw7i) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L100)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

See if you can extend `check_mempool_txs_eq` into `check_mempool`, which verifies address_to_queue and state in a similar manner that it does txs.

Can be in a separate PR if this is blocking Mohammad.
</blockquote></de [...]

2024-06-16 06:05 UTC, giladchase requested changes
Having trouble keeping track of the changes, can you plz modify the PR description to explain where things stand now? I understand that the handling of `State` has changed?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72#-:-O-UdEdVDZYjs3Q5SKEa:b1c9cgg)* status: 4 of 10 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Ubef2CVNFLOY1mRsh:-O-Ubef2CVNFLOY1mRsi:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/badec6e79e3a1af5d8219a26bb03c933badb7298/crates/mempool/src/mempool.rs#L41)):*
> ```XML
>     pub fn empty() -> Self {
>         Mempool::new([]).unwrap()
>     }
> ```





_Suggestion:_
```XML
    pub fn empty() -> Self {
        Mempool::default()
    }
```
___
*[`crates/mempool/src/mempool_test.rs` line 181 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GfQj3D5IiLpqllCWl:-O-K71gU4qKk7aMgBQ-6:bak896o) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L181)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

yep
which one should I remove?
</blockquote></details>

The one here. Having a separate test for this is good, and this test should only test a simple happy flow scenario.


<!-- Sent from Reviewable.io -->

2024-06-16 08:46 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 4 of 10 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GYlIh1Ea_SzYi6tnY:-O-V4Syc0JxQryjNRWzZ:b-4blh) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L57)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@MohammadNassar1 in the case where the sender_address is removed from address_queue, should its state also be removed?
</blockquote></details>

I think so. Removed it.
___
*[`crates/mempool/src/mempool.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Ubef2CVNFLOY1mRsh:-O-V5_u76Un0ELskxOsz:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/badec6e79e3a1af5d8219a26bb03c933badb7298/crates/mempool/src/mempool.rs#L41)):*
> ```XML
>     pub fn empty() -> Self {
>         Mempool::new([]).unwrap()
>     }
> ```

Done.
___
*[`crates/mempool/src/mempool_test.rs` line 181 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GfQj3D5IiLpqllCWl:-O-V5HFj9eK99qcWUBQM:b-896fix) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L181)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The one here. Having a separate test for this is good, and this test should only test a simple happy flow scenario.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-16 09:52 UTC, elintul requested changes
> Reviewed 2 of 7 files at r6, 1 of 6 files at r7, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 6 of 10 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzhJopDAMiZyoh0jM-I:-NzhJopEBHTnQbAJ0uSh:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/8c60422a9cd31b490ab2e28ffbf5873f6e00a257/crates/mempool/src/mempool.rs#L23)):*
> ```XML
> pub struct Mempool {
>     // TODO: add docstring explaining visibility and coupling of the fields.
>     txs_queue: TransactionPriorityQueue,
> ```





_Suggestion:_
```XML
tx_queue
```
___
*[`crates/mempool/src/priority_queue.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgVayZ2TXL4CpsKsH-:-NzgVayZ2TXL4CpsKsH0:bu66pso) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L64)):*
> ```XML
> // TODO: remove when is used.
> #[allow(dead_code)]
> #[derive(Debug)]
> ```

So that `.0` isn't needed; usually good for simple wrappers.



_Suggestion:_
```XML
#[derive(Debug), derive_more::Deref]
```
___
*[`crates/mempool/src/priority_queue.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgVNeC0b8XzvzvBg1X:-NzgVNeD9TBbrxPbQ_LW:bpxolc3) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L66)):*
> ```XML
> #[derive(Debug)]
> // Assumption: there are no gaps, and the transactions are received in order.
> pub struct AddressPriorityQueue(pub Vec<ThinTransaction>);
> ```

So that the invariant holds.



_Suggestion:_
```XML
Vec<ThinTransaction>
```
___
*[`crates/mempool/src/priority_queue.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgW6DLCYusejzAx7cI:-NzgW6DLCYusejzAx7cJ:boqsugk) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L66)):*
> ```XML
> #[derive(Debug)]
> // Assumption: there are no gaps, and the transactions are received in order.
> pub struct AddressPriorityQueue(pub Vec<ThinTransaction>);
> ```

Not a good name, since it contains impl. details: the type of the data structure, which can change (and the name will remain outdated). 
Variables should be called in a behavioral manner, according to their role. In this case: 



_Code quote:_
```XML
AddressPriorityQueue
```
___
*[`crates/mempool/src/priority_queue.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VRlAu-0pnaUMbmTD3:-O-VRlAu-0pnaUMbmTD4:b-9o5jl8) ([raw file](https://github.com/starkware-libs/mempool/blob/9aa0c40b4c92aef80a737e3141de010e01a0c1c2/crates/mempool/src/priority_queue.rs#L72)):*
> ```XML
> 
> // TODO: remove when is used.
> #[allow(dead_code)]
> ```

Isn't it used in this PR?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/mempool/src/priority_queue.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VRpEJ1JBOmoUpUA-L:-O-VRpEJ1JBOmoUpUA-M:bgpfhap) ([raw file](https://github.com/starkware-libs/mempool/blob/9aa0c40b4c92aef80a737e3141de010e01a0c1c2/crates/mempool/src/priority_queue.rs#L73)):*
> ```XML
> // TODO: remove when is used.
> #[allow(dead_code)]
> impl AddressStore {
> ```

Do we need all these methods?



_Code quote:_
```XML
impl AddressStore
```


<!-- Sent from Reviewable.io -->

2024-06-16 09:52 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 6 of 10 files reviewed, 12 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-16 10:28 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 6 of 10 files reviewed, 15 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 50 at r9](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VYDCz13S38OJwLJF6:-O-VYDCz13S38OJwLJF7:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c83f38ed748ef5c4384a816fdabeb7ba951521c4/crates/mempool/src/mempool.rs#L50)):*
> ```XML
>     // check and add transactions from `address_to_store`.
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
>         let txs = self.txs_queue.pop_last_chunk(n_txs);
> ```





_Suggestion:_
```XML
eligible_txs
```
___
*[`crates/mempool/src/mempool.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VYIDI5xhWJUHijvrD:-O-VYIDI5xhWJUHijvrE:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c83f38ed748ef5c4384a816fdabeb7ba951521c4/crates/mempool/src/mempool.rs#L51)):*
> ```XML
>     pub fn get_txs(&mut self, n_txs: usize) -> MempoolResult<Vec<ThinTransaction>> {
>         let txs = self.txs_queue.pop_last_chunk(n_txs);
>         for tx in &txs {
> ```





_Suggestion:_
```XML
// TODO: add staging area.
// Remove transactions from mempool.
for tx in &txs {
```
___
*[`crates/mempool/src/mempool.rs` line 59 at r9](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-V_W6F2ti_us729rSG:-O-V_W6F2ti_us729rSH:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/c83f38ed748ef5c4384a816fdabeb7ba951521c4/crates/mempool/src/mempool.rs#L59)):*
> ```XML
>                 } else if let Some(next_tx) = address_queue.top() {
>                     self.txs_queue.push(next_tx.clone());
>                 }
> ```





_Suggestion:_
```XML
                // Remove address from the mempool if no transactions from this account left.
                if address_queue.is_empty() {
                    self.address_to_store.remove(&tx.sender_address);
                // Push next nonce to priority queue.
                } else if let Some(next_tx) = address_queue.top() {
                    self.txs_queue.push(next_tx.clone());
                }
```


<!-- Sent from Reviewable.io -->

2024-06-17 08:52 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/priority_queue.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgW6DLCYusejzAx7cI:-O-WF6907q4KDch9AG_d:bwojjsm) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L66)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not a good name, since it contains impl. details: the type of the data structure, which can change (and the name will remain outdated). 
Variables should be called in a behavioral manner, according to their role. In this case:
</blockquote></details>

it was like this before and @MohammadNassar1 asked to change it. Anyway, I think it's a better name, so I'm changing it back. 
___
*[`crates/mempool/src/priority_queue.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VRlAu-0pnaUMbmTD3:-O-WGcrn9RsN5hBozAIL:b-jp377f) ([raw file](https://github.com/starkware-libs/mempool/blob/9aa0c40b4c92aef80a737e3141de010e01a0c1c2/crates/mempool/src/priority_queue.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't it used in this PR?
</blockquote></details>

correct
___
*[`crates/mempool/src/priority_queue.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VRpEJ1JBOmoUpUA-L:-O-WGUJo5CtSjXI1tpsl:bgh981d) ([raw file](https://github.com/starkware-libs/mempool/blob/9aa0c40b4c92aef80a737e3141de010e01a0c1c2/crates/mempool/src/priority_queue.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we need all these methods?
</blockquote></details>

I use all of them


<!-- Sent from Reviewable.io -->

2024-06-18 11:53 UTC, MohammadNassar1 requested changes
> Reviewed 3 of 5 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/mempool/src/mempool.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-GYlIh1Ea_SzYi6tnY:-O-f1b0o2udWY-k35XSq:b-e2tga4) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool.rs#L57)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think so. Removed it.
</blockquote></details>

Yes, the state can be removed once the transaction is removed from Mempool.
___
*[`crates/mempool/src/mempool.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-f8w3P249KJ_LQfYWL:-O-f8w3P249KJ_LQfYWM:b-w5bhyy) ([raw file](https://github.com/starkware-libs/mempool/blob/0d5526ceba6c107b2152ace5115a065f3cc9ee8e/crates/mempool/src/mempool.rs#L67)):*
> ```XML
>     /// TODO: support fee escalation and transactions with future nonces.
>     /// TODO: change input type to `MempoolInput`.
>     pub fn add_tx(&mut self, tx: ThinTransaction) -> MempoolResult<()> {
> ```

Why have you removed the `AccoutState`?
Note that now you don't check duplicates for an address you do not have in the Mempool.



_Code quote:_
```XML
(&mut self, tx: ThinTransaction)
```
___
*[`crates/mempool/src/priority_queue.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgW6DLCYusejzAx7cI:-O-fAuqI0jnyo25ptAri:b-q2ivon) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L66)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

it was like this before and @MohammadNassar1 asked to change it. Anyway, I think it's a better name, so I'm changing it back.
</blockquote></details>

But they're not prioritized transactions. They are non-ready transactions.


<!-- Sent from Reviewable.io -->

2024-06-18 14:20 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-f8w3P249KJ_LQfYWL:-O-fYwnK73LAi4rVWIaF:b-wcgqrt) ([raw file](https://github.com/starkware-libs/mempool/blob/0d5526ceba6c107b2152ace5115a065f3cc9ee8e/crates/mempool/src/mempool.rs#L67)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why have you removed the `AccoutState`?
Note that now you don't check duplicates for an address you do not have in the Mempool.
</blockquote></details>

Good point! added it + test for it here #256
___
*[`crates/mempool/src/priority_queue.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgVayZ2TXL4CpsKsH-:-O-fda1-Co_1mfdvT6EB:b-8sfsqc) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L64)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So that `.0` isn't needed; usually good for simple wrappers.
</blockquote></details>

#255 
___
*[`crates/mempool/src/priority_queue.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/mempool/72#-NzgW6DLCYusejzAx7cI:-O-fEqPa37ATJkZuFSrM:bdhraj0) ([raw file](https://github.com/starkware-libs/mempool/blob/93b11116398e3340614af131428ee9ca6cac0ee5/crates/mempool/src/priority_queue.rs#L66)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

But they're not prioritized transactions. They are non-ready transactions.
</blockquote></details>

But they're prioritized to become ready.


<!-- Sent from Reviewable.io -->

2024-06-18 15:17 UTC, MohammadNassar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72#-:-O-fv6Fr5PIz9gAkzeMQ:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`crates/gateway/src/gateway_test.rs` line 53 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-fpoUG3W5gzRWjMOaZ:-O-fpoUG3W5gzRWjMOa_:b28d2bn) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/gateway/src/gateway_test.rs#L53)):*
> ```XML
> // TODO(Ayelet): add test cases for declare and deploy account transactions.
> #[tokio::test]
> async fn test_add_tx() {
> ```

see [here](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool_test.rs#L44-L47) how we used fixture



_Code quote:_
```XML
async fn test_add_tx() {
```
___
*[`crates/mempool/src/mempool.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-f8w3P249KJ_LQfYWL:-O-fkCGm6VdVn4LqDftA:b-u727xm) ([raw file](https://github.com/starkware-libs/mempool/blob/0d5526ceba6c107b2152ace5115a065f3cc9ee8e/crates/mempool/src/mempool.rs#L67)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Good point! added it + test for it here #256
</blockquote></details>

Thanks :crown:!
___
*[`crates/mempool/src/mempool_test.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-fu1wPEUSRay36Knqn:-O-fu1wPEUSRay36Knqo:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool_test.rs#L102)):*
> ```XML
>     let (tx_tip_10_address_2, account3) =
>         add_tx_input!(Tip(10), TransactionHash(StarkFelt::THREE), contract_address!("0x2"));
>     let (tx2_address_0, _) = add_tx_input!(
> ```





_Suggestion:_
```XML
tx_address_0_nonce_1
```
___
*[`crates/mempool/src/mempool_test.rs` line 154 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-fumYjBcUvvviF-utx:-O-fumYjBcUvvviF-uty:b-61cdsn) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool_test.rs#L154)):*
> ```XML
>     let (tx_tip_80_address_2, account3) =
>         add_tx_input!(Tip(80), TransactionHash(StarkFelt::THREE), contract_address!("0x2"));
>     let (tx2_address_0, _) = add_tx_input!(
> ```

same like above



_Code quote:_
```XML
(tx2_address_0
```
___
*[`crates/mempool/src/mempool_test.rs` line 186 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-fu_v49TYdbe-oW0VD:-O-fu_v49TYdbe-oW0VE:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool_test.rs#L186)):*
> ```XML
> #[rstest]
> fn test_add_tx_with_duplicate_tx(mut mempool: Mempool) {
>     let (tx, _account) = add_tx_input!(Tip(50), TransactionHash(StarkFelt::ONE));
> ```





_Suggestion:_
```XML
(tx, _
```


<!-- Sent from Reviewable.io -->

2024-06-19 08:52 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool_test.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-fu1wPEUSRay36Knqn:-O-jM4slE4GIdfsP_rEp:b-r1aaoj) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool_test.rs#L102)):*
> ```XML
>     let (tx_tip_10_address_2, account3) =
>         add_tx_input!(Tip(10), TransactionHash(StarkFelt::THREE), contract_address!("0x2"));
>     let (tx2_address_0, _) = add_tx_input!(
> ```

already done here #254


<!-- Sent from Reviewable.io -->

2024-06-19 11:20 UTC, MohammadNassar1 reviewed
> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-06-19 12:17 UTC, giladchase requested changes
> Reviewed 1 of 5 files at r10, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-iz9tV0cugOfOHKT0q:-O-iz9tV0cugOfOHKT0r:b-c45inb) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool.rs#L49)):*
> ```XML
>         // Remove transactions from mempool.
>         for tx in &eligible_txs {
>             if let Some(address_queue) = self.address_to_queue.get_mut(&tx.sender_address) {
> ```

I think`address_queue` kind of sounds like a queue of addresses.

I don't think there's a reasonable way of succinctly describing this struct's implementation in a variable name, and we should not try to do so.
I think it should describe the behavior of what this represents.

In this case, this var represents a collection of transactions associated with an account (through its address, but this is an implementation detail, all that matters is identifying the account). Therefore, it should be something like `account_transactions`.

I also propose that the type of the field be changed to AccountTransactions, @elintul WDYT on both?



_Suggestion:_
```XML
account_transactions
```
___
*[`crates/mempool/src/mempool.rs` line 58 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-j8aSn-dIPFam6OG0n:-O-j8aSn-dIPFam6OG0o:undefined) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool.rs#L58)):*
> ```XML
>                     self.tx_queue.push(next_tx.clone());
>                 }
>             }
> ```





_Suggestion:_
```XML
                 match address_queue.pop_front() {
                    Some(account_tx_ref) => assert_eq!(account_tx_ref.tx_hash, tx.tx_hash),
                    None => panic!("Queued transaction should be present in account transactions"),
                }
                match address_queue.top() {
                    Some(next_account_tx) => self.tx_queue.push(next_account_tx.clone()),
                    None => {
                        self.address_to_queue.remove(&tx.sender_address);
                    }
                }
            }
```
___
*[`crates/mempool/src/mempool_test.rs` line 100 at r6](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-Gchc2BRjxCEPPZ_fb:-O-itH_y3RWSU2sFJWbi:b-q9epqy) ([raw file](https://github.com/starkware-libs/mempool/blob/3e9b04366177290689d0b3c0b31cfc3b7a60a53c/crates/mempool/src/mempool_test.rs#L100)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

different PR
</blockquote></details>

Sababa, but plz use `check_mempool_txs_eq` here in its current form  instead of 4 txs_queue.contains calls.
___
*[`crates/mempool/src/priority_queue.rs` line 73 at r8](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-VRpEJ1JBOmoUpUA-L:-O-isYZ34D5-0dWV5dB5:br6spbv) ([raw file](https://github.com/starkware-libs/mempool/blob/9aa0c40b4c92aef80a737e3141de010e01a0c1c2/crates/mempool/src/priority_queue.rs#L73)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I use all of them
</blockquote></details>

I think we need them because we can't expose/Deref the internal type, due to the invariants we have on it.


<!-- Sent from Reviewable.io -->

2024-06-19 14:07 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/mempool/src/mempool.rs` line 95 at r13](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-koB_4BXK1MKtlOQh7:-O-koB_4BXK1MKtlOQh8:b-6t9thq) ([raw file](https://github.com/starkware-libs/mempool/blob/2849768d7f71687aec810531deace5154af5c2ec/crates/mempool/src/mempool.rs#L95)):*
> ```XML
>         if address_queue.len() == 1 {
>             self.tx_queue.push(tx);
>         }
> ```

First line here is coupled with the `if` below: if `or_default` was triggered then address_queue.len will be 1.

See if you can unconditionally add to `tx_queue` in the or_default case somehow, hopefully without uglying things up too much (it will likely be uglier though :( )
 



_Code quote:_
```XML
        let address_queue = self.address_to_queue.entry(tx.sender_address).or_default();

        if address_queue.contains(&tx) {
            return Err(MempoolError::DuplicateTransaction { tx_hash: tx.tx_hash });
        }

        address_queue.push(tx.clone());
        if address_queue.len() == 1 {
            self.tx_queue.push(tx);
        }
```


<!-- Sent from Reviewable.io -->

2024-06-20 07:27 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-iz9tV0cugOfOHKT0q:-O-oW50N4dH5Xh5KLwxN:b-t7sx1d) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool.rs#L49)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

In the meantime, I added a todo to change the name
</blockquote></details>

where was it added?
___
*[`crates/mempool/src/mempool.rs` line 95 at r13](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-koB_4BXK1MKtlOQh7:-O-oXdDI798XQGhsM_l-:b-tku0u4) ([raw file](https://github.com/starkware-libs/mempool/blob/2849768d7f71687aec810531deace5154af5c2ec/crates/mempool/src/mempool.rs#L95)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Good point. Also, `address_queue.contains(&tx)` is a redundant check for an empty vector.
</blockquote></details>

Can you use match instead of if-let-else, it's almost always better.


<!-- Sent from Reviewable.io -->

2024-06-20 07:47 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/mempool/src/mempool.rs` line 49 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-iz9tV0cugOfOHKT0q:-O-oaLXX78kDM_HNbPrj:b-fm66pm) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

where was it added?
</blockquote></details>

above 'AddressPriorityQueue' struct
___
*[`crates/mempool/src/mempool.rs` line 58 at r12](https://reviewable.io/reviews/starkware-libs/mempool/72#-O-j8aSn-dIPFam6OG0n:-O-obMbj4EjSbKVr1V8Q:b-dvhkm1) ([raw file](https://github.com/starkware-libs/mempool/blob/490e102c62b9068e92ba2fc206e6434a5aff63d0/crates/mempool/src/mempool.rs#L58)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done. I used `if let` instead of `match` because the `remove` operation requires the result to be handled
</blockquote></details>

used match


<!-- Sent from Reviewable.io -->

2024-06-23 10:09 UTC, giladchase reviewed
Ayelet is OOO, i'm taking over the PR :smiling_imp: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72#-:-O03ZQdq-iu_loH1hYp6:bsqguia)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-06-24 08:49 UTC, giladchase approved these changes

2024-06-24 12:11 UTC, elintul reviewed
> Reviewed 2 of 3 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/mempool/72)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-07-09 19:26 UTC, giladchase commented
All code has been extracted into separate PRs merged or on review, closing.

2024-07-09 19:26 UTC, closed without merging